### ISSUE TITLE
Ability to check the amount of tokens remaining using the API?

### ISSUE THREAD

**Issue by proudmuslim-dev** [openai/openai-python#10]
I couldn't find any reference to this in the docs and the slack chatroom is quite dead, so I'm opening an issue here to suggest it if it's not implemented yet.

**Comment by hallacy** [comment]
Thanks for the issue and sorry it took so long to get back to you.  I'm going to close this ticket since there are now usage dashboards on the playground: https://beta.openai.com/account/usage.  Feel free to reopen if you think this is in error.
