### ISSUE TITLE
Missing default value to logprobs in openai.types.chat.chat_completion.Choice

### ISSUE THREAD

**Issue by davorrunje** [openai/openai-python#1006]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

#980 added token `logprobs` to chat completions of type `Optional[ChoiceLogprobs]` in [`openai.types.chat.chat_completion.Choice`](https://github.com/openai/openai-python/blob/3ad4e8bc9d89d7a81586bf598289ff62b0a339b9/src/openai/types/chat/chat_completion.py#L33) and [`openai.types.chat.chat_completion_chunk.Choice`](https://github.com/openai/openai-python/blob/3ad4e8bc9d89d7a81586bf598289ff62b0a339b9/src/openai/types/chat/chat_completion_chunk.py#L97). In the latter, the default value is set to `None`, while in the former it is not set. This causes backward compatibility problems with code written for versions prior to 1.5.0.

### To Reproduce

Execution of the following code fails:

```python 
from openai.types.chat.chat_completion import ChatCompletionMessage, Choice

msg = ChatCompletionMessage(role="assistant", content="")

Choice(
    index=0,
    finish_reason="stop",
    message=msg,
)
```
The output
```
----> 1 Choice(
      2     index=0,
      3     finish_reason="stop",
      4     message=msg,
      5 )

File /.venv-3.10/lib/python3.10/site-packages/pydantic/main.py:164, in BaseModel.__init__(__pydantic_self__, **data)
    162 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    163 __tracebackhide__ = True
--> 164 __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)

ValidationError: 1 validation error for Choice
logprobs
  Field required [type=missing, input_value={'index': 0, 'finish_reas...=None, tool_calls=None)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.5/v/missing
```
Setting `logprobs` to `None` fixes the problem.
```python 
from openai.types.chat.chat_completion import ChatCompletionMessage, Choice

msg = ChatCompletionMessage(role="assistant", content="")

Choice(
    index=0,
    finish_reason="stop",
    message=msg,
    logprobs=None # added line
)
```

### Code snippets

```Python
see above
```

### OS

Linux

### Python version

Python 3.10.13

### Library version

openai 1.6.0

**Comment by rattrayalex** [comment]
Why are you instantiating `Choice` in this way? Do you mean to instantiate `ChoiceParam`?

**Comment by rattrayalex** [comment]
ah, it seems you're doing this for tests, is that right? 

Hmm, we didn't intend for these models to be instantiated this way, which of course means these sorts of changes are indeed breaking. If we do this we'll want to add `= None` to all such fields.

This is something we'll have to think about and likely won't be actioned until after the new year.

Thank you for raising this!

**Comment by davorrunje** [comment]
Thank you the reply.

The main reason I raised the issue is that it broke AutoGen (https://github.com/microsoft/autogen/issues/1043). I made a PR there, but until the new version is released everyone has to downgrade openai lib as remedy.

i understand your argument and agree with it in general. The thing that was puzzling me was that the default value was not set it in [openai.types.chat.chat_completion.Choice](https://github.com/openai/openai-python/blob/3ad4e8bc9d89d7a81586bf598289ff62b0a339b9/src/openai/types/chat/chat_completion.py#L33, but it was set in [openai.types.chat.chat_completion_chunk.Choice](https://github.com/openai/openai-python/blob/3ad4e8bc9d89d7a81586bf598289ff62b0a339b9/src/openai/types/chat/chat_completion_chunk.py#L97). I could not understand why and assumed ir was an oversight.

**Comment by rattrayalex** [comment]
Thank you @davorrunje !
