### ISSUE TITLE
At MacOS, not working well

### ISSUE THREAD

**Issue by apollo812** [openai/openai-python#1014]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Now I am fine-tuning using llama_index==0.9.15 and openai==1.1.0 version.
When I use the Window 10 OS, it working well but when I use the MacOS, not working well.
It returns to such error.

```
/usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/test_all.py:7: in <module>
    from src.main import app  # Import the FastAPI application instance from the main module
src/main.py:19: in <module>
    from finetune.FineTuningClass import FineTuningClass
src/finetune/FineTuningClass.py:8: in <module>
    from llama_index import SimpleDirectoryReader, ServiceContext, VectorStoreIndex
.local/lib/python3.11/site-packages/llama_index/__init__.py:17: in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/__init__.py:16: in <module>
    from llama_index.embeddings.openai import OpenAIEmbedding
.local/lib/python3.11/site-packages/llama_index/embeddings/openai.py:18: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/__init__.py:2: in <module>
    from llama_index.llms.anyscale import Anyscale
.local/lib/python3.11/site-packages/llama_index/llms/anyscale.py:11: in <module>
    from llama_index.llms.openai import OpenAI
.local/lib/python3.11/site-packages/llama_index/llms/openai.py:28: in <module>
    from llama_index.llms.openai_utils import (
.local/lib/python3.11/site-packages/llama_index/llms/openai_utils.py:6: in <module>
    from openai import ChatCompletion, Completion
E   ImportError: cannot import name 'ChatCompletion' from 'openai' (/home/user/.local/lib/python3.11/site-packages/openai/__init__.py)
```

So I upgraded the OpenAI version to 1.3.7 but got such error.

```
from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

I think this is a dependency issue between the llama_index and openai.
Is there anyone who know the solution?

Thank you!!!

### To Reproduce

When I use the Window 10 OS, it working well but when I use the MacOS, not working well.
This is requirements.txt file.

```
httpx
pytest
black
isort
mypy
fastapi
uvicorn
python-multipart
python-dotenv
requests
Pillow
openai==1.1.0
pdf2image
gpt_index
langchain
llama_index==0.9.15
pypdf
spacy
ragas
datasets
docx2txt
cryptography
```

### OS

macOS

### Python version

Python 3.11.0

### Library version

openai v1.1.0 & v1.3.7

**Comment by BlueHephaestus** [comment]
Did you try this with the most up-to-date version of the library? openai v1.6.1?

Additionally, if you could paste what command or code you were using to get this error, I may be able to help address it. Otherwise it's difficult for me to nail down a cause.

**Comment by rattrayalex** [comment]
This does not look like a bug in the SDK, so I'm going to go ahead and close this issue.

For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!
