### ISSUE TITLE
Addition of plotly as a dependency for installing OpenAI API

### ISSUE THREAD

**Issue by sarthakforwet** [openai/openai-python#1021]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

While working with OpenAI API's embeddings_utils module, I ran into the following error while importing the get_embeddings and get_embedding function from it.

<img width="559" alt="image" src="https://github.com/openai/openai-python/assets/46163196/1dc6dc37-44b4-4f74-b78d-1ad982df81d3">

Hence, I think plotly should be added as a dependency for installing OpenAI API.

**Comment by rattrayalex** [comment]
`embeddings_utils.py` is no longer supported in this library; they've moved to the openai cookbook. You'll have to add all deps to your project yourself. Sorry for the confusion!
