### ISSUE TITLE
Auth flow of custom http client not invoked when making a request

### ISSUE THREAD

**Issue by TomSteenbergen** [openai/openai-python#1026]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When passing a custom http client to the OpenAI client, it does not properly use the custom client's auth flow. 

In the client's `_request` method, `self.custom_auth` is passed to `self._client.send` ([link to source code](https://github.com/openai/openai-python/blob/main/src/openai/_base_client.py#L877)).

The property `custom_auth` however is simply defined as `return None` ([link to source code](https://github.com/openai/openai-python/blob/main/src/openai/_base_client.py#L555C19-L555C19)).

Because we explicitly pass `None` to the `auth` argument of the `send` method of the `httpx` client, the client doesn't use the default value `USE_CLIENT_DEFAULT` for the `auth` argument ([link to source code](https://github.com/encode/httpx/blob/master/httpx/_client.py#L882)).

Is there a reason why we have this `custom_auth` property on the client? If we do not pass it to the `auth` argument of `self._client.send`, everything works as expected and the auth logic of the custom `httpx` client is properly invoked.

### To Reproduce

```python
openai_client = OpenAI(
    api_key="<API_KEY>",
    base_url="<BASE_URL>",
    http_client="<HTTP_CLIENT>",
)

completion = openai_client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Last name of the president of the United States",
        }
    ],
    model="gpt-3.5-turbo",
)  # Does not invoke the authentication flow of the client passed using `http_client`.
```

### OS

MacOS 14.2

### Python version

3.11.6

### Library version

1.3.9

**Comment by RobertCraigie** [comment]
Sorry about this, we should have a fix out shortly.

**Comment by TomSteenbergen** [comment]
Awesome, thanks @RobertCraigie. Let me know if I can help by filing a PR or reviewing.

**Comment by RobertCraigie** [comment]
@TomSteenbergen PR is here: https://github.com/openai/openai-python/pull/1028

This fix will be included in the next release.
