### ISSUE TITLE
Inconsistent performance of chat api

### ISSUE THREAD

**Issue by Zhang-Zelong** [openai/openai-python#1036]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When call the `client.chat.completions.create(..., logprobs=True)` with `gpt-3.5-turbo-1106`
Sometime it will raise below error
```
Error code: 400 - {'error': {'message': "This model does not support the 'logprobs' parameter.", 'type': 'invalid_request_error', 'param': 'logprobs', 'code': None}}
```

### To Reproduce

Run the code snippets in jupyter about 5~8 times, sometime it run correctly, somtime will raise an error.
https://platform.openai.com/docs/api-reference/chat/create?lang=python

### Code snippets

```Python
from openai import OpenAI
client = OpenAI()

completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hello!"}
  ],
  logprobs=True,
  top_logprobs=2
)
```

### OS

Linux

### Python version

python3.9.13

### Library version

openai v1.6.1

**Comment by rattrayalex** [comment]
This issue is a duplicate; see https://github.com/openai/openai-python/issues/975#issuecomment-1874273936
