### ISSUE TITLE
system_fingerprint is None

### ISSUE THREAD

**Issue by elisa-abridge** [openai/openai-python#1038]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Per the documentation [here](https://platform.openai.com/docs/guides/text-generation/reproducible-outputs), the OpenAI API should return a `system_fingerprint`. However, when calling any model that is not `gpt-3.5-turbo-1106` or `gpt-4-1106-preview`, the `system_fingerprint` is always `None`.

Is this working as designed? Is this parameter only supported in these two models? If so, can this requirement be documented? The link above doesn't mention this requirement and neither does the API documentation.

### To Reproduce

1. copy and paste notebook [here](https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter)
2. change this line to an older model:
GPT_MODEL = "gpt-3.5-turbo-1106"

For example:
GPT_MODEL = "gpt-3.5-turbo-0613"

3. the `system_fingerprint` returned is `None`

### OS

Unix

### Python version

Python v3.10

### Library version

openai v1.6.1

**Comment by rattrayalex** [comment]
@elisa-abridge – the section you've linked to is marked "beta", which is probably why it's only available in certain models.

cc @logankilpatrick @nknj – I assume the linked docs should be updated for clarity?

Either way, this does not sound like a bug in the SDK, so I'm going to go ahead and close this issue.

**Comment by elisa-abridge** [comment]
The API documentation does not have any beta flag and has `system_fingerprint`. The API is not behaving as documented currently. 

Here is the link to the API documentation:
https://platform.openai.com/docs/api-reference/chat/object

**Comment by rattrayalex** [comment]
Note that the types in this SDK indicate that `system_fingerprint` may be `None`.
