### ISSUE TITLE
joint translation and transcription

### ISSUE THREAD

**Issue by DiTo97** [openai/openai-python#1044]
I would like to keep track of a English speech history no matter the spoken language.

Is it possible to achieve joint translation and transcription with the current whisper model API?

Thus far we have experimented with the following two approaches:
1. anylanguage-to-English translations API + transcriptions API
2. transcriptions API + GPT-4 turbo completions API for anylanguage-to-English

It would be nice to have a unified way to achieve that; am I missing something with the API as-is?

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by DiTo97** [comment]
Not at all, @rattrayalex! Thank you.

For future reference, the discussion has been moved to this [thread](https://community.openai.com/t/joint-translation-and-transcription/580359).
