### ISSUE TITLE
Limit not working when listing messages

### ISSUE THREAD

**Issue by cajomferro** [openai/openai-python#1045]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I'm not able to list messages of a thread filtering by a certain limit.

### To Reproduce

See the code snippet below.

### Code snippets

```Python
# Assuming we have 20 messages in a thread with id "XYZ".


raw_messages = []
async for m in assistant.async_beta_client.threads.messages.list("XYZ", order="asc", limit=1):
    print(m)
    raw_messages.append(m) 
print(len(raw_messages))

# At the end of this code, the result is 20 and the loop runs 20 times. I was expecting a single result.
```

### OS

macOS

### Python version

Python v3.11

### Library version

openai v1.6.1 (but also previous versions)

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by rattrayalex** [comment]
Ah, you are actually making 20 API calls here, thanks to our auto-pagination feature (see the README). To make just a few:

```py
raw_messages = []
page = await assistant.async_beta_client.threads.messages.list("XYZ", order="asc", limit=1)
for m in page.data:
    print(m)
    raw_messages.append(m) 
print(len(raw_messages))
```
