### ISSUE TITLE
Support on setting the API_BASE variable

### ISSUE THREAD

**Issue by pillowsofwind** [openai/openai-python#1051]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Hi Openai developers! 

In the new version of openai-python package (>=1.0), I find it rather inconvenient to set the `OPENAI_API_BASE` variable. That is to say, it is impossible to set the variable with something either like:

```
client = OpenAI(
    api_base = "",
    api_key = ""
)
```

or export the variable in the terminal like:

export OPENAI_API_BASE=

But in order versions, one can conveniently set the variable through the Python script, using something like `openai.api_base=`

**Comment by rattrayalex** [comment]
It has been renamed: 

https://github.com/openai/openai-python?tab=readme-ov-file#module-level-client
```py
openai.base_url = "https://..."
```
or `OpenAI(base_url="…")` or `OPENAI_BASE_URL=…`.
