### ISSUE TITLE
Return usage when streaming chat completions.

### ISSUE THREAD

**Issue by samshapley** [openai/openai-python#1053]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Is it possible to return token usage when streaming in the final chunk?

otherwise we need to also use TikToken in an application where both streaming is enabled vs disabled.

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by jackmpcollins** [comment]
There is a community post for this here: https://community.openai.com/t/openai-api-get-usage-tokens-in-response-when-set-stream-true/141866
The corresponding issue on the JS client is https://github.com/openai/openai-node/issues/506 and comments there indicate this will be added to the API.

@rattrayalex  Would you consider reopening this issue so we can subscribe to be notified when streaming usage has been added to the python client? Thanks

This is a requested feature for the package I maintain https://github.com/jackmpcollins/magentic/issues/74

**Comment by rattrayalex** [comment]
Sorry, I can't guarantee that we'd remember to close this issue when the feature ships, so I'd rather not reopen.

If we do remember, however, we'll leave a comment here so you'll be notified.

**Comment by samshapley** [comment]
For anyone looking in the future, this is now shipped

https://x.com/openaidevs/status/1787573348496773423?s=46&t=jm46NyFc_ht8JJU4ZFVivw
