### ISSUE TITLE
[assistants API] How long are the validity periods of Messages and Runs? #611

### ISSUE THREAD

**Issue by ghost** [openai/openai-python#1055]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

[assistants API] How long are the validity periods of Messages and Runs?
The deletion API of Assistants and Threads, my understanding is that it will always exist if it is not actively deleted.
As for Messages and Runs, I’m not sure how long they last.
【assistants API】Messages、Runs的有效期是多久？
Assistants、Threads的删除的API，我的理解是不主动删除一直存在
而Messages、Runs的是多久不太确定

### To Reproduce

-

### OS

-

### Python version

-

### Library version

-

**Comment by rattrayalex** [comment]
For questions about the underlying API (as opposed to the Python library), please post at [community.openai.com](https://community.openai.com).
