### ISSUE TITLE
system_fingerprint is None

### ISSUE THREAD

**Issue by elisa-abridge** [openai/openai-python#1056]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Per the documentation [here](https://platform.openai.com/docs/api-reference/chat/object), the OpenAI API should return a system_fingerprint. However, when calling any model that is not gpt-3.5-turbo-1106 or gpt-4-1106-preview, the system_fingerprint is always None.

The link above doesn't mention any model requirement.

### To Reproduce

copy and paste notebook [here](https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter)
change this line to an older model:
GPT_MODEL = "gpt-3.5-turbo-1106"
For example:
GPT_MODEL = "gpt-3.5-turbo-0613"

the system_fingerprint returned is None

### OS

Ubuntu

### Python version

Python v3.10

### Library version

openai v1.6.1

**Comment by elisa-abridge** [comment]
Note this is the same issue as reported [here](https://github.com/openai/openai-python/issues/1038), but I wasn't able to re-open the issue. 

I am reporting again because the API is not behaving as documented in the API reference. The API reference has no beta flags on it.

**Comment by rattrayalex** [comment]
Thank you. 

This repo is for _SDK_ issues, not API or API documentation issues. I'll raise this again with the API team, but in the future, https://github.com/openai/openai-openapi would be a better place for this kind of thing.

**Comment by jberryman** [comment]
for the record, elisa-abridge reported here: https://github.com/openai/openai-openapi/issues/167
