### ISSUE TITLE
Finetuning classifier giving recommendations which are not from any of the specified categories used to train the models

### ISSUE THREAD

**Issue by mrmrinal** [openai/openai-python#106]
Hello!

I made a finetuned classifier with 7 categories, similar to the one shown at `examples/finetuning/finetuning-classification.ipynb` and used the following command to create the classifier.

```shell
openai api fine_tunes.create -t "data_prepared_train.jsonl" -v "data_prepared_valid.jsonl" --compute_classification_metrics --classification_n_classes 7 -m ada
```

I use the following command in python when querying from the classifier

```python
res = openai.Completion.create(model=ft_model, prompt = prompt + "\n\n###\n\n", max_tokens=1, temperature=0, logprobs=5)
```

However, when querying a completion from the classifier, the `log_probs` returns values which does not fall under any of the predefined categories. I have tried these with both numerical categories, and string based categories, and the same behavior is still exhibited. Was wondering if there was any way to stop these other non-predefined categories in the `log_probs` as they do not aid with classification in my use case. Just having the probabilities for the predefined categories would suffice. Additionally, there is also the concern that the fine-tuning model could classify the prompt into one of the undefined categories.

Here are a few examples of such occurrences:

**Numerical Categories**
Predefined categories are from 0-6 inclusive

```python
<OpenAIObject at 0x174ab8f9450> JSON: {
  "text_offset": [
    57
  ],
  "token_logprobs": [
    -0.08814435
  ],
  "tokens": [
    " 1"
  ],
  "top_logprobs": [
    {
      " 1": -0.08814435,
      " 2": -8.10889,
      " 5": -7.6156697,
      " 6": -2.4937658,
      " 7": -9.455983
    }
  ]
}
```
Here it suggests the value `" 7"` which has never been specified in the dataset

```python
<OpenAIObject at 0x174ab8cf360> JSON: {
  "text_offset": [
    28
  ],
  "token_logprobs": [
    -0.028152594
  ],
  "tokens": [
    " 5"
  ],
  "top_logprobs": [
    {
      " 0": -8.047939,
      " 4": -6.4044333,
      " 5": -0.028152594,
      " 6": -3.8101103,
      " very": -8.138523
    }
  ]
}
```
Here it suggests the value `" very"` which is not an integer

```Python
<OpenAIObject at 0x174ab8cac70> JSON: {
  "text_offset": [
    60
  ],
  "token_logprobs": [
    -0.07207727
  ],
  "tokens": [
    " 2"
  ],
  "top_logprobs": [
    {
      " 2": -0.07207727,
      " 3": -6.8346596,
      " 4": -6.0346746,
      " 6": -2.7322218,
      "2": -8.06412
    }
  ]
}
```
Here it suggests `"2"` which is different from `" 2"`

**String categories**
Where categories are ["background", "bug", "feature-request" (shows up as feature), "follow-up", "null", "painpoint" (shows up as pain), "usability"]

```Python
<OpenAIObject at 0x174ab91d630> JSON: {
  "text_offset": [
    60
  ],
  "token_logprobs": [
    -0.2158865
  ],
  "tokens": [
    " feature"
  ],
  "top_logprobs": [
    {
      " UX": -8.75913,
      " feature": -0.2158865,
      " features": -7.479752,
      " functionality": -9.452176,
      " usability": -1.6482441
    }
  ]
}
```
Here it is returning other options such as `" UX"`, `" features"`, `" functionality"`, etc over other predefined categories.

```Python
<OpenAIObject at 0x174ab8ed900> JSON: {
  "text_offset": [
    52
  ],
  "token_logprobs": [
    -0.001725924
  ],
  "tokens": [
    " pain"
  ],
  "top_logprobs": [
    {
      " Pain": -6.667007,
      " bug": -9.389308,
      " pain": -0.001725924,
      " painful": -8.79043,
      "pain": -9.397688
    }
  ]
}
```

Here it is returning many different  versions of "pain".

Would really appreciate any advice/support over this, as such completions which are not part of the predefined categories are not expected.

**Comment by mrmrinal** [comment]
Thank you @hallacy and @zafercavdar for your replies! I actually have larger than 100 samples per category and have set the epochs to the default epochs which according to the documentation has 4 epochs, yet still getting these anomalous results. I have been using the numerical categories in this case. I believe it might be better to just lookout for the 7 categories specified.

**Comment by hallacy** [comment]
@mrmrinal I'm gonna go ahead and close out this issue since I think your idea of looking out for the categories seems like the right one. Feel free to reopen this issue if you have any concerns.
