### ISSUE TITLE
azure_endpoint logic not appropriate for running Azure LLMs through a proxy

### ISSUE THREAD

**Issue by gtmtech** [openai/openai-python#1063]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I access my Azure LLM through a gateway proxy service - e.g Microsoft APIM. Its quite opinionated on the format, and I've found that the format is:

`https://myserver/proxy/openai/v1/` `deployments/gpt-4/chat/completions`

The new (as in openai v1) standard way of specifying the azure_endpoint should be azure_endpoint="https://myserver/proxy/openai/v1/"

However, the code in https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py#L192-L195 specifically adds an /openai on the end of my azure_endpoint - this leads to:

https://myserver/proxy/openai/v1/openai/deployments/gpt-4/chat/completions --> #404

At the moment I notice L183 that I can use base_url instead, and then azure_endpoint wont work, but worth noting that langchain spits warnings that azure_endpoint is the new way forward, and you shouldnt use base_url any more, and llama-index doesnt allow you to set that at all. 

All this means if you're accessing Azure LLMs through an API Gateway (as for example happens and is mandatory in heavily regulated environments), you have to do things which may be on their way out. 

If you're intending to keep base_url around, and it is not deprecated, I'll raise a bug in langchain telling them to get rid of the deprecation warning. 

But I think a better solution is to make the forced addition of the /openai configurable. 

### To Reproduce

Run this code with openai 1.7.0

import logging
import os
logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(levelname)s - %(message)s")

from openai import AzureOpenAI

client = AzureOpenAI(
  azure_endpoint = "https://myserver/proxy/openai/v1",
  api_key = os.getenv("OPENAI_API_KEY"),
  api_version = "2023-05-15"
)

client.chat.completions.create(
  messages = [
    {
      "role": "user", "content": "whats the capital of France"
    }
  ],
  model = "gpt-4",
  temperature = 0.5,
  stream = False
)

Running this will give you:

2024-01-11 17:44:52,143 - DEBUG - HTTP Request: POST https://myserver/proxy/openai/v1/openai/deployments/gpt-4/chat/completions?api-version=2023-05-15 "403 Forbidden"

Note the additional /openai 

### OS

macOS

### Python version

3.11.5

### Library version

openai v1.7

**Comment by rattrayalex** [comment]
Hi @gtmtech , thanks for raising this!

We do not plan to adjust `azure_endpoint` in this way, because `base_url` should indeed be used for more exceptional cases such as the proxy you mention. 


> langchain spits warnings that azure_endpoint is the new way forward, and you shouldnt use base_url any more, and llama-index doesnt allow you to set that at all

> If you're intending to keep base_url around, and it is not deprecated, I'll raise a bug in langchain telling them to get rid of the deprecation warning.

Perfect – LangChain & Llama-index should be adjusted here; I'd appreciate it if you'd open issues in them to not warn in this case / allow this pattern!

cc @kristapratico for visibility.
