### ISSUE TITLE
APIStatusError: Error code: 307

### ISSUE THREAD

**Issue by lanke0720** [openai/openai-python#1070]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

APIStatusError                            Traceback (most recent call last)
[<ipython-input-40-ef6a5d33e7aa>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 
----> 4 result = client.chat.completions.create(
      5     model="gpt-4-vision-preview",
      6     messages=[

4 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    947 
    948             log.debug("Re-raising status error")
--> 949             raise self._make_status_error_from_response(err.response) from None
    950 
    951         return self._process_response(

APIStatusError: Error code: 307

My format refers to the demo and other people's submissions. Still reporting an error。
eg:

### To Reproduce

call the api

### Code snippets

```Python
from openai.types import Image, ImagesResponse


result = client.chat.completions.create(
    model="gpt-4-vision-preview",
    messages=[
        {
            "role": "user",
            "content":[
              "please description img",
              *map(lambda x: {"image": x, "resize": 768}, base64Frames[0::20]),
            ]
        },
    ],
    max_tokens=200,
)

print(result.choices[0].message.content)
```

### OS

colab

### Python version

3

### Library version

1.7.2

**Comment by rattrayalex** [comment]
This is a redirect code. How are you instantiating the client? Do you use a proxy? Do you have any environment variables for the base url?

**Comment by lanke0720** [comment]
> This is a redirect code. How are you instantiating the client? Do you use a proxy? Do you have any environment variables for the base url?

yeah,  china

Instantiate the client,
 I use the simplest way to achieve
I understand that url environment variables can be implemented： 
`
os.environ['OPENAI_API_KEY'] = 'sk-xxx'
openai.api_base = "https://oneapi.xty.app/v1"`

`from openai import OpenAI
client = OpenAI(
    base_url="https://oneapi.xty.app/v1",
    api_key="sk-xxx"
)`

The transfer key I use

I tried sending files and the code worked, but sending pictures didn't work.

How to solve this problem?

thanks!

**Comment by rattrayalex** [comment]
Why is your proxy doing a redirect? Could you change things to not require that?

**Comment by rattrayalex** [comment]
The workaround would be to pass a custom httpx client using `follow_redirects=True`, eg:

```py
client = OpenAI(
    base_url="https://oneapi.xty.app/v1", 
    api_key="sk-xxx",
    http_client=httpx.Client(
        base_url="https://oneapi.xty.app/v1",
        follow_redirects=True,
    ),
)

**Comment by lanke0720** [comment]
> The workaround would be to pass a custom httpx client using `follow_redirects=True`, eg:
> 
> ```python
> client = OpenAI(
>     base_url="https://oneapi.xty.app/v1", 
>     api_key="sk-xxx",
>     http_client=httpx.Client(
>         base_url="https://oneapi.xty.app/v1",
>         follow_redirects=True,
>     ),
> )
> ```

Q:Why is your proxy doing a redirect? Could you change things to not require that?
A:Because this is the code I purchased, it cannot be modified.

InternalServerError                       Traceback (most recent call last)
[<ipython-input-11-3ac874af7687>](https://localhost:8080/#) in <cell line: 19>()
     17 }
     18 
---> 19 result = client.chat.completions.create(**params)
     20 print(result.choices[0].message.content)
     21 

8 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    947 
    948             log.debug("Re-raising status error")
--> 949             raise self._make_status_error_from_response(err.response) from None
    950 
    951         return self._process_response(

InternalServerError: Error code: 500 - {'error': {'message': 'json: cannot unmarshal array into Go value of type string (request id: 202401140920136620831892Cywr8jo)', 'type': 'new_api_error', 'param': '', 'code': 'count_token_messages_failed'}}

**Comment by lanke0720** [comment]
> The workaround would be to pass a custom httpx client using `follow_redirects=True`, eg:
> 
> ```python
> client = OpenAI(
>     base_url="https://oneapi.xty.app/v1", 
>     api_key="sk-xxx",
>     http_client=httpx.Client(
>         base_url="https://oneapi.xty.app/v1",
>         follow_redirects=True,
>     ),
> )
> ```

Q:Why is your proxy doing a redirect? Could you change things to not require that?
A:Because this is the code I purchased, it cannot be modified.

It seems that a new problem has been encountered here,   Is the following still an agency issue?

InternalServerError Traceback (most recent call last)
in <cell line: 19>()
17 }
18
---> 19 result = client.chat.completions.create(**params)
20 print(result.choices[0].message.content)
21

8 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
947
948 log.debug("Re-raising status error")
--> 949 raise self._make_status_error_from_response(err.response) from None
950
951 return self._process_response(

InternalServerError: Error code: 500 - {'error': {'message': 'json: cannot unmarshal array into Go value of type string (request id: 202401140920136620831892Cywr8jo)', 'type': 'new_api_error', 'param': '', 'code': 'count_token_messages_failed'}}


Thanks!

**Comment by rattrayalex** [comment]
Glad to hear the workaround fixed the redirect problem for you!

That 500 looks like a problem with the backend of the API or proxy that you are hitting.
