### ISSUE TITLE
logprobs parameter support for Chat Completion API and GPT-4 model 

### ISSUE THREAD

**Issue by iamramengirl** [openai/openai-python#1080]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

May you please share a documentation regarding the correct usage of logprobs parameter in Chat Completion API as well as support for the following models.

1. gpt-4-0613
2. gpt-4-1106-Preview

Currently, when using the parameter with the above models the following errors are returned by the Chat Completion API. openai version is 1.7.2

gpt-4-06-13
BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request argument supplied: logprobs', 'type': 'invalid_request_error', 'param': None, 'code': None}}

gpt-4-1106
BadRequestError: Error code: 400 - {'error': {'message': "This model does not support the 'logprobs' parameter.", 'type': 'invalid_request_error', 'param': 'logprobs', 'code': None}}

### To Reproduce

Please see code snippet below.

### Code snippets

```Python
from openai import AzureOpenAI
 
client = AzureOpenAI(
  azure_endpoint = 'API_ENDPOINT', 
  api_key='API_KEY',  
  api_version='2023-05-15',
  azure_deployment = 'gpt-4-1106'
)

response = client.chat.completions.create(
    model='gpt-4',
    messages=[
        {....}
    ],
    logprobs=True,
    top_logprobs=2
)
response
```

### OS

Windows11

### Python version

Python v3.11.2

### Library version

openai v1.7.2

**Comment by kristapratico** [comment]
@iamramengirl `logprobs` and `top_logprobs` are not supported for chat completions by the Azure API quite yet. I expect support to come online soon, but don't have an ETA at the moment.

**Comment by iamramengirl** [comment]
@kristapratico Thank you for the information!

**Comment by iamramengirl** [comment]
Hello @kristapratico any rough ETA you may share as many customers are waiting for this feature. Thanks!

**Comment by kristapratico** [comment]
@iamramengirl unfortunately I cannot share details about timelines. I will update this thread once it is available. Thanks for understanding.

**Comment by iamramengirl** [comment]
Thank you, @kristapratico!

**Comment by RichDCs** [comment]
any update? thanks!

**Comment by kristapratico** [comment]
Not yet. Promise to come back and update the thread when it's available.

**Comment by rattrayalex** [comment]
This is a request for the Azure API, and not the Python SDK, so I've gone ahead and closed this issue – but you can keep an eye here to find out when this feature is available there.

**Comment by mrshu** [comment]
@kristapratico could you please still update this thread once it is available on Azure? I believe quite a few of us are subscribed to it because of that.

Thanks!

**Comment by rawsh** [comment]
For a while gpt4-turbo deployed on azure was working with `logprobs=True`, `top_logprobs=5`, now the same code is getting

```
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model does not support the 'logprobs' parameter.", 'type': 'invalid_request_error', 'param': 'logprobs', 'code': None}}
```

**Comment by kristapratico** [comment]
> @kristapratico could you please still update this thread once it is available on Azure? I believe quite a few of us are subscribed to it because of that.
> 
> Thanks!

Yes. AFAIK it is still not officially supported.

**Comment by Toubat** [comment]
> For a while gpt4-turbo deployed on azure was working with `logprobs=True`, `top_logprobs=5`, now the same code is getting
> 
> ```
> openai.BadRequestError: Error code: 400 - {'error': {'message': "This model does not support the 'logprobs' parameter.", 'type': 'invalid_request_error', 'param': 'logprobs', 'code': None}}
> ```

Ran into the same issue. Have you found a solution?

**Comment by MarcusElwin** [comment]
Same issue here:
```python
BadRequestError: Error code: 400 - {'error': {'message': "This model does not support the 'logprobs' parameter.", 'type': 'invalid_request_error', 'param': 'logprobs', 'code': None}}
```

**Comment by gopikrishnachaganti** [comment]
i am also getting the same error with openai 1.13.3 latest version. can somebody help which version has the logprobs support for chat completion api for AzureOpenAI?

**Comment by rattrayalex** [comment]
As @kristapratico said above, this is still not supported in the Azure
API. It's not an SDK issue.

**Comment by pradeepdev-1995** [comment]
Any update on this?

**Comment by pierre-nedelec** [comment]
Really interested in this as well!

**Comment by kristapratico** [comment]
logprobs / top_logprobs are now supported on Azure with API version 2024-03-01-preview.

**Comment by joshuafernandes** [comment]
Hi @kristapratico thanks for this. Does the current implementation in `2024-03-01-preview.` actually return logprobs values or does it just allow the params as a passthrough? Not sure if Im doing something incorrect though, so would appreciate any pointers

I've got `openai 1.30.1` and the following on GPT-4-32k /0613 (I have tried GPT-4/0613 as well with the same result)

```
client = AzureOpenAI(
        azure_endpoint=ai_endpoint,
        api_key=ai_api_key,
        api_version="2024-03-01-preview",
    )
    completion = client.chat.completions.create(
      model="gpt-4-32",
      messages=messages,
      temperature=0,
      max_tokens=800,
      logprobs=True,
      top_logprobs=2,
      extra_body={
          "data_sources": [
              {
                  "type": "azure_search",
                  "parameters": {
....................
```
which lets me run the request fine but always returns the following only

```
ChatCompletion(id='644940......f4f8ae', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="To run 
```
It's always None and never an actual value so its impossible to figure out the confidence level

Cheers

**Comment by kristapratico** [comment]
@joshuafernandes it looks like you're using the on your data feature. I'm hearing that `logprobs` is not supported with on your data so I think this is expected.

**Comment by joshuafernandes** [comment]
Hi @kristapratico thanks for that :) That is correct, Im using my own data for this one. How does one get a confidence of the answer when using custom data? Ideally we'd like to automate some things and have the bot reply when the confidence was above a certain threshold

**Comment by kristapratico** [comment]
@joshuafernandes there is currently no confidence returned by the API, but I've shared your feedback with the team. One thing you might try is adjusting the `strictness` parameter which provides a way to filter out documents which don't have high similarity scores.

Information on the parameter: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data?tabs=ai-search#runtime-parameters

**Comment by joshuafernandes** [comment]
Gotcha thankyou @kristapratico for sharing it with the team. 

I don't know how feasible this is, but maybe another option in the interim might be would be to include the `@score` parameter returned as part of the citations when it queries Azure AI search - that would work just as well to gauge confidence?

**Comment by kristapratico** [comment]
@joshuafernandes I think it is more likely that Azure OpenAI will add support for logprobs. Your feedback helps better prioritize the feature, so thank you!

**Comment by r-pathak** [comment]
Bumping this - would love to know when this will be supported by Azure.

**Comment by wyatt-halluminate** [comment]
adding my support here for AzureOpenAI to support logprobs

**Comment by hjenryin** [comment]
Probably you already know it from [another issue](https://github.com/openai/openai-python/issues/1468#issuecomment-2227345227), but setting api version to "2024-06-01" does the trick for me. `logprobs` and `top_logprobs` work now.

**Comment by wyatt-halluminate** [comment]
thanks @hjenryin !
