### ISSUE TITLE
Is there a way to print or log to a file every word that is sent to the OpenAI API, in the same format that the API receives them?

### ISSUE THREAD

**Issue by tyler-suard-parker** [openai/openai-python#1081]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

I would like to be able to view whatever gets sent to the OpenAI API, after it gets sent, as a .json.  I would like to see what the OpenAI server sees when my messages arrive to it.

### Additional context

This would help with building my own agents using existing framework.

**Comment by rattrayalex** [comment]
You should be able to do this with a custom `http_client` using [httpx `event_hooks`](https://www.python-httpx.org/advanced/#event-hooks), which can be used as interceptors / middleware, for example:

```py
def log_request(request):
    print(f"Request event hook: {request.method} {request.url} - Waiting for response")

def log_response(response):
    request = response.request
    print(f"Response event hook: {request.method} {request.url} - Status {response.status_code}")

client = openai.OpenAI(
    http_client=httpx.Client(
        event_hooks={'request': [log_request], 'response': [log_response]}
    )
)
```
but where you print the request/response body.
