### ISSUE TITLE
When debug logging is enabled, api-key header is also printed

### ISSUE THREAD

**Issue by danigian** [openai/openai-python#1082]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When debug logging is enabled, `FinalRequestOptions` is entirely dumped because of the following code:

https://github.com/openai/openai-python/blob/3d61ed42aba652b547029095a7eb269ad4e1e957/src/openai/_base_client.py#L436-L437

This includes the `api-key` header that would be great to avoid logging

### To Reproduce

1. Enable debug logging
2. Get a AsyncAzureOpenAI client and execute any kind of request against the service
3. See the api-key getting logged as part of the headers

### OS

WSL

### Python version

Python v3.9.18

### Library version

openai v1.7.2

**Comment by rattrayalex** [comment]
Thanks for raising, we'll look into this.

**Comment by jkondek1** [comment]
Is thera any update concerning this issue?

**Comment by abaerptc** [comment]
Are there plans to fix this soon?

**Comment by RobertCraigie** [comment]
this was fixed in `1.54.3`!
