### ISSUE TITLE
openai_object

### ISSUE THREAD

**Issue by hzy20001211** [openai/openai-python#1091]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am 
from openai import openai_object

it reports the error:
ImportError: cannot import name 'openai_object' from 'openai'

my openai version is 1.8.0
I wonder if there exist a version problem

### To Reproduce

1.from openai import openai_object
2.ImportError: cannot import name 'openai_object' from 'openai'

### OS

Linux

### Python version

Python v3.8

### Library version

openai v1.8.0

**Comment by rattrayalex** [comment]
This has been removed from the library in v1

**Comment by hzy20001211** [comment]
> This has been removed from the library in v1.

So are there any other interfaces that replace this class?

**Comment by rattrayalex** [comment]
The SDK has been completely rewritten, so I suggest getting familiar with the new setup. There may or may not be a directly comparable class depending on your exact needs.

**Comment by Haruka1307** [comment]
how about downgrade to 0.28.0 ?
