### ISSUE TITLE
when I use gpt-3.5-turbo-1106, an openai.APIStatusError occurred

### ISSUE THREAD

**Issue by TheHonestBob** [openai/openai-python#1096]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

openai.APIStatusError: <html>
  <head>
    <title>Request Header Fields Too Large</title>
  </head>
  <body>
    <h1><p>Request Header Fields Too Large</p></h1>
    Error parsing headers: &#x27;limit request headers fields&#x27;
  </body>
</html>

### To Reproduce

无

### Code snippets

```Python
stream = OpenAI(api_key='my key').openai_engine.chat.completions.create(
                    model="gpt-3.5-turbo",
                    messages=messages,
                    stream=True,
                    temperature=0.1
                )
```

### OS

linux

### Python version

python3.9

### Library version

openai 1.9.0

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
