### ISSUE TITLE
Chat completion endpoint cannot remember its previous messages

### ISSUE THREAD

**Issue by HuskyDanny** [openai/openai-python#1097]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

![image](https://github.com/microsoft/semantic-kernel/assets/40053881/33ab5f58-d40e-4781-993f-7152cb29016d)
With this request, llm should answer my last question. But it says it doesn;t know. Is ChatPromptTemplate with chat completion endpoint supposed to remember the previous messages or I should manually added them in the latest user prompt?
Chat completion takes a list of messages
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/88e62be8-d05c-4175-a303-05f3f483fc2e)
Response saying don't know previous message
![image](https://github.com/microsoft/semantic-kernel/assets/40053881/d270c98a-2026-42a7-a559-03ce2c0aafa3)

### To Reproduce

This is my code for setting up using semantic kerner which uses openai package in the end to send the request, basically it add the previous messages into the ChatPromptTemplate.
```
system_message = """
You are a technical supporter that help users' questions, you should give 1-2 sentences to explain the answer and code examples for the question based on only the following contexts.
You may find the contexts provide information for multiple potential answers, you can give up to 3 most relevant answers separated by numbers like 1. 2. 3.

Follow this pattern to answer the question:
Contexts:
- Document path_title1 : page_content1
&&&
- Document path_title2 : page_content2

Question: question

Answer: answer
"""

prompt_template = """
Contexts:
{{$context}}

Question: {{$input}}
"""

def preprocess_messages(messages : list):
    transformed_messages = []
    transformed_messages.append({"role": "system", "message": system_message})
    for message in messages:
      role = "assistant" if message["role"] == "bot" else message["role"]
      transformed_message = {"role": role, "message": message["content"]}
      if (role != "system"):
        transformed_messages.append(transformed_message)
    return transformed_messages

def create_chat_prompt_template_instance(kernel : Kernel, messages : list = []):
    req_settings = sk_oai.AzureChatRequestSettings(max_tokens=2000, temperature=0, extension_data={"chat_system_prompt": system_message})
    req_settings.unpack_extension_data()
    config = PromptTemplateConfig(completion=req_settings)
    template = ChatPromptTemplate(prompt_template, kernel.prompt_template_engine, config)
    if (messages and len(messages) > 0):
      processed_messages = preprocess_messages(messages)
      for message in processed_messages:
        template.add_message(message["role"], message["message"])
    function_config = SemanticFunctionConfig(config, template)
    return kernel.register_semantic_function("ChatBot", "rag_chat", function_config)

  # simplified calling
  messages = [{"content": "Q1", "role": "user"}, {"content": "A1", "role": "bot"},{"content": "Q2", "role": "user"}]
  query=messages[-1]['content']
  context['context'] = combined_documents
  context['input'] = query

  previous_messages = messages[:-1]
  chat_function = create_chat_prompt_template_instance(kernel=kernel, messages=previous_messages)

  response = await kernel.run_async(chat_function, input_context=context)
```

### OS

Ubuntu

### Python version

python3.9

### Library version

openai1.0

**Comment by HuskyDanny** [comment]
It seems like different wording will bring gpt's memory back, this is confusing

![image](https://github.com/microsoft/semantic-kernel/assets/40053881/b0f33e9c-4fad-439f-b591-72618680f66e)

**Comment by rattrayalex** [comment]
This does not look like a bug in the SDK (more like a prompt engineering question or a problem in the underlying model), so I'm going to go ahead and close this issue. 
For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!
