### ISSUE TITLE
Bug in the clustering jupyter example

### ISSUE THREAD

**Issue by giosilvi** [openai/openai-python#110]
In the following code in the clustering notebook example, at the first cell:

```
df['text-similarity-babbage-001'] = df.babbage_similarity.apply(eval).apply(np.array)
matrix = np.vstack(df.babbage_similarity.values)
```

the second  line should be the following: `matrix = np.vstack(df['text-similarity-babbage-001'].values)`

**Comment by ted-at-openai** [comment]
Thanks! I'll fix it this week.

**Comment by hallacy** [comment]
Hi @giosilvi, does the commit above fix your issue?

**Comment by giosilvi** [comment]
Yes, that fixes it!
