### ISSUE TITLE
[Assistants API] Run Step Tool call element changes type depending on run status

### ISSUE THREAD

**Issue by jordan-barrett-jm** [openai/openai-python#1107]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When polling run steps to read tool calls, I've observed that when the run is not in status 'completed' the function object in the `tool_calls` array is of type `dict`, however, once the run is completed it becomes a regular object. This has implications for how the tool call attributes can be accessed, leading to redundant code checking the element type. I have specifically observed this with function tool calls. I haven't done any work with the other types of Assistant tools.

### To Reproduce

1. Initiate a run that requires the use of a function
2. Retrieve the latest run step associated with the run
3. Attempt to read the tool calls when the run is of status `completed` versus when it's in an `in_progress `or `requires_action `state.

### OS

Windows 11

### Python version

Python v3.9,3

### Library version

openai v1.3.5

**Comment by rattrayalex** [comment]
cc @athyuttamre do you know why this might be happening? (my guess is the object shape changes in ways that aren't documented properly in the openapi spec)

**Comment by athyuttamre** [comment]
Thanks for the report! I think it's because of a bug in our OpenAPI spec, attempting to fix here: https://github.com/openai/openai-openapi/pull/187.
