### ISSUE TITLE
Can't import openai module without authentication error

### ISSUE THREAD

**Issue by lostinplace** [openai/openai-python#1108]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Given the following import:

```python
def do_stuff():

    secret = "vgtc/dev/openai-secret"
    secret_values = get_secret_json(secret)
    
    import openai

    client = openai.OpenAI(**secret_values)
```

The exception is raised:

"The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"

This happens because on line 316 of `openai/__init__.py`  it attempts to initialize client proxies (before I have requested initialization to occur)

This isn't a problem for those who use environment variables to leak their secrets to processes, but for those of us who want stricter control of our secrets than what is available by handing them over to the OS, it makes it impossible to even import the library without creating an exception to our security policy.

Here's a blog post on it:

https://www.cloudtruth.com/blog/the-pitfalls-of-using-environment-variables-for-config-and-secrets#:~:text=Developers%20often%20use%20environment%20variables,information%20poses%20significant%20security%20risks.

### To Reproduce

1. New environment
2. pip install openai
3. `import openai`
4. See crash

### OS

Win11

### Python version

3.12

### Library version

openai v1.10.0"

**Comment by rattrayalex** [comment]
Can you share a stacktrace?

**Comment by ducminh-phan** [comment]
I also encountered this issue, but only when debugging with Pycharm. Here's the stack trace:

```
  File "/*****/main.py", line 1, in <module>
    import openai
  File "/*****/venv/lib/python3.12/site-packages/openai/__init__.py", line 316, in <module>
    from ._module_client import (
  File "/*****/venv/lib/python3.12/site-packages/openai/_module_client.py", line 69, in <module>
    chat: resources.Chat = ChatProxy().__as_proxied__()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 504, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PyRaiseCallback.__call__
  File "_pydevd_bundle/pydevd_pep_669_tracing_cython.pyx", line 47, in _pydevd_bundle.pydevd_pep_669_tracing_cython.PEP669CallbackBase.frame
  File "/*****/venv/lib/python3.12/site-packages/openai/_utils/_proxy.py", line 49, in __class__
    proxied = self.__get_proxied__()
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/*****/venv/lib/python3.12/site-packages/openai/_utils/_proxy.py", line 55, in __get_proxied__
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "/*****/venv/lib/python3.12/site-packages/openai/_module_client.py", line 12, in __load__
    return _load_client().chat
           ^^^^^^^^^^^^^^
  File "/*****/venv/lib/python3.12/site-packages/openai/__init__.py", line 295, in _load_client
    _client = _ModuleClient(
              ^^^^^^^^^^^^^^
  File "/*****/venv/lib/python3.12/site-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by rattrayalex** [comment]
Ah, I believe that's a separate issue. Can you report it to the PyCharm team? (cc @RobertCraigie who has worked on this area). In the meantime, you can work around the problem by setting an API Key with an environment variable.

Without more information, the bug reported here isn't something I can action, so I'm going to go ahead and close this issue. If @lostinplace is able to share more details, we can reopen.

**Comment by RobertCraigie** [comment]
Yes this is a pycharm specific issue, they changed something recently which results in it being much more greedy and calls into places it shouldn't which then triggers validation on our end.

**Comment by Znunu** [comment]
bumping this because I had the same issue while using pycharm. I actually don't mind setting an environment variable instead, but this is one of those cryptic errors, so it took me a long time to find out what's wrong

**Comment by rattrayalex** [comment]
@Znunu can you please report this to PyCharm? Or bump the PyCharm bug if it already exists?
