### ISSUE TITLE
AsyncAzureClient connection hangs frequently

### ISSUE THREAD

**Issue by nsbradford** [openai/openai-python#1109]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

something very strange: the python OpenAI AzureClient works fine, but using the AsyncAzureClient results in hanging connection ~5% of the time

### To Reproduce

Run a bunch of requests (~100) to GPT-4 using `AsyncAzureClient`, eventually one of them will hang for 20+ minutes before timing out

### OS

macOS

### Python version

Python v3.11.6

### Library version

1.6.1

**Comment by rattrayalex** [comment]
Hi @nsbradford – what gives you the sense that this is an SDK problem rather than an API problem on the Azure end?

**Comment by rattrayalex** [comment]
cc @kristapratico

**Comment by nsbradford** [comment]
hi there! if I run my suite of tests I only ever experience this using AsyncAzureClient, with AzureClient it always works fine. I'll try and create a minimal example, but because it's so low-frequency it might be tricky...

**Comment by nsbradford** [comment]
I seem to be able to replicate it pretty reliably (maybe 10-20% of the time?) with requests to "gpt-4-32k-0613" that are over 20k tokens using the async client - the problem happens with both Azure and OpenAI endpoints. But never with the sync client (!?)

**Comment by kristapratico** [comment]
@nsbradford do I have this right?

- Hang only occurs with async
- Reproduces with both Azure and OpenAI endpoints

I'll try to repro this on my end. At first I suspected rate limiting with a large retry-after value, but that wouldn't make sense if you aren't seeing this with the sync client. 

I'd suggest enabling [debug logging](https://github.com/openai/openai-python?tab=readme-ov-file#logging) to help troubleshoot this issue and also upgrading your `openai` library to the latest if you haven't already.

**Comment by rattrayalex** [comment]
>  Running the bad request via the script below directly does not timeout, but it does timeout when running my application. Is there any other possible reason this could be happening so consistently?

Interesting. Can you share more about your application setup, in particular what kind of async setup you're using, what multithreading/similar you're doing, and how many things dealing with OpenAI in parallel you may be doing?

And just to be clear - you're seeing this with both `AsyncOpenAI` and `AsyncAzureOpenAI`, yes?

**Comment by rattrayalex** [comment]
cc @RobertCraigie for thoughts here

**Comment by nsbradford** [comment]
Thanks! It seems to happen both when i'm using pytest, and when I'm running in production on Celery workers. When I start a workflow that runs several LLM requests back to back, it's never the first one that fails, usually after only a few. There are never any other tests or requests being made at the same time. It seems to be only on larger requests; the one i'm able to see happen regularly is 20k+ tokens

Anecdotally, the only thing that this reminds me of is that the JavaScript SDK also used to hang sometimes if you submitted a very large request to GPT-4 (but haven't tested that in 6 months)

But again, we've never seen it happen with the Sync openai client, while on the Async client it happens quite often in both dev and prod :( My totally harebrained suspicion: something about the underlying http client behaves weirdly on very large/long-running requests?

**Comment by RobertCraigie** [comment]
@nsbradford I suspect the underling cause of your issue is [this one](https://github.com/encode/httpcore/issues/830) which should hopefully be [fixed soon](https://github.com/encode/httpcore/issues/830#issuecomment-1916467037).

**Comment by aryan1107** [comment]
#1134 Also is similar lot of timeouts in Azure and customer can't wait for 120+ seconds for answer.

**Comment by nsbradford** [comment]
Thanks @RobertCraigie (and good to see the Stainless team again), looking forward to the release 🙏

**Comment by RobertCraigie** [comment]
Please try installing `httpcore==1.0.3`! This should fix the issues you're seeing.
