### ISSUE TITLE
Seed

### ISSUE THREAD

**Issue by csipapicsa** [openai/openai-python#1116]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [x] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Hi,

I would like to inquire about the behavior of the seed value in making chat interactions deterministic. Currently, it seems that the determinism is only "more or less" reliable, often deviating from the expected path after the second response-answer, regardless of the model used. Could this be addressed or clarified in future updates?

**Comment by rattrayalex** [comment]
This sounds like a question about the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
