### ISSUE TITLE
Mypy typing error when treating a ChatCompletionSystemMessageParam as dict

### ISSUE THREAD

**Issue by pamelafox** [openai/openai-python#1123]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

We have a list like:

```
messages: list[ChatCompletionMessageParam]
```

We then convert a message to a dict:

```
dict(messages[0])
```

Mypy does not like that:

Argument 1 to "dict" has incompatible type "ChatCompletionSystemMessageParam | ChatCompletionUserMessageParam | ChatCompletionAssistantMessageParam | ChatCompletionToolMessageParam | ChatCompletionFunctionMessageParam"; expected "SupportsKeysAndGetItem[str, str]"  [arg-type]

I'm not sure if this is a bug with mypy or with the SDK, to be honest. Or maybe there's even a better approach in our code. I see that your classes extend TypedDict, so I'd think that should be considered as SupportsKeysAndGetItem, but I'm probably missing something.

### To Reproduce

See code above. You can also see our CI failing here: https://github.com/Azure-Samples/azure-search-openai-demo/actions/runs/7786990746/job/21233073297?pr=1233

### OS

MacOS

### Python version

3.11

### Library version

1.10.0

**Comment by RobertCraigie** [comment]
Unfortunately this looks to just be a mypy bug. [Pyright](https://github.com/microsoft/pyright) doesn't report any errors in this case.

Note that in general I would strongly recommend just relying on Pyright as bugs and features are implemented at a much faster rate compared to mypy.

**Comment by pamelafox** [comment]
We can look into pyright, we've been using mypy for more of our projects. Pyright makes sense given we're from Microsoft but mypy seems to be more popular with Python community.

**Comment by RobertCraigie** [comment]
Ah @pamelafox, you can't pass TypedDicts to functions that expect a dict because that dictionary could be mutated to include leys that aren't present on the TypedDict or other similar issues.

You have two options that I can see:
- Use `Mapping[str, object]` if you dont do any mutation
- Reference our types directly

**Comment by pamelafox** [comment]
Ah, great point! `Mapping[str, object]` works for those functions (they do not mutate) and makes mypy happy. Feel free to close this, unless there are additional improvements planned.

By the way, I just looked up DL numbers for mypy vs pyright, and its 5 million weekly vs 400K weekly, so we might move to pyright ourselves but I expect much of the community will still use mypy.

**Comment by sanmai-NL** [comment]
@pamelafox You may close this yourself.
