### ISSUE TITLE
Add a return-type flag to the CLI fine-tuning command

### ISSUE THREAD

**Issue by samlouiscohen** [openai/openai-python#113]
I'm using the OpenAI CLI fine-tuning command `openai api fine_tunes.create` within an automated data-collection + training loop. Given that this process is automated, it would be really helpful to have the ability to specify the output format from this command - specifically the ability to just return the new fine-tuned model ID rather than the whole text block (which then needs to be parsed).

**Comment by hallacy** [comment]
Hi @samlouiscohen! Thanks for the issue.  Can you elaborate a bit more on what you're currently seeing versus what you'd like to see?

**Comment by hallacy** [comment]
I'm going to close this issue due to lack of activity.  Please feel free to reopen it!
