### ISSUE TITLE
export 'Usage' class as apart of openai.types

### ISSUE THREAD

**Issue by lilyydu** [openai/openai-python#1135]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Hi there,

I'm using the library and writing tests to mock `CreateEmbeddingResponse`. To mock the class, I'm configuring the properties, including the `usage` parameter. I'd like to instantiate a '`Usage`' object for this. Hence, requesting it to be exported with `openai.types.` Thanks!

**Comment by rattrayalex** [comment]
cc @RobertCraigie can you share how to access this?

**Comment by RobertCraigie** [comment]
Hi @lilyydu, there are two ways you can access the `Usage` type today:
```py
from openai.types.create_embedding_response import Usage
```

or

```py
from openai.types import create_embedding_response

create_embedding_response.Usage
```
