### ISSUE TITLE
Assistants API

### ISSUE THREAD

**Issue by Dyke-F** [openai/openai-python#1139]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Is there a way to customize the Assistants chat response? 
Given the outcome of certain tool uses, id like the assistant to respond in a different manner. 

I guess this somehow should happen in the client.beta.threads.runs.create function

**Comment by charlyjazz-sprockets** [comment]
Use instructions or extra instructoin in the run arguments
