### ISSUE TITLE
AttributeError: 'function' object has no attribute 'completion'

### ISSUE THREAD

**Issue by abhiram1809** [openai/openai-python#1142]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

```

client = OpenAI(api_key = "API-KEY")
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)
```

Gives an Error on Colab
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-26-2409eaa814b3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 chat_completion = client.chat.completions.create(
      2     messages=[
      3         {
      4             "role": "user",
      5             "content": "Say this is a test",

AttributeError: 'function' object has no attribute 'completions'
`
Version: openai 1.12.0

### To Reproduce

```
client = OpenAI(api_key = "API-KEY")
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)
```

### Code snippets

```Python
Already Attached
```

### OS

linux

### Python version

Python 3.11

### Library version

openai v1.12.0

**Comment by seohyunjun** [comment]
i have same issue now 

might be define class some error 

i solved 

direct import module

``` python
import openai

messages_pompt = []
messages_pompt += [{"role":"user", "content": promt}]
response = openai.chat.completions.create(
        messages = messages_pompt,
        model="gpt-3.5-turbo-0613",
        temperature=0,
        max_tokens=500,
    )
```
