### ISSUE TITLE
`usage` of Completion.Create is None 

### ISSUE THREAD

**Issue by GalDayan** [openai/openai-python#1145]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

usage object is None - how could it be?
It didn't happen before; today, that's the first time it happened.
What is the scenario in which usage is None? 
Why was it the first time that happened?

### To Reproduce

Run the code about with openai version = 1.3.3 or 1.12.0 and usage object will be none.

### Code snippets

```Python
openai_response = self.client.chat.completions.create(
            model=model, messages=messages, temperature=temperature,
            max_tokens=max_tokens, top_p=top_p,
            frequency_penalty=frequency_penalty, presence_penalty=presence_penalty, stop=stop
        )

        openai_usage = openai_response.usage # Sometimes usage is None
```
```


### OS

Linux

### Python version

Python 3.9.18

### Library version

openai v1.3.3 or openai v1.12.0
Using Azure OpenAI

**Comment by berniwal** [comment]
I encountered the same issue today, for me this happens only for the "gpt-35-turbo-0301" engine, other engines are working as expected. I am using the api_version "2023-09-15-preview".

**Comment by rattrayalex** [comment]
This does not look like a bug in the SDK, so I'm going to go ahead and close this issue.

The API may not always respond with `usage`.
