### ISSUE TITLE
name 'openai' is not defined in openai 1.2.0

### ISSUE THREAD

**Issue by ejgutierrez74** [openai/openai-python#1151]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

This code should work as documented in usage https://github.com/openai/openai-python

Also i have doubt about using client with or without api key as parameter...in courses of OpenAi form DeepLearning, they show client without api key as parameter, and they prefer to use an environment variable saved in a .env file.:

```
client = OpenAI(
    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY"),
)

```

or

`client = OpenAI()`

### To Reproduce

1 - Execute the snippet below from DeepLearning official short course. Reading the usage of your main github file as linked above, it should work.

2 - Gives error : name 'openai' is not defined in openai 1.2.0

### Code snippets

```Python
from openai import OpenAI
import os


from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv()) # read local .env file

openai.api_key  = os.getenv('OPENAI_API_KEY')

client = OpenAI()

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0
    )
    return response.choices[0].message.content



def get_completion_from_messages(messages, 
                                 model="gpt-3.5-turbo", 
                                 temperature=0, 
                                 max_tokens=500):
    response = client.chat.completions.create(model=model,
    messages=messages,
    temperature=temperature, 
    max_tokens=max_tokens)
    return response.choices[0].message.content

messages =  [  
{'role':'system', 'content':'You are an assistant that speaks like Shakespeare.'},    
{'role':'user', 'content':'tell me a joke'},   
{'role':'assistant', 'content':'Why did the chicken cross the road'},   
{'role':'user', 'content':'I don\'t know'}  ]

response = get_completion_from_messages(messages)
print(response)
```
```


### OS

Ubuntu 22.04

### Python version

Python 3.11

### Library version

openai v1.2.0

**Comment by ejgutierrez74** [comment]
I dont think if its correct but seems this work, as i have RateLimitsError

```
import os

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv()) # read local .env file

from openai import OpenAI

client = OpenAI(    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY")
)

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0
    )
    return response.choices[0].message.content



def get_completion_from_messages(messages, 
                                 model="gpt-3.5-turbo", 
                                 temperature=0, 
                                 max_tokens=500):
    response = client.chat.completions.create(model=model,
    messages=messages,
    temperature=temperature, 
    max_tokens=max_tokens)
    return response.choices[0].message.content
```

**Comment by rattrayalex** [comment]
You figured it out – you needed to remove this line `openai.api_key  = os.getenv('OPENAI_API_KEY')`

the rate limiting error you mention is not a problem from the SDK, but may be due to an unrelated problem like needing to activate billing, get a new API key, or reduce your traffic.

**Comment by ejgutierrez74** [comment]
Then would be nice to update the doc:

1 - When as the doc in DeepLearning courses says

`client = OpenAI( )`

Then the api key should be loaded in somewhere sometime...isnt it ?

2 - In the second case your doc:

client = OpenAI(    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY")
)

I assume that should be a .env file in the same directory of the notebook, with the key value line:
OPENAI_API_KEY = "sk-dsfdsfds-...."

Am i right it ??

And then about RatelimitError, im just following the course, and didnt do anything...the first call i made outside the course notebook it gives me that error...dont know if its openai or library bug/problem...probably openai...

Thanks

**Comment by rattrayalex** [comment]
Hi @ejgutierrez74, those are totally reasonable questions! We use GitHub issues for tracking bugs in the SDK. For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!

**Comment by ejgutierrez74** [comment]
Thanks @rattrayalex , but perhaps as you work with openai, you know the answer....

But to be more concrete in your doc of usage:


```
from openai import OpenAI, 

client = OpenAI(    # This is the default and can be omitted
    api_key=os.environ.get("OPENAI_API_KEY")
)

```
This does not work because you have to previously load the OPENAI_API_KEY as i noted in previous post:

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv()) # read local .env file

Should be added in my opinion to the code in usage of openai-python library. Or at least write that openai key should be loaded.

Thanks
