### ISSUE TITLE
'timestamp granularity', new featured added to AudioAPI Feb 9th not accessible

### ISSUE THREAD

**Issue by fanpeeps** [openai/openai-python#1153]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

audio.transcriptions.create() parameter 'timestamp_granularities' not recognized.  

As per API changelog, parameter added to API Feb 9th:
https://platform.openai.com/docs/changelog

### To Reproduce

passing timestamp_granularities=["word"] to audio.transcriptions.create() results in 

TypeError: Transcriptions.create() got an unexpected keyword argument 'timestamp_granularities'

### Code snippets

```Python
---> 19 transcript = client.audio.transcriptions.create( #openai.audio.transcriptions.create(
     20   file=wavfile,
     21   model="whisper-1",
     22   response_format="verbose_json",
     23   timestamp_granularities=["word"]
     24 )

TypeError: Transcriptions.create() got an unexpected keyword argument 'timestamp_granularities'
```

### OS

All

### Python version

3.11.4

### Library version

openai-1.12.0

**Comment by fanpeeps** [comment]
Documented parameter under Timestamps heading on this page:

https://platform.openai.com/docs/guides/speech-to-text/supported-languages

**Comment by rattrayalex** [comment]
Thanks for raising this. I'm checking with the appropriate team what the correct course of action is.

**Comment by rattrayalex** [comment]
ah, this is in the latest release; you just need to upgrade your package.
