### ISSUE TITLE
All API Errors raised during streaming raise the same generic message ("An error occurred during streaming")

### ISSUE THREAD

**Issue by tdene** [openai/openai-python#1160]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

All API Errors raised during streaming raise the same generic message ("An error occurred during streaming").    
See [line 64 of _streaming.py](https://github.com/openai/openai-python/blob/main/src/openai/_streaming.py#L64).

The `data["error"]` field is completely disregarded for streaming errors. Instead, it could be read to raise the correct type of error.
This is a major quality-of-life issue with custom inference servers that seek to follow the openai standard.

### To Reproduce

1. Spin up a custom inference server.
2. Have users access it via the `openai` Python library.
3. Introduce an arbitrary error in your inference server, and handle it correctly, by returning the error's code, param, and type inside of the streaming response.
4. Notice that the users will always get the generic "An error occurred during streaming" message.

### Code snippets

```Python
The relevant part of the codebase uses this code snippet:

if is_mapping(data) and data.get("error"):
    raise APIError(
        message="An error occurred during streaming",
        request=self.response.request,
        body=data["error"],
    )
```

A different part of the codebase uses this code snippet:
```
raise self._make_status_error_from_response(err.response) from None
```

This latter type of functionality should also be used while iterating over a stream.
```


### OS

Ubuntu 20.04.5 LTS

### Python version

Python v.3.11.6

### Library version

openai v1.11.1

**Comment by aryan1107** [comment]
this might be due to moderation being triggered.

**Comment by clemlesne** [comment]
Frequently having the same issue with GPT-4 0116-Preview on Azure OpenAI.

**Comment by RobertCraigie** [comment]
Sorry about this! The error messages will be improved in the next release https://github.com/openai/openai-python/pull/1218/files

**Comment by vishuhumanliai** [comment]
I'm having this issue with gpt-4o + agent implementation, can anybody help me out?
raise APIError(
openai.APIError: An error occurred during streaming)

**Comment by RobertCraigie** [comment]
Are you on the latest version?

**Comment by vishuhumanliai** [comment]
> Are you on the latest version?
I'm using these versions
openai==1.8.0,
langchain==0.1.1

**Comment by RobertCraigie** [comment]
You are on quite an old version that does not include this fix. Please upgrade
