### ISSUE TITLE
`openai migrate` fails to translate multiple `except` blocks with old `openai.error` objects

### ISSUE THREAD

**Issue by liffiton** [openai/openai-python#1165]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am running `openai migrate` on a codebase written for 0.28.1, and it doesn't correctly process a try/except with multiple except blocks.  E.g.

```
try:
   [calling the completions API]
except openai.error.RateLimitError as e:
   [handle it]
except openai.error.AuthenticationError as e:
   [handle it]
[other except blocks with other openai.error.* types...]
```

The migrate command translates just the first except block to use the newer class (`openai.RateLimitError`, e.g.) and ignores the later ones.

Each time I re-run `openai migrate` it translates one more except block, so that is a simple workaround.

### To Reproduce

1. Write a simple test case like the above code.
2. Run `openai migrate`
3. See it translates only one except block.

### OS

Linux

### Python version

Python v3.10.12

### Library version

openai v1.12.0

**Comment by rattrayalex** [comment]
Thanks for the report!

Cc @morgante

**Comment by morgante** [comment]
Fix should be out shortly: https://github.com/getgrit/stdlib/pull/114

**Comment by rattrayalex** [comment]
Thanks for reporting @liffiton and for fixing @morgante !
