### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by ducminh-phan** [openai/openai-python#117]
In the function `openai.embeddings_utils.get_embeddings` ([code](https://github.com/openai/openai-python/blob/3edecbee24102299dd6e4a35af031780e9ad0f9a/openai/embeddings_utils.py#L30)), there is a check for the length of the input texts list:

```python
assert len(list_of_text) < 2048, "The batch size should not be larger than 2048."
```

From the error message `The batch size should not be larger than 2048`, I expect that this function accepts a list of length 2048. However, the assertion `assert len(list_of_text) < 2048` allows a maximum length of 2047. I find this quite confusing.

**Comment by hallacy** [comment]
I think that makes sense. It seems like it should be a <= instead of a <.

Added as part of https://github.com/openai/openai-python/pull/118
