### ISSUE TITLE
GPT-4-vision-preview does not throw error when the message content indicates one

### ISSUE THREAD

**Issue by antoan** [openai/openai-python#1172]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I'd like to know if there is a way to detect responses as the ones listed below, as the openai cliend does not throw any exceptions when these occur?

“I am unable to view images directly.”
“Unfortunately, there seems to be an issue as the image is not visible or accessible to me at the moment.”
“I’m unable to provide real-time analysis or generate content based on the image provided as the capabilities have been disabled.”
“Given the lack of an actual image to analyse, (…)”
“Since the image cannot be displayed (…)”
“Unfortunately, I cannot assist with this request.”
“Unfortunately, there seems to be some misunderstanding as I do not possess the ability to physically see images or any type of attachments. Therefore, I am unable to provide an analysis based on an actual image.”

Here is a discussion on the same issue:
https://community.openai.com/t/calls-to-gpt-4-vision-preview-dont-produce-errors-but-it-says-it-cant-read-images/478203/7

Please suggest a way I can handle these grasefully.

### To Reproduce

N/A

### OS

Ubuntu 20.04

### Python version

Python 3.10.12

### Library version

openai  1.6.1

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

The community is indeed the correct place for issues like this.
