### ISSUE TITLE
Simple stream example does not work with GPT-4 model

### ISSUE THREAD

**Issue by haje01** [openai/openai-python#1176]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Hi, I'm using OpenAI Python API version 1.12.0

The simple stream example from your GitHub repository does not work on the GTP-4 model. The GPT-3.5-Turbo model worked without issue. 

```python
from openai import OpenAI

client = OpenAI()

stream = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")
```

Error message:
```
Traceback (most recent call last):
  File "/home/haje01/test.py", line 25, in <module>
    for chunk in response:
  File "/home/haje01/.pyenv/versions/ml/lib/python3.9/site-packages/openai/_streaming.py", line 43, in __iter__
    for item in self._iterator:
  File "/home/haje01/.pyenv/versions/ml/lib/python3.9/site-packages/openai/_streaming.py", line 62, in __stream__
    raise APIError(
openai.APIError: An error occurred during streaming
```

### To Reproduce

1. `pip install openai==1.12.0`
2. run above code

### OS

Ubuntu 20.04.5 LTS (WSL)

### Python version

Python 3.9.15

### Library version

openai 1.12.0

**Comment by rattrayalex** [comment]
Is that the entire stacktrace? Can you share any more details?

**Comment by haje01** [comment]
The code hasn't worked since yesterday, probably because of this issue
https://status.openai.com/incidents/ssg8fh7sfyz3

But it suddenly started working well a few hours after I reported it. You can safely assume that the issue I reported has been resolved.

Thank you for your attention!
