### ISSUE TITLE
Implement the new TTS file formats

### ISSUE THREAD

**Issue by GunniBusch** [openai/openai-python#1180]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The speech api implementation is not up to date. 
It doesn’t yet support the new Output formats like WAV
https://github.com/openai/openai-openapi/pull/202

### To Reproduce

1. Create a speech request
2. Try to use e.g. wav as the media type.

### Code snippets

```Python
https://github.com/openai/openai-python/blob/a7115b5f33acd27326e5f78e19beb0d73bd3268e/src/openai/types/audio/speech_create_params.py#L29
```

### OS

macOS

### Python version

v3.11.3

### Library version

v1.13.2

**Comment by microsoftbuild** [comment]
This is strange. I have been using `client.audio.speech.with_streaming_response.create()` with the `response_format= "wav"` without any issues.

openai package v1.8.0
python version 3.11.7

**Comment by rattrayalex** [comment]
This is done: https://github.com/openai/openai-python/pull/1189
