### ISSUE TITLE
SSL errors when connecting to OpenAI azure endpoint while using library

### ISSUE THREAD

**Issue by killmepete** [openai/openai-python#1183]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Hi,

Over the last few weeks I've been configuring a site to site VPN between AWS and Azure so we can use the OpenAI endpoints that Azure now offers through a Privatelink. We're using a sample taken from the docs (with correct values replaced etc)

`import os
import openai
openai.api_type = "azure"
openai.api_base = os.getenv("AZURE_OPENAI_ENDPOINT") 
openai.api_key = os.getenv("AZURE_OPENAI_KEY")
openai.api_version = "2023-05-15"

response = openai.ChatCompletion.create(
    engine="gpt-35-turbo", # engine = "deployment_name".
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Does Azure OpenAI support customer managed keys?"},
        {"role": "assistant", "content": "Yes, customer managed keys are supported by Azure OpenAI."},
        {"role": "user", "content": "Do other Azure AI services support this too?"}
    ]
)

print(response)
print(response['choices'][0]['message']['content'])`

I'm unfortunately receiving an SSL error when attempting to connect to the Azure endpoint while on the VPN. The error is...

`Max retries exceeded with url: /openai/deployments//chat/completions?api-version=1106-preview (Caused by SSLError(CertificateError("hostname 'myorg.privatelink.openai.azure.com' doesn't match either of '*.cognitiveservices.azure.com', '*.api.cognitive.microsoft.com', '*.dev.cognitive.microsoft.com', '*.openai.azure.com'"))).
`

I initially thought this might be an issue with the domain I was using so have also attempted myorg.openai.azure.com (the endpoint seen in the azure console) and IP with the same problem. Issues I've seen similar to this online suggest a couple of solutions...

- Use certifi to find where the local certificate chain is and add the root cert which you can grab from hitting the endpoint through the browser, this has had no effect when I've tried.
- Disable SSL verification (Not really a fix and a bad solution)

I thought it could be something to do with the infrastructure setup but after running a pure SSL test I can receive a handshake from the endpoint, going via the browser also doesn't present the same certificate issue. Is this something other people have experienced or is this a bug with the openAI library/azure implementation?

### To Reproduce

1. Create an Azure endpoint with Privatelink
2. Connect to a corporate VPN
3. Run above code sample

### Code snippets

```Python
None
```

### OS

MacOS

### Python version

Python 3.8.18

### Library version

latest

**Comment by rattrayalex** [comment]
You'll likely need to [pass a custom `httpx` client](https://github.com/openai/openai-python?tab=readme-ov-file#configuring-the-http-client) configured for your VPN's SSL setup. 

See httpx's SSL docs here: https://www.python-httpx.org/advanced/ssl/
