### ISSUE TITLE
Official release version - PyPi or Github?

### ISSUE THREAD

**Issue by kekePower** [openai/openai-python#1191]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

I'm just wondering what the official release version is. I see on PyPi version 1.12.0 and here on Github version 1.13.2. Since I packaged it for Mageia, I chose to go for the version on PyPi because it felt "safer".

Thank you.

### Additional context

N/A

**Comment by rattrayalex** [comment]
Sorry about this – we had a few releases not go out to PyPI due to a bug recently. The next release will go out to PyPI as well.

**Comment by rattrayalex** [comment]
The latest version has been released to PyPI: https://pypi.org/project/openai/1.13.3/
