### ISSUE TITLE
openai.File is no longer supported

### ISSUE THREAD

**Issue by ericabutts** [openai/openai-python#1192]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

You tried to access openai.File, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

I'm trying to train an OpenAI Azure model by uploading a file but I'm getting an error that the openai.File is no longer supported.
There is no other sample documentation to explain the updated method of uploading training data to Azure OpenAI.

### To Reproduce

Try to upload a jsonl file to OpenAi Azure by using openai.File.create with the Microsoft example under "Upload your training data"
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/fine-tuning?tabs=turbo%2Cpython&pivots=programming-language-python

### Code snippets

```Python
# Upload fine-tuning files

import openai
import os

openai.api_key = os.getenv("AZURE_OPENAI_KEY")
openai.api_base =  "https://nit.openai.azure.com/"
openai.api_type = 'azure'
openai.api_version = '2023-12-01-preview' # This API version or later is required to access fine-tuning for turbo/babbage-002/davinci-002

training_file_name = 'test.jsonl'
validation_file_name = 'test.jsonl'

# Upload the training and validation dataset files to Azure OpenAI with the SDK.

training_response = openai.File.create(
    file=open(training_file_name, "rb"), purpose="fine-tune", user_provided_filename="training_set.jsonl"
)
training_file_id = training_response["id"]

validation_response = openai.File.create(
    file=open(validation_file_name, "rb"), purpose="fine-tune", user_provided_filename="validation_set.jsonl"
)
validation_file_id = validation_response["id"]

print("Training file ID:", training_file_id)
print("Validation file ID:", validation_file_id)
```

### OS

macOS

### Python version

Python v3

### Library version

openai v1.0.1

**Comment by rattrayalex** [comment]
Please see the v1 migration guide: https://github.com/openai/openai-python/discussions/742
