### ISSUE TITLE
AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 3*********************************5. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

### ISSUE THREAD

**Issue by pradeepdev-1995** [openai/openai-python#1209]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

API key does not work with Openai version ```openai==1.13.3```
But the same API key works with previous versions such as  ```openai==0.27.0```

### To Reproduce

use openai==1.13.3 and use this code
```
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": final_prompt
        }
    ],
    model="model",
)
print(chat_completion)
```
which will return the **Incorrect API key provided** error
BUT the same API key works with ```openai==0.27.0```
with this code
```
completion = openai.ChatCompletion.create(
          engine="model",
          temperature=0.1,
          messages=[{"role": "user", "content": final_prompt}]
       )
```

### OS

Ubuntu

### Python version

Python3.9

### Library version

openai==1.13.3

**Comment by rattrayalex** [comment]
Hmm, I don't think most OpenAI API Keys start with a 3 (but rather `sk-`) - there's probably a problem with how you're passing the API Key to the library. 

For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server.

**Comment by pradeepdev-1995** [comment]
I am using Azure openai key subscription. which starts with 3 @rattrayalex

**Comment by rattrayalex** [comment]
how are you instantiating the client?

**Comment by IgorGanapolsky** [comment]
> Hmm, I don't think most OpenAI API Keys start with a 3 (but rather `sk-`) - there's probably a problem with how you're passing the API Key to the library.

Where did you get that idea?  I just created an OpenAI key and it starts with `sk-`

**Comment by IgorGanapolsky** [comment]
Is there a fix for this?  I am facing the same issue.

**Comment by cneskey** [comment]
For anyone running old notebooks and getting this, restart runtime and run again should resolve.

**Comment by chelxxx** [comment]
> Is there a fix for this? I am facing the same issue.

any solution? i am facing the same problem

**Comment by Tkag0001** [comment]
> > Is there a fix for this? I am facing the same issue.
> 
> any solution? i am facing the same problem

I have same issue, do you know how to fix it

**Comment by jkkjjj** [comment]
any solution? i am facing the same problem

**Comment by cneskey** [comment]
> > Is there a fix for this? I am facing the same issue.
> 
> any solution? i am facing the same problem

restart the runtime and run again
