### ISSUE TITLE
Ability to change OPENAI_BASE_URL and OPENAI_API_HOST for testing purposes

### ISSUE THREAD

**Issue by ouvaa** [openai/openai-python#1214]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

to define our own API_HOST for testing

**Comment by rattrayalex** [comment]
You should be able to use the `OPENAI_BASE_URL` environment variable, as [documented in the readme](https://github.com/openai/openai-python?tab=readme-ov-file#configuring-the-http-client). Does that work for you?
