### ISSUE TITLE
Incompatible: `with_streaming_response` `stream_to_file` `response_format='aac'`

### ISSUE THREAD

**Issue by tom-huntington** [openai/openai-python#1220]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The following example errors
```
line 31, in generate_audio
    response.stream_to_file(output_file)
AttributeError: 'ResponseContextManager' object has no attribute 'stream_to_file
```

However, if you remove either `with_streaming_response` or `response_format='aac'` it works

### To Reproduce

```
from openai import OpenAI
client = OpenAI()
response = client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="alloy",
    input="hello aac",
    response_format='aac'
)
response.stream_to_file("output.m4a")
```

### OS

wsl

### Python version

3.8.10

### Library version

1.13.3

**Comment by rattrayalex** [comment]
Did you try using it as a context manager?
```py
from openai import OpenAI
client = OpenAI()
with client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="alloy",
    input="hello aac",
    response_format='aac'
) as response:
    response.stream_to_file("output.m4a")
```

**Comment by flipsideview** [comment]
Hi ,

Is there a fix to this bug ? I keep hitting this output often " Due to a bug, this method doesn't actually stream the response content, `.with_streaming_response.method()` should be used instead
  response.stream_to_file(speech_file_path)" Thx

**Comment by digitalbore** [comment]
Same here

**Comment by Harsh-2200** [comment]
> Hi ,
> 
> Is there a fix to this bug ? I keep hitting this output often " Due to a bug, this method doesn't actually stream the response content, `.with_streaming_response.method()` should be used instead response.stream_to_file(speech_file_path)" Thx


You can use this 


from openai import OpenAI
client = OpenAI()
speech_file_path = "speech.mp3"

response = client.audio.speech.create(
    model="tts-1",
    voice="alloy",
    input="The quick brown fox jumped over the lazy dog.",
)


with open(speech_file_path, "wb") as audio_file:
    audio_file.write(response.content)
