### ISSUE TITLE
Non caught exception `NetworkError` is raised by `httpx`

### ISSUE THREAD

**Issue by clemlesne** [openai/openai-python#1241]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

In some circumstances of faulty network (like on developer laptop, poor VPN, …), `httpx` raises a `NetworkError` (`ConnectError`, `ReadError`, `WriteError`, `CloseError`) exception. This error is related to the network management of the library, but the library do not catch it.

It would be easier to catch `NetworkError` and to map it to a `APIError`.

[See HTTPX doc for exception handling.](https://www.python-httpx.org/exceptions/)

### To Reproduce

1. Run any command involving the remote endpoint
2. Close / interrupt the network connection a few seconds
3. See the error

### OS

macOS 14.3.1

### Python version

Python v3.12.1

### Library version

openai v1.14.0

**Comment by clemlesne** [comment]
I'll pause this issue for now, I detected the issue a few weeks ago, and looking at the code, it seems that it was fixed by: ba4f7a976247de8aa79fcd362e056ec9ce5ea4a0.

**Comment by rattrayalex** [comment]
Thank you @clemlesne !
