### ISSUE TITLE
error: Module "openai.types.beta.threads.run" has no attribute "ToolAssistantToolsFunction"

### ISSUE THREAD

**Issue by Wendong-Fan** [openai/openai-python#1242]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Hi there, i was using old version 1.2.3, seems in the new version 1.14.0 `ToolAssistantToolsFunction` has been removed, but I need this function to validate openai tool schema. Thanks in advance!

### To Reproduce

from openai.types.beta.threads.run import ToolAssistantToolsFunction

### OS

macOS

### Python version

Python v 3.10

### Library version

openai v1.14.0

**Comment by pstern-sl** [comment]
I believe this has been renamed FunctionToolCall. Is that the type you need?

**Comment by Wendong-Fan** [comment]
Hey @pstern-sl , thank you for your help!
