### ISSUE TITLE
Multiprocessing pattern unclear

### ISSUE THREAD

**Issue by leondz** [openai/openai-python#1271]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Since v1.x, `openai` breaks use in `multiprocessing`, because `multiprocessing` chooses to pickle jobs and `openai` doesn't intend to support pickling (as far as I can see from #837).

This renders the pattern for doing multithreaded calling unclear. The reasons and policy are stated in #837 but no solution suggested. I'd like to be doing tens of thousands of requests per hour and I'd like to do these in parallel from a python program. What's the recommended pattern for multithreaded calling as of `openai` v.1x? I'm not working with more than about 100 parallel calls.

### To Reproduce

* wrap any chat/completion request in `multiprocessing`
* observe `TypeError: cannot pickle '_thread.RLock' object`

### OS

Linux

### Python version

Python 3.12

### Library version

1.12.0

**Comment by RobertCraigie** [comment]
If you want to parallelise single chat completion calls then you should either use `threading` or `asyncio`.

If you're spawning multiple processes using `multiprocessing` then you'll just have to create a new `OpenAI` instance in each process unfortunately.

Does that make sense / help?

**Comment by leondz** [comment]
OK, thanks. No free lunch but when is there? Will work it out
