### ISSUE TITLE
openai.Model.list() is invalid

### ISSUE THREAD

**Issue by caishuo-C** [openai/openai-python#1297]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

After the version update, openai.Model.list() is invalid, now how do I see which models the API can call?

### To Reproduce

above

### OS

linux

### Python version

3.9

### Library version

1.13.3

**Comment by rattrayalex** [comment]
Please [migrate to v1](https://github.com/openai/openai-python/discussions/742).
