### ISSUE TITLE
can't find finetuning example

### ISSUE THREAD

**Issue by anindita-mahapatra** [openai/openai-python#130]
hello

Clicking on the olympics example shows code has moved but I cannot access it either in the cookbook nor in openai-python
This code example has moved. You can now find it in the [OpenAI Cookbook](https://github.com/openai/openai-cookbook) at [examples/fine-tuned_qa/](https://github.com/openai/openai-cookbook/tree/main/examples/fine-tuned_qa).

**Comment by hallacy** [comment]
Hi @anindita-mahapatra!

Thanks for writing in! We went ahead and restored that link in the cookbook so this should just work now.  Please let us know if there's anything else we can do.
