### ISSUE TITLE
Azure API Manager with Azure OpenAI

### ISSUE THREAD

**Issue by ltivmitre** [openai/openai-python#1308]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

We proxy the Azure OpenAI service using API Manager. The system design is from Microsoft found here: https://github.com/microsoft/AzureOpenAI-with-APIM.

The request would be for a way to override/set a custom endpoint url along with api key name. (ex. below the key name is Ocp-Apim-Subscription-Key)

example code
#!/bin/bash
apimUrl="THE_HTTPS_URL_OF_YOUR_APIM_INSTANCE"
modelName="GPT-3_5-Turbo" # Probaby what you named your model, but change if necessary
apiVersion="2023-03-15-preview" # Do not change this value, unless you are testing a different API version
subscriptionKey="YOUR_APIM_SUBSCRIPTION_KEY"

url="${apimUrl}"/deployments/"${modelName}"/chat/completions?api-version="${apiVersion}"
key="Ocp-Apim-Subscription-Key: ${subscriptionKey}"

curl $url -k -H "Content-Type: application/json" -H $key -d '{
    "messages": [
        {
            "role": "system",
            "content": "You are an AI assistant that helps people find information."
        },
        {
            "role": "user",
            "content": "What are the differences between Azure Machine Learning and Azure AI services?"
        }
    ]
}'

**Comment by kristapratico** [comment]
@ltivmitre if I'm not mistaken, this is possible with the library today by configuring the AzureOpenAI client to use `base_url` with your custom endpoint URL and by passing your subscription key in the `default_headers`:

```python
import openai

client = openai.AzureOpenAI(
    base_url="https://name.azure-api.net/deployments/modelName",
    api_key="placeholder",
    default_headers={"Ocp-Apim-Subscription-Key": "yourkey"},
    api_version="2024-02-01"
)

```

**Comment by rattrayalex** [comment]
Thank you Krista!

**Comment by kaejo89-shell** [comment]
Thank you Krista, this resolved my issue too.
