### ISSUE TITLE
`gpt-4-turbo-2024-04-09` not pointing to correct cutoff date without an explicitly set system message statement

### ISSUE THREAD

**Issue by FlyingFathead** [openai/openai-python#1310]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library _(sort of, because it affects it too)_

### Describe the bug

While this issue intersects with the usage of the Python API, it primarily pertains to a deeper, potentially systemic concern affecting model performance and accuracy across any interfacing tool.

**Issue Description:**
When interfacing with various model versions (specifically noted with `gpt-4-turbo-2024-04-09`), it appears that without an explicit declaration of the model version within the system message, e.g., “You are gpt-4-turbo-2024-04-09,” the model does not correctly anchor to its designated context and capabilities. It exhibits behaviors reminiscent of older versions or operates with outdated knowledge, such as assuming a knowledge cutoff either in April 2023 or all the way back to September 2021. This misalignment occurs despite selecting the correct model version in API settings, indicating a potential oversight in how model version grounding is internally managed.

**Impact:**
Such behavior can significantly impede the model's utility and accuracy, particularly in contexts requiring up-to-date information or specific model functionalities.

**Additional Context:**
I have shared these findings within the OpenAI Developer Community, garnering corroborative feedback and additional insights which indicate this is not an isolated incident:

- [Community Post 1](https://community.openai.com/t/gpt-4-turbo-2024-04-09-will-think-its-in-2021-unless-specified/712483)
- [Community Post 2](https://community.openai.com/t/gpt-4-turbo-2024-04-09-will-think-its-in-2021-unless-specified/712483/6)

I'm submitting this report here to ensure the issue receives appropriate attention and to facilitate a cross-disciplinary examination of its implications and potential resolutions, since as of now it's affecting model performance and since the Python API is among the most popular methods to utilize the OpenAI model(s).

Thank you for your time and attention to this matter.

### To Reproduce

**(Use the code snippet below for a simple A/B test example)**

1. **Without Specified System Message:**
   - Initialize a session with the model `gpt-4-turbo-2024-04-09` without specifying any additional context or information about its version in the system message.
   - Ask the model about recent events or information post-April 2023, which should fall within its knowledge base if it were accurately aligned with its latest training data.
   - Observe and note any responses that suggest the model is unaware of events or information after April 2023, indicating it is not leveraging its most current training. 

2. **With Specified System Message:**
   - In a new session, explicitly tell the model "You are gpt-4-turbo-2024-04-09" in the system message.
   - Repeat the inquiry about recent events or specific information post-April 2023.
   - Compare the responses to those from Step 1 to observe any notable improvements or corrections in the model's awareness and accuracy, suggesting that the explicit context provided has re-aligned the model with its expected knowledge base.

### Further explanation of the issue

End-users of the API would reasonably expect that when they select a specific model version, like `gpt-4-turbo-2024-04-09`, the model inherently understands and aligns with its latest training data up to the declared cutoff without needing any additional nudges or clarifications. Right now this is _not_ the case.

The absence of an explicit version declaration in the system message leads to 'AI hallucination', where the model outputs are inaccurately anchored in past knowledge, incorrectly suggesting a knowledge cut-off in 2021. 

This misalignment persists despite correct model version selection in API settings, suggesting a need for improved internal management of model version grounding. This seems to be a persisting issue across the GPT-4 model checkpoint variants, but the problem is most prominent in the latest version.

By following the mentioned inclusion in the system message, anyone replicating the test should be able to see a clear contrast in the model's performance and awareness of its knowledge cutoff, based on whether or not its version was explicitly stated in the system message. 

A simple method to A/B test this is to use i.e. the provided Python code (see below) to run diagnostics on the model and spot the difference yourself. You can change the test question to any post-April 2023 event by editing the `user_question` variable.

### Code snippets

To replicate and test the issue:

```Python
import os
from openai import OpenAI

# User question to be asked
user_question = "Is Cormac McCarthy still alive?"

# Instantiate the client with your API key
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

# Inform the user about the question being asked without model guidance
print("---")
print(f"Asking without specifying the model version in the system message: {user_question}")
print("---")
response = client.chat.completions.create(
    model="gpt-4-turbo-2024-04-09",
    messages=[
        {"role": "system", "content": "You are an AI assistant based on OpenAI's GPT-4."},
        {"role": "user", "content": user_question}
    ]
)

# Print the response
print(response.choices[0].message.content)

# Inform the user about the question being asked with model guidance
print("---")
print(f"Asking while specifying 'You are gpt-4-turbo-2024-04-09' in the system message: {user_question}")
print("---")
response_with_system_message = client.chat.completions.create(
    model="gpt-4-turbo-2024-04-09",
    messages=[
        {"role": "system", "content": "You are gpt-4-turbo-2024-04-09"},
        {"role": "user", "content": user_question}
    ]
)

# Print the response
print(response_with_system_message.choices[0].message.content)
```
_(note how even pointing out the model's role as a GPT-4 AI assistant is not enough to align it to the most current cutoff date data)_

### OS

(all)

### Python version

Python v3.11

### Library version

openai v1.14.2

**Comment by rattrayalex** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
