### ISSUE TITLE
Azure OpenAI API doesn't return consistent model ids

### ISSUE THREAD

**Issue by mspronesti** [openai/openai-python#1313]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

When compared with the "classical" API, Azure's doesn't seem to return a consistent model ID after a completion. For instance, I have a deployment of the following models:
- `gpt-4-0613` 
- `gpt-4-1106-preview`
- `gpt-4-0125-preview`

However, when calling a completion, the `model` attribute of the retrieved object is always `gpt-4` (differently from the "classical" API which provides the full name of the model).

Same with `gpt-35-turbo-0613`, `gpt-35-turbo-1106`, `gpt-35-turbo-0125`.

**Comment by rattrayalex** [comment]
cc @kristapratico
