### ISSUE TITLE
Add timestamp_granularities for AzureOpenAI

### ISSUE THREAD

**Issue by pourmand1376** [openai/openai-python#1324]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

```
TypeError: Translations.create() got an unexpected keyword argument 'timestamp_granularities'
```
This is when calling AzureOpenAI client with code below. 

### To Reproduce

To Reproduce you should use AzureOpenAI client (OpenAI client is fine):

```python
import os
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key="API_KEY",  
    api_version="2023-12-01-preview",
    azure_endpoint="ENDPOINT_URL"
)
audio_file = open("output_audio.m4a", "rb")
transcript = client.audio.translations.create(
  model="whisper-1",
  file=audio_file,
  prompt="",
  response_format="verbose_json",
  timestamp_granularities=["word"] # or segment
  
)

```

I've already also made a PR. 
- #1323 

### Code snippets

This code actually works without any problem:

```python
from openai import OpenAI
client = OpenAI(api_key='OPENAPI_KEY')

audio_file = open("output_audio.m4a", "rb")
transcript = client.audio.transcriptions.create(
  file=audio_file,
  model="whisper-1",
  response_format="verbose_json",
  timestamp_granularities=["word"],
)

print(transcript.words)
```
But When you change OpenAI to AzureOpenAI it doesn't work. 

Also this argument is supported in Azure and it works. So, it is just the matter of adding it here. 

### OS

MacOS, Linux

### Python version

Python v3.12.1

### Library version

1.20.0

**Comment by rattrayalex** [comment]
It looks like you may have mixed up `transcriptions` and `translations` when switching between clients? Translations don't support that param: https://platform.openai.com/docs/api-reference/audio/createTranslation

**Comment by pourmand1376** [comment]
Thank you for observing that. It is odd that as I tested `translation` actually supports that parameter and even gives `segment level` and `word level` results. But anyway. My Problem was from me and this is solved now.

**Comment by rattrayalex** [comment]
Ah – in that case, please open a PR or issue on https://github.com/openai/openai-openapi !
