### ISSUE TITLE
AttributeError: 'ThreadRunCreated' object has no attribute 'type'

### ISSUE THREAD

**Issue by nick-youngblut** [openai/openai-python#1334]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

From the docs at https://github.com/openai/openai-python/blob/main/helpers.md:

```python
from typing_extensions import override
from openai import AssistantEventHandler, OpenAI
from openai.types.beta.threads import Text, TextDelta
from openai.types.beta.threads.runs import ToolCall, ToolCallDelta

client = OpenAI()  # NOTE: this is an edit to the original code: `client = openai.OpenAI()`

class EventHandler(AssistantEventHandler):
  @override
  def on_text_created(self, text: Text) -> None:
    print(f"\nassistant > ", end="", flush=True)

  @override
  def on_text_delta(self, delta: TextDelta, snapshot: Text):
    print(delta.value, end="", flush=True)

  def on_tool_call_created(self, tool_call: ToolCall):
    print(f"\nassistant > {tool_call.type}\n", flush=True)

  def on_tool_call_delta(self, delta: ToolCallDelta, snapshot: ToolCall):
    if delta.type == 'code_interpreter':
      if delta.code_interpreter.input:
        print(delta.code_interpreter.input, end="", flush=True)
      if delta.code_interpreter.outputs:
        print(f"\n\noutput >", flush=True)
        for output in delta.code_interpreter.outputs:
          if output.type == "logs":
            print(f"\n{output.logs}", flush=True)

with client.beta.threads.runs.stream(
  thread_id=thread.id,            # using real thread ID
  assistant_id=assistant.id    # using real assistant ID
) as stream:
    for event in stream:
        if event.type == "thread.message.delta" and event.data.delta.content:
            print(event.data.delta.content[0].text)
```

throws the following error:

```
  File "/workspaces/ChatGPT-Arc/tmp/sandbox.py", line 108, in main
    stream_run(client, thread, assistant)
  File "/workspaces/ChatGPT-Arc/tmp/sandbox.py", line 80, in stream_run
    if event.type == "thread.message.delta" and event.data.delta.content:
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 792, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ThreadRunCreated' object has no attribute 'type'
```

It appears that the docs are out-of-date.

Using ` event.data.object` instead of `event.type` works for me:

```python
        for event in stream:
            if event.data.object == "thread.run.step.delta" and event.data.delta.content:
                print(event.data.delta.content[0].text)
```

Note also that  `client = openai.OpenAI()` should be `client = OpenAI()` in the example code.

### To Reproduce

See above

### OS

macOS

### Python version

3.9.19

### Library version

1.21.2

**Comment by RobertCraigie** [comment]
Thanks for reporting, this has been fixed :)

**Comment by nick-youngblut** [comment]
Thanks @RobertCraigie !

Do you know if the docs will soon be aligned in regards to vector store file batching:

The [File Search docs](https://platform.openai.com/docs/assistants/tools/file-search/quickstart?context=streaming) show:

```python
file_batch = client.beta.vector_stores.file_batches.upload_and_poll(
  vector_store_id=vector_store.id, files=file_streams
)
```

...but `upload_and_poll` is not described in the [Vector Store File Batches docs](https://platform.openai.com/docs/api-reference/vector-stores-file-batches).

**Comment by rattrayalex** [comment]
cc @nknj re; adding `upload_and_poll` to the docs.

**Comment by nick-youngblut** [comment]
> OpenAI is not adding higher-level helpers like upload_and_poll to the reference docs.

@rattrayalex I'm curious why OpenAI is not include some helpers in the docs? Why leave them undocumented? Will they soon be deprecated?

**Comment by nknj** [comment]
Thanks for the feedback. Longer term, we want to launch a SDK reference in our docs that documents these. The current reference is an API reference and doesn't include SDK specific helpers. These are documented in the helpers.md files in the SDKs and we link to them via our docs. 

> Will they soon be deprecated?
No, they wont!

**Comment by GoldenJoe** [comment]
This issue is not fixed. I just got the same error with the following:
`
with client.beta.threads.runs.stream(
   thread_id = thread_id,
   assistant_id = assistant_id
) as stream:
   for event in stream:
      if event.type == 'thread.message.delta' and event.delta.
         text = print(event.data.delta.content[0].text)
         print(f"{text}", end="", flush=True)
         yield text
`

`Error during streaming: 'ThreadRunCreated' object has no attribute 'type'`

**Comment by RobertCraigie** [comment]
@GoldenJoe can you open a new issue with a full repro script & stack trace?
