### ISSUE TITLE
AttributeError When Using 'vector_stores' Method in OpenAI Python Client

### ISSUE THREAD

**Issue by yash980** [openai/openai-python#1336]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

After upgrading to the latest version of the OpenAI Python client (openai==1.21.2), I am encountering an AttributeError when attempting to use the new 'vector_stores' method as described in the documentation. The error suggests that the 'OpenAI' object does not have an attribute 'vector_stores'.

![image](https://github.com/openai/openai-python/assets/29830264/dd25dbe3-5b69-443a-b8f1-52db32ca7636)

![image](https://github.com/openai/openai-python/assets/29830264/cd0b735e-3dba-458c-b2f8-bebc8d42a8b4)

### To Reproduce

Install the latest version of the OpenAI Python client (openai==1.21.2).
Execute the following Python code:
```
from openai import OpenAI
client = OpenAI()

vector_store = client.vector_stores.create(
  name="Support FAQ"
)
print(vector_store)
```

### Code snippets

```Python
from openai import OpenAI
client = OpenAI()

vector_store = client.vector_stores.create(
  name="Support FAQ"
)
print(vector_store)
```

### OS

Ubuntu 20.04.6 LTS

### Python version

Python 3.8.10

### Library version

openai 1.21.2

**Comment by yash980** [comment]
It looks like there's a small oversight in the official documentation. I just realized that to get the 'vector_stores' method to work, you need to access it through the 'beta' namespace on the client. So, instead of using `client.vector_stores`, you should use `client.beta.vector_stores`. This tweak seems to make everything work as expected!

**Comment by frippe75** [comment]
There is nothing under beta as well. Tried 

```
if 'beta' in dir(client):
    print("Beta attributes and methods:")
    print(dir(client.beta))
```

pip3 install openai .... But maybe not "latest" enough

**Comment by rattrayalex** [comment]
Yes, you need to be on the latest version of the library (`pip install --upgrade openai`) and access with `client.beta.vector_stores`.

cc @nknj that the docs need to be updated.

**Comment by rattrayalex** [comment]
I'm told the docs have been fixed!

**Comment by Puns1inger** [comment]
This still seems to be an issue.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[34], [line 2](vscode-notebook-cell:?execution_count=34&line=2)
      [1](vscode-notebook-cell:?execution_count=34&line=1) # Create a vector store called "Feedback Statements"
----> [2](vscode-notebook-cell:?execution_count=34&line=2) vector_store = client.beta.vector_stores.create(name="Feedback Statements")

AttributeError: 'Beta' object has no attribute 'vector_stores'
