### ISSUE TITLE
Fix BadRequestError when using ChatCompletionMessage with explicit tool_calls=None

### ISSUE THREAD

**Issue by tarunamasa** [openai/openai-python#1351]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

## Description
When creating a ChatCompletionMessage instance with `tool_calls` explicitly set to `None`, a subsequent chat completion request using that message fails with a `BadRequestError`. The error message indicates that None is not of type `array` for `messages.0.tool_calls`.

## Steps to reproduce:

Create a ChatCompletionMessage instance with tool_calls set to None.
Use the created message in a chat completion request.
Expected behavior:
The chat completion request should succeed, as setting tool_calls to None should be equivalent to not specifying it at all.

Actual behavior:
The chat completion request fails with a `BadRequestError`, indicating that None is not of type `array` for `messages.0.tool_calls`.

## Proposed solution:
Modify the `ChatCompletionMessage` class to handle the case when tool_calls is explicitly set to `None`. If tool_calls is `None`, it should be treated the same as if it were not specified, allowing the chat completion request to succeed.

## Additional information:

OpenAI version: 1.23.2
Python version: Python 3.11.8
Operating system: macOS
**Steps to Reproduce:**

1. **Install the required libraries**:
	* `!pip install openai==1.23.2 python-dotenv -q`
2. **Import the necessary modules and load the environment variables**:
	* `from openai.types.chat import ChatCompletionMessage`
	* `from openai import AsyncOpenAI`
	* `import os`
	* `from dotenv import load_dotenv`
	* `load_dotenv()`
3. **Create an instance of the `AsyncOpenAI` client**:
	* `client = AsyncOpenAI(api_key=os.environ.get("OPENAI_API_KEY"))`
4. **Create two `ChatCompletionMessage` objects with `tool_calls=None`**:
	* `message2 = ChatCompletionMessage(content="foo bar", role="assistant")`
		+ Output: `ChatCompletionMessage(content='foo bar', role='assistant', function_call=None, tool_calls=None)`
	* `message3 = ChatCompletionMessage(content="foo bar", role="assistant", tool_calls=None)`
		+ Output: `ChatCompletionMessage(content='foo bar', role='assistant', function_call=None, tool_calls=None)`
5. **Verify that both objects pass equality checks and have the same `model_dump()` output**:
	* `assert message2 == message3`
	* `assert message2.model_dump() == message3.model_dump()`
6. **Attempt to create a chat completion using both objects**:
	* `await client.chat.completions.create(model="gpt-3.5-turbo", messages=[message2])` (Expected to succeed)
	* `await client.chat.completions.create(model="gpt-3.5-turbo", messages=[message3])` (Expected to fail with a `BadRequestError`)

**Expected Behavior:**

Both objects should be treated equally and result in a successful chat completion creation.

**Actual Behavior:**

One object succeeds, while the other fails with a `BadRequestError`.

**Proposed Fix:**

Modify the serialization of `ChatCompletionMessage` objects to handle `tool_calls=None` consistently, ensuring that identical objects are treated equally in API requests.

**Additional Context:**

This issue may be related to how `tool_calls` is serialized and deserialized in the OpenAI API. A thorough review of the serialization process is recommended to prevent similar inconsistencies in the future.
### OS

macOS

### Python version

Python 3.11.8

### Library version

1.23.2

**Comment by rattrayalex** [comment]
Sorry, this library intentionally chooses for `tool_calls=None` to send `"tool_calls": null` in the API, and the API intentionally chooses to 400 when you do that. This way, in the future, `tool_calls=None` could have a different meaning without breaking backwards-compatibility. 

I know this is a bit confusing/disappointing – apologies for that.

The workaround is to use `NotGiven` instead of `None` in this case.
