### ISSUE TITLE
openai.BadRequestError: Error code: 400 - Unrecognized request argument supplied: dataSources.

### ISSUE THREAD

**Issue by DavidHWWang** [openai/openai-python#1354]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When I use chat.completions.create(), and give extra_body, encounter this error.

I've checked endpoint uri, key, ai search endpoint and key. Nothing wrong.

After I remove extra_body, it worked.

### To Reproduce

client = AzureOpenAI(
    azure_endpoint="",
    api_key="",
    azure_deployment="",
    api_version="",
)

completion = client.chat.completions.create(
    model=deployment,
    messages=[
        {
            "role": "user",
            "content": "What are my available health plans?",
        },
    ],
    extra_body={
        "dataSources": [
            {
                "type": "AzureCognitiveSearch",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    "indexName": os.environ["AZURE_AI_SEARCH_INDEX"]
                }
            }
        ]
    }
)

### OS

windows

### Python version

Python 3.11.5

### Library version

openai v1.23.2

**Comment by kristapratico** [comment]
@DavidHWWang which API version are you targeting? The arguments you're supplying in the extra_body seem appropriate for the older preview version, but not newer versions of the API. I recommend updating to the latest GA version `2024-02-01` if possible which accepts the data sources in snake_case:

```python

client = AzureOpenAI(
    azure_endpoint="",
    api_key="",
    azure_deployment="",
    api_version="2024-02-01",
)

completion = client.chat.completions.create(
    model=deployment,
    messages=messages,
    extra_body={
        "data_sources":[
            {
                "type": "azure_search",
                "parameters": {
                    "endpoint": os.environ["AZURE_AI_SEARCH_ENDPOINT"],
                    "index_name": os.environ["AZURE_AI_SEARCH_INDEX"],
                    "authentication": {
                        "type": "api_key",
                        "key": os.environ["AZURE_AI_SEARCH_API_KEY"],
                    }
                }
            }
        ],
    }
)
```
