### ISSUE TITLE
Add PowerShell files to the list of supported files for retrieval 

### ISSUE THREAD

**Issue by dfinke** [openai/openai-python#1379]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [ ] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

When adding a PowerShell file to the vector store it throws an error `Files with extensions [.ps1] are not supported for retrieval.`

A workaround could be to rename the ps1 files to `.java` or another supported format. 

I would like to request PowerShell files be added to the support list.

Please let me know if I need to pursue this on a different channel. - Thank you

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?
