### ISSUE TITLE
assistant run polling endless

### ISSUE THREAD

**Issue by anyerqi** [openai/openai-python#1407]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

`client.beta.threads.runs.create_and_poll` will run endless, when the status of run is `imcomplete`

the unnormal run info:
```json
{
    "id": "run_t7khKpQ2vvQJAnO3mJcRa47Y",
    "object": "thread.run",
    "created_at": 1715252643,
    "assistant_id": "asst_7HoUHfUXf8KPJQaetjN5suKP",
    "thread_id": "thread_9JfoNfFWttmyx9GSHVi6T9Gd",
    "status": "incomplete",
    "started_at": 1715252644,
    "expires_at": null,
    "cancelled_at": null,
    "failed_at": null,
    "completed_at": 1715252648,
    "required_action": null,
    "last_error": null,
    ......
    "max_completion_tokens": null,
    "max_prompt_tokens": null,
    "truncation_strategy": {
        "type": "auto",
        "last_messages": null
    },
    "incomplete_details": {
        "reason": "max_prompt_tokens"
    },
}
```

### To Reproduce

1. use file search tools: `tools=[{"type": "file_search"}]`
2. trigger the limitation of `max_prompt_tokens`

### OS

ubuntu

### Python version

Python 3.10.12

### Library version

openai v1.26.0

**Comment by rattrayalex** [comment]
Sorry to hear you're having troubles!  

This sounds like an issue with the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?

**Comment by nknj** [comment]
Good catch and thanks for reporting -- we'll fix this in the next SDK version very soon. 🙏
