### ISSUE TITLE
Too verbose logs

### ISSUE THREAD

**Issue by louis030195** [openai/openai-python#141]
Hi, is there any way to reduce these logs?

```
message='OpenAI API response' path=https://api.openai.com/v1/fine-tunes processing_ms=228 request_id=FOO response_code=200
INFO:openai:message='OpenAI API response' path=https://api.openai.com/v1/fine-tunes processing_ms=228 request_id=BAR response_code=200
```

To me, these logs should be DEBUG.

**Comment by hallacy** [comment]
Hey @louis030195!

Thanks for writing in.  I think that makes sense.  We can get this into our backlog. If you'd like to take a shot at it, I'd be happy to review a PR as well!
