### ISSUE TITLE
Support load-balancing across OpenAI instances

### ISSUE THREAD

**Issue by simonkurtz-MSFT** [openai/openai-python#1410]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Introduce the ability to use a prioritized set of backends and load-balance across different OpenAI instances.

### Additional context

I wrote a [Python OpenAI Load Balancer](https://github.com/simonkurtz-MSFT/python-openai-loadbalancer) as an example of what may be useful.

**Comment by rattrayalex** [comment]
Thank you for sharing, @simonkurtz-MSFT ! cc @kristapratico 

I don't expect we'll be able to add this to the library itself anytime soon, but I'll keep it in the back of my mind. In the meantime, will be happy to send folks towards your library.

**Comment by simonkurtz-MSFT** [comment]
Thank you! I have it as just a module, not a publishes library yet. That's a next step.

Do you all have a page that lists community projects for additional functionality that you link to?

**Comment by rattrayalex** [comment]
Not to my knowledge!
