### ISSUE TITLE
Parametr name mismatch.

### ISSUE THREAD

**Issue by Valek-Z** [openai/openai-python#1412]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Parametr name mismatch in method create_and_run_stream parametr `tool_resources` when call  post request body data named tool.
And result :
openai.BadRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'tool'.", 'type': 'invalid_request_error', 'param': 'tool', 'code': 'unknown_parameter'}}
![image](https://github.com/openai/openai-python/assets/40039970/c99b6a77-d749-4257-b3e4-f283d880512c)

### To Reproduce

Call method client.beta.threads.create_and_run() with filled tool_resources param.

### OS

Windows

### Python version

python v3.10

### Library version

openai v1.28.1

**Comment by RobertCraigie** [comment]
Thanks for the report and sorry for the delay in fixing this, it will be fixed in the next release: https://github.com/openai/openai-python/pull/1537
