### ISSUE TITLE
Using Azure open AI Assistant throws TypeError: create() got an unexpected keyword argument 'file_ids'

### ISSUE THREAD

**Issue by Karishma73** [openai/openai-python#1416]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am working on Azure notebook and while creating Azure Open AI Assistant [source1](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/code-interpreter?tabs=python), [source2](https://github.com/Azure/AI-in-a-Box/blob/main/gen-ai/Assistants/api-in-a-box/personal_finance/assistant-personal_finance.ipynb) I am getting `TypeError: create() got an unexpected keyword argument 'file_ids'`, I tried the solution mentioned [here](https://community.openai.com/t/typeerror-messages-create-got-an-unexpected-keyword-argument-file-ids/722104) even though it is not from AZURE but it gives me different error TypeError: Assistants.create() got an unexpected keyword argument 'attachments', The same[ code](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/code-interpreter?tabs=python) works fine locally without any `TypeError: create() got an unexpected keyword argument 'file_ids'` is there an update for creating assistants api on AZURE notebook(or any other cloud based notebook it is not working on Databricks notebook  too , it was working on Databrick notebook few weeks ago) or it is a new bug related to this [bug](https://github.com/microsoft/autogen/issues/2580) ? I am using gpt-35-turbo-16k-0613 model, openai 1.28.1 version. I am not using `autogen` library.  

### To Reproduce

[details](https://learn.microsoft.com/en-us/answers/questions/1665693/using-azure-open-ai-assistant-throws-typeerror-cre
Run below code in Azure or Databricks notebook to reproduce error 
`from openai import AzureOpenAI
    
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),  
    api_version="2024-02-15-preview",
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    )

# Upload a file with an "assistants" purpose
file = client.files.create(
  file=open("speech.py", "rb"),
  purpose='assistants'
)

# Create an assistant using the file ID
assistant = client.beta.assistants.create(
  instructions="You are an AI assistant that can write code to help answer math questions.",
  model="gpt-4-1106-preview",
  tools=[{"type": "code_interpreter"}],
  file_ids=[file.id]
)`)

<img width="635" alt="image" src="https://github.com/openai/openai-python/assets/60409314/920b2478-f4e1-4663-afef-e7b6f038810b">
<img width="649" alt="image" src="https://github.com/openai/openai-python/assets/60409314/883922db-e096-46ab-b97e-a3fcc174292e">
<img width="635" alt="image" src="https://github.com/openai/openai-python/assets/60409314/37105618-6b69-4ba8-91a1-40f630ec4695">

### OS

Linux 22.05.09, 

### Python version

3.8.5

### Library version

openai- 1.28.1

**Comment by kristapratico** [comment]
@Karishma73 the version of the openai library you are using by default supports [Assistants v2](https://platform.openai.com/docs/assistants/migration). Azure OpenAI does not support v2 yet. In the meantime, I recommend [downgrading your openai library version to 1.20.0](https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-quickstart?tabs=command-line%2Ctypescript&pivots=programming-language-python#set-up) which still uses the v1.

**Comment by Karishma73** [comment]
thank you @kristapratico, downgrading worked for me.

**Comment by kristapratico** [comment]
@Karishma73 FYI Azure now supports Assistants v2 with `api_version="2024-05-01-preview"`

**Comment by Karishma73** [comment]
I am getting error: B`adRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'tool_resources'.", 'type': 'invalid_request_error', 'param': 'tool_resources', 'code': 'unknown_parameter'}}` while working on `openai==1.28.1`
Below is my code:
```
assistant = client.beta.assistants.create(
      instructions='''My Instruction''',
      model="My model deployment name",
      tools=[{"type": "code_interpreter"}],
      tool_resources={"code_interpreter": {"file_ids": [file.id]}}
    )
```

**Comment by kristapratico** [comment]
@Karishma73 I'm not able to reproduce this. Did you update your client to target `api_version="2024-05-01-preview"`?

```python
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-05-01-preview",
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
)

```
