### ISSUE TITLE
Any Examples of GPT-4o？

### ISSUE THREAD

**Issue by kaixindelele** [openai/openai-python#1419]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

There are currently no multi-modal calling examples for 4o in this lib or documentation.

**Comment by liuhetian** [comment]
really need this

**Comment by david-labs-ca** [comment]
We just bumped our assistants to use gpt-4o model, instead of gpt and they are working fine. No other change. Taking less time now. Maybe you can find some examples of calling assistants on the community forums.

**Comment by lcctoor** [comment]
I have maintained an unofficial package that supports gpt-4o, and an example has been written in the documentation:

[https://pypi.org/project/openai2/](https://pypi.org/project/openai2/)

**Comment by RobertCraigie** [comment]
Hi, `gpt-4o` can currently be used with any of the example scripts here: https://github.com/openai/openai-python/tree/main/examples
