### ISSUE TITLE
Does it support multi key polling？

### ISSUE THREAD

**Issue by yuanjie-ai** [openai/openai-python#1432]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Does it support multi key polling？

### Additional context

Does it support multi key polling？

**Comment by rattrayalex** [comment]
Not currently, no. Can you share more about what you would like to see and why? 

Is there any reason that calling `.poll(id)` in a for-loop would not work well for you?

**Comment by Jan13295** [comment]
I think this should be closed right?
