### ISSUE TITLE
`ChatCompletionAssistantMessageParam` is incorrectly typed

### ISSUE THREAD

**Issue by willbakst** [openai/openai-python#1433]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The `ChatCompletionAssistantMessageParam` has the incorrect types for the `function_call`, `name`, and `tool_calls` fields. All of these fields should be marked `Optional[...]` but they are not.

While this doesn't break the type itself, downstream it prevents the use of `pydantic` with these types.

### To Reproduce

Run the code in the snippet below.

`pydantic` will try to validate `ChatCompletionAssistantMessageParam` and fail because `function_call` is None (as returned by the API). I would expect either (1) that the returned message does not include the `function_call` field like it excludes the `name` field or (2) for the `ChatCompletionAssistantMessageParam` type to allow for `function_call` to be `None` in it's type definition.

### Code snippets

```Python
from openai.types.chat import ChatCompletionAssistantMessageParam
from pydantic import BaseModel

class MyModel(BaseModel):
    history: list[ChatCompletionAssistantMessageParam]

history = [
    {
        "content": None,
        "role": "assistant",
        "function_call": None,
        "tool_calls": [
            {
                "id": "id",
                "function": {
                    "arguments": '{"location":"Tokyo, Japan"}',
                    "name": "GetCurrentWeather",
                },
                "type": "function",
            }
        ],
    },
]
my_model = MyModel(history=history)
print(my_model)
```

### OS

14.2.1

### Python version

3.9.16

### Library version

1.30.1

**Comment by rattrayalex** [comment]
Sorry, I believe this is working as intended. You aren't supposed to send `"function_call": null` in the API, so the type `'funcion_call': None` is not allowed.

Perhaps @RobertCraigie has an idea on how to better handle the pydantic issue you mention.

**Comment by willbakst** [comment]
The main reason I brought this up is that the [documentation](https://platform.openai.com/docs/guides/function-calling) shows inserting `response.choices[0].message` back into the messages array (line 57 of the code example), and that returned message has `'function_call': None`, so either the type is incorrect and that value should be allowed or the return value shouldn't have `function_call` in it at all.

Of course, the downstream effect here is that when using Pydantic it fails with a ValidationError unless I manually remove `function_call` since `None` isn't a valid option.

**Comment by rattrayalex** [comment]
Gotcha, thanks. Okay so I think the backend may have changed recently

**Comment by willbakst** [comment]
For me the issue is that I have my own Pydantic model with the message as a field, so the validation fails on my own object (and I want to validation to make sure I'm sending the right message structure).

**Comment by david-mykoai** [comment]
The `tool_calls` parameter is also marked as optional in the OpenAI API reference. Could this be fixed as well?
In fact, passing in an empty array no longer works for me, passing in `None` is the only way I could get the API to not return an error.
