### ISSUE TITLE
Missing Authorization header in request

### ISSUE THREAD

**Issue by AkshaySangwan8571** [openai/openai-python#1434]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

### To Reproduce

Make API requests 

### Code snippets

```Python
import openai 
import os
import re

class OpenAI:
    def __init__(self):
        # os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
        openai.api_key = openai.api_key = os.getenv("OPENAI_API_KEY")
      


    def gpt(self, prompt):
        response = openai.chat.completions.create(
            model="gpt-3.5-turbo-0125",
            # model="gpt-4",
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt},
                {"role": "assistant", "content": "Respond consisely, response should only include natural language."},
            ],
                temperature = 0,
                top_p=0.5,
                seed=123
        )
        print(response)
        return response.choices[0].message.content
```

### OS

Windows 11

### Python version

Python v3.11.4

### Library version

openai v1.0.1

**Comment by rattrayalex** [comment]
chances are `OPENAI_API_KEY` is not actually set.

For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!
