### ISSUE TITLE
Async completions.create method does I/O in the event loop

### ISSUE THREAD

**Issue by balloob** [openai/openai-python#1446]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am working on the Home Assistant OpenAI integration. Home Assistant has started warning when we see I/O being done in the event loop and it printed this warning:

```
2024-05-25 03:03:21.716 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by integration 'openai_conversation' at homeassistant/components/openai_conversation/conversation.py, line 170: result = await client.chat.completions.create( (offender: /home/vscode/.local/ha-venv/lib/python3.12/site-packages/distro/distro.py, line 1099: with open(self.os_release_file, encoding="utf-8") as release_file:)
```

It looks like `distro` is used to set the platform headers. When calling the Linux platform, it [opens the release file](https://github.com/python-distro/distro/blob/master/src/distro/distro.py#L1103). This makes `distro` not async-safe.

### To Reproduce

1. Call `await client.chat.completions.create`

### OS

macOS

### Python version

Python 3.12.3

### Library version

openai==1.3.8

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll take a look.

**Comment by bdraco** [comment]
There is also a blocking `stat()` syscall one line above it https://github.com/python-distro/distro/blob/7ce285cb4decab9f2b52763a5510c2ac11189b55/src/distro/distro.py#L1102.

**Comment by bdraco** [comment]
Greetings.  Here is how we watch for blocking calls in the event loop

https://github.com/home-assistant/core/blob/71a9ba25dca17a3bd07c46dedcdcfff1ff7228be/homeassistant/block_async_io.py#L159
https://github.com/home-assistant/core/blob/71a9ba25dca17a3bd07c46dedcdcfff1ff7228be/homeassistant/util/loop.py#L111

It gets enabled early in the startup process.

**Comment by balloob** [comment]
Can confirm that there is no longer I/O being reported in the event loop by Home Assistant.
