### ISSUE TITLE
tool_resources parameter throwing error while creating Assistant v2 with AZURE client

### ISSUE THREAD

**Issue by Karishma73** [openai/openai-python#1449]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am using openai==1.28.1 and while creating assistant I am getting `BadRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'tool_resources'.", 'type': 'invalid_request_error', 'param': 'tool_resources', 'code': 'unknown_parameter'}} `. I am taking references from [Source](https://platform.openai.com/docs/assistants/migration/what-has-changed) [source](https://learn.microsoft.com/en-us/azure/ai-services/openai/whats-new#assistants-v2-preview) Below is the code which is throwing me error when I am trying tool_resource

### To Reproduce

Run below code with AZURE api key and endpoint, even if I change the below  code with `tool_choice={"code_interpreter": {"file_ids": [file.id]}}` it won' t work  it gives error `TypeError: Assistants.create() got an unexpected keyword argument 'tool_choice'`
[source](https://learn.microsoft.com/en-us/azure/ai-services/openai/whats-new#assistants-v2-preview) 

```
assistant = client.beta.assistants.create(
      instructions='''My Instruction''',
      model="My model deployment name",
      tools=[{"type": "code_interpreter"}],
      tool_resources={"code_interpreter": {"file_ids": [file.id]}}
    )
```

### OS

Linux

### Python version

3.10.1

### Library version

openai==1.28.1

**Comment by kristapratico** [comment]
@Karishma73 see this [comment](https://github.com/openai/openai-python/issues/1416#issuecomment-2135892055), you need to update the API version you're targeting to `2024-05-01-preview` which supports Assistants v2. Here's an [example](https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-quickstart?tabs=command-line%2Ctypescript&pivots=programming-language-python#create-the-python-app).

Also [tool_choice](https://platform.openai.com/docs/api-reference/runs/createRun) is not accepted when creating an assistant, but this can be passed when creating the run.

**Comment by Karishma73** [comment]
thanks @kristapratico

**Comment by zakaria-aabbou** [comment]
Hello, I tried the "2024-05-01-preview" api version with openai==1.30.4, but it didn't work for me :

`from openai import AzureOpenAI
import os

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-05-01-preview", # 2024-02-15-preview
    azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    )
    # Upload a file with an "assistants" purpose
file = client.files.create(
  file=open("speech.py", "rb"),
  purpose='assistants'
)

# Create an assistant using the file ID
assistant = client.beta.assistants.create(
  instructions="You are an AI assistant that can write code to help answer math questions.",
  model=ENGINE_GPT4,
  tools=[{"type": "code_interpreter"}],
  file_ids=[file.id]
)
`

I get this error:
`TypeError: Assistants.create() got an unexpected keyword argument 'file_ids'`

**Comment by Karishma73** [comment]
@zakaria-aabbou  you need to use tool_resources parameter  try below code while creating assistant, it is working for me :
`assistant = client.beta.assistants.create(
  instructions="You are an AI assistant that can write code to help answer math questions.",
  model=ENGINE_GPT4,
  tools=[{"type": "code_interpreter"}],
  tool_resources={ "code_interpreter": {"file_ids": [file.id]}}
)`

I am using openai==1.28.1

**Comment by madhubandru** [comment]
Thanks  @Karishma73 it worked!
