### ISSUE TITLE
You've made too many requests, please wait one minute and try again. 

### ISSUE THREAD

**Issue by insoxin** [openai/openai-python#145]
Request ID: ..
Please contact us through our [help center](https://help.openai.com/en/)
if this issue persists.
Return to homepage

**Comment by hallacy** [comment]
Hi @insoxin, thanks for writing in!

This error looks like our system working as intended to rate limit users.  Is there a different response you are expecting?

**Comment by hallacy** [comment]
I'm going to close this due to inactivity. Please let me know if there's additional information!
