### ISSUE TITLE
partially initialized module 'openai' has no attribute 'Completion'

### ISSUE THREAD

**Issue by shelu16** [openai/openai-python#147]
python gpt2.py
Traceback (most recent call last):
  File "D:\EVE_NG\gpt2.py", line 2, in <module>
    import openai
  File "D:\EVE_NG\openai.py", line 8, in <module>
    response = openai.Completion.create(
               ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'openai' has no attribute 'Completion' (most likely due to a circular import)

**Comment by hallacy** [comment]
Hi @shelu16,

Can you tell me a bit more about how you've set up the openai package? We haven't heard this issue from other users and I can't reproduce this locally.
