### ISSUE TITLE
AsyncAssistantStreamManager Error

### ISSUE THREAD

**Issue by Senna1960321** [openai/openai-python#1473]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

async def requestGpt(response):
    print("requestGpt called")
    async with client.beta.threads.runs.stream(
        thread_id=thread.id,
        assistant_id=assistant.id,
        event_handler=EventHandler(response)
    ) as stream:
        await stream.until_done()

When I use this way to call a assistant streaming, the type of stream is AssistantStreamManager, not the AsyncAssistantStreamManager

### To Reproduce

async def requestGpt(response):
    print("requestGpt called")
    async with client.beta.threads.runs.stream(
        thread_id=thread.id,
        assistant_id=assistant.id,
        event_handler=EventHandler(response)
    ) as stream:
        await stream.until_done()

### OS

macOS

### Python version

Python 3.10

### Library version

openai             1.23.6

**Comment by meorphis** [comment]
Hey @Senna1960321 thanks for reporting. I have not been able to repro this. I tried creating a thread and an assistant then running the snippet you provided but I got an `AsyncAssistantStreamManager` as expected.

To be clear, you are using an `AsyncOpenAI` object as your `client`, right? Could you please provide more comprehensive repro instructions (i.e. an end-to-end repro)?

**Comment by Senna1960321** [comment]
Yes, I want to use a AsyncOpenAI object as my client. @meorphis 
This is my code, the type of stream is AssistantStreamManager
client = OpenAI(
    api_key='openai_key'
)

message = client.beta.threads.messages.create(
  thread_id=thread.id,
  role="user",
  content="Please answer again, I do not understand you."
)

class EventHandler(AsyncAssistantEventHandler):
    # def __init__(self, response):
    #     super().__init__()
    #     self.response = response

    @override
    async def on_event(self, event: AssistantStreamEvent) -> None:
        print("on_event called")
        if event.event == "thread.run.step.created":
            details = event.data.step_details
            if details.type == "tool_calls":
                print("Generating code to interpret:\n\n```py")
        elif event.event == "thread.message.created":
            print("\nResponse:\n")

async def requestGpt():
    print("requestGpt called")
    stream = client.beta.threads.runs.stream(
        thread_id=thread.id,
        assistant_id=assistant.id,
        event_handler=EventHandler()
    )
    print(f"Stream type: {type(stream)}")
    async with stream as stream:
        await stream.until_done()

**Comment by meorphis** [comment]
Hey @Senna1960321 - thank you for posting your code. What I meant is that instead of
```
client = OpenAI(
    api_key='openai_key'
)
```
You should be using:
```
client = AsyncOpenAI(
    api_key='openai_key'
)
```
This will solve your problem :)

**Comment by Senna1960321** [comment]
Thanks a lot @meorphis , I tried it so that it did solve my problem perfectly
