### ISSUE TITLE
AzureOpenAI doesn't support parameter chunking_strategy while creating vector store.

### ISSUE THREAD

**Issue by DakshNsut** [openai/openai-python#1484]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [x] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

OpenAI recently added a new feature to their library, which says we can customize the chunking strategy used to split and store files in vector stores using the new parameter **"chunking_strategy"** to be used while creating a vector store.
https://platform.openai.com/docs/changelog (June 3rd, file search customizations)
![image](https://github.com/openai/openai-python/assets/97459596/b28ac955-ce32-44ac-bef5-185ebb19e45d)
If I try creating a new vector store mentioning the custom chunking strategy using the **OpenAI client**, I am able to successfully create one.
![image](https://github.com/openai/openai-python/assets/97459596/1cf032f3-94ca-45b3-a94e-78b11806994b)
But, if I try creating a new vector store mentioning the custom chunking strategy using the **AzureOpenAI client**, I get BadRequestError which says **unknown parameter: chunking_strategy**.
![image](https://github.com/openai/openai-python/assets/97459596/c96cc2a7-22e1-4bcc-9112-6da8a207039b)
![image](https://github.com/openai/openai-python/assets/97459596/d066f3e5-3936-43a9-8b65-319b632ff7f3)
I have tried upgrading the openai python library, but that doesn't solve the issue.
I request AzureOpenAI to update their module as per the changes done by openai library.

**Comment by DakshNsut** [comment]
Okay, thank you for your reply.

**Comment by kristapratico** [comment]
@DakshNsut what dgellow said is correct, the Azure OpenAI service does not yet support `chunking_strategy`. I don't have an ETA for you, but you can follow the [what's new](https://learn.microsoft.com/en-us/azure/ai-services/openai/whats-new) page on MS Learn for updates.
