### ISSUE TITLE
assistant streaming slow

### ISSUE THREAD

**Issue by Senna1960321** [openai/openai-python#1485]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When I attempt to use the assistant function and perform streaming returns, I notice that the assistant and thread created with my most frequently used API key have a very slow response time, taking about 20 seconds to return content after establishing the connection. However, when I create a new assistant and thread with another API key, it only takes about 3-5 seconds to get a response. Why is this happening? Is it because my frequently used API key internally stores a large amount of assistant, thread, and file content?

### To Reproduce

just request with the different api key  and their assistant and thread

### OS

macOS

### Python version

Python 3.10

### Library version

openai             1.23.6

**Comment by dgellow** [comment]
Hi @Senna1960321,

Reading your bug description I would think it's related to OpenAI backend, not the Python SDK. But if you could share an example we could use to reproduce the problem that would be helpful.

**Comment by Senna1960321** [comment]
Thanks for the heads up @dgellow , the responsiveness became normal after I pulled the new assistant and thread with the usual api key.
