### ISSUE TITLE
After fine tuning gpt3 model, how to know f1 score as a evaluation?

### ISSUE THREAD

**Issue by imrankh46** [openai/openai-python#149]
After fine tuning gpt3 for text generation, so how I can know f1 score using openai cli ?

**Comment by hallacy** [comment]
Hi @imrankh46, thanks for writing in.

Calculating F1 score will depend a lot on your use case and given that it's very highly situation dependent, we don't support it in the CLI. That said, you might be able to find ideas either on help.openai.com or https://community.openai.com/.  Hope this helps.

**Comment by hallacy** [comment]
I'm going to close this issue due to inactivity. Feel free to reopen
