### ISSUE TITLE
Python code defaults to 'base64' encoding_format in the embeddings endpoint, but docs say it should be 'float'

### ISSUE THREAD

**Issue by hillarysanders** [openai/openai-python#1490]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Hi, your docs say that the default `encoding_format` in your [embeddings/create endpoint is `float`](https://platform.openai.com/docs/api-reference/embeddings/create#embeddings-create-encoding_format), however your [python package code applies a default of 'base64' when a value isn't supplied](https://github.com/openai/openai-python/blob/main/src/openai/resources/embeddings.py#L94-L95).

Can you switch this to 'float' so the python package is conformant with your docs? 

### To Reproduce

Run an OpenAI embeddings query with the python client:
```
import openai
client = openai.OpenAI(...)
response = client.embeddings.create(
   model=<model>,
   input="I am a string to embed!",
   # notably, NOT specifying encoding_format here
) 
 ```
 Uses base64 encoding instead of float, oddly.

### Code snippets

```Python
NA
```

### OS

macOS

### Python version

3.12.3

### Library version

1.35.0

**Comment by RobertCraigie** [comment]
@hillarysanders The Python SDK should only default to `base64` if you don't specify an `encoding_format` & have numpy installed.

We do this as it's more performant for the API to response with `base64` & then decode directly in the SDK than to receive `float`s from the API.

Did you run into any issues here or would an update to the docs mentioning this behaviour suffice?
