### ISSUE TITLE
Error while using parallel_tool_calls parameter with AzureOpenAI

### ISSUE THREAD

**Issue by RajPoojara** [openai/openai-python#1492]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Getting below error when calling the chat.completion.create function with parallel_function_calls=False parameter with AzureOpenAI client. 

openai.BadRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'parallel_tool_calls'.", 'type': 'invalid_request_error', 'param': 'parallel_tool_calls', 'code': 'unknown_parameter'}}

NOTE: This is only for the scenario where the Function Calling feature is being used. 

### To Reproduce

Just create a client with AzureOpenAI.
Call the client.chat.completion.create method and with that, also pass the parallel_function_calls=False (as it is True by default).
You will get the above error.

### OS

Any

### Python version

Any

### Library version

openai v1.34.0

**Comment by dgellow** [comment]
Hi @RajPoojara,

Based on the error code 400 you mentioned the issue seems to be with Azure's API, not with OpenAI SDK itself. I would suggest that you follow and/or comment in the related ticket https://github.com/Azure/azure-rest-api-specs/issues/29545, or contact the Azure team directly.
