### ISSUE TITLE
This old format doesn;t supported anymore

### ISSUE THREAD

**Issue by lucasjinreal** [openai/openai-python#1510]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

response = client.chat.completions.create(
    # model="alibaba/Qwen1.5-110B-Chat",
    model="Qwen/Qwen2-7B-Instruct",
    messages=[
        {
            "role": "system",
            "content": [{"type": "text", "text": "you are a dog"}],
            "name": "",
        },
        {
            "role": "user",
            "content": [{"type": "text", "text": "你好啊"}],
            "name": "",
        },
        {
            "role": "assistant",
            "content": [
                {
                    "type": "text",
                    "text": "你好，我是一条狗，我叫汪昂",
                }
            ],
            "name": "",
        },
        {
            "role": "user",
            "content": [{"type": "text", "text": "Hello"}],
            "name": "",
        },
    ],
    stream=True,
)

Am using openai to create, got request format error:

openai.BadRequestError: Error code: 400 - {'code': 50400, 'message': 'The request parameter is invalid, Please check again.', 'data': None, 'error': 'The request parameter is invalid, Please check again.'}

this format previous works OK> why?

### To Reproduce

gyiguy

### OS

macOS

### Python version

3.11

### Library version

openai latest

**Comment by mophilly** [comment]
I also ran into this. python replied with "You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0"

Code snippet
`response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=1000,
        temperature=0.7,
    )`

OS
MacOS Sonoma (14.5)

Python Version
Python 3.12

Library version
openai v1.35.8.

**Comment by rattrayalex** [comment]
The 400 response from @lucasjinreal appears to be coming from a non-OpenAI server. This does not appear to be an SDK issue.

@mophilly your snippet there has `openai.ChatCompletion.create` instead of `openai.chat.completions.create`, and in either case seems unrelated to this issue.
