### ISSUE TITLE
Send input below model and other parameters in json bodies of HTTP requests

### ISSUE THREAD

**Issue by neoq** [openai/openai-python#1525]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

When I send a request to an OpenAI compatible endpoint using the following code:
```python
import openai
client = openai.OpenAI(
	base_url="https://base.tld/v1",
	api_key="xxx",
)
embedding = client.embeddings.create(
	model="e5-mistral-7b-instruct",
	input="San Francisco",
)
print(embedding)
```
It sends an HTTP request with the following body, where the input always comes before the model.
```json
{"input": "San Francisco", "model": "e5-mistral-7b-instruct"}
```
I think it would be better to always put the `input` last, after the `model` so that implementers of the OpenAI API can branch earlier in processing a request based on `model`. This is only a problem for large (eg. >8KB) inputs, which do not fit into typical web server buffers anymore.
That is, the body should look like this instead:
```json
{"model": "e5-mistral-7b-instruct", "input": "San Francisco"}
```

At $WORK we offer an OpenAI compatible API and route based on the model parameter, so we have to buffer the whole `input` before the request can be forwarded to the correct upstream server hosting that model. This routing only works for inputs that don't exceed our buffer size, meaning we can only process smaller requests.
If the model came before input instead, it would be possible to parse the model and route based off it with only a small buffer size, even for inputs that far exceed the buffer size.

An added benefit of the proposed parameter order would be slightly improved latency, because the upstream can be decided earlier and the input is starting to get sent sooner.

I imagine we are not the only ones branching based on `model`, so this change would improve latency and allow for bigger inputs across the whole ecosystem.

I am honestly not sure if this can be changed in this repo since the code is generated. Maybe changing the order in the API spec:
https://github.com/openai/openai-openapi/blob/0df12d7b3ac997517fda38842f41d99a8e7f4e6a/openapi.yaml#L8873
would be the easiest way to fix it, although the OpenAPI spec is not really *wrong* since the API is oblivious to the order.

The issue exists for other endpoints such as `/chat/completions`, where messages comes before model. I encountered it while creating `/embeddings` for many inputs.

**Comment by rattrayalex** [comment]
Thanks for the clearly-written feature request. 

This isn't something we'd plan to put work into, but you're welcome to put up a PR to the `openapi.yaml` you linked changing the order, and you might get lucky in what comes out 🤷

**Comment by neoq** [comment]
Thank you! I will try :)
Fyi: For now we will support an optional header with the `model` that is used for routing to support larger requests.

**Comment by rattrayalex** [comment]
That's a reasonable idea, but why not put up such a PR? it's low-cost and low-risk, and would benefit more of your users with less work on their/your part, right?

**Comment by neoq** [comment]
Yes, I was trying to say that I will try submitting the PR as well :)
