### ISSUE TITLE
AzureOpenAI AuthenticationError

### ISSUE THREAD

**Issue by mzwaMoj** [openai/openai-python#1527]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Hi, 

I have a `.env` file with the necessary AzureOpenAI credentials. However, I am getting this error message AuthenticationError: 
Error code: 401 - {'statusCode': 401, 'message': 'Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API.'}

When I try to execute the code from this microsoft learn source: https://learn.microsoft.com/en-us/azure/ai-services/openai/chatgpt-quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python

### Below is the full python code.

`import os
from openai import AzureOpenAI

client = AzureOpenAI(
  api_key = os.getenv("AZURE_OPENAI_KEY"),  
  api_version = os.getenv("AZURE_OPENAI_VERSION"),
  azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
)

response = client.chat.completions.create(
    model="gpt-35-turbo", # model = "deployment_name".
    messages=[
        {"role": "system", "content": "Assistant is a large language model trained by OpenAI."},
        {"role": "user", "content": "Who were the founders of Microsoft?"}
    ]
)

#print(response)
print(response.model_dump_json(indent=2))
print(response.choices[0].message.content)`

### OS

Windows

### Python version

Python v3.11.7

### Library version

openai v1.35.10

**Comment by rattrayalex** [comment]
For help developing with the OpenAI API from fellow developers, I recommend the [OpenAI Discord](https://discord.com/invite/openai) server!

cc @kristapratico
