### ISSUE TITLE
Every-time getting error `insufficient_quota`.

### ISSUE THREAD

**Issue by Mio-moji** [openai/openai-python#1559]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [ ] This is an issue with the Python library

### Describe the bug

I am trying the basic example to query the ChatGPT but always getting. I created new account a week ago and never used its API. Now, when i create the API key use it, it gets me that error.

>openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

### To Reproduce

Run the given code, you will get the error.

### Code snippets

```Python
import openai

# Initialize the OpenAI client with your API key
openai.api_key = "sk-proj-************************"
client = openai.OpenAI(api_key=openai.api_key)

def ask_chatgpt(question):
    chat_completion = client.chat.completions.create(
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": question}
        ],
        model="gpt-3.5-turbo",
    )
    return chat_completion['choices'][0]['message']['content'].strip()

# Example usage
question = "What is the capital of France?"
response = ask_chatgpt(question)
print(response)
```

### OS

Ubuntu 24.04 LTS 

### Python version

3.12

### Library version

1.35.14
```[tasklist]
### Tasks
```

**Comment by RobertCraigie** [comment]
Hi @Mio-moji this looks like an API issue, please ask for help on the [community forum](https://community.openai.com/) or contact support.
