### ISSUE TITLE
Adding support for customized file name

### ISSUE THREAD

**Issue by luigi-raynel-dev** [openai/openai-python#1564]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

On my server I save the file with a different name, and I would like to customize the name of the created file by passing a parameter to the client.files.create method as in the example below. Is this viable?
```py
attachment = client.files.create(file=open("randomfilename.pdf", "rb"), purpose=purpose, filename="MyCustomFilename.pdf")
```

**Comment by sebastian-srikanth** [comment]
Hi @luigi-raynel-dev,

Can you give more context, can you paste your working code, if possible?

**Comment by RobertCraigie** [comment]
Hi @luigi-raynel-dev, you can customise the filename today with this syntax:
```py
client.files.create(
    file=("myfilename.txt", open("randomfilename.pdf", "rb")),
    purpose="assistants",
)
```
