### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by AnasBenAmor10** [openai/openai-python#1577]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Error:

You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742 

### To Reproduce

*

### Code snippets

```Python
def get_embeddings(self, chunks):
        embeddings = []
        for chunk in chunks:
            try:
          
                response = openai.Embedding.create(
                    input=chunk  
                    model="text-embedding-ada-002"
                )
                embeddings.append(response['data'][0]['embedding'])
            except Exception as e:
                print(f"Error: {e}")
        return embeddings
```

### OS

Windows

### Python version

Python 3.11.5

### Library version

openai 1.37.0

**Comment by RobertCraigie** [comment]
please read the error message

> You tried to access openai.Embedding, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.
> 
> You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.
> 
> Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
> 
> A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by AnasBenAmor10** [comment]
openai migrate this command does not work with windows
