### ISSUE TITLE
add parallel_tool_calls to Runs.create_and_poll

### ISSUE THREAD

**Issue by gokhanmeteerturk** [openai/openai-python#1580]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Currently client.beta.threads.runs.create_and_poll doesn't accept parallel_tool_calls as an argument, and throws:
`TypeError: Runs.create_and_poll() got an unexpected keyword argument 'parallel_tool_calls'`

It can be included and passed to `self.create` here:
https://github.com/openai/openai-python/blob/195c05a64d39c87b2dfdf1eca2d339597f1fce03/src/openai/resources/beta/threads/runs/runs.py#L866C12-L889C10

**Comment by RobertCraigie** [comment]
Thanks for the report, this will be fixed in the next release https://github.com/openai/openai-python/pull/1582
