### ISSUE TITLE
be explicit about parallel_tool_call option for streams

### ISSUE THREAD

**Issue by mottoslo** [openai/openai-python#1595]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

For runs created by opening a stream, parallel_tool_call options could only be set to false using the extra_body argument, because the runs.stream function does not accept parallel_tool_call as an argument.
Because multiple tool outputs can only be submitted in a single request, managing and syncing the state of each tool_calls can add unnecessary complication in some use_cases. In that case, it requires testing to find out that turning off the parallel_tool_call option is also possible in streams, since documentation for parallel_tool_call is only provided for non-stream approach.

I've checked that parallel_tool_call option works as expected if passed in as extra_body. Although this works fine for me, I think such option should be explicitly set as keyword argument.

### Additional context

I'm quite new to the programming world, and I would like to try and make a PR for this if my request turns out to be valid.
It would be a great experience for me :)

**Comment by RobertCraigie** [comment]
Thanks for the report, the `parallel_tool_calls` request param will be added in the next release https://github.com/openai/openai-python/pull/1598
