### ISSUE TITLE
Support pydantic dataclasses in structured outputs

### ISSUE THREAD

**Issue by 9dogs** [openai/openai-python#1614]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

It would be great to be able to use data schemas defined as [pydantic dataclasses](https://docs.pydantic.dev/latest/concepts/dataclasses/) in structured outputs. E.g.
```python

from pydantic.dataclasses import dataclass
from openai import OpenAI

client = OpenAI()

@dataclass
class CalendarEvent:
    name: str
    date: str
    participants: list[str]

completion = client.beta.chat.completions.parse(
    model="gpt-4o-2024-08-06",
    messages=[
        {"role": "system", "content": "Extract the event information."},
        {"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
    ],
    response_format=CalendarEvent,
)

event = completion.choices[0].message.parsed
```

Pydantic dataclasses can be easily transformed into JSON schema via the [model_json_schema](https://docs.pydantic.dev/latest/api/json_schema/#pydantic.json_schema.model_json_schema) function.

**Comment by UtsavChokshiCNU** [comment]
@9dogs ... Are you able to even run the code from their tutorial with pydanitc?
It returns me an error : 
`AttributeError: 'Completions' object has no attribute 'parse'`

**Comment by parth126** [comment]
@UtsavChokshiCNU You need to update the api version to the latest version. Older version did not have parse attribute

**Comment by RobertCraigie** [comment]
Support for `pydantic.dataclasses.dataclass` has been added in `v1.42.0`
