### ISSUE TITLE
Too permissive permissions in file

### ISSUE THREAD

**Issue by arpitjain099** [openai/openai-python#1618]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Extracting files from a malicious tar archive without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten, due to the possible presence of directory traversal elements (..) in archive paths.

Affected file: https://github.com/openai/openai-python/blob/631a2a7156299351874f37c4769308a104ce19ed/src/openai/cli/_tools/migrate.py#L151-151

### To Reproduce

Bug present in file - https://github.com/openai/openai-python/blob/631a2a7156299351874f37c4769308a104ce19ed/src/openai/cli/_tools/migrate.py#L151-151

### Code snippets

```Python
Indicated here - https://github.com/openai/openai-python/blob/631a2a7156299351874f37c4769308a104ce19ed/src/openai/cli/_tools/migrate.py#L151-151
```

### OS

macOS

### Python version

3.11.4

### Library version

1.40.1

**Comment by RobertCraigie** [comment]
We are not worried about malicious tar archives in this case as we will only ever be downloading the tar archives from a trusted source.
