### ISSUE TITLE
Arbitrary file write during tarfile extraction

### ISSUE THREAD

**Issue by arpitjain099** [openai/openai-python#1620]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Extracting files from a malicious tar archive without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten, due to the possible presence of directory traversal elements (..) in archive paths.

### To Reproduce

Issue present in this line - https://github.com/openai/openai-python/blob/631a2a7156299351874f37c4769308a104ce19ed/src/openai/cli/_tools/migrate.py#L144

### Code snippets

```Python
https://github.com/openai/openai-python/blob/631a2a7156299351874f37c4769308a104ce19ed/src/openai/cli/_tools/migrate.py#L144
```

### OS

macOS

### Python version

3.11.4

### Library version

1.40.1

**Comment by RobertCraigie** [comment]
https://github.com/openai/openai-python/pull/1621#issuecomment-2294930975
