### ISSUE TITLE
The return type hint of `client.audio.transcriptions.create()` is incorrect.

### ISSUE THREAD

**Issue by gbaian10** [openai/openai-python#1633]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The return type hint of `client.audio.transcriptions.create()` is `Transcription`, and this type has a `text` attribute.

However, when the `response_format` is equal to `text`, `srt`, or `vtt`, its return value is str.
In this case, calling the text attribute will result in an error.

### To Reproduce

```py
import openai
from dotenv import load_dotenv

load_dotenv()

file_path = "example.wav"

client = openai.OpenAI()
with open(file_path, "rb") as file:
    transcript = client.audio.transcriptions.create(
        model="whisper-1", file=file, response_format="srt"
    )

    print(transcript)
    print(type(transcript))
    print(transcript.text)
    print(type(transcript.text))
```

### OS

Windows 10

### Python version

Python v3.12.4

### Library version

openai v1.40.3

**Comment by RobertCraigie** [comment]
Thanks for the report, this will be fixed in the next release. https://github.com/openai/openai-python/pull/1756
