### ISSUE TITLE
openai migrate - "ERROR (code: 200) - Too many params for text: expected maximum 1" 

### ISSUE THREAD

**Issue by jamintz** [openai/openai-python#1647]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

```ERROR (code: 200) - Too many params for text: expected maximum 1``` when running ```openai migrate```

### To Reproduce

openai migrate

### OS

macOS

### Python version

Python 3.12.5

### Library version

1.40.6

**Comment by RobertCraigie** [comment]
Can you share a full stack trace?

**Comment by jamintz** [comment]
> Can you share a full stack trace?

@RobertCraigie how do I do that?

**Comment by RobertCraigie** [comment]
oh is that all the output you get after running the command?

**Comment by gigantoq** [comment]
So there is no fix for this?

**Comment by morgante** [comment]
@gigantoq Until #1649 is released you can install Grit directly: https://docs.grit.io/cli/quickstart

Then just run `grit apply openai`.

**Comment by Shihab-Litu** [comment]
I got the same error below while apply "openai migrate" command:
"Your working tree currently has untracked changes and Grit will rewrite files in place. Do you want to proceed? yes
ERROR (code: 200) - Too many params for text: expected maximum 1"

OS- Linux-20.04
python-3.9.12

How to resolve this error?

**Comment by jaypinho** [comment]
I just received the same error too.

Python 3.13.0
MacOS Sequoia 15.1.1

**Comment by morgante** [comment]
Just follow the instructions above.
