### ISSUE TITLE
Completion api injecting restart text after every prompt, no option to switch it off like in playground

### ISSUE THREAD

**Issue by drisme** [openai/openai-python#166]
I'm not sure this is an issue with the python api per se.
When using the completion api to generate the next line of a poem using davinci, the api always starts the text with "\n\n". This can't be filtered with the logit parameter as the phrase "\n\n" is actually 4 tokens according to the tokenizer: [59, 77, 59, 77]

What is the correct workaround?
Is there any plan to add the option "Inject restart text" like in the playground? The restart text adds 4 tokens to each request, which adds up fast...

**Comment by hallacy** [comment]
I'm going to close this due to inactivity. Feel free to reopen.
