### ISSUE TITLE
Run Lifecycle Documentation Broken Link in README

### ISSUE THREAD

**Issue by camiloandresok** [openai/openai-python#1669]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The error involves a broken link in the README file that was supposed to direct users to the "Run Lifecycle Documentation." The broken link prevents users from accessing essential information about the project's execution stages, leading to potential confusion or errors in using the project. Fixing it is important for proper guidance.

### To Reproduce

- Navigate to the Repository: Open the GitHub 
- Locate the README File: Scroll down the main repository page to find the README file
- Find the Polling Helpers Section:
- Within the "Polling Helpers" section, look for a link labeled "Run Lifecycle Documentation."
- Click on this link.
- Observe the Error:
-  "404 Not Found" on https://platform.openai.com/docs/assistants/how-it-works/run-lifecycle 

### OS

All

### Python version

All

### Library version

All

**Comment by RobertCraigie** [comment]
Thanks for the report, this docs link has been restored!
