### ISSUE TITLE
ChatCompletionSystemMessageParam.name is not optional but the description says it should be

### ISSUE THREAD

**Issue by fgmacedo** [openai/openai-python#1670]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

The class param [`ChatCompletionSystemMessageParam.name`](https://github.com/openai/openai-python/blob/05fa732c024b55ddda1f5f8b107ce78233acd3ce/src/openai/types/chat/chat_completion_system_message_param.py#L20) is described as being optional, in fact, the API works without issues if we don't pass this param. But the type is not marked as optional. (Same issue with [`ChatCompletionUserMessageParam.name`](https://github.com/openai/openai-python/blob/05fa732c024b55ddda1f5f8b107ce78233acd3ce/src/openai/types/chat/chat_completion_user_message_param.py#L20) and [`ChatCompletionAssistantMessageParam.name`](https://github.com/openai/openai-python/blob/05fa732c024b55ddda1f5f8b107ce78233acd3ce/src/openai/types/chat/chat_completion_assistant_message_param.py#L47)).

Instead of being declared as

```py
class ChatCompletionSystemMessageParam(TypedDict, total=False):
    content: Required[Union[str, Iterable[ChatCompletionContentPartTextParam]]]
    """The contents of the system message."""

    role: Required[Literal["system"]]
    """The role of the messages author, in this case `system`."""

    name: str
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """
```

It should be declared as:

```py
class ChatCompletionSystemMessageParam(TypedDict, total=False):
    content: Required[Union[str, Iterable[ChatCompletionContentPartTextParam]]]
    """The contents of the system message."""

    role: Required[Literal["system"]]
    """The role of the messages author, in this case `system`."""

    name:  Optional[str]
    """An optional name for the participant.

    Provides the model information to differentiate between participants of the same
    role.
    """
```

### To Reproduce

Given this test file:

```
# test.py
import openai

client = openai.OpenAI()

response = client.beta.chat.completions.parse(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are an assistant."},  # <-  mypy claims this line has an error
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "What's up?"},
            ],
        },
    ],
)
```

Run:

``` bash
mypy .
```

Output:
```py
test.py:8: error: Type of TypedDict is ambiguous, none of ("ChatCompletionSystemMessageParam", "ChatCompletionUserMessageParam", "ChatCompletionAssistantMessageParam") matches cleanly  [misc]
```

### OS

ubuntu

### Python version

Python 3.12.2

### Library version

openai 1.42.0

**Comment by RobertCraigie** [comment]
What mypy version are you using? I can't reproduce on `1.11.1`.

Regardless, this is not a bug in the library. The `total=False` keyword argument in the class definition means that all fields that don't use the `Required` type can be omitted.

Please report a bug with mypy if this continues to fail for you.

**Comment by fgmacedo** [comment]
Hi @RobertCraigie , thanks for your fast reply. I'm using the same mypy version. Ok, now I see the `total=False`...  I don't know what's going on to make mypy sad. I'll skip the linter for this line. Best regards!
