### ISSUE TITLE
file attatched to thread cannot be searched

### ISSUE THREAD

**Issue by cclehui** [openai/openai-python#1672]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

i have a assistant with tool file search

and create a new thread , ask question "who is berryhoneffaaa"  (berryhoneffaaa is person only me know in my private knowlege database) ,  assisitant anwered  "I couldn't find any information on "berryhoneffaaa" in the files provided. If you have any additional context or details about Berryhoneffaaa, please provide them so I can better assist you."  . this is what i excepted

and then i upload my private knowlege file and attatached the file to the thread , and ask "who is berryhoneffaaa" , it **still** **answer "i dont known"**

![image](https://github.com/user-attachments/assets/947c43f7-235c-4771-86d7-8f13e6a32c0f)

**if i upload file before a ask the question, the assistant file search will search the uploaded file and  get the right answer**

### To Reproduce

see the Describe

### Code snippets

```Python
openai playground have this problem too
```

### OS

macOS

### Python version

python3.10

### Library version

openai 1.40.8

**Comment by RobertCraigie** [comment]
This is an issue with the API, not the Python SDK so please ask for help on the community forum!
