### ISSUE TITLE
Indentation error in _utils/_utils.py

### ISSUE THREAD

**Issue by seanonymous** [openai/openai-python#1678]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

It looks like there's a bug in the _utils/_utils.py file:
```
            for variant in variants:
                matches = all((param in given_params for param in variant))
                if matches:
                    break
            else:  # no break
                if len(variants) > 1:
                    variations = human_join(
                        ["(" + human_join([quote(arg) for arg in variant], final="and") + ")" for variant in variants]
                    )
                    msg = f"Missing required arguments; Expected either {variations} arguments to be given"
```
That `if matches:` and `else:  # no break` aren't aligned in the wrapper function. 

### To Reproduce

Look at the code in the wrapper() function of _utils/_utils.py

### OS

macOS

### Python version

Python 3.11

### Library version

openai v1.42.0

**Comment by RobertCraigie** [comment]
Ah this is not a bug!

The `else` is specifically aligned with the `for` loop so it'll be invoked if the `break` in the loop isn't hit.

Here's some docs on this syntax as it is fairly uncommon: https://book.pythontips.com/en/latest/for_-_else.html#else-clause
