### ISSUE TITLE
Add Memory to API

### ISSUE THREAD

**Issue by hayescode** [openai/openai-python#1699]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

The long term memory feature in ChatGPT is a great feature that i'd like to make available to my users via API. Before I invest time developing a less capable solution I want to check with the devs if this is on the API roadmap?

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
