### ISSUE TITLE
examples/embeddings/Visualize_in_3d.ipynb is empty

### ISSUE THREAD

**Issue by VoiceBeer** [openai/openai-python#1738]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Actually all the examples of embeddings are empty, could anybody share some example codes?

**Comment by RobertCraigie** [comment]
@VoiceBeer there is no `examples/embeddings` directory in this repo, where are you seeing these example notebooks?

**Comment by VoiceBeer** [comment]
Hi @RobertCraigie thx for the reply. I entered the repo via the “`the code for how to visualize embedding space in 3D dimension is available here`” link in the `text similarity models` section of this URL: [https://openai.com/index/introducing-text-and-code-embeddings/](url)

**Comment by RobertCraigie** [comment]
Thanks for the report, I've shared this with the OpenAI team so I'm going to close this for now.
