### ISSUE TITLE
Get info about model

### ISSUE THREAD

**Issue by palandovalex** [openai/openai-python#1759]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

I can list models, like this:

```python
import openai

for model in openai.models.list():
    print(model.id)

```

but i cant get info about model type. I dont get info about data types, that models acepts.

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
