### ISSUE TITLE
Audio generation from audio

### ISSUE THREAD

**Issue by yashinsmast** [openai/openai-python#1808]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

OpenAI recently introduced a new feature for generating audio from audio, and according to their documentation, you can use the new feature in Python by adding a parameter called modalities. However, when I try to use the feature, I receive the following error:

TypeError: Completions.create() got an unexpected keyword argument 'modalities'

It seems that the modalities parameter might not be recognized or properly implemented in the version I'm using. Could you please assist in resolving this issue and confirm if there are additional steps or updates required to use this feature?

**Comment by RobertCraigie** [comment]
it sounds like you aren't on the latest version, could you try updating? you can verify the version that your code is running with `import openai; print(openai.__version__)`
