### ISSUE TITLE
Difference response between requests from openai package and api.openai.com

### ISSUE THREAD

**Issue by trungnghiatn** [openai/openai-python#181]
Hi,
This is a simple example that return difference response between request from `openai` package and through the HTTP request
```
Human: "Give me an example sentence for the word: python"

> package:  'The python coiled itself around the tree branch.'
> HTTP request: 'Example: I am learning to code in Python this summer.'
```
Sometime, the HTTP response contains other words than `Example`, such as `Computer`, `AI`, `Bot`, `Robot`, ...
I wonder what is parameter to exclude these prefix in the response from HTTP request?
Thanks

**Comment by hallacy** [comment]
Hi @trungnghiatn, thanks for writing in.

There shouldn't be a difference between `openai` and HTTP (since `openai` is mostly a wrapper our around HTTP endpoints). Can you confirm that the settings in both cases are similar? In particular, you'd want to compare outputs with temperature=0

**Comment by trungnghiatn** [comment]
This is the **kwargs using `openai`:
```python
question = "What is the largest country in the world?"
response = openai.Completion.create(
            model='text-davinci-003',
            prompt=f'Human: {question}\nAI: ',
            temperature=0,
            max_tokens=200,
            top_p=1,
            frequency_penalty=0,
            presence_penalty=0.6,
            stop=['Human:', 'AI:']
        )
```
and this is the request body for request via HTTP:
```python
question = "What is the largest country in the world?"
body = {
            "stream": False,
            "prompt": [f"Human: {question}\nAI: "],
            "top_p": 1,
            "frequency_penalty": 0,
            "echo": False,
            "model": "text-davinci-003",
            "presence_penalty": 0.6,
            "temperature": 0,
            "n": 1,
            "max_tokens": 200,
            "best_of": 1,
            "stop": ['Human:', 'AI:']
        }
```
I tried to make both ways have the same configs but the outputs are slightly different:
via `openai`
```

The largest country in the world is Russia, with a total area of 17,098,242 square kilometers.
```
via `http`
```
?

The largest country in the world is Russia, with a total area of 17,098,242 square kilometers.
```
Please tell me your thought.

**Comment by hallacy** [comment]
So that I can replicate, can you show me the rest of your http call? These responses look pretty close

**Comment by hallacy** [comment]
I'm going to close this due to inactivity. Feel free to reopen.
