### ISSUE TITLE
Fine-tuning without using CLI

### ISSUE THREAD

**Issue by antocapp** [openai/openai-python#186]
Hello everyone, is there any example or snippet of code on how to fine-tune using the `FineTune` class directly in Python script, instead of the CLI commands?

**Comment by logankilpatrick** [comment]
Hey! You can see what we have available in the API here: https://beta.openai.com/docs/api-reference/fine-tunes?lang=python. With that said, it is not currently possible to use the Python SDK end to end for all of the steps required to create a fine tuned model. You will need to use the CLI for various steps like uploading data.

I know that having this directly in the Python SDK might be useful so we will explore this internally.

**Comment by antocapp** [comment]
Thanks @logankilpatrick !
