### ISSUE TITLE
Does logit_bias work for audio_preview?

### ISSUE THREAD

**Issue by justinebreuch** [openai/openai-python#1866]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

https://platform.openai.com/docs/api-reference/chat/create#logit_bias

### To Reproduce

When I pass logit_bias into the text-only models I get substantially different results than when I pass it into gpt-4o-audio-preview. It doesn't reject the logit_bias which makes me believe it is valid, but I'm unusure it's having an effect. Could you confirm? Thanks! 

### OS

macOS

### Python version

Python V2.11.4

### Library version

openai v1.01

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue as I'm not aware of the answer here myself.

Would you mind reposting at [community.openai.com](https://community.openai.com)?
