### ISSUE TITLE
make prompt caching available through api for prompts with less than 1024 token

### ISSUE THREAD

**Issue by leeflix** [openai/openai-python#1881]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

we could make great use of this awesome feature but our prompts are only around 700 tokens big

**Comment by RobertCraigie** [comment]
Thanks for reporting!  

This sounds like an issue with the underlying OpenAI API and not the SDK, so I'm going to go ahead and close this issue. 

Would you mind reposting at [community.openai.com](https://community.openai.com)?
