### ISSUE TITLE
Azure Endpoint URL is not Trailing-Slash Agnostic

### ISSUE THREAD

**Issue by Jozef833** [openai/openai-python#1894]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

In src/openai/lib/azure.py, there are four cases where the endpoint URL is simply concatenated like:

`f"{azure_endpoint}/openai/deployments/{azure_deployment}"`
or
`f"{azure_endpoint}/openai"`

If `azure_endpoint` has a trailing forward slash (which many comments in the code suggest is allowed, as well as [an example in the repository](https://github.com/openai/openai-python/blob/83f4774156dc3e29c7fe6be9ffd681df68534509/examples/azure.py#L29)), it will have `//` in the URL, which is wrong.

To make it agnostic, it should be:

`f"{azure_endpoint.rstrip("/")}/openai/deployments/{azure_deployment}"`
and
`f"{azure_endpoint.rstrip("/")}/openai"`

This would be sufficient to fix it: #1893 https://github.com/openai/openai-python/pull/1893/commits/673a496582ccf5d960e26a846cd6df81e837a9f9

### To Reproduce

1. Initialize an AsyncAzureOpenAI client.
2. Await on client.chat.completions.with_raw_response.create(**model_args).
3. The error code will be 404 Resource not found because the URL is not properly formatted.

### OS

Windows 10

### Python version

Python 3.12.4

### Library version

openai v1.6.1

**Comment by RobertCraigie** [comment]
Fixed in https://github.com/openai/openai-python/pull/1935
