### ISSUE TITLE
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by gregpr07** [openai/openai-python#1903]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

`SyncHttpxClientWrapper` has hard coded proxies but it no longer exists in httpx 0.28

### To Reproduce

1. `pip install openai`
2. the bug appears when calling `openai.OpenAI(**client_params, **sync_specific)`

### Code snippets

```Python
Traceback (most recent call last):
  File "/Users/greg/Documents/Work/browser-use/browser-use/examples/try.py", line 45, in <module>
    llm = get_llm(args.provider)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greg/Documents/Work/browser-use/browser-use/examples/try.py", line 28, in get_llm
    return ChatOpenAI(model='gpt-4o', temperature=0.0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 551, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/openai/_client.py", line 123, in __init__
    super().__init__(
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 857, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greg/Documents/Work/browser-use/browser-use/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 755, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

### OS

macOS

### Python version

Python v3.11.4

### Library version

openai 1.55.2

**Comment by simonw** [comment]
Same issue:
- #1902

**Comment by dgellow** [comment]
Thanks for the report, as mentioned by @simonw this is similar to #1902 and will be fixed by https://github.com/openai/openai-python/issues/1903. I will close this issue as duplicate.

**Comment by 3218923350** [comment]
What is the solution now？

**Comment by 3218923350** [comment]
I directly commented out the proxies in the constructor of SyncHttpxClientWrapper in openai/_base_client.py, and it works properly now.

**Comment by RobertCraigie** [comment]
Updating to the latest `openai` version will fix the issue.

**Comment by bsenftner** [comment]
Is this supposed to be fixed? I'm still seeing the 'proxies' issue when trying to update a container at AWS. I've updated to OpenAI 1.55.3, and my code does not use Httpx at all. I'm using the Async client.

    client = AsyncOpenAI( api_key=get_settings().OPENAI_API_KEY, )
    File "/home/app/venv/lib/python3.9/site-packages/openai/_client.py", line 337, in __init__
    super().__init__(
    File "/home/app/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1428, in __init__
    self._client = http_client or AsyncHttpxClientWrapper(
    File "/home/app/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1325, in __init__
    super().__init__(**kwargs)
    TypeError: __init__() got an unexpected keyword argument 'proxies'

**Comment by bsenftner** [comment]
Yes I am on the latest version. I log the OpenAI version via "RUN pip3 show openai" during container build, as well as 'import openai; log.info(openai.__version__)' when my app starts up and both confirm version 1.55.3.

**Comment by dgellow** [comment]
@bsenftner Could you try to pin httpx to 0.27.2? That wouldn't explain why it doesn't work in your environment but would unblock you

**Comment by bsenftner** [comment]
@dgellow I'm starting to think my pipeline may have some additional issue. I tried your suggestion of pinning httpx to 0.27.2 yesterday, and still saw the issue. Since that time my AWS specialist has been double checking things, so I'm trying the pinning of httpx to 0.27.2 again and will report back. 

No one else is seeing this, still, I guess?

**Comment by bsenftner** [comment]
Looks like the pinning is working now. My local container builds have been working the entire time, so I suspect I need to examine my build & deploy pipeline at AWS. If it's only me, then it's only my issue.

**Comment by goy-jin** [comment]
> 我在 openai/_base_client.py 的 SyncHttpxClientWrapper 的构造函数中直接注释掉了代理，现在它现在可以正常工作了。

我没有找到这个
>>> print(openai.__version__)
1.56.1

**Comment by redhatpeter** [comment]
Has this issue been fixed? still happening to me. 
python -c 'import openai; print(openai.__version__)'
1.56.2
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by vip2580** [comment]
using autogen to create agents still having same issue
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by tauqirghani** [comment]
I was having the same issue in 1.54.3, installing 1.55.3 solved my issue
