### ISSUE TITLE
New https release is breaking openai sdk while intitiating Async client

### ISSUE THREAD

**Issue by Alavi1412** [openai/openai-python#1908]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Recently, my codebase started to fail while initiating AsyncOpenAi. While debugging, I noticed AsyncOpenAI is using a version of `httpx` that accept keyword `proxies` but in the latest version (httpx 0.28.0), this keyword argument is removed from `__init__`.

To fix it, I manually limited installed httpx to use `0.27.2` which solves the problem but OpenAI SDK should have applied already that limitation on httpx allowed versions.

### To Reproduce

1. Install openai v1.30.1 with latest version of `httpx` (0.28)
2. Create a new instance of AsyncOpenAI
3. You should see the error at the instance creation.

### OS

Ubuntu

### Python version

3.9

### Library version

openai v1.30.1

**Comment by RobertCraigie** [comment]
This has already been fixed in the latest release! https://github.com/openai/openai-python/issues/1902
