### ISSUE TITLE
`ModuleNotFoundError: No module named 'openai'` even though installed

### ISSUE THREAD

**Issue by thann3** [openai/openai-python#192]
<img width="660" alt="Screenshot 2023-01-23 at 12 52 32 AM" src="https://user-images.githubusercontent.com/87835921/213999217-6f22d4f3-d6e9-4cb1-bbb7-4f2cee8ab700.png">
Hello, 
I created a new python=3.9 conda environment, and installed openai with pip. However, I found that I am unable to import it. 
Would anyone be willing to advise? Many thanks!

**Comment by logankilpatrick** [comment]
Hey! If you created a conda environment, you might need to also install the package with conda. Alternatively, you can create a new python virtual env by using the following commands :

```
python3 -m venv env

source env/bin/activate

pip3 install -r requirements.txt
```
[Note: python3 and pip3 assume MacOS as the operating system]

**Comment by logankilpatrick** [comment]
I am going to close this for now, but please let us know if you are still having issues after this!
