### ISSUE TITLE
Json_schema structured output type fails when extra_body is provided 

### ISSUE THREAD

**Issue by csirbu** [openai/openai-python#1928]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Trying to use the client.beta.chat.completions.parse function works until i try to provide an extra body argument, in this case Azure AI Search index.
Tested with versions 1.53.0, 1.54.3 and 1.57.0 

### To Reproduce

1. Run the completion without extra body
2. Remove comment for extra_body(give a valid azure search endpoint and index)

Error:
BadRequestError: Error code: 400 - {'error': {'requestid': '', 'code': 400, 'message': "Validation error at #/response_format/type: Input should be 'text' or 'json_object'"}}    

### Code snippets

```Python
class Answer(BaseModel):
    answer: str
extra_body = {
                 "data_sources": [
                    {
                        "type": "azure_search",
                        "parameters": {
                            "in_scope": True,
                            "strictness": int(4),
                            "top_n_documents": int(10),
                            "endpoint": "<azure search endppoint>",
                            "index_name": "<index-name>",
                            "authentication": {
                                "type": "system_assigned_managed_identity"
                            },
                            "embedding_dependency": {
                                "type": "deployment_name", 
                                "deployment_name": "text-embedding-3-large",
                                "dimensions": 3072,
                            },
                            "query_type": "vector_semantic_hybrid",
                            "semantic_configuration": "my-semantic-config",
                        }
                    }
                ]
            }
message_text = [ {"role": "user", "content": "when was google founded?"}]

structured_completion = openai_client.beta.chat.completions.parse(  
    model="gpt-4o",  
    messages=message_text,  
    max_tokens=800,  
    temperature=0.3, 
    # extra_body=extra_body,
    response_format=Answer
)  

response = structured_completion.choices[0].message.parsed
print(response)
```

### OS

macOS

### Python version

Python 3.12.7

### Library version

1.57.0

**Comment by RobertCraigie** [comment]
cc @kristapratico, I can't reproduce this with the main client

**Comment by ghost** [comment]
> [@csirbu](https://github.com/csirbu) Azure OpenAI [structured outputs](https://learn.microsoft.com/azure/ai-services/openai/how-to/structured-outputs?tabs=python-secure) is currently not supported with bring your own data. If passing an Azure Search index for your data source, `response_format`s supported are `text` and `json_object`. Note that this is a current limitation of the Azure service, not an issue with the Python client library. I'll pass on your feedback to the team.

was this issue solved?
