### ISSUE TITLE
All Playground Config Options are not available via API

### ISSUE THREAD

**Issue by normand1** [openai/openai-python#2]
There are a few config options that are available in the Playground, but not via the API. For example: Frequency Penalty, Presence Penalty, Best Of, etc. Is there a way to use these in the library now or will these eventually be added?

**Comment by schnerd** [comment]
@normand1 Those parameters should be supported. For instance:

```
response = openai.Completion.create(
  engine="davinci",
  prompt="Hello world",
  temperature=0,
  best_of=2,
  frequency_penalty=0.5,
  presence_penalty=2,
)
```

Pretty much anything you can pass as a part of the REST API (as defined in our API reference) should be accepted in the python API.
