### ISSUE TITLE
fix yes , i just recently found a funny problem , see this

### ISSUE THREAD

**Issue by doniramdani810** [openai/openai-python#205]
regards
Doni ramdani
Doniramdani810@gmail.com

![image](https://user-images.githubusercontent.com/108279884/214986941-a7d77060-92cf-4eb8-a330-ca287d6b41f0.png)

**Comment by hallacy** [comment]
Hi @doniramdani810,

This repo is only for openai-python related issues. For assistance on chat.openai.com, feel free to reach out on the forum or consult help.openai.com.
