### ISSUE TITLE
RateLimitError (You exceeded your current quota, please check your plan and billing details.)

### ISSUE THREAD

**Issue by StepHaze** [openai/openai-python#212]
I started using openai, created an account, got API Key.
When I try to use it, I get the error message: RateLimitError. You exceeded your current quota, please check your plan and billing details.

        openai.api_key = "..."
        openai.Model.list()
        response = openai.Completion.create(
            model='text-davinci-003',
            ........................
        )

**Comment by StepHaze** [comment]
Is it free or not?

**Comment by zhayujie** [comment]
I have encountered the same problem, and the frequency of my calling the interface is not high.

**Comment by hallacy** [comment]
Hi @StepHaze,

This repo is only for openai-python related issues. For assistance with Rate Limits, feel free to reach out on the forum or consult help.openai.com.

**Comment by Otkirbek10** [comment]
I am also had this error

**Comment by lokesh074** [comment]
is there any way to return this message in another form like if we get this error and we want to handle exception how can we do ?we want to return response same in api

**Comment by qaixerabbas** [comment]
@lokesh074 it depend on your use case and code that you write. In simple terms use try and except block and instead of returning the response from OpenAI API, you can customize this and return this in your own code.

**Comment by aaroniversion** [comment]
I try to use another person API Key, still have this problem, I do not not know how to solve it? or some one tried it before?

**Comment by qaixerabbas** [comment]
@aaroniversion you should check the available usage in the other person's usage page and check if he/she has an active subscription.

**Comment by MarcoA-013** [comment]
I have tested on may-02 several times and got no errors, now, in first test got the message... Think can be some kind of problem in API/Servers? One day works, another day nope...

**Comment by MarcoA-013** [comment]
PS: I have a free account with only 20 requests of 150.000 🔢
