### ISSUE TITLE
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!

### ISSUE THREAD

**Issue by zhayujie** [openai/openai-python#213]
I encountered many `RateLimitError` errors when I accessed the Completion interface today, but I actually did not call frequently, only about a few times a minute.

error message:
```bash
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
```

my request:
```python
response = openai.Completion.create(
      model="text-davinci-003",  
      prompt=query,
      temperature=0.9,  
      max_tokens=1200,  
      top_p=1,
      frequency_penalty=0.0,  
      presence_penalty=0.0,  
      stop=["#"]
  )
```
my env: 

+ Python 3.7.5
+ ubuntu 16.04

**Comment by hallacy** [comment]
Hi @zhayujie,

This repo is only for openai-python related issues. For assistance, feel free to reach out on the forum or consult help.openai.com.
