### ISSUE TITLE
Getting requests.exceptions.ChunkedEncodingError when using TaskCompletion in stream mode or 

### ISSUE THREAD

**Issue by WalidAxo** [openai/openai-python#218]
### Describe the bug

Hi, 

I'm using the openaI python module and I'm experiencing some issues lately. I'm making a streaming completion task. Randomly I'm getting the following exception "**requests.exceptions.ChunkedEncodingError : ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)**". 

`def send_completion_task_stream(self):`
 `       prompt = """my prompt"""`
 `           response = self.completion_task.create(prompt=prompt, model=self.modal_name, stop=self.stop,`
 `                                                  temperature=self.temperature,`
  `                                                 top_p=self.top_p, frequency_penalty=self.frequency_penalty,`
 `                                                  presence_penalty=self.presence_penalty,`
 `                                                  max_tokens=3000,`
 `                                                  stream=True`
                                                   )`
 `       return response `
 do you know what can cause this error ? 
 
 Thank you
 
 Best regards
        
        

### To Reproduce

1- Send a streaming completion task and put max-token to 3000
2 - The errors appears (but randomly)

### OS

macOs

### Python version

Python 3.10

### Library version

openai-python-0.26.1

**Comment by R0uter** [comment]
same here, for me it happens in non-English content and not related to the max-token I guess bcs I was set to 500.

**Comment by javi111717** [comment]
I'm having the same problem when making completions in spanish language.

**Comment by spelsbergsam** [comment]
Facing the same issues right now. I can see in the Sentry stack trace it looks as if the first exception that occurred was in the urllib3 library. 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/23108544/218780695-04550b2a-8fbe-4c3b-9eda-e353b1793662.png">

However, I got a 200 from openai

<img width="829" alt="image" src="https://user-images.githubusercontent.com/23108544/218781018-013fb48a-9b00-48dc-9381-d40e55ce434c.png">

And i can see that the data received back from openai even includes the text for a generation. 

<img width="812" alt="image" src="https://user-images.githubusercontent.com/23108544/218781375-f7e59353-32aa-4a1a-97b1-2925cc79fe93.png">

Not sure why the error is happening only occasionally

**Comment by WalidAxo** [comment]
Today is impossible to use the api. I'm getting the error over and over. 

Any idea on what causing it ?

**Comment by WalidAxo** [comment]
Today is impossible to use the api. I'm getting the error over and over.

Any idea on what causing it ?

**Comment by ArtemBernatskyy** [comment]
lol, maybe we need to migrate to Azure API of ChatGPT...

**Comment by yannoth** [comment]
same error here

**Comment by aditivin** [comment]
same here. Anyone found a solution for it?

**Comment by benjaminb** [comment]
Same, every single request I've sent to `gpt-4` for the last 2 days fails due to this chunked encoding error. Is there a way to recover from this state while streaming?

**Comment by rattrayalex** [comment]
I believe this has been resolved; please let me know if that's not the case and we can reopen.
