### ISSUE TITLE
What are the depencies? Why are these not specified in setup.py

### ISSUE THREAD

**Issue by alvitawa** [openai/openai-python#220]
### Describe the bug

Installing openai on a clean repo doesn't work because dependencies are missing such as numpy and matplotlib.

### To Reproduce

- 

### OS

linux

### Python version

3.8

### Library version

latest

**Comment by hallacy** [comment]
H @alvitawa, thanks for the bug.

The dependencies are listed in https://github.com/openai/openai-python/blob/main/setup.cfg. If you need numpy and matplotlib, you're probably trying to do finetuning or wandb work and should install one of the target like datalib or wandb.
