### ISSUE TITLE
Why not open to China

### ISSUE THREAD

**Issue by LightByteCode** [openai/openai-python#229]
### Describe the feature or improvement you're requesting

I hope that the OpenAI API will be opened to China.

**Comment by abodacs** [comment]
Hoping the same for Egypt

**Comment by logankilpatrick** [comment]
Thanks for flagging, see our supported countries here: https://platform.openai.com/docs/supported-countries

**Comment by abodacs** [comment]
Thanks for your replay but the link is not working in Egypt also

![Screenshot from 2023-03-03 22-52-07](https://user-images.githubusercontent.com/554032/222827322-e9a6a7e0-e88e-4dbb-8450-454a70575ea8.png)

**Comment by michaelwnau** [comment]
> Thanks for flagging, see our supported countries here: https://platform.openai.com/docs/supported-countries

What are the exceptions listed for Ukraine?
