### ISSUE TITLE
openai.Completion.retrieve()

### ISSUE THREAD

**Issue by hend41234** [openai/openai-python#231]
### Describe the bug

**EngineAPIResource.__init__() takes from 1 to 2 positional arguments but 3 were given**

### To Reproduce

does this only happen to me when using 'retrieve' in openai.
i got this error :  **"EngineAPIResource.__init__() takes from 1 to 2 positional arguments but 3 are given"**

### Code snippets

```Python
key = "my_api_key"
openai.api_key=key
id_chat = "my_completion_id"
try:
    result = openai.Completion.retrieve(id_chat)
    print(result['choices'][0]['text'])
except Exception as a:
    print(a)
```

### OS

arch linux

### Python version

Python 3.10.9

### Library version

openai-python v0.26.5

**Comment by FizzyAgent** [comment]
openai currently does not support retrieving past completions, you should save and manage completion responses client-side.

**Comment by hallacy** [comment]
^ is correct. There is no way to retrieve past completions with the API

**Comment by Fiyaas** [comment]
https://github.com/openai/openai-python/issues/231#issue-1603189938

**Comment by Fiyaas** [comment]
key = "my_api_key"
openai.api_key=key
id_chat = "my_completion_id"
try:
    result = openai.Completion.retrieve(id_chat)
    print(result['choices'][0]['text'])
except Exception as a:
    print(a)
