### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?

### ISSUE THREAD

**Issue by mike2505** [openai/openai-python#239]
### Describe the bug

Trying to run gpt-3.5-turbo model but it's throwing next error: AttributeError: module 'openai' has no attribute 'ChatCompletion'. Did you mean: 'Completion'?
Updated to latest version, not working.

### To Reproduce

1. Install latest openai
2. Copy code from official documentation
3. Run

### Code snippets

```Python
import openai
openai.api_key = 'sk-***'

completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo", 
  messages=[{"role": "user", "content": "Tell the world about the ChatGPT API in the style of a pirate."}]
)

print(completion)
```

### OS

Arch Linux - 6.1.4-arch1-1

### Python version

Python v3.10.9

### Library version

openai-python v0.27.0

**Comment by logankilpatrick** [comment]
Can you try making a new virtual env and seeing if the issue persists?

**Comment by mike2505** [comment]
> Can you try making a new virtual env and seeing if the issue persists?

Fixed
