### ISSUE TITLE
There is no metadata, please fix it

### ISSUE THREAD

**Issue by kopyl** [openai/openai-python#241]
### Describe the bug

There is no metadata in the response for individual words like what's the language of a word, start time and end time.

### To Reproduce

1. Run the code snippet below.

### Code snippets

```Python
os
import openai

openai.organization = os.environ.get("OPENAIORGANIZATIONID")
openai.api_key = os.environ.get("OPENAIAPIKEY")

file = open("/Users/olehkopyl/Downloads/test.m4a", "rb")
transcription = openai.Audio.transcribe("whisper-1", file)

print(transcription)
```

### OS

macOS

### Python version

3.8.13

### Library version

0.27.0

**Comment by mpokrass** [comment]
hi there! we do offer a different response format for whisper if you want to get more verbose data about the audio. you can try it out like so

```python
import openai
f = open("/path/to/file.mp3", "rb")
transcript = openai.Audio.transcribe("whisper-1", f, response_format="verbose_json")
```

**Comment by kopyl** [comment]
@mpokrass nope, 

1. It only transcribes in one language
2. It does not tell a language for each token/segment

Any way to make it actually work?
