### ISSUE TITLE
Can't access gpt-3.5-turbo - AttributeError: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by kenist0n** [openai/openai-python#242]
### Describe the bug

Can't access gpt-3.5-turbo with python. getting an error when i try to use openai.ChatCompletion.create

### To Reproduce

1. pip install openai
2. import openai + key
3. enter code snippet into jupyter notebook
4. get error

### Code snippets

```Python
# Note: you need to be using OpenAI Python v0.27.0 for the code below to work
import openai

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

### OS

windows11

### Python version

python 3.9.7

### Library version

openai-python v0.27.0

**Comment by mrbullwinkle** [comment]
I was having the same issue. If you haven't already it might be worth running pip freeze to make sure you are actually on the  .0.27.0 package. I found that `pip install openai` wasn't resulting in my existing package being updated to the lastest version I had to do a force reinstall:

```
pip install --force-reinstall -v "openai==0.27.0"
````
Then everything worked as expected:
![image](https://user-images.githubusercontent.com/31510320/222267632-e972ecd0-7701-416e-ba95-4fa7fd3c0cad.png)

**Comment by Wikileas** [comment]
> I was having the same issue. If you haven't already it might be worth running pip freeze to make sure you are actually on the .0.27.0 package. I found that `pip install openai` wasn't resulting in my existing package being updated to the lastest version I had to do a force reinstall:
> 
> ```
> pip install --force-reinstall -v "openai==0.27.0"
> ```
> 
> Then everything worked as expected: ![image](https://user-images.githubusercontent.com/31510320/222267632-e972ecd0-7701-416e-ba95-4fa7fd3c0cad.png)

For me, this did not work, I had to install from source, since that for some reason, I could only download version until 0.26.5.

**Comment by BigPapaK** [comment]
> I was having the same issue. If you haven't already it might be worth running pip freeze to make sure you are actually on the  .0.27.0 package. I found that `pip install openai` wasn't resulting in my existing package being updated to the lastest version I had to do a force reinstall:
> 
> 
> 
> ```
> 
> pip install --force-reinstall -v "openai==0.27.0"
> 
> ````
> 
> Then everything worked as expected:
> 
> ![image](https://user-images.githubusercontent.com/31510320/222267632-e972ecd0-7701-416e-ba95-4fa7fd3c0cad.png)
> 
> 
> 
> 

That worked perfectly, got ir working right after. So weird it didn't work though, cause whenever i installed and deinstalled it said i actually had v0.27 on my machine.

**Comment by ChangQingAAS** [comment]
> athyuttamre

##### you can change your host:

in ~/.pip/pip.conf
```
[global]
index-url= http://mirrors.aliyun.com/pypi/simple/
extra-index-url= https://pypi.python.org/simple

[install]
trusted-host=mirrors.aliyun.com
```

or  run this in shell
```shell
pip install -i http://pypi.python.org/simple/ openai==0.27.0
```

**Comment by zhangsz1998** [comment]
> ```shell
> pip install -i http://pypi.python.org/simple/ openai==0.27.0
> ```

Change 'http' to 'https' and everything works fine for me. Thank!

**Comment by WpUser10** [comment]
could u tell me what url to use for gpt-3.5-turbo ?
i was trying old one and i did not works.
$url = 'https://api.openai.com/v1/chat';

**Comment by HAIXteam** [comment]
HI, I am trying this on ubuntu 18.x server. getting the same error.
tried with both:
pip install --force-reinstall -v "openai==0.27.0"
pip install -i http://pypi.python.org/simple/ openai==0.27.0

ERROR: Could not find a version that satisfies the requirement openai==0.27.0 (from versions: none)
ERROR: No matching distribution found for openai==0.27.0


ERROR: Could not find a version that satisfies the requirement openai==0.27.0 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
ERROR: No matching distribution found for openai==0.27.0

**Comment by zhangsz1998** [comment]
I think you should update your python version since openai==0.27.0 requires python >= 3.7.1

**Comment by WpUser10** [comment]
It’s easy for you with everything ready, but I’m connecting to PHP, and in general I had to write everything from scratch.

**Comment by scoobypro1234** [comment]
It is Easy to Fix this Error.
Just Simply convert chatcompletions to completions

the error will be fixed.
