### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'ChatCompletion'

### ISSUE THREAD

**Issue by monk1337** [openai/openai-python#246]
### Describe the bug

The feature was working few hours ago, now it's giving error. 

### To Reproduce

```
import openai

openai.api_key = 'key'

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)
```

### OS

macOS

### Python version

Python v3.7.1

### Library version

openai v0.26.5

### no function  as ChatCompletion the defined methods

```
import openai
print(openai.__dir__())
```

['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__path__', '__file__', '__cached__', '__builtins__', '__annotations__', 'os', 'Optional', 'error', 'util', 'version', 'openai_response', 'api_requestor', 'openai_object', 'api_resources', 'Answer', 'Classification', 'Completion', 'Customer', 'Edit', 'Deployment', 'Embedding', 'Engine', 'ErrorObject', 'File', 'FineTune', 'Image', 'Model', 'Moderation', 'Search', 'APIError', 'InvalidRequestError', 'OpenAIError', 'api_key', 'api_key_path', 'organization', 'api_base', 'api_type', 'api_version', 'verify_ssl_certs', 'proxy', 'app_info', 'enable_telemetry', 'ca_bundle_path', 'debug', 'log', '__all__']

**Comment by logankilpatrick** [comment]
Please bump your `openai v0.26.5` to v0.27.0.

**Comment by elias-py** [comment]
You should have the new version v.27.0

**Comment by onesecurity** [comment]
running the command:

`pip install --upgrade openai
`
Alternatively, to install it manually, do the following:

1. Download openai-0.27.0-py3-none-any.whl from https://pypi.org/project/openai/#files
2. Run `pip install openai-0.27.0-py3-none-any.whl`

**Comment by captain-miao** [comment]
openai-0.27.0

2023-03-02 11:16:49,016 - openai - INFO - error_code=None error_message='Invalid URL (POST /v1/engines/gpt-3.5-turbo/chat/completions)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

**Comment by captain-miao** [comment]
> openai-0.27.0
> 
> 2023-03-02 11:16:49,016 - openai - INFO - error_code=None error_message='Invalid URL (POST /v1/engines/gpt-3.5-turbo/chat/completions)' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False

It's already OK, caused by parameter error.


```python
        response = completion.create(
            model="gpt-3.5-turbo-0301",
            messages=[{"role": "user", "content": update.message.text}],
            max_tokens=1024,
            n=1,
            temperature=0.5,
        )
        update.message.reply_text(response["choices"][0]["message"]["content"])
```

**Comment by hanswang73** [comment]
> 

I do it, but the problem do not disappear.

**Comment by hanswang73** [comment]
> running the command:
> 
> `pip install --upgrade openai ` Alternatively, to install it manually, do the following:
> 
> 1. Download openai-0.27.0-py3-none-any.whl from https://pypi.org/project/openai/#files
> 2. Run `pip install openai-0.27.0-py3-none-any.whl`

I do it, but the problem do not disappear.

**Comment by mizumot** [comment]
Restarting Python itself may solve the problem. It worked for me.

**Comment by emilycowe** [comment]
I'm getting the same issue, despite using openai-0.27.0. Does anyone have any ideas of what else I can try?

**Comment by monk1337** [comment]
I solved the issue by upgrading the openai v27.0 by

`pip install --upgrade openai`

Example Usage:

ChatGPT API has been added in [Promptify](https://github.com/promptslab/Promptify); you can use it like this.

`from promptify import OpenAI
from promptify import Prompter

sentence     =  """The patient is a 93-year-old female with a medical                   
                history of chronic right hip pain, osteoporosis,                    
                hypertension, depression, and chronic atrial                        
                fibrillation admitted for evaluation and management                
                of severe nausea and vomiting and urinary tract                
                infection"""

model        = OpenAI('key', model = "gpt-3.5-turbo")
nlp_prompter = Prompter(model)


result       = nlp_prompter.fit('ner.jinja',
                          domain      = 'medical',
                          text_input  = sentence, 
                          labels      = None)

eval(result['text'])`

Output

`[{'E': '93-year-old', 'T': 'Age'},
 {'E': 'chronic right hip pain', 'T': 'Medical Condition'},
 {'E': 'osteoporosis', 'T': 'Medical Condition'},
 {'E': 'hypertension', 'T': 'Medical Condition'},
 {'E': 'depression', 'T': 'Medical Condition'},
 {'E': 'chronic atrial fibrillation', 'T': 'Medical Condition'},
 {'E': 'severe nausea and vomiting', 'T': 'Symptom'},
 {'E': 'urinary tract infection', 'T': 'Medical Condition'},
 {'Branch': 'Internal Medicine', 'Group': 'Geriatrics'}]`

More examples: Question-Answering, Relation-Extraction, Classification, NER etc in [three lines of code](https://github.com/promptslab/Promptify)

**Comment by suyin1203** [comment]
use jupyter
1. pip uninstall openai
2. close kernel (shut down kernel)
3. open notebook
4. !pip install --upgrade openai
5. its run

**Comment by hiddenchamp** [comment]
I wasted a lot of time to try to get it working. Maybe this helps someone:

AFTER updating with `pip install --upgrade openai `

Go here:

`In pycharm go to settings > project blabla > python interpreter > click the + sign > find openai > click "Specify version: 0.27.0" VERY IMPORTANT > click install package. Restart pycharm.`

It should work now.

**Comment by emilycowe** [comment]
> I wasted a lot of time to try to get it working. Maybe this helps someone:
> 
> AFTER updating with `pip install --upgrade openai `
> 
> Go here:
> 
> `In pycharm go to settings > project blabla > python interpreter > click the + sign > find openai > click "Specify version: 0.27.0" VERY IMPORTANT > click install package. Restart pycharm.`
> 
> It should work now.

Do you have any idea how to get it working if you're not using Pycharm? Im having the same issue despite updating openai.

**Comment by hiddenchamp** [comment]
> Do you have any idea how to get it working if you're not using Pycharm? Im having the same issue despite updating openai.

No unfortunately. I just started coding in python 1 month ago because of AI.
I guess if you are using something else, try to uninstall the current openai module and force the version number somehow.

**Comment by hanswang73** [comment]
I have the same problem, but the reason is that I copy a venv directory, so VSCode still use the python.exe in original venv directory ....

**Comment by manish-marwah** [comment]
in Jupyter notebook, you have restart the kernel after upgrading openai, then it works

**Comment by ArslanKAS** [comment]
**Solution for Jupyter Notebook or Notebook in VSC:**
1- pip install -U openai
2- restart the kernel

**Comment by xin007-kong** [comment]
@monk1337   I tried your code but I meet the following mistake
    model = OpenAI('key', model="gpt-3.5-turbo")
TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by jzade** [comment]
> 

This worked perfectly. What's strange is that I ran pip install openai again because I know ChatCompletion was not a listed resource in the openai definition. This did not update the library but running the command suggested resolved our issues. Thanks!

**Comment by logankilpatrick** [comment]
Folks, this is a common Python issue, it is not an issue on the OpenAI package side, if you create a new virtual env and install the package in there, it will work without issue. But the global python package version issue is likely causing this problem for everyone. 

Please open new issues if this does not work using a virtual env!

**Comment by utkarshp1161** [comment]
update your python version:

I updated from python3.7 to python3.10, and upgraded openapi using pip, worked for me.

**Comment by xuuxij** [comment]
I did this in PowerShell, My 'venv' virtual environment and windows CMD.  This was the only thing that worked for me.

python3 -m pip install --upgrade openai

**Comment by Integ** [comment]
Don't name your python file `openai.py`!

**Comment by sherry-500** [comment]
I'm getting the same issue, despite using openai-3.2.0

**Comment by JagoWang** [comment]
> 

It's worked

**Comment by cavin91dsouza** [comment]
For those struggling, also ensure one more thing:
 Package 'openai' requires Python '>=3.7.1'

**Comment by mishra077** [comment]
1. Check your python-version it needs to be >= 3.7
2. Check your openai version it needs to  v27.0 or greater.
3. If above points doesn't help you make sure you don't have file named openai.py
4. Lastly, if you're using conda and tried to install using both conda and pip commands. Uninstall openai from your conda env and try to run it again.

**Comment by VadimBoev** [comment]
> Don't name your python file `openai.py`!

thanks, it solved my problem

**Comment by githycody** [comment]
This did it for me using python in VSC.

1. pip install --upgrade openai
2. Install the latest version of Python
3. go to Settings (VSC) > Extensions > Python: Default Interpreter Path - Change python to python3
4. Restart VSC

Should now work
