### ISSUE TITLE
can not work with  jupyterlab-desktop

### ISSUE THREAD

**Issue by wwj718** [openai/openai-python#247]
### Describe the bug

When I use openai package with  [jupyterlab-desktop](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.6.1-2), the following error occurred:

<img width="743" alt="image" src="https://user-images.githubusercontent.com/3153878/222313242-bd1b48da-bd09-44f2-9e63-e9342d880f21.png">

environment:

- MacOS 13.2.1(M1)
- openai == 0.27.0
- jupyterlab-desktop == 3.6.1-2
  - python3.8

### To Reproduce

1. open jupyterlab-desktop
2. install openai: `!pip install openai`
3. import openai

### Code snippets

```Python
import openai
```

### OS

MacOS 13.2.1(M1)

### Python version

python3.8

### Library version

openai == 0.27.0

**Comment by logankilpatrick** [comment]
Hey! This looks like a Jupyter issue, the kernel is essentially the Jupyter runtime so if it is not working, you need to troubleshoot on the Jupyter side.
