### ISSUE TITLE
Ability to batch prompts in Chat Completion like for the Completion endpoint.

### ISSUE THREAD

**Issue by h-gharbi** [openai/openai-python#254]
### Describe the feature or improvement you're requesting

In the Completion endpoint we can batch input prompts in one API request. It would be nice to have the same feature for the Chat Completion.

**Comment by sfarrell5123** [comment]
it already has index in the response.

either batch on the chat endpoint

or allow us gpt-35-turbo on the complete endpoint - so we can batch there.

**Comment by logankilpatrick** [comment]
I am going to close for now since this repo is for the Python SDK not API feedback but will follow up if we end up adding this.

**Comment by JakeWinter** [comment]
Tried to see async requests in python, sometimes it stalls out, sometimes I works well

**Comment by morenobonaventura** [comment]
this is an alternative solution:
https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py

**Comment by SantoshGuptaML** [comment]
> this is an alternative solution: https://github.com/openai/openai-cookbook/blob/main/examples/api_request_parallel_processor.py

This doesn't seem to be quite fully done for the chat completions endpoint, I get an error with the tokenizer. I created a version that is working

https://github.com/openai/openai-cookbook/blob/987d8cb2585424bad1594b5e50787ef221d5cc3d/examples/api_request_parallel_processor.py#L353

**Comment by FilippoBoni1921** [comment]
I am facing the same issue. I think that giving the possibility to batch the request was a really helpful feature for completion that has been removed with chat.completion. I think that would have been better to spend some time on it before releasing. 
Anyway I think quite some time has passed and still we do not have a concrete alternative. Apart from the introduction of the "system message" I do not see a lot of advantages of chat.completions over simple completion.
Also I have one question: why completions has been being labelled as legacy for such a long time but not eliminated, nor fully substituted?
I am really looking forward to an alternative for batch processing if someone can suggest. I hope to receive an answer even after so so much time from the opening of the issue
