### ISSUE TITLE
How to get the parameters in gpt 3.5 turbo?

### ISSUE THREAD

**Issue by hiddenchamp** [openai/openai-python#256]
### Describe the feature or improvement you're requesting

With davinci I used these:

```
                    max_tokens=40,
                    n=1,
                    stop=None,
                    temperature=0.5
```

How can I get the same with gpt 3.5 turbo in python?

### Additional context

NEVERMIND: I just found out that it works the same way. I had an error when I tried it initially.

**Comment by logankilpatrick** [comment]
You can see all the available params here: https://platform.openai.com/docs/api-reference/chat/create
