### ISSUE TITLE
Possibility of token limit increase

### ISSUE THREAD

**Issue by sandeepreddy5** [openai/openai-python#264]
### Describe the bug

Hi, currently we are facing problems with token limitation which is 4097. Is there any possibility to increase existing token limit to 7000 tokens.
Thanks in advance 

### To Reproduce

NA

### OS

Linux

### Python version

Python v3.8

### Library version

openai-python v0.26.5

**Comment by logankilpatrick** [comment]
Hey, there is no way to increase the number of tokens, I suggest you try out some different truncation approaches.
