### ISSUE TITLE
openai.error.APIConnectionError: Unexpected error communicating with OpenAI.  If this problem persists, let us know at support@openai.com.

### ISSUE THREAD

**Issue by swlcyx** [openai/openai-python#265]
### Describe the bug

openai.error.APIConnectionError: Unexpected error communicating with OpenAI.  If this problem persists,
let us know at support@openai.com.

### To Reproduce

openai.error.APIConnectionError: Unexpected error communicating with OpenAI.  If this problem persists,
let us know at support@openai.com.

### Code snippets

```Python
response = openai.Completion.create
```

### OS

win

### Python version

3.7

### Library version

openai==0.8.0 openai==0.27.0

**Comment by logankilpatrick** [comment]
Hey, it looks like you are using the wrong syntax, it should be:

```python
completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": "Hello!"}
  ]
)
```
