### ISSUE TITLE
ChatGPT API

### ISSUE THREAD

**Issue by tmgthb** [openai/openai-python#268]
### Describe the feature or improvement you're requesting

I would like to be able to manage multiple users in the ChatGPT. The idea is for the API to understand who is speaking as now only one user, one system and one assistant. It would be cool to have possibility to define multiple users and even multiple assistants (specialization?)
So the inputs would be sonething similar as below: 
{role: “user1”, ”content”: ”I think open source is great way to improve LLMs..”}
{role: “user12, ”content”: ”I think open source LLMs can be risky in hands of bad actors.”}

### Additional context

See above

**Comment by logankilpatrick** [comment]
Thanks for the suggestion! It is something we are aware people are interested in : )
