### ISSUE TITLE
Consider using hatch as build-backend?

### ISSUE THREAD

**Issue by ischaojie** [openai/openai-python#269]
### Describe the feature or improvement you're requesting

`setup.py` + `setup.cfg` is an outdated way of building Python projects. The configuration can be moved to `pyproject.toml` for consistency.

[hatch](https://github.com/pypa/hatch) is a modern python project management tool. hatch is used by the likes of fastAPI, black, pydantic and others to manage projects.

**Comment by RobertCraigie** [comment]
In our [v1 beta](https://github.com/openai/openai-python/discussions/631) we've migrated to Rye which uses [Rye](https://rye-up.com/) under the hood.
