### ISSUE TITLE
Django text not near and no space

### ISSUE THREAD

**Issue by 161134077** [openai/openai-python#272]
### Describe the feature or improvement you're requesting

Django bot chatgpt text not near, why?

![chatgpt](https://user-images.githubusercontent.com/39833970/222942356-741f98b4-aa65-44f9-8646-2b23dfc07bcd.PNG)

chatgpt text near and space

![chatgpt2](https://user-images.githubusercontent.com/39833970/222942395-495fc103-e694-40f6-95b9-fb3e6d1f3134.PNG)

**Comment by logankilpatrick** [comment]
Hey! Please use the built in feedback button on ChatGPT to give these suggestions, we do not monitor this repo for ChatGPT feedback.
