### ISSUE TITLE
Incomprehensible Response Using Davinci

### ISSUE THREAD

**Issue by Hugh0120** [openai/openai-python#276]
### Describe the bug

I used the OpenAI API to call the Davinci model, but the results are incomprehensible and different from what is returned in the playground.

Here is what it responds:

`
{
  "id": "cmpl-6qyqT0nO2doVmbzd4zdVoOvbtWM00",
  "object": "text_completion",
  "created": 1678084965,
  "model": "gpt-3.5-turbo-0301",
  "choices": [
    {
      "text": "们以前的关于春天万物竞发，勃勃生机，优势在我们以前的资源浮奏游戏。\n\n1. 软件开发错误。\n\n2. 微软离席。\n\n3. 我不想对大部分小偷一点说话，但是总要加快进一步的开发人员应当迁移所有行为之间关系。如果大家负责开发人员或者已经选用了一些理由来重复使用不合理性，那么刚才凭着中文字幕来汇集数据，随时上传到Twitter、Facebook、Google+各方面的微信公众图片账户。而这一时候如果能在微信上带有明显的内容时遇到一个微博广告，就相当关注。你不能标准化交流，不能原始冲突...",
      "index": 0,
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 68,
    "completion_tokens": 420,
    "total_tokens": 488
  }
}`

### To Reproduce

just using the api introduced in https://platform.openai.com/docs/guides/completion

### Code snippets

```Python
response = openai.Completion.create(
  model="gpt-3.5-turbo",
  prompt="按照以下要求生成一篇中文文章，关于春天万物竞发，勃勃生机，优势在我",
  temperature=0.7,
  max_tokens=1695,
  top_p=1,
  frequency_penalty=0.59,
  presence_penalty=0.77
)
```

### OS

macOS

### Python version

Python 3.7.6

### Library version

v.0.27.0

**Comment by logankilpatrick** [comment]
> response = openai.Completion.create(
  model="gpt-3.5-turbo",
  prompt="按照以下要求生成一篇中文文章，关于春天万物竞发，勃勃生机，优势在我",
  temperature=0.7,
  max_tokens=1695,
  top_p=1,
  frequency_penalty=0.59,
  presence_penalty=0.77
)

this will not work, you need to use the ChatCompletions API: https://platform.openai.com/docs/api-reference/chat

Let me know if you are still having issues after that!

**Comment by Hugh0120** [comment]
I posted the wrong code which related to another [issue ](https://github.com/openai/openai-python/issues/263)
but same error occurs when I use text-davinci-003 and openai.createCompletion API

could you check the req id `cmpl-6qyqT0nO2doVmbzd4zdVoOvbtWM00` to see if there is any problem with my req?
