### ISSUE TITLE
acreate method fail when using async 

### ISSUE THREAD

**Issue by menghonghan** [openai/openai-python#278]
### Describe the bug

![image](https://user-images.githubusercontent.com/61367724/223109301-718e8e33-36d8-4ad3-8146-f26eca0bc295.png)

![image](https://user-images.githubusercontent.com/61367724/223112509-f2a783fe-30bb-4402-849a-403cfbdb4697.png)

when using async  acreate , the API timeout 

### To Reproduce

async def chat(query, retry_count=0):
response = await openai.ChatCompletion.acreate(
         model="gpt-3.5-turbo",  
         messages=query,
         temperature=0.7,  
         max_tokens=1200,  
         top_p=1,
         frequency_penalty=0.0,  
         presence_penalty=0.0,  
     )

     out = response.choices[0]['message']['content']

@gpt_app.post("/gpt_go")
async def gpt_go(request: Request):
    json_data = await request.form()
    
    role = json_data["role"]
    content = json_data["content"]
    output = await chat([{"role": "system", "content":"hello"}])
    return output

### OS

linux

### Python version

Python 3.7

### Library version

openai 0.27.0

**Comment by TheLZY** [comment]
In my server, upgrade aiohttp to 3.8.4 solved this.

> https://github.com/nonebot/nonebot2/issues/1784#issuecomment-1462842717

**Comment by wadecong** [comment]
ClientSession(trust_env=True)

https://stackoverflow.com/a/63364551/2142477

**Comment by frostming** [comment]
Workaround: replace the session object:


```python
with ClientSession(trust_env=True) as session:
    openai.aiosession.set(session)
    ...
```

**Comment by jinghan23** [comment]
I met the same problem. I'm wondering if the above solutions work for you? I'm not sure how to add ClientSession in the codes

**Comment by artmatsak** [comment]
In my case, the issue turned out to be `urllib` (probably?) failing to locate the CA SSL certificates on the system. The funny thing is that non-async requests worked - apparently because the OpenAI API library uses different HTTP libraries for sync and async.

For me (Python 3.10 installed via MacPorts on macOS), the fix was to add this to `.zshrc`:

```
export SSL_CERT_FILE=$(python3 -m certifi)
```

**Comment by RobertCraigie** [comment]
This should be fixed in the [upcoming v1 beta](https://github.com/openai/openai-python/discussions/631)! Please try it and let us know!
