### ISSUE TITLE
Moderation bypasses proxy settings

### ISSUE THREAD

**Issue by jfduque** [openai/openai-python#279]
### Describe the bug

In an environment without direct access to the Internet, If you pass proxy settings to the `openai `object and try to perform input validation, the `openai.Moderation.create()` call hangs on or times out.

Those same proxies do work for `openai.ChatCompletion.create()` and `openai.ChatCompletion.create()` calls.

### To Reproduce

1. Prepare a no-internet environment that includes http&https proxy
2. Import openai library, set api key and proxy
3. Try to moderate a message
4. `openai.Moderation.create()` hangs on forever or until timeout

### Code snippets

```Python
openai.api_key = "OPENAI_API_KEY"
openai.proxy = {"http": "<PROXY>", "https": "<PROXY>"}

message = "I will kill you"
moderation_resp = openai.Moderation.create(input=message) # Times out
```

### OS

Linux

### Python version

Python v3.9

### Library version

v0.27.0

**Comment by YangYangGirl** [comment]
I also meet the problem

**Comment by tu95** [comment]
my code is running good on python 3.8.10.
"As shown in the code below"
my proxy software is v2ray-core.
```
openai.api_key = "sk-xxxxxxxx"
openai.proxy = {
    "http":"http://127.0.0.1:7890",
    "https":"http://127.0.0.1:7890"
}
```

**Comment by Mrin7** [comment]
This resolution did not work on anaconda jupyter notebook. Any alternatives?

**Comment by SixGoodX** [comment]
> my code is running good on python 3.8.10. "As shown in the code below" my proxy software is v2ray-core.
> 
> ```
> openai.api_key = "sk-xxxxxxxx"
> openai.proxy = {
>     "http":"http://127.0.0.1:7890",
>     "https":"http://127.0.0.1:7890"
> }
> ```

我用的和你一样的代理软件，但是找不到对应的proxy , 是10808还是10809？ 我用的wsl
<img width="322" alt="3e6b447afa3cb4dd7b140fc9717de31" src="https://github.com/openai/openai-python/assets/81814968/231b65f1-6a04-4b55-a81e-478b92496a9f">

**Comment by rattrayalex** [comment]
This should be resolved in v1 of this library. If that's not the case, please open a new issue.
