### ISSUE TITLE
Why do we get a `openai.error.InvalidRequestError` if we pass `None` to `logit_bias` even if it defaults to `null`?

### ISSUE THREAD

**Issue by nbro10** [openai/openai-python#288]
### Describe the bug

According to [the docs](https://platform.openai.com/docs/api-reference/completions/create#completions/create-logit_bias), `logit_bias` defaults to `null`, but if we pass `None` to this parameter we get `openai.error.InvalidRequestError`

> openai.error.InvalidRequestError: None is not of type 'object' - 'logit_bias'

So, I suppose this is a bug in this package, as `None` should correspond to what the docs refer to as `null`, or the documentation is wrong.

### To Reproduce

Use the script below

### Code snippets

```Python
import openai

completions = openai.Completion.create(model="text-davinci-003",
                                       prompt="hello",
                                       logit_bias=None)
print(completions)
```

### OS

macos monterey (12.5.1)

### Python version

Python 3.8.13

### Library version

0.27.0

**Comment by ReactiveClown** [comment]
I have experienced the same problem. In the documentation is is stated, that the default value should be null.
![image](https://user-images.githubusercontent.com/124299308/224328820-e4d2765a-dcf3-4b1c-9cc9-46c8696a7cd0.png)
However, when providing it explicitly, I'm getting the same error in the Postman as OP.
![image](https://user-images.githubusercontent.com/124299308/224328966-3356bb61-c6b4-49de-9f27-eb85e45506a8.png)

**Comment by ReactiveClown** [comment]
As far as I have investigated the API. It looks like providing the empty map has fixed the problem.
![image](https://user-images.githubusercontent.com/124299308/224329903-f969ff20-68b7-43ea-a6c7-7bbed56fe6f3.png)
So I believe, that there are two solutions here. First one would be changing the documentation and providing the "Defaults to empty map". Second one would be changing the API so it can accept the `null` value as `logit_bias` parameter.

Looking forward for any updates on this case and decided solution from the developers.

**Comment by logankilpatrick** [comment]
I will have the team take a look at this later this week.

**Comment by rattrayalex** [comment]
Closing because this is an API issue rather than an SDK issue.
