### ISSUE TITLE
Support Whisper from CLI

### ISSUE THREAD

**Issue by szepeviktor** [openai/openai-python#292]
### Describe the feature or improvement you're requesting

It would be nice to upload audio files with the CLI tool and get the API response.
Thank you for considering.

**Comment by mpokrass** [comment]
hi there! the CLI already supports the Whisper API endpoints. Here's an example of how to use it:

```bash
openai api audio.transcribe  -f=/path/to/your/file.mp3
```

**Comment by szepeviktor** [comment]
Thank you Michelle!
