### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by wljackhero** [openai/openai-python#299]
### Describe the bug

python code:

`import openai
openai.api_key = "sk-m0DqPqTSAWoZ2XXXXXXXXXBZ4C"  # api_key hidden

completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world!"}])
print(completion.choices[0].message.content)`

openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

personal accout, google about this problem. Seems like i need to bind a credit card first before i can use ths API?

### To Reproduce

pip install openai
run the code above

### Code snippets

```Python
import openai
openai.api_key = "sk-m0DqPqTSAWoZ2XXXXXXXXXBZ4C"  # api_key hidden

completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world!"}])
print(completion.choices[0].message.content)
```

### OS

Windows 10 Home Version 22H2

### Python version

Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32

### Library version

openai.version.VERSION '0.27.1'

**Comment by logankilpatrick** [comment]
Please check your account, you likely do not have any free credits and thus would need to add a credit card. If you have free credits and still get this issues, please let me know.

**Comment by ganesh-355** [comment]
I have not used my free credits yet and I am getting my quota has been exceeded

**Comment by KalilBalech** [comment]
> Please check your account, you likely do not have any free credits and thus would need to add a credit card. If you have free credits and still get this issues, please let me know.

I got this issue. I have never made any request, but i have received the message "You exceeded your current quota, please check your plan and billing details". This doesnt make any sense, since I have just created my openai account

**Comment by andrzejskowron** [comment]
I've got the same problem. This bug should not be closed.

**Comment by rattrayalex** [comment]
This is not a Python library issue – for API issues, please discuss at community.openai.com or ask for account-specific help at https://help.openai.com/

**Comment by NCPlays11** [comment]
I'm having the same issue but my dashboard shows that I haven't used anything.
