### ISSUE TITLE
HTTP 500 Internal Server Error & HTTP 429 Too Many Requests

### ISSUE THREAD

**Issue by haoning7788** [openai/openai-python#307]
### Describe the bug

Today is March 14, 2023, I read logs and find some "HTTP 500 Internal Server Error" errors, here are two request id: 

65f570730b40007dde214d6c94758fce
e5ad2d7adee633e0c72ba78c54f63e44

Please help analysis what happened.

At the same time, I meet the error "HTTP 429 Too Many Requests", honestly say my request is not up the limitation according to Api  document, but who knows what happened.

Thank you.

### To Reproduce

I submit request id above

### OS

Ubuntu

### Python version

Python 3.7.1

### Library version

latest

**Comment by kristapratico** [comment]
@haoning7788 two questions:

1) can you clarify if you're using the Azure or OpenAI endpoints?
2) Which library version are you using?
