### ISSUE TITLE
Async openai.Embedding.acreate forcibly prints INFO, whereas openai.Embedding.create prints DEBUG

### ISSUE THREAD

**Issue by kenn** [openai/openai-python#312]
### Describe the bug

When `openai.Embedding.acreate` gets called many times, it prints a lot to STDERR, like so:

```
INFO:openai:message='OpenAI API response' path=https://api.openai.com/v1/engines/text-embedding-ada-002/embeddings processing_ms=350 request_id=681e326f4d3241ef9427e95c9eede485 response_code=200
INFO:openai:message='OpenAI API response' path=https://api.openai.com/v1/engines/text-embedding-ada-002/embeddings processing_ms=350 request_id=681e326f4d3241ef9427e95c9eede485 response_code=200
...
```

and there's no way to stop it to clutter the console. That is because `util.log_info` is used in `APIRequestor.arequest_raw` whereas `util.log_debug` is used in `APIRequestor.request_raw`, and it actually `print`s directly to STDERR.

https://github.com/openai/openai-python/blob/main/openai/util.py#L63-L67
```py
def log_info(message, **params):
    msg = logfmt(dict(message=message, **params))
    if _console_log_level() in ["debug", "info"]:
        print(msg, file=sys.stderr)
    logger.info(msg)
```

It may be intentional, and avoidable as follows, but it also suppress other logging. The different behaviors between sync/async seems like it's a bug.

```py
logger = logging.getLogger("openai")
logger.setLevel(logging.WARN)
... API calls ...
logger.setLevel(logging.INFO)
```

### To Reproduce

1. Call `openai.Embedding.acreate`
2. Watch the console output for STDERR

### OS

macOS

### Python version

Python v3.10.10

### Library version

openai-python v0.26.2

**Comment by RobertCraigie** [comment]
This is fixed in our [v1 beta](https://github.com/openai/openai-python/discussions/631)! The only logs we print are directly using the `logging` module so you can control what levels are displayed.

https://github.com/openai/openai-python/tree/v1?tab=readme-ov-file#logging
