### ISSUE TITLE
Transcription function cannot handle response format specifications of "text" or "vtt"

### ISSUE THREAD

**Issue by matthew-at-qamcom** [openai/openai-python#314]
### Describe the bug

Transcription function cannot handle response format specifications of "text" or "vtt".  When those are specified, an exception is raised.

### To Reproduce

1. Using Python, obtain a transcript for an audio file: `transcript = openai.Audio.transcribe("whisper-1", audio_file, response_format=response_format)`.
2. Note that `response_format="json"` and `response_format="verbose_json"` work without issue.
3. Replace response format with `response_format="vtt"` or `response_format="text"`
4. Note that the code now raises an exception `json.decoder.JSONDecodeError`

### OS

Linux

### Python version

Python 3.10.6

### Library version

openai 0.27.0

**Comment by mpokrass** [comment]
hi there - this was fixed in [0.27.1](https://github.com/openai/openai-python/releases/tag/v0.27.1)!

**Comment by matthew-at-qamcom** [comment]
Thanks.  Sorry, I should have checked I was running the latest version.
