### ISSUE TITLE
Must provide an 'engine' when using ChatCompletion api

### ISSUE THREAD

**Issue by vincilee2** [openai/openai-python#318]
### Describe the bug

I followed the instructions from https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb
but got an error:
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

### To Reproduce

using a Azure openai endpoint
execute the following code snippets with your own api_key
```
import openai
openai.api_type = "azure"
# Example OpenAI Python library request
MODEL = "gpt-3.5-turbo"
response = openai.ChatCompletion.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Knock knock."},
        {"role": "assistant", "content": "Who's there?"},
        {"role": "user", "content": "Orange."},
    ],
    temperature=0,
)

response
```

### Code snippets

```Python
import openai
openai.api_type = "azure"
# Example OpenAI Python library request
MODEL = "gpt-3.5-turbo"
response = openai.ChatCompletion.create(
    model=MODEL,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Knock knock."},
        {"role": "assistant", "content": "Who's there?"},
        {"role": "user", "content": "Orange."},
    ],
    temperature=0,
)

response
```

### OS

macOS

### Python version

Python 3.9.13

### Library version

openai-python-0.27.2

**Comment by onemonstera** [comment]
According to the documentation, Azure endpoints does not work with chatpcompletion yet.  It is only working for completion, embedding, and fine-tuning operations for now.

https://github.com/openai/openai-python
"Please note that for the moment, the Microsoft Azure endpoints can only be used for completion, embedding, and fine-tuning operations. "

**Comment by buswedg** [comment]
I believe you need access to the Azure Chat Completions API preview. More [here](https://techcommunity.microsoft.com/t5/ai-cognitive-services-blog/working-with-gpt-4-and-chatgpt-models-on-azure-preview/ba-p/3773595).

**Comment by iaalm** [comment]
This should be an easy fix. Opened PR #359

**Comment by iaalm** [comment]
I hit same issue and eventually I found that I need to first deploy a model on Azure portal. Then use parameter "engine" rather than "model" and pass the deployed engine name. It works for me.😄

**Comment by joeyDIGs** [comment]
What worked for me was replacing 

```python
llm = AzureOpenAI(
    deployment_name="td2",
    model_name="text-davinci-002", 
)
```

For 
```python
llm = AzureOpenAI(
    engine="td2",
    model_name="text-davinci-002", 
)
```
