### ISSUE TITLE
InvalidRequestError: 'answers' is not one of ['fine-tune'] - 'purpose'

### ISSUE THREAD

**Issue by akashuh** [openai/openai-python#327]
### Describe the bug

Following the steps used to create an answers service at: https://platform.openai.com/docs/guides/answers

While trying the following command: 
openai.File.create(file=open("data.json"), purpose='answers')

Getting the following error: 
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
Cell In[32], line 1
----> 1 openai.File.create(file=open("data.json"), purpose='answers')

File [c:\Users\akash.sharma\Miniconda3\envs\gptenv\lib\site-packages\openai\api_resources\file.py:84](file:///C:/Users/akash.sharma/Miniconda3/envs/gptenv/lib/site-packages/openai/api_resources/file.py:84), in File.create(cls, file, purpose, model, api_key, api_base, api_type, api_version, organization, user_provided_filename)
     60 @classmethod
     61 def create(
     62     cls,
   (...)
     71     user_provided_filename=None,
     72 ):
     73     requestor, url, files = cls.__prepare_file_create(
     74         file,
     75         purpose,
   (...)
     82         user_provided_filename,
     83     )
---> 84     response, _, api_key = requestor.request("post", url, files=files)
     85     return util.convert_to_openai_object(
     86         response, api_key, api_version, organization
     87     )

File [c:\Users\akash.sharma\Miniconda3\envs\gptenv\lib\site-packages\openai\api_requestor.py:226](file:///C:/Users/akash.sharma/Miniconda3/envs/gptenv/lib/site-packages/openai/api_requestor.py:226), in APIRequestor.request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    205 def request(
...
    683         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    684     )
    685 return resp

InvalidRequestError: 'answers' is not one of ['fine-tune'] - 'purpose'

### To Reproduce

Just following steps on the OpeAI Answers Service Page. 

Error:

---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
Cell In[32], line 1
----> 1 openai.File.create(file=open("data.json"), purpose='answers')

File [c:\Users\akash.sharma\Miniconda3\envs\gptenv\lib\site-packages\openai\api_resources\file.py:84](file:///C:/Users/akash.sharma/Miniconda3/envs/gptenv/lib/site-packages/openai/api_resources/file.py:84), in File.create(cls, file, purpose, model, api_key, api_base, api_type, api_version, organization, user_provided_filename)
     60 @classmethod
     61 def create(
     62     cls,
   (...)
     71     user_provided_filename=None,
     72 ):
     73     requestor, url, files = cls.__prepare_file_create(
     74         file,
     75         purpose,
   (...)
     82         user_provided_filename,
     83     )
---> 84     response, _, api_key = requestor.request("post", url, files=files)
     85     return util.convert_to_openai_object(
     86         response, api_key, api_version, organization
     87     )

File [c:\Users\akash.sharma\Miniconda3\envs\gptenv\lib\site-packages\openai\api_requestor.py:226](file:///C:/Users/akash.sharma/Miniconda3/envs/gptenv/lib/site-packages/openai/api_requestor.py:226), in APIRequestor.request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    205 def request(
...
    683         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    684     )
    685 return resp

InvalidRequestError: 'answers' is not one of ['fine-tune'] - 'purpose'

### Code snippets

```Python
openai.File.create(file=open("data.json"), purpose='answers')
```

### OS

Windows 10

### Python version

Python v 3.9.16

### Library version

v0.26.4

**Comment by hallacy** [comment]
Hi @akashuh,

The /answers endpoint has been removed and the ability to upload new files with this purpose has been removed as well. Please check our transition guide: https://github.com/openai/openai-cookbook/tree/main/transition_guides_for_deprecated_API_endpoints for ideas on how to replicate the functionality.
