### ISSUE TITLE
Error regarding knowledge cutoff

### ISSUE THREAD

**Issue by 2010person** [openai/openai-python#341]
### Describe the bug

In the system message to GPT-3.5-turbo, I have set the knowledge cutoff to the 27/3/22 (so it knows all the events that have happened today). But, when I ask it who the current PM is, it says Boris Johnson instead of Rishi Sunak. I have put images in the code snippets below. Am I doing anything wrong?

### To Reproduce

1. Use GPT-3.5-turbo
2. Set the knowledge cutoff date to 27/3/23
3. Ask it who the British PM is.

### Code snippets

```Python
Code (user is a variable):
messages=[
        {"role": "system", "content": "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible. Knowledge cutoff: {27/3/23} Current date: {26/3/23}"},
        {"role": "user", "content": user},
        {"role": "assistant", "content": "Hi user, your question delights me the answer is:"},
    ]
Output: 
As of my knowledge cutoff date of March 27, 2023, Boris Johnson is still serving as Prime Minister of the United Kingdom, so there hasn't been a Prime Minister after him yet.
```

### OS

Windows 11

### Python version

Python v3.10.4

### Library version

openai-python v0.27.2

**Comment by hallacy** [comment]
Changing the knowledge cutoff date doesn't modify the model weights.  The data it was trained on is still from awhile ago and so it doesn't have knowledge of more recent events. Hope this helps.

This repo is only for openai-python sdk issues. For more help on model behavior, please reach out to our support team on help.openai.com

**Comment by 2010person** [comment]
Ok thanks that cleared it up for me!
