### ISSUE TITLE
one shot whisper to chat completion

### ISSUE THREAD

**Issue by go-dockly** [openai/openai-python#346]
### Describe the feature or improvement you're requesting

Probably not the right place, but it would improve the api tremendously if instead of a text prompt of a chat completion request to add a feature where an audio file can be transcribed and interpreted at once.

### Additional context

Right now it is necessary to do two calls.
first: to whisper
second: to gpt completion with the response of whisper.

**Comment by danielfaust** [comment]
I disagree. While I'm doing the same, I think the separation is beneficial. For one you can test Whisper without it then invoking ChatGPT, and you can test ChatGPT without having to re-submit the audio for transcription. The effort and network-traffic increase to do this in two steps is minimal.

**Comment by Tweaker177** [comment]
It would be a nice feature to have, to simplify things for those using Whisper who want a simplified workflow.   However I definitely would not want to do away with the option to keep them separate, as many users incorporate other Speech models and frameworks, like Apple's Speech Framework, or Google's API's for Text To Speech and Speech To Text.  

Also, Even if it's fed directly to  GPT from Whisper, I still want the direct output of Whisper before going to GPT for error handling, general evals of the model, or prompts used, and for more creative uses (feeding the output of one model to the input of another, then taking that output and sending it back, networking neural engines in effect..

**Comment by hallacy** [comment]
At this time there's no plan to merge these two features together into one call.  I'll bring up the idea to the team cc @jeffsharris
