### ISSUE TITLE
Does the `text-davinci-003` model support 4000, 4096 or 4097 tokens?

### ISSUE THREAD

**Issue by nbro10** [openai/openai-python#347]
### Describe the feature or improvement you're requesting

I'm just trying to make sure that the documentation is really correct, because, often, the documentation doesn't seem to contain all info necessary to understand something. 

[The docs](
https://platform.openai.com/docs/models/gpt-3-5) say that the context length for `text-davinci-003` is <s>4000</s> (now they say 4097). There would be no reason to believe that this is not correct, if most models didn't have a context length of 2048 and 4096 = 2048*2

So, can **an official OpenAI employee/developer** confirm that the context length for `text-davinci-003` is really <s>4000</s> (4097) and not 4096?

Can you please also tell me the actual context length of models like 

- text-curie-001
- text-babbage-001
- text-ada-001

The docs now say 2049, but previously they used to say 2048. 

### Additional context

I already asked this question here https://community.openai.com/t/does-the-text-davinci-003-model-support-4000-or-4096-tokens/89507, but I got an answer from a bot (apparently) or a user that posts useless answers, which I don't know if I can trust. I have also tried to ask for help in the help center, but the chat doesn't even open. See [this](https://community.openai.com/t/is-it-really-not-possible-to-change-the-email-name-and-phone-number-associated-with-an-account/72165). That's why I am asking here, with the hope that I get an **official answer from an official OpenAI qualified employee**.

**Comment by logankilpatrick** [comment]
I will answer over on the community site.
