### ISSUE TITLE
The actual result and expected results are not matching after fine tuning.

### ISSUE THREAD

**Issue by FSDSAbhi** [openai/openai-python#354]
### Describe the bug

After fine tuning the model with custom data, there is a difference in the actual result and expected result.

### To Reproduce

Example:
{"prompt":"Who is the highest scorer in the NBA?","completion":" The highest scorer in the NBA is currently Stephen Curry, with an average of 30.1 points per game."}

Prompt: Who is the highest scorer in the NBA?
Actual Result: The highest scorer in the NBA is currently Stephen Curry, with an average of 30.1 points per game. 
This player has an average field goal percentage of 58.5%. This player has an average 3-point field goal percentage of 56.3%. This player has an average free throw percentage of 64.9%. This player has an average field goal percentage of 54.7%. This player has an average 3-point field goal percentage of 54.7%. This player has an average free throw percentage of 51.1%. This player has an average field goal percentage of 49.8%. This player has an average 3-point field goal percentage of 55.2%. This player has an average free throw percentage of 55.2%. This player has an average 3-point field goal percentage of 56.3%. This player has an average free throw percentage of 54.7%. This player has an average 3-point field goal percentage of 54.7%. This player has an average free throw percentage of 51.1%. This player has an average field goal percentage of 51.1%. This player has an average 3-point field goal percentage of 56.3%. This player has an average free throw percentage of 54.7%. This player

Expected Result:  The highest scorer in the NBA is currently Stephen Curry, with an average of 30.1 points per game.

### Code snippets

```Python

    # Generate a response from the fine-tuned model
    response = openai.Completion.create(
        engine=model_id,
        prompt=prompt,
        max_tokens=1024,
        n=1,
        stop=None,
        temperature=0.7
    width=80, height=20)
```

### OS

macOS

### Python version

3.8

### Library version

openai 0.27.2

**Comment by hallacy** [comment]
The fine tuning process does not guarantee that a given input will output a specific output.  It only helps steer the model towards the outputs you've provided.  Feel free to play around with some of the fine tuning settings to see if it helps.  You could also try turning down the temperature to 0 to see if that gets you closer to what you're expecting.
