### ISSUE TITLE
Whisper Timestamp support.

### ISSUE THREAD

**Issue by ayanmond** [openai/openai-python#366]
### Describe the feature or improvement you're requesting

- output returned by Whisper should contain sentence-level ad word-level timestamps.

**Comment by pjmpjmpjm** [comment]
Word-level timestamps are MUCH NEEDED but apparently not yet available.

In getting any kid of timestamps, the prompts are seemingly of no value.  Particularly, adding "--form response_format=XXX" to your prompt seems to have no effect.  

However, the response_format optional argument does work and yields SRT, VTT, and Verbose_JSON responses.

This example yields a VTT response:

import openai
audio_file= open("example.mp3", "rb")
response_format="vtt"
transcript = openai.Audio.transcribe("whisper-1", audio_file, response_format=response_format)

The optional file formats give you some timestamps.

See more info under "Create Transcription" here: https://platform.openai.com/docs/api-reference/audio/create?lang=python

**Comment by kaustavb79** [comment]
For sentence level timestamp , provide the response format as **verbose_json**

Sample Code:

`openai.Audio.transcribe("whisper-1", audio_file,response_format="verbose_json")`

**Comment by thiswillbeyourgithub** [comment]
Btw an alternative to get word timestamp is to use [whispercpp](https://github.com/ggerganov/whisper.cpp/) : 

example command : ./main -m models/ggml-small-q4_1.bin --threads 4 --processors 1 --max-len=1 --print-progress --language "en" -f your_file.wav --prompt "your prompt"

My use case is not to have super high accuracy over the whole text but instead to just detect when I use the word "stop" to later split a long audio into sub files. Hence whispercpp is enough. So of course using the small model is fine in my case.

**Comment by rattrayalex** [comment]
As mentioned above, sentence-level timestamps are available with `verbose_json` and word-level timestamps are available in whispercpp but not yet the API. 

API feature requests belong at community.openai.com – I'm sure you can find and upvote this one there.
