### ISSUE TITLE
Use python to report an error

### ISSUE THREAD

**Issue by shanpengtao** [openai/openai-python#375]
### Describe the bug

<img width="969" alt="image" src="https://user-images.githubusercontent.com/7127463/229757093-055ea104-3d67-4a94-b29e-b00646ecfb06.png">

### To Reproduce

<img width="836" alt="image" src="https://user-images.githubusercontent.com/7127463/229756890-0b2f7327-bae7-48c0-b60d-2cadda5786d0.png">

### OS

macOS 12.6

### Python version

Python2.7

### Library version

openai-0.6.4-py2.7.egg-info

**Comment by hallacy** [comment]
Hi @shanpengtao. I'm not entirely sure what issue you're trying to report. If I had to guess, it's that the openai package isn't working on your system because we only support python 3.7+ and not python 2.x.  You'll need to upgrade your python version to use this package
