### ISSUE TITLE
Missing rate limit details for chatGPT turbo API

### ISSUE THREAD

**Issue by junwang-wish** [openai/openai-python#379]
### Describe the bug

There is no details on the TPM unit for chatgpt turbo api since the website only provided https://platform.openai.com/docs/guides/rate-limits/overview

TYPE 1 TPM EQUALS
davinci 1 token per minute
curie 25 tokens per minute
babbage 100 tokens per minute
ada 200 tokens per minute

### To Reproduce

1. Read https://platform.openai.com/docs/guides/rate-limits/overview 
2. Realize TPM is not really tokens per minute, but depends on model type
3. Realize there is no details on ChatGPT API's "1 TPM equals ..."
4. Wonder why not show number of raw tokens per minute, and instead create "TPM" as a misleading abstraction?

### OS

Any

### Python version

Any

### Library version

Any

**Comment by ra312** [comment]
Hi @junwang-wish, shall we display TPM info differently for each model? Can you please point to specific package or maybe share Open AI API key so that it is possible to reproduce and locate the bug in the code ?

**Comment by hallacy** [comment]
Hello PLEASE DO NOT SHARE OPEANI API KEYS. OpenAI will be able to debug issues without them

**Comment by hallacy** [comment]
@logankilpatrick can you look at this as part of our API documentation?

**Comment by Fen1Snow** [comment]
目前发现api速率问题会直接导致aoi-ket报错sk错误   目前修改速率之后解决报错   期待后进一步观察

**Comment by Fen1Snow** [comment]
目前发现api速率问题会直接导致OPENAI API 密钥报错sk错误目前修改速率之后解决，报错修复后等待进一步观察

**Comment by logankilpatrick** [comment]
This should be fixed now and we also released a new rate limit section of your OpenAI account page which has the details for your specific account.
