### ISSUE TITLE
import openai seems to take a long time

### ISSUE THREAD

**Issue by hallacy** [openai/openai-python#380]
### Describe the feature or improvement you're requesting

Doing a fresh `import openai` seems to take about 4-5 seconds

(reproducible with `start_time = time.time(); import openai; print(time.time() - start_time)`).  This startup time seems like given the straightforward nature of the repo.

**Comment by hauntsaninja** [comment]
Do this https://github.com/hauntsaninja/boostedblob/blob/236cb2dbefdde8e31e7249b2fd4776b2e7afd207/boostedblob/__init__.py#L5

**Comment by hauntsaninja** [comment]
The other expensive thing is the `import pandas`

**Comment by hauntsaninja** [comment]
Things I use are:
- `python -X importtime -c 'import openai'`
- `pyinstrument --show-regex='.*' test.py` where `test.py` contains `import openai`

**Comment by hallacy** [comment]
Is this kinda what you were thinking? https://github.com/openai/openai-python/pull/386 It feels a little clunky splitting up the datalib file like this but for a small number of imports, seemed ok for now
