### ISSUE TITLE
fine_tunes.prepare_data  ERROR in read_any_format validator: Your file `train.txt` does not appear to be in valid TXT format

### ISSUE THREAD

**Issue by LunarAurora666** [openai/openai-python#383]
### Describe the bug

hi, 
everyone
When i use fine_tunes to import my train date, there is an error about it. 
Please give me some support about it. thanks. 

### To Reproduce

step1 ： pip3 install --upgrade openai
step2：set OPENAI_API_KEY="sk-XXXXXXXXX"
step3:  openai tools fine_tunes.prepare_data -f train.txt

### Code snippets

```Python
(base) PS D:\Personal> openai tools fine_tunes.prepare_data -f train.txt
Analyzing...


ERROR in read_any_format validator: Your file `train.txt` does not appear to be in valid TXT format. Please ensure your file is formatted as a valid TXT file.

Aborting...
(base) PS D:\Personal>
```

### OS

windows

### Python version

Python 3.9.13

### Library version

openai-0.27.4

**Comment by hallacy** [comment]
Hi @LunarAurora666,

Can you provide a snippet of your .txt file? I won't be able to figure out if there's an issue in this repo without it

**Comment by LunarAurora666** [comment]
> Hi @LunarAurora666,
> 
> Can you provide a snippet of your .txt file? I won't be able to figure out if there's an issue in this repo without it

ok. Here is an example of my file. please check， thanks.

{"prompt":"龙叔叔","completion":"智勇双全独爱马卡龙"}
{"prompt":"付女士","completion":"一夜暴富"}

**Comment by hallacy** [comment]
If I had to guess, one a number of things could be done to fix your issue:
