### ISSUE TITLE
Embeddings "/v1/embeddings"endpoint support.

### ISSUE THREAD

**Issue by sjnho** [openai/openai-python#397]
### Describe the feature or improvement you're requesting

Embeddings use api url as "/engines/text-embedding-ada-002/embeddings", can we support the "/v1/embeddings" with **model** in Request body? 
I 'm new to openai api and only found new entrypoint described in https://platform.openai.com/docs/api-reference/embeddings/create

**Comment by lewiswilliam** [comment]
Hi @sjnho 

Yes you can create embeddings by passing the model in request body in the following way:
`curl https://api.openai.com/v1/embeddings \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "input": "The food was delicious and the waiter...",
    "model": "text-embedding-ada-002"
  }'`

You can get more information on models for embedding here:
https://platform.openai.com/docs/guides/embeddings/what-are-embeddings

`text-embedding-ada-002` is the suggested one though. Let know if you have any further queries.

**Comment by sjnho** [comment]
@lewiswilliam Thanks for reply. Sorry, I may not have explained it very clearly.  I mean when I use 
``` py
import openai
# choose text to embed
text_string = "sample text"

# choose an embedding
model_id = "text-similarity-davinci-001"
embedding = openai.Embedding.create(input=text_string, model=model_id)
```
This library will request  to https://api.openai.com/engine/text-similarity-davinci-001/embeddings
Could it request to https://api.openai.com/v1/embeddings ?

**Comment by lewiswilliam** [comment]
@sjnho thats a first generation model which is no more recommended, please check here https://platform.openai.com/docs/guides/embeddings/what-are-embeddings

Why dont you try `text-embedding-ada-002`, its cheaper and probably more better.

**Comment by sjnho** [comment]
> @sjnho thats a first generation model which is no more recommended, please check here https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
> 
> Why dont you try `text-embedding-ada-002`, its cheaper and probably more better, also recommended 😀

It's just  sample code from readme. But when I changed to text-embedding-ada-002 , this libray still request to `/engines/text-embedding-ada-002/embeddings` , not request to `/v1/embeddings`, this is why I open this issue.

**Comment by lewiswilliam** [comment]
@sjnho my guess is this: since we are using the python sdk, they have managed the routing in the sdk itself. If you go via `/v1/embeddings` then 1st step in that process will be to route it to the correct model which in this case will be `/engines/text-embedding-ada-002/embeddings`

**Comment by japanvik** [comment]
Hi @lewiswilliam 

Could you point me to a reference? I don't see it anywhere in the openai documentation, which indicates that the end point should be formatted as /engines/text-embedding-ada-002/embeddings. The [official doc]( https://platform.openai.com/docs/api-reference/embeddings/create) indicates that the endpoint is https://api.openai.com/v1/embeddings and the model is passed in as a request parameter upon POST.

Also, what is the python sdk you are referring to here?

Thanks
V

**Comment by lewiswilliam** [comment]
Hi @japanvik 

You are correct, the end point to be used is https://api.openai.com/v1/embeddings

As per the above discussion, the openai python sdk internally goes to /engines/text-embedding-ada-002/embeddings

The python sdk is the official openai python sdk which can be found here - https://github.com/openai/openai-python

**Comment by notedit** [comment]
When will the new URL be updated?

**Comment by japanvik** [comment]
Hi @lewiswilliam 

According to the official Open AI documentation, the [engines endpoint is deprecated](https://platform.openai.com/docs/api-reference/engines).
I believe it still works for backward compatibility reasons, but it should be calling /v1/embeddings with a json payload indicating the model to be used.

@hallacy any thoughts?

**Comment by MalteHB** [comment]
Hi all
I would also really appreciate an update on this. 
@hallacy are you going to update the SDK to support the newest API documentation?

**Comment by RobertCraigie** [comment]
The SDK was updated to support embeddings & the v1 SDK also includes support for embeddings!
