### ISSUE TITLE
Python 3.10 not support???

### ISSUE THREAD

**Issue by bensonchow123** [openai/openai-python#40]
When I try to use python 3.10 to run the openai library, it returns 

PS C:\Users\USER\Desktop\Gpt-3> pip install openai
Collecting openai
  Using cached openai-0.10.5.tar.gz (157 kB)
Collecting requests>=2.20
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting tqdm
  Using cached tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting pandas>=1.2.3
  Using cached pandas-1.3.3.tar.gz (4.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\USER\Desktop\Gpt-3\venv\Scripts\python.exe' 'C:\Users\USER\AppData\Local\Temp\pip-standalone-pip-ip8y9guu\__env_pip__.zip\pip' install --ignore-i
nstalled --no-user --prefix 'C:\Users\USER\AppData\Local\Temp\pip-build-env-djvlomh4\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i http
s://pypi.org/simple -- 'setuptools>=51.0.0' wheel 'Cython>=0.29.21,<3' 'numpy==1.17.3; python_version=='"'"'3.7'"'"' and (platform_machine!='"'"'arm64'"'"' or platform
_system!='"'"'Darwin'"'"') and platform_machine!='"'"'aarch64'"'"'' 'numpy==1.18.3; python_version=='"'"'3.8'"'"' and (platform_machine!='"'"'arm64'"'"' or platform_sy
stem!='"'"'Darwin'"'"') and platform_machine!='"'"'aarch64'"'"'' 'numpy==1.19.3; python_version>='"'"'3.9'"'"' and (platform_machine!='"'"'arm64'"'"' or platform_syste
m!='"'"'Darwin'"'"') and platform_machine!='"'"'aarch64'"'"'' 'numpy==1.19.2; python_version=='"'"'3.7'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy==1.19.2; py
thon_version=='"'"'3.8'"'"' and platform_machine=='"'"'aarch64'"'"'' 'numpy>=1.20.0; python_version=='"'"'3.8'"'"' and platform_machine=='"'"'arm64'"'"' and platform_s
ystem=='"'"'Darwin'"'"'' 'numpy>=1.20.0; python_version=='"'"'3.9'"'"' and platform_machine=='"'"'arm64'"'"' and platform_system=='"'"'Darwin'"'"''

**Comment by willstott101** [comment]
`numpy` has got `3.10` pre-builds on PyPI now - wanna try again?

**Comment by hallacy** [comment]
I'm gonna close this issue for now but feel free to reopen if this is still an issue
