### ISSUE TITLE
openai cli `--stream` error

### ISSUE THREAD

**Issue by oiuv** [openai/openai-python#402]
### Describe the bug

![image](https://user-images.githubusercontent.com/13300261/232494925-353ab498-3b3a-4406-b780-955dc6afa1e7.png)

When adding the `--stream` parameter to the OpenAI command, an error occurred.

### To Reproduce

When adding the `--stream` parameter to the OpenAI command, an error occurred.

```
> openai api chat_completions.create -m gpt-3.5-turbo -g user "Hello" --stream
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\openai.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\_openai_scripts.py", line 70, in main
    args.func(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\cli.py", line 144, in create
    sys.stdout.write(c["message"]["content"])
KeyError: 'message'
```

### OS

Windows

### Python version

Python v3.10.6

### Library version

openai v0.27.4

**Comment by the-Luthier** [comment]
It looks like you get this error because OpenAI-Python library does not support streaming. You can use OpenAI-Python package to handle this issue.   https://pypi.org/project/openai/

I would like to know if this works. Have a nice day!

**Comment by oomti** [comment]
The completions request for the "ada" with stream=True works correctly.

![image](https://user-images.githubusercontent.com/23347037/233226732-9b86e9dd-ce5e-4bef-b325-b0a69692dc82.png)

The ChatCompletions request with "gpt-4" with stream=True returns the response iterator correctly. 

![image](https://user-images.githubusercontent.com/23347037/233227209-55a6af2c-0645-4cc2-84a4-fd940c0443d1.png)

One of the confusing issue is that completions requires a message=[string] input, while a ChatCompletions requires a message=list[dict] input in the format of {"role":"user|system|assistant", "content":"[user message]"}

It can also be confusing that depending on a stream output or a bulk result the type of the result is different.

**Comment by oomti** [comment]
The problem with the CLI that it expects a ["message"]["content"] in the response from the returned function value after making the call:
![image](https://user-images.githubusercontent.com/23347037/233228865-db575772-6991-49ee-b665-af0a76c60208.png)

Here is a sample response if you receive a single response:

![image](https://user-images.githubusercontent.com/23347037/233229209-62bce2e5-a797-4b39-aa86-4322310dc274.png)

**Comment by RobertCraigie** [comment]
This is fixed in the v1 SDK!

```sh
$ openai api chat.completions.create -g user 'say hi!' -m 'gpt-4' --stream
```
