### ISSUE TITLE
Using Azure and OpenAI at the same time

### ISSUE THREAD

**Issue by rmilkowski** [openai/openai-python#411]
### Describe the bug

Currently it seems there is no strightforward way to be able to send requests to both OpenAI and Azure from same python program. Ideally this should be possible:

openai = OpenAI(key=key)
azureai = OpenAI(key=key, api_base=xxx, ....)

While currently given key, api_base, etc. are global variables to the module, the above won't work.

### To Reproduce

-

### OS

Linux

### Python version

Python 3

### Library version

latest

**Comment by ellis-jc** [comment]
+1 on this. 

Right now we have different models available on each side and using the two providers in tandem is a huge pain

**Comment by sevenjay** [comment]
+1 on this.
We run both and a load balance in front of them, need this teature, too.

**Comment by rmilkowski** [comment]
> According to [this response](https://github.com/openai/openai-python/issues/324#issuecomment-1484644590), there is a non-documented feature: Many API features accept named arguments such as:
> 
> ```
> import openai
> openai.ChatCompletion.create(model=gpt_model_config.model_engine,
>                              api_key=SECRET
>                              api_base=BASE,
>                              api_type=TYPE,
>                              api_version=VERSION,
>                            ...)
> ```
> 
> Setting the `api_key` and `api_base` per request may address your issue.

I just tried it with openai.Image.create() and it works.
Thank you.

btw: looks like the upcoming 1.0.0 module version will finally support client instantiation. See https://github.com/openai/openai-python/discussions/631
