### ISSUE TITLE
[QUESTION] Sometime it said the model is overload

### ISSUE THREAD

**Issue by duong77476** [openai/openai-python#414]
### Describe the bug

Sometime i use Open AI API, it have this message:
model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID fac8b65ed1c009c456a00410c4f6c376 in your message.)

Does anybody know why?

### To Reproduce

.

### OS

Ubuntu 22.04

### Python version

Python 3.9

### Library version

0.26.4

**Comment by hc20k** [comment]
This isn't a bug, this just means that the model is getting a lot of traffic from other users

**Comment by duong77476** [comment]
> This isn't a bug, this just means that the model is getting a lot of traffic from other users

Yes, i just found down that, i'll close this as completed
