### ISSUE TITLE
Expose X-Ratelimit-* headers on ChatCompletion API requests

### ISSUE THREAD

**Issue by lukepighetti** [openai/openai-python#416]
### Describe the feature or improvement you're requesting

If you make a call to `POST /v1/chat/completions` manually, you get a few very helpful headers that estimate time to rate-limiting

```
x-ratelimit-limit-requests: 3500
x-ratelimit-remaining-requests: 3499
x-ratelimit-reset-requests: 17ms
```

However, if you call `openai.ChatCompletion.create(...)` or `openai.ChatCompletion.acreate(...)`, these helpful rate limit values are not returned by the function.

It would be nice if we could get access to these headers, or have them returned in a helpful format along with the response

**Comment by jzumwalt** [comment]
+1 for this, preventing a rate limit error is better for everyone!

**Comment by shyamal-anadkat** [comment]
what would be the preferred format  here?

**Comment by lukepighetti** [comment]
Just forwarding the response headers in a nice way

**Comment by jzumwalt** [comment]
`requests` supports response [hooks ](https://www.tutorialspoint.com/requests/requests_event_hooks.htm)

Perhaps `openai.api_requestor` could allow the calling app to define a `session_hook` which could then be used in-turn to create a response hook.

**Comment by pors** [comment]
> what would be the preferred format here?

@shyamal-anadkat Maybe get the response headers from requests as is: https://requests.readthedocs.io/en/latest/user/quickstart/#response-headers

The completion response is currently a generator, so maybe you can add a flag `response_headers` to the `create` calls, and if it is set, return a tuple: `(headers, response-generator)`?

**Comment by WebsheetPlugin** [comment]
+1

**Comment by Gabriel-Macias** [comment]
+1, this feature would be really helpful

**Comment by geraudloup** [comment]
Ok I have found a solution (at least for those using `acreate`) :
Bellow is an exemple :
```python
import aiohttp
import asyncio

async def log_response_headers(session, trace_config_ctx, params: aiohttp.TraceRequestEndParams):
    print(f"Received response headers from {params.url}: {params.response.headers}")

trace_config = aiohttp.TraceConfig()
trace_config.on_request_end.append(log_response_headers)

async def generate_chatgpt_response():
     async with aiohttp.ClientSession(trace_configs=[trace_config]) as session:
            openai.aiosession.set(session)
            response = await openai.ChatCompletion.acreate(...)
    return response
asyncio.run(generate_chatgpt_response())
```

So I found the solution like this :
in `__init__.py` (line 67): 
```python
aiosession: ContextVar[Optional["ClientSession"]] = ContextVar(
    "aiohttp-session", default=None
)  # Acts as a global aiohttp ClientSession that reuses connections.
# This is user-supplied; otherwise, a session is remade for each request.
```

And in `api_requestor.py` (line 769):
```python
@asynccontextmanager
async def aiohttp_session() -> AsyncIterator[aiohttp.ClientSession]:
    user_set_session = openai.aiosession.get()
    if user_set_session:
        yield user_set_session
    else:
        async with aiohttp.ClientSession() as session:
            yield session
```

**Comment by anaelmashinsky** [comment]
+1, headers field in response would be very helpful

**Comment by marcoloco23** [comment]
For synchronous invocation this will store headers. 

```
import requests

headers = {}

def capture_and_filter_headers(response, *args, **kwargs):
    nonlocal headers
    headers = response.headers

s = requests.Session()
s.hooks = {'response': capture_and_filter_headers}

openai.requestssession = s
```

**Comment by RobertCraigie** [comment]
This is supported in [v1](https://github.com/openai/openai-python/discussions/631) which was just released!

You can access the rate limit information like so:

```py
from openai import OpenAI

client = OpenAI()

response = client.chat.completions.with_raw_response.create(
    model="gpt-4",
    messages=[
        {
            "role": "user",
            "content": "Say hi!",
        }
    ],
)
print(response.headers.get("x-ratelimit-reset-requests"))

completion = response.parse()
print(completion.model_dump_json(indent=2))
```

**Comment by Jonas1312** [comment]
does it work for AzureOpenAI client too? I tried it and it does not return any ratelimit information

**Comment by rattrayalex** [comment]
That sounds like an Azure OpenAI API issue – I recommend requesting the feature from them.

**Comment by ishaan-jaff** [comment]
@rattrayalex @RobertCraigie is there any tradeoff to switching 
from `chat.completions.create`
to `chat.completions.with_raw_response.create` 

I found mentions of `legacy_response` in the code base, but what's the diff between the two ?

**Comment by RobertCraigie** [comment]
@ishaan-jaff the main difference is that `.with_raw_response` will return a response object that uses async methods in the next major release, see this docstring: https://github.com/openai/openai-python/blob/0c1e58d511bd60c4dd47ea8a8c0820dc2d013d1d/src/openai/_legacy_response.py#L32

**Comment by ishaan-jaff** [comment]
okay and just confirming - there is absolutely no way to access the response headers if I use `chat.completions.with_raw_response.create` ?

**Comment by RobertCraigie** [comment]
do you mean `chat.completions.create()`?

no there isn't a direct way but you could use httpx event hooks https://www.python-httpx.org/advanced/#event-hooks

**Comment by ishaan-jaff** [comment]
okay thanks for the help @RobertCraigie , will look into this

**Comment by PSU3D0** [comment]
@RobertCraigie Are headers accessible via `with_raw_response`?

**Comment by RobertCraigie** [comment]
@PSU3D0 yes it's the exact same setup
