### ISSUE TITLE
Is the order of batched embeddings data indeterministic?

### ISSUE THREAD

**Issue by ravwojdyla** [openai/openai-python#420]
### Describe the bug

Looking over the code related to embeddings, I've noticed:
https://github.com/openai/openai-python/blob/c556584eff3b36c92278e6af62cfe02ebb68fb65/openai/embeddings_utils.py#L48-L49

Which I have not seen in the API documentation (or other examples), tho I may have missed it. Should the user expect that the order of returned batched embeddings from the API may not be deterministic and thus not be in the same order as input data?

### To Reproduce

```py
get_embeddings(["foo bar", "foo baz"])
```

### OS

macOS

### Python version

python 3.10

### Library version

0.27.4

**Comment by ravwojdyla** [comment]
Git blame points me to @lilianweng, would love your input please.

**Comment by ravwojdyla** [comment]
@lilianweng thanks! Will go ahead and PR to delete those lines to avoid future confusion. Unless you believe there's a value in keeping them.

**Comment by lilianweng** [comment]
^ @hallacy wdyt?

**Comment by hallacy** [comment]
Seems fine. Approved and merged
