### ISSUE TITLE
openai.error.InvalidRequestError: Unrecognized request argument supplied: logprobs

### ISSUE THREAD

**Issue by pradeepdev-1995** [openai/openai-python#433]
### Describe the bug

I need the ```logprobs``` value from the API.

The code I tried

``` 
response = openai.ChatCompletion.create(
            model='gpt-3.5-turbo',
            messages=[{"role": "user", "content": "Who won the world series in 2020?"}],
            max_tokens=193,
            temperature=0,
            logprobs=1
        )
```
but it shows the error
```openai.error.InvalidRequestError: Unrecognized request argument supplied: logprobs```

### To Reproduce

I need the ```logprobs``` value from the API.

The code I tried

``` 
response = openai.ChatCompletion.create(
            model='gpt-3.5-turbo',
            messages=[{"role": "user", "content": "Who won the world series in 2020?"}],
            max_tokens=193,
            temperature=0,
            logprobs=1
        )
```
but it shows the error
```openai.error.InvalidRequestError: Unrecognized request argument supplied: logprobs```

### OS

Ubuntu

### Python version

Python3.9

### Library version

openai-0.27.6

**Comment by eaftan** [comment]
I don't think the chat API supports the `logprobs` parameter.  See https://platform.openai.com/docs/api-reference/chat/create

**Comment by pradeepdev-1995** [comment]
@eaftan If so what is the method to see the token probabilities in chatgpt response?

**Comment by rattrayalex** [comment]
This is now available!

**Comment by pradeepdev-1995** [comment]
which version of openai package I should use for this @rattrayalex ?

**Comment by rattrayalex** [comment]
The latest version.
