### ISSUE TITLE
Return `finish_reason` early in streaming multi choice `ChatCompletion`

### ISSUE THREAD

**Issue by ebraraktas** [openai/openai-python#434]
### Describe the feature or improvement you're requesting

Return `finish_reason` early in streaming multi choice(`n` > 1) `ChatCompletion`.

### Additional context

Messages containing `finish_reason` for different `choice`s are sent at the end of streaming request. However, different `choice`s can be completed at different times, and it would be very useful to have `finish_reason` to determine if a `choice` is completed early.

This may not be related to Python library, and possibly must be fixed in the API implementation.

**Comment by Gabriel-Gotti** [comment]
this was a constructed HD screen pathroute someone used my nodes ID at for cross device reason: i have employee pgn files they gain access too

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This does indeed sound like a feature request for the underlying OpenAI API and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?
