### ISSUE TITLE
What is the default value of  max_token argument in ChatCompletion API

### ISSUE THREAD

**Issue by pradeepdev-1995** [openai/openai-python#436]
### Describe the bug

What is the default value of  max_token argument in ChatCompletion API

### To Reproduce

What is the default value of  max_token argument in ChatCompletion API

### OS

Ubuntu

### Python version

Python3.9

### Library version

openai==0.27.0

**Comment by naourass** [comment]
I'm wondering the same, wth is the default value of max_tokens in `openai.ChatCompletion.create()`? The docs say:

> max_tokens
> integer or null
> Optional
> Defaults to 16

But it doesn't seem that `16` is the default value.

**Comment by athyuttamre** [comment]
Per the documentation, it is infinity i.e. the endpoint will sample tokens until the model completes a message.

https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens
