### ISSUE TITLE
Moderation endpoint is missing a timeout/request_timeout parameter

### ISSUE THREAD

**Issue by danieljannai21** [openai/openai-python#444]
### Describe the feature or improvement you're requesting

Just like any other endpoint, a timeout is very much needed for the moderation endpoint.

**Comment by jhoseph88** [comment]
@danieljannai21 Thanks for catching this! I also ran into this and went ahead and submitted https://github.com/openai/openai-python/pull/475 to address it.

**Comment by RobertCraigie** [comment]
This is fixed in the [v1 SDK](https://github.com/openai/openai-python/discussions/631)!

A `with_options` method is provided that allows you to customise client level defaults on a per-request basis
```py
import httpx
from openai import OpenAI

client = OpenAI()

completion = client.with_options(timeout=httpx.Timeout(connect=2)).chat.completions.create(
    model="gpt-4",
    messages=[
        {
            "role": "user",
            "content": "Say hi!",
        }
    ],
)
```

**Comment by jhoseph88** [comment]
@RobertCraigie That's fantastic! Thank you so much for the update. 🚀
