### ISSUE TITLE
How to set the context in jsonl file for fine tuning

### ISSUE THREAD

**Issue by pradeepdev-1995** [openai/openai-python#445]
### Describe the feature or improvement you're requesting

I need to fine-tune an ```ada``` model.
I have the **instruction set** which describes the task to perform. The instruction set contains 8-10 commands which are the rules to be followed in the inference time.
Along with these commands, I have some examples to feed the system as a few shots.

So while finetuning I can put the few shot examples in the JSONL file in the following format
```
{"prompt":<example 1>", "completion":<example1 response>}
{"prompt":<example 2>", "completion":<example2 response>}
```

But where should i keep the **instruction set/rules to follow/command set/prompt** while finetuning?
Is it possible to keep this also in the JSONL file?

**Comment by logankilpatrick** [comment]
Hey! Please refer to our updated guide on fine-tuning: https://platform.openai.com/docs/guides/fine-tuning/example-format, there is only one way to pass in data for training with the traditional completion pairs, see the example above, everything you want the model to know must be in the prompt completion pair.
