### ISSUE TITLE
How to extract model name from Azure deployment name ?

### ISSUE THREAD

**Issue by mspronesti** [openai/openai-python#447]
### Describe the feature or improvement you're requesting

I'm using Azure OpenAI and I have more than one deployed model of the same type. I'd like to know how can I map a deployed model's name to the corresponding model's name, e.g. 'TestDavinci' ->'text-davinci-003'

**Comment by kristapratico** [comment]
Hi @mspronesti, the mapping from model name to deployment name can be found in the Azure OpenAI studio. Is your feature request to be able to do this programmatically? The Deployment.list() API can be called to retrieve some of this information. For example,

```python
import openai

openai.api_type = "azure"
openai.api_base = "https://<your-resource>.openai.azure.com/"
openai.api_key = "<your-key>"
openai.api_version = "2023-03-15-preview"

deployments = openai.Deployment.list()
print(deployments)
```

This returns a response where `id` is your deployment name and `model` is the model name.

```json
{
  "data": [
    {
      "created_at": 1681171441,
      "id": "text-embedding-ada-002-2",
      "model": "text-embedding-ada-002",
      "object": "deployment",
      "owner": "organization-owner"
    }
  ],
  "object": "list"
}
```

Can you clarify if you're looking for more information than what's in the above response?

**Comment by mspronesti** [comment]
Hello @kristapratico, the `Deployment.list()` API is what I was looking for, thanks! 
I'm closing this issue then.
I recommend opening the discussion session for this repository to allow people pose questions, as "bug report" and "feature request" are very much restrictive categories :)

**Comment by kristapratico** [comment]
Glad to hear that works for you. 

> I recommend opening the discussion session for this repository to allow people pose questions, as "bug report" and "feature request" are very much restrictive categories :)

^FYI @hallacy for repo feedback

**Comment by Harish-Tricon** [comment]
Thanks @kristapratico , for your response. My end goal is to fetch the deployments name form Azure openai. I used the below script:
`import openai

openai.api_type = "azure"
openai.api_base = "https://<your-resource>.openai.azure.com/"
openai.api_key = "<your-key>"
openai.api_version = "2023-03-15-preview"

deployments = openai.Deployment.list()
print(deployments)`

But getting :
{
    "error": {
        "code": "404",
        "message": "Resource not found"
    }
}

Even though deployments exists.

**Comment by kristapratico** [comment]
@mspronesti I'm not able to reproduce the error. Can you confirm that you are using the full endpoint to your resource on this line?

> "https://.openai.azure.com/"

I'm not sure if you just redacted the resource name for privacy. I'd expect it to look something like ""https://{my-resource}.openai.azure.com/""

**Comment by Harish-Tricon** [comment]
> @mspronesti I'm not able to reproduce the error. Can you confirm that you are using the full endpoint to your resource on this line?
> 
> > "https://.openai.azure.com/"
> 
> I'm not sure if you just redacted the resource name for privacy. I'd expect it to look something like ""https://{my-resource}.openai.azure.com/""

I  tried this end point also, but giving the same response @kristapratico .
`{
"error": {
"code": "404",
"message": "Resource not found"
}
}`

**Comment by kristapratico** [comment]
@Harish-Tricon the endpoint is specific to your Azure OpenAI resource. If you go to your Azure portal, and navigate to your Azure OpenAI resource, you can get the endpoint value by clicking "Keys and Endpoints" under the "Resource Management" section. It should look something like this (with the {my-resource} part substituted for your specific resource name): "https://{my-resource}.openai.azure.com/"

**Comment by enricoros** [comment]
@kristapratico Hi, I see the `/openai/deployments` url is still working, but only with `2023-03-15-preview`. This is almost the equivalent of OpenAI `https://api.openai.com/v1/models` API - it's 1 HTTP call to get the list of available models.

As my App (https://github.com/enricoros/big-agi) is in Typescript, and I'm adding Azure integration, this method works for me, and does not require python or larger libraries. Is this going to stay around?

**Comment by kristapratico** [comment]
> @kristapratico Hi, I see the `/openai/deployments` url is still working, but only with `2023-03-15-preview`. This is almost the equivalent of OpenAI `https://api.openai.com/v1/models` API - it's 1 HTTP call to get the list of available models.
> 
> As my App (https://github.com/enricoros/big-agi) is in Typescript, and I'm adding Azure OpenAI integration, this method works for me and does not require Python or more extensive libraries - which is great. Is this going to stay around?

@dereklegenzoff can you help answer this question?
