### ISSUE TITLE
Retrieve token limit and cost of a model from API

### ISSUE THREAD

**Issue by endolith** [openai/openai-python#448]
### Describe the feature or improvement you're requesting

It should be possible to retrieve the token limit and cost per 1k tokens programmatically from the API instead of needing to look them up on the website and hardcode them into programs.

https://github.com/openai/tiktoken/issues/109

**Comment by endolith** [comment]
Especially since the cost changes over time...

**Comment by logankilpatrick** [comment]
Agreed that we should support this, we don't today so I am going to take this as API feedback but I hope we can add it in the future.
