### ISSUE TITLE
stream completions did not work on async api

### ISSUE THREAD

**Issue by lsaint** [openai/openai-python#456]
### Describe the bug

According to [How_to_stream_completions](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb)
```
response = openai.ChatCompletion.create(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': "What's 1+1? Answer in one word."}
    ],
    temperature=0,
    stream=True  
)

for chunk in response:
    print(chunk)
```
we can stream a chat completion via `ChatCompletion.create`
but when I use `ChatCompletion.acreate` ,  it failed.
```
TypeError: 'async_generator' object is not iterable
```

### To Reproduce

```
response = openai.ChatCompletion.acreate(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': "What's 1+1? Answer in one word."}
    ],
    temperature=0,
    stream=True  
)

for chunk in response:
    print(chunk)
```

### Code snippets

```Python
response = openai.ChatCompletion.acreate(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': "What's 1+1? Answer in one word."}
    ],
    temperature=0,
    stream=True  
)

for chunk in response:
    print(chunk)
```
```


### OS

macOS

### Python version

Python 3.11

### Library version

0.27.2

**Comment by liho00** [comment]
hi ser whats the solution for this issue?

**Comment by issamhaimour** [comment]
> ### Describe the bug
> 
> According to [How_to_stream_completions](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb)
> 
> ```
> 
> response = openai.ChatCompletion.create(
> 
>     model='gpt-3.5-turbo',
> 
>     messages=[
> 
>         {'role': 'user', 'content': "What's 1+1? Answer in one word."}
> 
>     ],
> 
>     temperature=0,
> 
>     stream=True  
> 
> )
> 
> 
> 
> for chunk in response:
> 
>     print(chunk)
> 
> ```
> 
> we can stream a chat completion via `ChatCompletion.create`
> 
> but when I use `ChatCompletion.acreate` ,  it failed.
> 
> ```
> 
> TypeError: 'async_generator' object is not iterable
> 
> ```
> 
> ### To Reproduce
> 
> ```
> 
> response = openai.ChatCompletion.acreate(
> 
>     model='gpt-3.5-turbo',
> 
>     messages=[
> 
>         {'role': 'user', 'content': "What's 1+1? Answer in one word."}
> 
>     ],
> 
>     temperature=0,
> 
>     stream=True  
> 
> )
> 
> 
> 
> for chunk in response:
> 
>     print(chunk)
> 
> ```
> 
> ### Code snippets
> 
> ```Python
> response = openai.ChatCompletion.acreate(
> 
>     model='gpt-3.5-turbo',
> 
>     messages=[
> 
>         {'role': 'user', 'content': "What's 1+1? Answer in one word."}
> 
>     ],
> 
>     temperature=0,
> 
>     stream=True  
> 
> )
> 
> 
> 
> for chunk in response:
> 
>     print(chunk)
> 
> ```
> ```
> 
> 
> ### OS
> 
> macOS
> 
> ### Python version
> 
> Python 3.11
> 
> ### Library version
> 
> 0.27.2
