### ISSUE TITLE
How to work with maximum context length is 2049 tokens?

### ISSUE THREAD

**Issue by SeaDude** [openai/openai-python#46]
I'd like to send the OpenAI's API, the text from various PDF's. Specifically, the [Summarize for a 2nd grader](https://beta.openai.com/examples/default-summarize) or the [TL;DR summarization](https://beta.openai.com/examples/default-tldr-summary) API's.

I can extract the text from PDF's using `PyMuPDF` and prepare the OpenAI prompt.

**Question:** How best to prepare the `prompt` when the token count is longer than the allowed 2049?

- Do I just truncate the text?
- Or is there a way to sample the text to "compress" it to lose key points?

**Comment by sagar1025** [comment]
Try the [Openai Forums](https://community.openai.com/)

**Comment by hallacy** [comment]
Hi @SeaDude, thanks for the issue! I'd agree with @sagar1025.  Please check out the forums and let support@openai.com know if you have any issues
