### ISSUE TITLE
Numba error when inference in thread (QThread, pyside6)

### ISSUE THREAD

**Issue by FranPuentes** [openai/openai-python#465]
### Describe the bug

Doing a chat inference with "text-davinci-003" into a QThread hangs the function "openai.Completion.create" "ad infinitum".

Only one error is reported in console: Numba reports that it cannot be in a thread because the data is not copied from the parent thread.

Finally, when I cancel the request, an exception is fired.

If I change the code to use -only- async, and it works. But I need use threads, because I want avoid locking the main thread.

### To Reproduce

class QUERY(QThread):

            def __init__(self, tutor, prompt):
                super().__init__(tutor);
                self.tutor=tutor;
                self.prompt=prompt;

            def query(self, prompt):
                MODEL="gpt-3.5-turbo";
                print("OpenAI: enviando texto a openAI", flush=True);
                r=openai.ChatCompletion.create(model=MODEL, messages=prompt, stream=False);
                print("OpenAI: esperando por la respuesta", flush=True);
                try:
                   if "choices" in r:
                      if len(r["choices"])>0 and "message" in r["choices"][0]:
                         if "content" in r["choices"][0]["message"]:
                            response=r["choices"][0]["message"]["content"];
                            self.tutor.history.append(response);
                            self.tutor.onResponse.emit(response);
                         else:
                            self.tutor.onError.emit("Ha fallado en: content",r);
                      else:
                         self.tutor.onError.emit("Ha fallado en: len choices o message",r);
                   else:
                      self.tutor.onError.emit("Ha fallado en: choices",r);

                except:
                   print(traceback.format_exc(), flush=True);
                   self.tutor.onError.emit("OpenAI ha fallado!");

                finally:
                   print("OpenAI: respuesta finalizada", flush=True);

### OS

Linux Ubuntu Jammy

### Python version

Python 3.9.16

### Library version

openai-python 0.27.0
numba 0.57

**Comment by rattrayalex** [comment]
Closing as stale. If this is still an issue in the v1 of this library, we can reopen.
