### ISSUE TITLE
Azure content management exception triggered by charset encoding issues

### ISSUE THREAD

**Issue by paulovn** [openai/openai-python#466]
### Describe the bug

I'm getting exceptions triggered by content management filter at the Azure endpoint, i.e. an `InvalidRequestError` with fields
* `error_code`: `content_filter`
*  `error_message`: _The response was filtered due to the prompt triggering Azure OpenAI?s content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766_

The prompt sent is trivial, the only issue is that it's in Spanish and has non-ASCII characters. I'm using `gpt-35-turbo` and the `ChatCompletion` method. The prompt is just:

      [{'role': 'user', 'content': 'quiero un móvil con una buena cámara'}]

(meaning _I want a mobile with a good camera_). This triggers the content filter, which does not make much sense, given that the message is harmless. Furthermore, if I _remove_ the accented character in `cámara`, i.e.

      [{'role': 'user', 'content': 'quiero un móvil con una buena camara'}]

... then the filter is not triggered, and I get a proper text response. Which makes less sense.

I've dug a bit in the code. The prompt seems to be serialized [here](https://github.com/openai/openai-python/blob/main/openai/api_requestor.py#L484):
```python
            if params and not files:
                data = json.dumps(params).encode()
                headers["Content-Type"] = "application/json"
```

Interestingly, if I change the serialization to

```python
            if params and not files:
                data = json.dumps(params, ensure_ascii=False).encode()
                headers["Content-Type"] = "application/json"
```

..then the content management filter is *not* triggered, even with an accented character, and I get a proper response. Which suggests some kind of unusual behavior at the endpoint, given that it behaves differently with escaped unicode characters than with regular UTF-8 text.

### To Reproduce

1. Peepare a prompt `[{'role': 'user', 'content': 'quiero un móvil con una buena cámara'}]
2. Send to the ChatCompletion API, with a gpt-35-turbo model
3. Content Management filter is triggered

### OS

Ubuntu

### Python version

Python 3.8.10

### Library version

openai-python v0.27.7

**Comment by kristapratico** [comment]
@paulovn I don't have an update for you yet, but just letting you know that I passed your issue to the Azure folks who work on content filtering.

**Comment by rattrayalex** [comment]
This does not look like a bug in the Python SDK, so I'm going to go ahead and close this issue.
