### ISSUE TITLE
Unsupported error message in using SDK nad playground

### ISSUE THREAD

**Issue by sm9i** [openai/openai-python#470]
### Describe the bug

Code example using readme:

```python
import openai
openai.api_key = "my key"

# list models
models = openai.Model.list()

# print the first model's id
print(models.data[0].id)

# create a chat completion
chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])

# print the chat completion
print(chat_completion.choices[0].message.content)
```

The following is the error message

```
whisper-1
Traceback (most recent call last):
  File "c:\Users\admin\Desktop\test-code\test.py", line 25, in <module>
    chat_completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hello world"}])
  File "C:\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Python310\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?
```

### To Reproduce

I thought it was a problem with my SDK, so I tried [playground](https://platform.openai.com/playground?mode=chat&model=gpt-3.5-turbo)and it was also an error.

![image](https://github.com/openai/openai-python/assets/31961133/511f6dc3-dc9e-4db7-96ab-1a00a8ef6e7e)

### OS

win

### Python version

3.10.4

### Library version

0.27.7

**Comment by sm9i** [comment]
I looked at other questions, but that didn't solve the problem. 
https://github.com/openai/openai-python/issues/271

**Comment by kristapratico** [comment]
Hi @sm9i - are you using the Azure OpenAI service? If so, you'll need to set some different variables to configure Azure with the Python SDK. See this guide here: https://learn.microsoft.com/azure/cognitive-services/openai/how-to/switching-endpoints#authentication

**Comment by sm9i** [comment]
> Hi @sm9i - are you using the Azure OpenAI service? If so, you'll need to set some different variables to configure Azure with the Python SDK. See this guide here: https://learn.microsoft.com/azure/cognitive-services/openai/how-to/switching-endpoints#authentication


Thank you. I did not use Azure OpenAI service or any other services, only referenced the OpenAI library

````python
import openai
````

**Comment by sm9i** [comment]
Hi, any new results on this issue, maybe it's a problem with my account?

**Comment by shiyishiaa** [comment]
好像是黑号了
https://www.reddit.com/r/SillyTavernAI/comments/167qrm8/comment/jys5ioi/?utm_source=share&utm_medium=web2x&context=3
