### ISSUE TITLE
Using openai.proxy on Anaconda Jupyter Notebook

### ISSUE THREAD

**Issue by Mrin7** [openai/openai-python#471]
### Describe the bug

import openai
openai.api_key = "XXXX"
proxies = {
'http': "http://xxxx:xxxx/",
'https': "https://xxxx:xxxx/"}
openai.proxy = proxies

I see this error : 
APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

### To Reproduce

proxies = {
'http': "http://xxxx:xxxx/",
'https': "https://xxxx:xxxx/"}
openai.proxy = proxies

### OS

Windows

### Python version

Python 3.10.9

### Library version

openai 0.27.7

**Comment by Renpf2022** [comment]
I also encountered this problem

**Comment by idhamari** [comment]
Here is an example to add the proxy: 

        openaiApiKey = "your openai api key"
        proxy = "http://yourproxy:port"
        opn   = ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613",openai_proxy=proxy,  openai_api_key=openaiApiKey)

**Comment by logankilpatrick** [comment]
This looks like an issue with Anaconda's environment and how it restricts connections, I am going to close this out.
