### ISSUE TITLE
AuthenticationError: <empty message>

### ISSUE THREAD

**Issue by isa-tr** [openai/openai-python#474]
### Describe the bug

I am using ChromaDB, I have a collection with the embeddings obtained with the text-embedding-ada-002 model and I want to query it. I already changed the OpenAI Key several times and it does not work. 

This is my code (see the image)

### To Reproduce

![image](https://github.com/openai/openai-python/assets/82721764/62851856-1c88-475d-886b-805a5ef867e4)

### OS

Ubuntu

### Python version

Python v3.10

### Library version

openai-python v0.27.7

**Comment by hallacy** [comment]
Hi! Do you have a request id that had this issue?

**Comment by isa-tr** [comment]
> Hi! Do you have a request id that had this issue?

What do you mean?

**Comment by jinfar** [comment]
Same error. 
Tried both
os.environ["OPENAI_API_KEY"] = " "
openai.api_key = " "

'x-request-id': '8bf6c2928d521bef1d6c6186358de51a'
'x-request-id': '84b78174d6396c0ba808d1f286cd9147'

**Comment by mehmetkoca** [comment]
#464

**Comment by isa-tr** [comment]
Thank you! That worked very well :)

**Comment by logankilpatrick** [comment]
Closing this out, looks like we got a resolution!
