### ISSUE TITLE
Is there a way to prevent the API from returning the same answers in different outputs of the same HTTP response?

### ISSUE THREAD

**Issue by nbro10** [openai/openai-python#479]
### Describe the feature or improvement you're requesting

When I make a request to the OpenAI API (specifically, the chat endpoint) with this package, I expect that different outputs, in the same response, are different. There's no reason for expecting different outputs to be the same - you could just copy them. This problem happens so often and it's so annoying. Even if we increase the temperature, this issue still occurs, i.e. the model may always return the same answer in different outputs. We should never pay for getting the same output in the same HTTP response multiple times. It would be like asking someone (a human) to come up with 5 different descriptions of a product, but 3 of them are repetitions.

So, is there a way to prevent the API from returning the same answer in different outputs? I think the answer is no. 

If not, could this be implemented in some way in the backend? It would also be great if this feature allowed us to make the comparison by ignoring cases (some standardized form) or maybe using some kind of similarity metric (but this is more advanced). 

Clearly, we need this to avoid making unnecessary calls and spending unnecessary credits. 

Prompt engineering doesn't really work in many cases. It's trial-and-error combined with headaches. What we need is the API or the backend to **enforce** the different outputs to contain different outputs/answers, otherwise, we'd better just remove the possibility to return multiple outputs because, at least, that's less misleading.

**Comment by logankilpatrick** [comment]
Hey! We don't support this today but you could try to build a work around using the presence penalty and passing one response to the next call: https://platform.openai.com/docs/api-reference/chat/create#presence_penalty
