### ISSUE TITLE
Different accounts at same time?

### ISSUE THREAD

**Issue by austinmw** [openai/openai-python#484]
### Describe the feature or improvement you're requesting

How might I use different accounts/api keys at the same time? For example if I have a company account that I want to use budget for embedding model, and personal account that I want to use budget for chat model?

Is there a way to create two client objects and pass one to each model class?

**Comment by Barqawiz** [comment]
I have encountered the same issue where switching the OpenAI key affects all imports. One possible solution is to initiate openai as an object, which seems not supported. 

Looking to hear from the OpenAI team about this too.

**Comment by aravindarc** [comment]
@Barqawiz @austinmw Did you guys find a workaround for this. This seems to be either a very bad design or an intentional restriction.

**Comment by logankilpatrick** [comment]
Hey! The way to do this is via the organization header, https://platform.openai.com/docs/api-reference/requesting-organization
