### ISSUE TITLE
Different token limit error than OpenAI while using Azure OpenAI Service with gpt-3.5-turbo,  api version 2023-03-15-preview

### ISSUE THREAD

**Issue by bhavishpahwa** [openai/openai-python#485]
### Describe the bug

When I send a request for gpt-3.5-turbo chat completion which is 8218(8138 in messages and 80 in completion) tokens long, I get the error message as InvalidRequestError: This model's maximum context length is 8192 tokens. However, you requested 8218 tokens (8138 in the messages, 80 in the completion). Please reduce the length of the messages or completion. Which is incorrect as the gpt-3.5-turbo model's max token limit is 4096 and the error that used to be present while using OpenAI platform. Also when I try to send a 8191 token long chat completion message I get Azure Content Filtering error.

### To Reproduce

1. Create an Azure Deployment.
2. Write the openai base code to send a request to Azure OpenAI with the deployment name.
3. Send a 8218 tokens long chat completion request.

### OS

macOS

### Python version

Python v3.10

### Library version

openai-python-0.27.7

**Comment by apptaro** [comment]
I have the same issue. I can send messages with more than 4096 tokens.
I wonder if it's an API issue, or gpt-3.5-turbo actually can take 8192 tokens now.

**Comment by kristapratico** [comment]
Hi @bhavishpahwa @apptaro,

For the Azure OpenAI gpt-35-turbo model, we recommend staying within the documented token limit. While we don't intend to change the behavior of version 0301 of the model, all future versions will only support 4k tokens.

**Comment by bhavishpahwa** [comment]
Sure @kristapratico that I understand. Is there any bug fix/ fix pending for this wrong error message or is this the normal expected behaviour?

**Comment by kristapratico** [comment]
@bhavishpahwa I don't think the error message is incorrect here. It's permissible to pass ~8k tokens, _however_ the recommended limit is ~4k. For this version 0301 of the model it will not be changed, but for future versions the 4k limit will be enforced.

**Comment by bhavishpahwa** [comment]
Okay @kristapratico thanks for the clarification.
