### ISSUE TITLE
Support for functions

### ISSUE THREAD

**Issue by francisjervis** [openai/openai-python#486]
### Describe the feature or improvement you're requesting

Pythonic support for functions as described in the feature [announcement](https://openai.com/blog/function-calling-and-other-api-updates).

**Comment by Ja-sonYun** [comment]
Seems like we can use like this
```python
completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo-0613",
    messages=[{"role": "user", "content": "What is the weather like in Boston?"}],
    functions=[
        {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        }
    ],
)
```
And the response is
```python
```

**Comment by francisjervis** [comment]
Right, saw the docs updated too. Leaving this open for *Pythonic* support tho haha, ie using either built-in or Pydantic types rather than horrors like `"string"` ;) Ideally, noting the safety issues, it should be taking an actual function as input, rather than JSON kinda-code.

**Comment by Ja-sonYun** [comment]
I totally agree with that pythonic support. We want some sort of type safe stuff like `TypedDict` at least.

**Comment by francisjervis** [comment]
See how tools are implemented in Langchain, for example. You should just be able to pass a function and have it receive the JSON as kwargs.

**Comment by Ja-sonYun** [comment]
I really happy if openai implement like that. I'm also thinking to wrap this in a pythonic way in my project, but this function calling needs descriptions or enum fields in properties, and i can't imagine where can we get description of passed function's parameter.

**Comment by francisjervis** [comment]
This is a real issue - even GPT-4 is apparently not yet reliably capable of returning consistent null values. I'm able to get more consistent results with carefully engineered "old fashioned" prompts for structured outputs as it stands anyhow, but my first impression is that this is not a "magic bullet" for getting machine-readable responses back...

**Comment by janekb04** [comment]
I have made a simple converter that converts a Python function into this JSON: https://github.com/janekb04/py2gpt

**Comment by Ja-sonYun** [comment]
> I don't think this works properly with the new "function" feature, because in here it is clear that the "function_call" element of the "messages" map is not transmitted to the API backend:
> 
> https://github.com/openai/openai-python/blob/041bf5a8ec54da19aad0169671793c2078bd6173/openai/cli.py#L119-L121

That is for cli, and the `ChatCompletion` class which we actually use is [this](https://github.com/openai/openai-python/blob/041bf5a8ec54da19aad0169671793c2078bd6173/openai/api_resources/chat_completion.py) class. check out `__init__.py`, you can see the `ChatCompletion` is imported from `api_resources`.
https://github.com/openai/openai-python/blob/041bf5a8ec54da19aad0169671793c2078bd6173/openai/__init__.py#L19

**Comment by rattrayalex** [comment]
Would you want something like [`runFunctions` / `runTools`](https://github.com/openai/openai-node#automated-function-calls) from the Node SDK?

**Comment by rattrayalex** [comment]
We're working on something like this! We're tracking separately, so I'm going to close this issue. Keep an eye on our releases!

**Comment by jackmpcollins** [comment]
I built https://github.com/jackmpcollins/magentic to solve exactly this issue of translating between python objects and openai LLM queries. @francisjervis if you are still looking for a solution, you might be interested in checking out the docs on how function calling works in magentic: https://magentic.dev/function-calling/
