### ISSUE TITLE
Make Decorators a built-in part of the function call functionality

### ISSUE THREAD

**Issue by MalikMAlna** [openai/openai-python#492]
### Describe the feature or improvement you're requesting

It would be really nice if we could have built-in decorators that abstract away a lot of the unnecessary function-calling boilerplate that causes the code to be more confusing and difficult to use than necessary. 

I felt like it took much more time to wrap my head around the value and utility of function calls in the recent API update than was necessary in part because of the boilerplate. Additionally, having a bunch of text describing functions that will eventually no longer be needed or might need to be changed syntactically or for other reasons in future updates seems like it would take a lot of time and effort to refactor in the long term. 

So I'd propose that built-in decorators for function calling are at least considered as a future option when granular control over the function call isn't immediately required.

### Additional context

I think [this project](https://github.com/unconv/gpt-pydecorator) does a great job of creating the functionality that I'm referring to here.

**Comment by rattrayalex** [comment]
Thanks for the suggestion! We're cooking up something like this. We're tracking internally so I'll go ahead and close this issue.

**Comment by lucasmsoares96** [comment]
any progress on this?

**Comment by MalikMAlna** [comment]
I would also like to hear if there's been any progress on this issue as well.
