### ISSUE TITLE
M1 issue

### ISSUE THREAD

**Issue by thedarkknight197** [openai/openai-python#500]
### Describe the bug

Same issue closed here, but I can't resolved in any way:
https://github.com/openai/openai-python/issues/338

### To Reproduce

pip install openai[datalib]

zsh: no matches found: openai[datalib]
michele@MacBook-Pro-di-michele model % pip install openai"[datalib]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/michele/Library/Python/3.8/lib/python/site-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]

michele@MacBook-Pro-di-michele model % 

michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: '[datalib]'

michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
michele@MacBook-Pro-di-michele model % 
michele@MacBook-Pro-di-michele model % pip install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3.8 install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]

michele@MacBook-Pro-di-michele model % 

### Code snippets

```Python
pip install openai[datalib]

zsh: no matches found: openai[datalib]
michele@MacBook-Pro-di-michele model % pip install openai"[datalib]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/michele/Library/Python/3.8/lib/python/site-packages (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]


michele@MacBook-Pro-di-michele model % 

michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: '[datalib]'


michele@MacBook-Pro-di-michele model % pip3 install openai \[datalib\]
michele@MacBook-Pro-di-michele model % 
michele@MacBook-Pro-di-michele model % pip install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % pip3.8 install openai\[datalib\]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openai[datalib] in /Users/michele/Library/Python/3.8/lib/python/site-packages (0.27.8)
Requirement already satisfied: requests>=2.20 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.30.0)
Requirement already satisfied: tqdm in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (4.65.0)
Requirement already satisfied: aiohttp in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.8.4)
Requirement already satisfied: numpy in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (1.24.3)
Requirement already satisfied: pandas>=1.2.3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2)
Requirement already satisfied: pandas-stubs>=1.1.0.11 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (2.0.2.230605)
Requirement already satisfied: openpyxl>=3.0.7 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openai[datalib]) (3.1.2)
Requirement already satisfied: et-xmlfile in /Users/michele/Library/Python/3.8/lib/python/site-packages (from openpyxl>=3.0.7->openai[datalib]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas>=1.2.3->openai[datalib]) (2023.3)
Requirement already satisfied: types-pytz>=2022.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from pandas-stubs>=1.1.0.11->openai[datalib]) (2023.3.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from requests>=2.20->openai[datalib]) (2023.5.7)
Requirement already satisfied: attrs>=17.3.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/michele/Library/Python/3.8/lib/python/site-packages (from aiohttp->openai[datalib]) (1.3.1)
Requirement already satisfied: six>=1.5 in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.2.3->openai[datalib]) (1.15.0)
michele@MacBook-Pro-di-michele model % openai tools fine_tunes.prepare_data -f training_data.jsonl
Analyzing...
Traceback (most recent call last):
  File "/opt/homebrew/bin/openai", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/openai/_openai_scripts.py", line 78, in main
    args.func(args)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/cli.py", line 594, in prepare_data
    df, remediation = read_any_format(fname)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/validators.py", line 481, in read_any_format
    assert_has_pandas()
  File "/opt/homebrew/lib/python3.9/site-packages/openai/datalib/pandas_helper.py", line 15, in assert_has_pandas
    raise MissingDependencyError(PANDAS_INSTRUCTIONS)
openai.datalib.common.MissingDependencyError: 

OpenAI error:

    missing `pandas`

This feature requires additional dependencies:

    $ pip install openai[datalib]


michele@MacBook-Pro-di-michele model %
```

### OS

MacOS Big Sur 11.7.7 (20G1345)

### Python version

Python 3.8

### Library version

openai 0.27.2

**Comment by nirban07** [comment]
hey are there any updates on why is this happening?

**Comment by rattrayalex** [comment]
This has been removed from v1. If you continue to encounter issues in the latest version, please open a new issue.
