### ISSUE TITLE
Error when importing embeddings_utils

### ISSUE THREAD

**Issue by LinuxIsCool** [openai/openai-python#511]
### Describe the bug

![image](https://github.com/openai/openai-python/assets/31582215/54a67736-3276-4644-a02e-22da54a5d579)

```
ImportError: cannot import name 'ARRAY_FUNCTIONS' from 'numpy.core.overrides' (/home/ygg/.cache/pypoetry/virtualenvs/stakeholderstudy-shsA1FjX-py3.10/lib/python3.10/site-packages/numpy/core/overrides.py)
```
```
openai==0.27.8                                                                                                                             
numpy==1.25.0
```

### To Reproduce

poetry add openai

from openai import embeddings_utils

### OS

Pop!_OS 22.04 LTS x86_64

### Python version

Python 3.10.6

### Library version

openai==0.27.8

**Comment by RobertCraigie** [comment]
FYI in our upcoming [v1 beta](https://github.com/openai/openai-python/discussions/631) we're moving away from providing the `embeddings_utils` module directly and instead will be providing snippets in the [OpenAI cookbook](https://github.com/openai/openai-cookbook) that you can copy-paste into your own projects so you can pick and choose what dependencies you want instead of having to install all of these dependencies through the `embeddings` extra:
```
scikit-learn >= 1.0.2
tenacity >= 8.0.1
matplotlib
plotly
numpy
scipy
pandas >= 1.2.3
pandas-stubs >= 1.1.0.11
openpyxl >= 3.0.7
```

**Comment by gkatsanos** [comment]
@RobertCraigie thats fine, but : https://cookbook.openai.com/examples/get_embeddings_from_dataset which is linked quite prominently in https://platform.openai.com/docs/guides/embeddings/use-cases needs to be updated or obsoleted.. spent probably a good 2-3 hours trying to figure out what I'm doing wrong :( 
PRs welcome? I can at least add a warning that this example won't work unless you use an older version of the openAI library.

**Comment by gkatsanos** [comment]
thank you , but I think I'm more confused than when I started :-)

**Comment by RobertCraigie** [comment]
sorry, you need to copy and paste that file somewhere locally, ideally you'd put it in `utils/embeddings_utils.py` and also add `utils/__init__.py`. Does that make sense?

**Comment by gkatsanos** [comment]
thank you Robert - I also realized there's a 'open on github' button that basically has the entire Jupyter Notebook available :) I guess need to find an accompanying book, a course or something similar that gives a little more context to what's happenng.

**Comment by gkatsanos** [comment]
@RobertCraigie quick thing; the https://github.com/openai/openai-cookbook/blob/main/examples/Get_embeddings_from_dataset.ipynb uses `engine` as a parameter for get_embedding but I think `model` is the new name of this argument https://platform.openai.com/docs/guides/embeddings/what-are-embeddings right?

**Comment by rattrayalex** [comment]
@gkatsanos for help related to the cookbook, please ping on the cookbook repo, or in the [OpenAI Discord](https://discord.com/invite/openai) server!

**Comment by gkatsanos** [comment]
Will do! Thank you!
