### ISSUE TITLE
command line for fine tune unable to pick api type

### ISSUE THREAD

**Issue by GPrakruth** [openai/openai-python#516]
### Describe the bug

openai [-h] [-V] [-v] [-b API_BASE] [-k API_KEY] [-p PROXY [PROXY ...]] [-o ORGANIZATION] {api,tools,wandb}

we have setup the environment variables for api_key, api_base, version and api_type
and we are trying to run fine tune model using the commands provided in open_ai_cookbook
we are facing an error of 
Error: The API type provided in invalid. Please select one of the supported API types: 'azure', 'azure_ad', 'open_ai'

### To Reproduce

%env OPENAI_API_TYPE  
%env OPENAI_API_VERSION 
%env OPENAI_API_KEY
%env OPENAI_API_BASE 

we are trying to run the following commands on cloud platform

!openai api fine_tunes.create -t "/FileStore/train.json" -v "/FileStore/test.json" --classification_metric "accuracy" --classification_labels "yes,no" --model "text-davinci-003" --max_iterations 100 --save_model "test_results"

we have also tried 

%sh /local_disk0/envs/pythonEnv/bin/openai --verbose --api-key <api_key>  -api-base <api_base> api fine_tunes.create -t /FileStore/train.json -v /FileStore/test.json --compute_classification_metrics --classification_positive_class <class>

Error: The API type provided in invalid. Please select one of the supported API types: 'azure', 'azure_ad', 'open_ai'

### OS

Linux

### Python version

3.9

### Library version

'0.27.8'

**Comment by rattrayalex** [comment]
v0.x has been deprecated; please try the v1.
