### ISSUE TITLE
Azure API does not support functions in chat?

### ISSUE THREAD

**Issue by Billijk** [openai/openai-python#517]
### Describe the bug

New `functions` parameter in ChatCompletion is not recognized when calling MS Azure endpoints. I got this error when I pass in my functions:

```
  File "call_chatgpt.py", line 52, in chatgpt
    chat_completion = openai.ChatCompletion.create(
  File "/root/anaconda3/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/root/anaconda3/lib/python3.8/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/root/anaconda3/lib/python3.8/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/root/anaconda3/lib/python3.8/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Unrecognized request argument supplied: functions
```

### To Reproduce

1. run the code snippet
2. get the error

### Code snippets

```Python
import openai

AZURE_KEY = "<key here>"
AZURE_ENDPOINT = "<endpoint here>"

messages = [{"role": "user", "content": "What's the weather like in Boston?"}]
functions = [
    {
        "name": "get_current_weather",
        "description": "Get the current weather in a given location",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "The city and state, e.g. San Francisco, CA",
                },
                "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
            },
            "required": ["location"],
        },
    }
]
openai.api_type = "azure"
openai.api_key = AZURE_KEY
openai.api_base = AZURE_ENDPOINT
openai.api_version = "2023-05-15"

chat_completion = openai.ChatCompletion.create(
    engine="gpt-35-turbo",
    messages=messages,
    functions=functions
)
```

### OS

linux

### Python version

python 3.8

### Library version

v0.27.8

**Comment by Billijk** [comment]
Found same issue here: https://stackoverflow.com/questions/76543136/how-to-do-function-calling-using-azure-openai

**Comment by luc-languagetools** [comment]
is there a known workaround ? or we need to wait for azure to support functions ?

**Comment by yippp** [comment]
https://learn.microsoft.com/en-us/answers/questions/1323694/error-calling-function-when-using-model-gpt-35-tur
Seems Azure has known this problem and is tring to fix it.

**Comment by kristapratico** [comment]
Function support with Azure API will be supported soon, but there is not an ETA quite yet.

**Comment by kristapratico** [comment]
Functions are now supported with the Azure API. You can see more details here: https://learn.microsoft.com/azure/ai-services/openai/how-to/function-calling

**Comment by amanoooo** [comment]
remember update this config
```openai.api_version = "2023-07-01-preview"```

**Comment by aiakubovich** [comment]
here what is working for me:

```
openai.api_version = "2023-07-01-preview"
response = openai.ChatCompletion.create(
    engine="gpt-35-turbo-0613",
    messages=[{"role": "user", "content": "Efficient operations on the ground and friendly, attentive employees everywhere."}],
    functions=functions,
    function_call="auto",
)
```

**Comment by qkxie** [comment]
> remember update this config `openai.api_version = "2023-07-01-preview"`

You save me.

**Comment by Billijk** [comment]
Thanks a lot for the efforts to make this work!

**Comment by linchpinlin** [comment]
The question came up again.

**Comment by kristapratico** [comment]
> The question came up again.

@linchpinlin can you share the error and an example of the code that reproduces it?

**Comment by kristapratico** [comment]
@linchpinlin I copy/pasted the example from the demo code and wasn't able to reproduce the error from it. Can you confirm that you've set the API version and model to those supported by functions?

> Function calling is available in the 2023-07-01-preview API version and works with version 0613 of gpt-35-turbo, gpt-35-turbo-16k, gpt-4, and gpt-4-32k.

**Comment by Sky640q** [comment]
Issue exists with azureopenai endpoint with client config: 
model="gpt-35-turbo-0613"

client = AzureOpenAI(
    azure_endpoint=endpoint,
    api_key=api_key,
    api_version="2023-07-01-preview"
    )

NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by janaka** [comment]
getting the same error with 0613 deployment and version "2023-07-01-preview"
