### ISSUE TITLE
ClientError vs ServerError

### ISSUE THREAD

**Issue by kenn** [openai/openai-python#518]
### Describe the feature or improvement you're requesting

Generally, it's a good idea to separate error responsibilities between client and server, just as HTTP status code represents with 400-499 (client error) vs 500-599 (server error).

This library has many error types, but they are all subclass of `OpenAIError` which makes it hard to handle exceptions at a higher level.

For instance, we'd swallow `ServiceUnavailableError` on the UI and let the user retry so that devs won't be bothered with the error notification on this. But we'd want to get notified upon `InvalidRequestError` because it's a bug in our codebase.

If we had `ServerError` and `ClientError`, we'd write some code like this:

```py
try:
    response = openai.ChatCompletion.create(**params)
except openai.error.ClientError as e:
    # This is our bug, notify and fix it!
    raise e
except openai.error.ServerError:
    # OpenAI seems to be busy
    # Do not raise error and prompt the user to retry later
```

I also see `tenacity.RetryError` for embeddings from time to time, so it would be great if it's handled in the same semantics.

### Additional context

The semantics here is:

- If we face a client error (403, 404, etc.), we want to raise the exception and report the error (often via tools like [Sentry](https://sentry.io/)) so that devs can fix it. Do NOT retry with the same set of parameters because it will fail until you fix the bug.
- If we face a server error (502, 503, etc.), the issue is usually temporary and retry would fix by itself.

Group those errors into one of the two parent classes, `ServerError` and `ClientError`.

```py
class OpenAIError(Exception):
class APIError(OpenAIError):
class TryAgain(OpenAIError):
class Timeout(OpenAIError):
class APIConnectionError(OpenAIError):
class InvalidRequestError(OpenAIError):
class AuthenticationError(OpenAIError):
class PermissionError(OpenAIError):
class RateLimitError(OpenAIError):
class ServiceUnavailableError(OpenAIError):
class InvalidAPIType(OpenAIError):
class SignatureVerificationError(OpenAIError):
```

**Comment by rjarun8** [comment]
I feel this is necessary for handling the exceptions better. It makes life so much easy when the parent aggregator is available to bucket the exceptions

Tested the implementation and here are the results. Please confirm if this aligns with the expectation to be addressed as part of this issue @kenn 

```
def test_openai_api():
    # Set your OpenAI API key
    openai.api_key = api_key  # Replace with your actual API key

    try:
        # Perform an API request that may result in a client error
        openai.Completion.create(
            model="text-davinci-003",
            prompt="Say this is a test",
            max_tokens=-1,
            temperature=0
        )
    except ClientError as e:
        # Handle client errors
        if isinstance(e, InvalidRequestError):
            print("Invalid Request Error:", e)
            # Additional handling logic for invalid request errors
        elif isinstance(e, AuthenticationError):
            print("Authentication Error:", e)
            # Additional handling logic for authentication errors
        else:
            print("Client Error:", e)
            # Default handling logic for other client errors
    except ServerError as e:
        # Handle server errors
        print("Server Error:", e)
        # Additional error handling logic can be added here

test_openai_api()
```


**Results:**

`Client Error: -1 is less than the minimum of 0 - 'max_tokens'`

**Comment by rattrayalex** [comment]
Great news, we have more granular error classes in the [beta of our upcoming v1.0.0](https://github.com/openai/openai-python/discussions/631)! Please try it out and let us know what you think.
