### ISSUE TITLE
There is an error in the README

### ISSUE THREAD

**Issue by expzhizhuo** [openai/openai-python#522]
### Describe the bug

![image](https://github.com/openai/openai-python/assets/64049774/b0a08fee-0aa2-4477-9796-b1b03bbdc056)
This error is in the final output and should read print(chat_completion.choices[0].message.content) instead of print(completion.choices[0].message.content)

### To Reproduce

![image](https://github.com/openai/openai-python/assets/64049774/d67652f1-5dec-428f-a32b-b76c8451bc5a)

### OS

macos

### Python version

3.9

### Library version

v26.4

**Comment by EliahKagan** [comment]
Merging #512 should fix this.

**Comment by logankilpatrick** [comment]
This is now resolved!
