### ISSUE TITLE
Import time >1s when running with pandas

### ISSUE THREAD

**Issue by pvicente** [openai/openai-python#525]
### Describe the bug

See import time when installing openai[datalib] due to pandas load time.

<img width="926" alt="Screenshot 2023-07-10 at 21 12 39" src="https://github.com/openai/openai-python/assets/471109/be5d9d58-21df-48e6-87da-5831e369a409">

### To Reproduce

Install openai and compare import time with and without [datalib] extension installed (pandas).

### Code snippets

```Python
In local 4s


import time
t1 = time.perf_counter()
from openai.datalib import pandas_helper
print(time.perf_counter() - t1, pandas_helper.pandas)

t1 = time.perf_counter()
try:
    pandas_helper.assert_has_pandas()
except pandas_helper.MissingDependencyError:
    pass
print(time.perf_counter() - t1, pandas_helper.pandas)

t1 = time.perf_counter()
try:
    pandas_helper.assert_has_pandas()
except pandas_helper.MissingDependencyError:
    pass
print(time.perf_counter() - t1, pandas_helper.pandas)
```

```
4.230538249947131 <module 'pandas' from '/Users/pedrovicente/.virtualenvs/openai-python-uihn/lib/python3.10/site-packages/pandas/__init__.py'>
6.669433787465096e-07 <module 'pandas' from '/Users/pedrovicente/.virtualenvs/openai-python-uihn/lib/python3.10/site-packages/pandas/__init__.py'>
2.919696271419525e-07 <module 'pandas' from '/Users/pedrovicente/.virtualenvs/openai-python-uihn/lib/python3.10/site-packages/pandas/__init__.py'>
```

### OS

Linux

### Python version

python 3.10

### Library version

openai-python v0.27.2

**Comment by pvicente** [comment]
@hallacy Could you kindly ack this and check PR please?

**Comment by RobertCraigie** [comment]
This has been fixed in our upcoming [v1 beta](https://github.com/openai/openai-python/discussions/631)!

We now [lazy import](https://github.com/openai/openai-python/blob/v1/src/openai/_extras/numpy_proxy.py) `pandas` and `numpy` so if you have them installed, they will only actually be imported when accessed.
