### ISSUE TITLE
Audio API Resource is Missing Timeout Handling

### ISSUE THREAD

**Issue by TedTimbrell** [openai/openai-python#528]
### Describe the feature or improvement you're requesting

Audio transcription can be time intensive (and in my case also somewhat time critical). In certain cases the OpenAI API is taking 20+ seconds to process audio and with the currently library we have no way of timing out the call, potentially leaving a worker or thread hanging until resolved ungracefully (such as an overall network response timeout or worker timeout). As is this forces users to either reimplement the call in `requests` to get access to network timeouts or re-implement the timeout logic on top of this method call via threads or subprocesses.

**Comment by logankilpatrick** [comment]
Verified this, checking with the team. The Audio class inherits from APIResource which has the request_timeout option so not sure what is going on here.

**Comment by RobertCraigie** [comment]
This is fixed in our [v1 beta](https://github.com/openai/openai-python/discussions/631) as we've unified to a single `timeout` argument which is passed to the client constructor and can be [configured](https://github.com/openai/openai-python/tree/v1?tab=readme-ov-file#timeouts) per-request using `client.with_options`.

```py
from openai import OpenAI

# Configure the default for all requests:
client = OpenAI(
    # default is 60s
    timeout=20.0,
)

# More granular control:
client = OpenAI(
    timeout=httpx.Timeout(60.0, read=5.0, write=10.0, connect=2.0),
)

# Override per-request:
client.with_options(timeout=5 * 1000).chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": "How can I list all files in a directory using Python?",
        }
    ],
)
```
