### ISSUE TITLE
GPT-4 Model Does Not Exist

### ISSUE THREAD

**Issue by cone387** [openai/openai-python#529]
### Describe the bug

The official says that the ChatGPT4 API has been opened. I have been paying the API with 3.5 before. In order to use the ChatGPT4 model API, I upgraded the Plus, but why I still can't use the API, prompting the GPT-4 Model Does Not Exist

### To Reproduce

import openai
import os
openai.api_key = ""
completion = openai.ChatCompletion.create(
	model="gpt-4",
	messages=[
		{
			"role": "user", 
			"content": "Tell the world abount the ChatGPT API",
		}
	]
)
print(completion.choices[0].message.content)

### OS

windows

### Python version

Python v3.11.4

### Library version

openai-python v0.27.2

**Comment by drewbitt** [comment]
You don't have API access to GPT-4 yet. For some reason, not everyone who paid before got access to GPT-4 despite what the blog post said. This is not related to this library; please close.

**Comment by cone387** [comment]
not yet resolved
