### ISSUE TITLE
A way to determine if a response is "not unknown"

### ISSUE THREAD

**Issue by taewookim** [openai/openai-python#539]
### Describe the feature or improvement you're requesting

Right now, there doesn't seem to be a way of determining if response from chatgpt is vague / not known without checking the response content. There should be some response code that API devs can check to see if there's a way to escalate the situation to a human agent.

https://stackoverflow.com/questions/76685545/chatgpt-a-way-to-determine-if-a-response-is-not-unknown

**Comment by logankilpatrick** [comment]
Cool idea! It does not exist today but will add this to our API feedback and will circle back in the future.
