### ISSUE TITLE
support 3rd party gateway

### ISSUE THREAD

**Issue by aberfitch** [openai/openai-python#541]
### Describe the feature or improvement you're requesting

Ability to route the calls via 3rd party API gateway's such as APIGEE, MuleSoft etc.
Client application doesn't need to store the actual API-key rather it'll be set at the API Gateway.

Right now it seem to support direct calls to OpenAI or Microsoft gateway (limited)

**Comment by rattrayalex** [comment]
See https://github.com/openai/openai-python#configuring-the-http-client for configuring proxies etc. In many cases you can simply pass `base_url=my_url`.
