### ISSUE TITLE
Split out the core library

### ISSUE THREAD

**Issue by xl0** [openai/openai-python#545]
### Describe the feature or improvement you're requesting

Would it be possible to split out the core functionality, essentially, the API wrapper, in a separate `openai-core` library with minimal dependencies? The advantage is precisely that - fewer dependencies and a smaller codebase for 99.9+% of the users.

If the other stuff, like the cli and the fine-tuning code, stays in `openai`, the users will not requires any changes.

**Comment by logankilpatrick** [comment]
Thanks for the suggestion, we will likely have a new OpenAI Python repo in the weeks / months to come so stay tuned!
