### ISSUE TITLE
Issue with populating api configs using environment variables after importing openai

### ISSUE THREAD

**Issue by lumoslnt** [openai/openai-python#557]
### Describe the bug

I'm encountering an issue where I am unable to populate the `api_key`, `api_base`, `api_type`, and `api_version` using environment variables.

The openai package seems to read the `api_key`, `api_base`, `api_type`, and `api_version` from environment variables only at the moment it is imported. If these api configs are specified after the openai package is imported, they are not recognized.

The code is in [here](https://github.com/openai/openai-python/blob/b82a3f7e4c462a8a10fa445193301a3cefef9a4a/openai/__init__.py#L42-L54).

### To Reproduce

Due to python's caching mechanism, to reproduce this issue, the openai package must be reloaded.

### Code snippets

```Python
import openai
import os

os.environ["OPENAI_API_KEY"] = "<api_key>"
os.environ["OPENAI_API_BASE"] = "<api_base>"
os.environ["OPENAI_API_TYPE"] = "<api_type>"
os.environ["OPENAI_API_VERSION"] = "<api_version>"

openai.Completion.create(prompt="Hello", engine="text-davinci-003", max_tokens=5)
```

### OS

Windows 11

### Python version

Python v3.8.16

### Library version

openai-python v0.27.8

**Comment by cometa-haley** [comment]
I faced the same Issue, at some point populating secrets from env seemed to stop working :(

**Comment by RobertCraigie** [comment]
This issue should be fixed in our [completely refactored v1 beta](https://github.com/openai/openai-python/discussions/631)! Our new module-level client handles this case as expected.

While we still provide a module-level client, we highly recommend using the client instantiation based API which avoids this problem entirely.
```py
from openai import OpenAI

client = OpenAI(
  api_key=os.environ['OPENAI_API_KEY'],  # this is also the default, it can be omitted
)
```

**Comment by cometa-haley** [comment]
Nice, thank you - a client approach is exactly what I have been looking for all these months <3
