### ISSUE TITLE
Hope  support  choose if   SSL verify on ChatCompletion.create 

### ISSUE THREAD

**Issue by lishukan** [openai/openai-python#561]
### Describe the feature or improvement you're requesting

Background:
 ChatCompletion.create does not support  the param  "verify"  .

When you meet some certify problem ,and you dont want to  fix SSL problem at first , you maybe want to  solve this accroding to extram param. Just like  the "verify" in  requests.request(xxxxx,verify=False).
![image](https://github.com/openai/openai-python/assets/23066239/a061e1c6-4c31-46a1-b0bb-c1e47ba23e99)

Especially the underlying layer of ChatConpletion.create  itself is also call requests.request method 。

But  unfortunately ，ChatCompletion.create does not support  this param   "verify"  ,and it has no provide any else param to solve this problem。

Undoubtedly, it is best that all requests should pass SSL validation. But in many people's environments, solving certificate issues requires a lot of extra effort. This is especially unfriendly to beginners.

Request:
So I suggest adding the parameter 'verify'  on  ChatCompletion.create, then we can choose if verify SSL by ourself。
And  I‘ll  make PR for this issue  later.
Hope you can also agree with my viewpoint

**Comment by q-x-iao** [comment]
You can already do this by by setting `openai.requestssession` to a custom session factory:

```python
import openai
import requests
def make_session():
  s = requests.Session()
  s.verify = ...
  return s
openai.requestssession = make_session
```

If you use asynchronous requests, you can set `openai.aiosession` instead.

**Comment by lishukan** [comment]
@q-x-iao  thanks your advise
