### ISSUE TITLE
Consider using a class constructor for configuration, not module globals

### ISSUE THREAD

**Issue by pamelafox** [openai/openai-python#563]
### Describe the feature or improvement you're requesting

This is the current way to configure the credentials for the openai library:

```
    openai.api_base = f"https://{AZURE_OPENAI_SERVICE}.openai.azure.com"
    openai.api_version = "2023-05-15"
    openai.api_type = "azure_ad"
    openai_token = await azure_credential.get_token(
        "https://cognitiveservices.azure.com/.default"
    )
    openai.api_key = openai_token.token
```

(Or simpler than that, if using keys instead of Azure credentials)

Here's how Python handles it, as far as I understand:

* When a file imports `openai`, Python stores it in the sysmodules dict
* Then when that file sets attributes of the module, Python updates the attributes of the module that's stored in the sysmodules dict
* When another file later imports openai, Python finds the module in the sysmodules dict and that hopefully has the correct attributes set 

This approach of configuring via module-level globals seems fairly brittle to me, since it's dependent on how Python caches modules, what order things are imported, and how things are imported. It also seems likely to be incompatible with multiprocessing or asynchronous workers in a large application.

I recommend instead something like what the NodeJS SDK uses, a class that can be instantiated with the configuration:

https://github.com/openai/openai-node

That also makes it possible to use different credentials in different parts of a codebase, by passing the credential'd object around. 

I realize that would be a significantly large change, but I think it would make for much more robust code overall.

**Comment by mpenndev** [comment]
We encountered this issue as we run async against multiple GPT endpoints.

As we scaled up the global configuration would sometimes get out of sync between the request being sent and the next request on a different configuration.

This behaviour should definitely be documented.

We did find a solution in that the global variables don't need to be set if you pass them into the request method, in our case `openai.ChatCompletion.acreate`.

By providing the `api_base`, `api_key` & `api_version` as parameters to `acreate` we were able to ensure the correct configuration values were used for each request.

**Comment by sodarfish** [comment]
@mpenndev  that's very helpful. thank you!

**Comment by RobertCraigie** [comment]
Great news – we've moved to a class instance based API in our new, fully rewritten [v1.0.0 library, now in beta](https://github.com/openai/openai-python/discussions/631):

```py
from openai import OpenAI

client = OpenAI(
  api_key=os.environ['OPENAI_API_KEY'],  # this is also the default, it can be omitted
)

client.chat.completions.create(...)
```

Please give it a try, and share feedback (big or small) in the linked discussion! (Not in this thread).
