### ISSUE TITLE
Return value of ChatGPT API

### ISSUE THREAD

**Issue by cousintiz** [openai/openai-python#564]
### Describe the feature or improvement you're requesting

I think that it would be nice for the API for any model before GPT-4, returns any type of value or a specific answer when the model is unable to answer the question (like for example; about events after 2021, and some other stuff it doesn’t know) because in this way devs could have more control about how to handle this cases, like using different resources for the wanted information.

**Comment by logankilpatrick** [comment]
Cool idea! Not possible today with our setup, but worth thinking about. Ideally the best solution is to just make the model have more up to date info. Closing this for now but added a label to circle back.

**Comment by cousintiz** [comment]
> Cool idea! Not possible today with our setup, but worth thinking about. Ideally the best solution is to just make the model have more up to date info. Closing this for now but added a label to circle back.

thanks. i agree with you, or just leave it as it is now, but also return some confidence threshold, depending on the answer given by the model. to any dev here, it can be cool to this in a post processing
