### ISSUE TITLE
Documentation for `Embedding.create()` is wrong when using Azure as backend

### ISSUE THREAD

**Issue by olsgaard** [openai/openai-python#565]
### Describe the bug

The `Embedding.create()` method [1] says that valid parameters are listed on https://platform.openai.com/docs/api-reference/embeddings, where available parameters are `model`, `input` and `user`.

However, when creating embeddings using Azure as OpenAI as backend, `engine` or `deployment_id` are required parameters and `model` is ignored. 

I'm not sure what is a good solution. Maybe the documentation should be changed to 

```
Creates a new embedding for the provided input and parameters.

See https://platform.openai.com/docs/api-reference/embeddings for a list
of valid parameters for calling OpenAI API

or https://learn.microsoft.com/en-gb/azure/ai-services/openai/reference#embeddings when using Azure OpenAI API.
```

[1] https://github.com/openai/openai-python/blob/7610c5adfaebe3ffdb9927a551a741a3fab1b62e/openai/api_resources/embedding.py#L15

### To Reproduce

```python
import openai
openai.api_type = "azure"
openai.api_key="ABC123..."
openai.Embedding.create(model='mymodel', input='hello world')
```
```python
File ~/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py:83, in EngineAPIResource.__prepare_create_request(cls, api_key, api_base, api_type, api_version, organization, **params)
     81 if typed_api_type in (util.ApiType.AZURE, util.ApiType.AZURE_AD):
     82     if deployment_id is None and engine is None:
---> 83         raise error.InvalidRequestError(
     84             "Must provide an 'engine' or 'deployment_id' parameter to create a %s"
     85             % cls,
     86             "engine",
     87         )
     88 else:
     89     if model is None and engine is None:

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>
```

### OS

Ubuntu 20.04 LTS

### Python version

Python 3.11

### Library version

openai-python 0.27.8

**Comment by logankilpatrick** [comment]
Hey @olsgaard that is because the OpenAI docs are for the OpenAI API, not the Azure API. Please refer to the Azure API docs for an up to date look at what they expect.

**Comment by innat-asj** [comment]
Instead of using model, we need to use deployment_id

```python
openai.Embedding.create(deployment_id='deploy_id', input='hello world')
```
