### ISSUE TITLE
Must provide an 'engine' or 'deployment_id' parameter

### ISSUE THREAD

**Issue by gabrielsusai** [openai/openai-python#569]
### Describe the bug

I am running the github code in local using VSCode start.cmd file. All the necessary packages were installed and the website is running now. When I prompt a quesestoin, I got the below error
Must provide an 'engine' or 'deployment_id' parameter

**Error**
Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

### To Reproduce

Clone the github report and changed few environment variables as given in the instructions. 

### OS

Windows

### Python version

Python v3.11.4

### Library version

openai 0.27.7

**Comment by kristapratico** [comment]
@gabrielsusai are you using OpenAI or Azure OpenAI? There is slightly different config between the two services as described here: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints

**Comment by gabrielsusai** [comment]
I am using Aure OpenAI and followed the instructions in GitHub to run locally.

**Comment by kristapratico** [comment]
Can you share the code sample you are using?

**Comment by prasann** [comment]
I had the similar error message. This section of the document helped me: https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints#keyword-argument-for-model

For Azure OpenAI, we shouldn't be using the `model` keyword inside `ChatCompletion.create`. 

instead `deployment_id={deployment_name}`  or `engine={deployment_name}` should be used.

**Comment by gabrielsusai** [comment]
The code in this project does use engine (see below). I was editing the .env.sample file which was the cause of the issue ( It will be better to update the documentation based on the instruction given [here](https://github.com/microsoft/sample-app-aoai-chatGPT/issues/154#issuecomment-1673870759))

 response = openai.ChatCompletion.create(
        engine=AZURE_OPENAI_MODEL,
        messages = messages,
        temperature=float(AZURE_OPENAI_TEMPERATURE),
        max_tokens=int(AZURE_OPENAI_MAX_TOKENS),
        top_p=float(AZURE_OPENAI_TOP_P),
        stop=AZURE_OPENAI_STOP_SEQUENCE.split("|") if AZURE_OPENAI_STOP_SEQUENCE else None,
        stream=SHOULD_STREAM
    )

Now I am getting a new error 

Error
Error communicating with OpenAI: HTTPSConnectionPool(host='bw-azureai.openai.azure.com', port=443): Max retries exceeded with url: //openai/deployments/GPT35Turbo/chat/completions?api-version=2023-03-15-preview (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))

**Comment by Alisultani1** [comment]
@prasann
