### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by wanyang6-tal** [openai/openai-python#570]
### Describe the bug

When I use FastAPI for forwarding and set stream=True, for example: async for res in await openai.ChatCompletion.acreate(**kwargs), when this request is terminated before it completes, an exception occurs as follows: [asyncio] [ERROR]: Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x7f0ca458c490>.

### To Reproduce

    1. Write a FastAPI request using the acreate method to return data in streaming format.
    2. Use a packet sending tool to make a request to the written API, terminate the request while receiving data.
    3. Wait for a moment, and the exception will be displayed in the terminal.

### OS

Linux 

### Python version

Python 3.11.4

### Library version

openai 0.27.8
```[tasklist]
### Tasks
```

**Comment by perryHV** [comment]
Hii @wanyang6-tal  I want to work on this issue please assign me.

**Comment by wanyang6-tal** [comment]
> Hii @wanyang6-tal I want to work on this issue please assign me.

sorry, I don't have permission
