### ISSUE TITLE
FineTuningJob does not support suffix >18 characters

### ISSUE THREAD

**Issue by majamil16** [openai/openai-python#585]
### Describe the bug

Hi, while updating migrating my FineTuning job from openai.FineTune => openai.FineTuningJob to support the new babbage-002 model I ran into the following issue:

```
InvalidRequestError                       Traceback (most recent call last)

4 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    763         stream_error = stream and "error" in resp.data
    764         if stream_error or not 200 <= rcode < 300:
--> 765             raise self.handle_error_response(
    766                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    767             )

InvalidRequestError: invalid suffix: *******************************, ensure this value has at most 18 characters
```

the docs say the suffix field supports up to [40 characters](https://platform.openai.com/docs/api-reference/fine-tuning/create#suffix). we used the same suffix with the previous endpoint with no issues. 

Wondering if this is an error in the docs, or if the new API does not support a custom suffix parameter > 18 characters?

### To Reproduce

invoke openai.FineTuningJob.create as follows
```
response = openai.FineTuningJob.create(training_file=response['id'], model=model, n_epochs=n_epochs, suffix="suffix-that-is-31-characters")
```

### OS

macOS

### Python version

Python 3.10.12

### Library version

0.27.9

**Comment by logankilpatrick** [comment]
Hey! The limit is actually 18, thanks for flagging, I am updating the docs, should be all set soon!
