### ISSUE TITLE
Add context length attribute to the model objects returned on the list and retrieve models endpoint.

### ISSUE THREAD

**Issue by microsoftbuild** [openai/openai-python#587]
### Describe the feature or improvement you're requesting

**Description:**

At present, the `openai.Model.list()` function provides a list of model objects, each characterized by four attributes, as exemplified below:

```json
{
  "id": "davinci",
  "object": "model",
  "created": 1686935002,
  "owned_by": "openai"
}
```

I would like to propose an augmentation to this functionality by introducing an additional attribute that conveys crucial information—the maximum context length or limit of each model.

**Request:**

I kindly request the incorporation of a new attribute to the model object that signifies the respective model's maximum context length. This enhancement would yield several benefits:

1. **Simplified Code Implementation:** By exposing the maximum context length directly through the model object, users can seamlessly adapt their code to automatically respect the context limit. This feature would empower users to fine-tune their applications to the specific capabilities of each model effortlessly, without having to manually store context limits individually for every model.

2. **Enhanced Adaptability:** The suggested attribute would enable OpenAI to dynamically adjust a model's context length, if needed, without disrupting users' code. This adaptability reflects a proactive approach towards model improvements while safeguarding the stability of user implementations.

**Proposed Attribute:**

I propose the inclusion of the following attribute in the model object:

```json
{
  "context_limit": {
    "type": "integer",
    "description": "The maximum context length that the model can effectively handle."
  },
}
```

The "context_limit" attribute, when integrated into the model object, would be of type "integer." It will succinctly convey the maximum number of tokens can be processed by the model. This clear and concise addition would provide developers with essential information upfront, contributing to an improved development experience.

### Additional context

There's been demand for this attribute on the OpenAI dev community as well. Here are the links for your reference:
- https://community.openai.com/t/request-query-for-a-models-max-tokens/161891
- https://community.openai.com/t/can-i-get-the-max-tokens-information-from-openai-api/143549

**Comment by rattrayalex** [comment]
Thanks for the feature request! I've bumped it with the team. 

The dev community is the best place for these; this repo is just for the Python library.

**Comment by caishuo-C** [comment]
After the version update, `openai.Model.list()` is invalid, now how do I see which models the API can call?

**Comment by microsoftbuild** [comment]
Here's API reference showing you how to do that @caishuo-C 
https://platform.openai.com/docs/api-reference/models/list
