### ISSUE TITLE
How do you set the number of epochs for FineTune.create on ChatGPT?

### ISSUE THREAD

**Issue by alexorona** [openai/openai-python#589]
### Describe the bug

I can fine-tune `gpt-3.5-turbo` just fine, but it looks like there's no way to change the number of epochs to something over than 10, even though the Guides recommend indicate that you can (`"If the model becomes less diverse than expected decrease the number by 1 or 2 epochs"`). It seems to be over training quite a bit. Past experience is that most LLMs just need 1-2 epochs. 

There doesn't seem to be an actual argument that can be passed to `FineTune.create` to change the number of training epochs. I've fine-tuned `davinic-003` before with the parameter `n_epochs`, but it doesn't seem to work with ChatGPT fine-tuning. There's no reference in `help(FineTune.create)` to epochs and passing `epochs`,  `n_epochs` to `FineTune.create` yields `extra fields not permitted`.

Running it through `openai api fine_tunes.create` also doesn't permit specification of epochs. Am I missing something?

### To Reproduce

1. Format and upload a dataset
2. Create a training job using the Python SDK with `FineTuningJob.create` passing an argument to change the number of epochs

### OS

Ubuntu 20.04

### Python version

Python 3.7.5

### Library version

openai-python 0.27.9

**Comment by microsoftbuild** [comment]
@alexorona In the updated API reference, you can see that the [n_epochs](https://platform.openai.com/docs/api-reference/fine-tuning/create#hyperparameters-n_epochs) hyperparam exists.

The reason that it's not shown in most examples is because it defaults to `auto`.

However, you should be simply able to specify a value for `n_epochs` in the `openai.FineTuningJob.create` function.

**Comment by wramalho** [comment]
Trying to use `openai.FineTuningJob.create` with `n_epochs` set to any value returns `InvalidRequestError: invalid n_epochs: <value>, extra fields not permitted`

E.g. Running the following code without n_epochs works:

`n_epochs = 5
model = "babbage-002"
response = openai.FineTuningJob.create(training_file=training_file_id, model=model, validation_file=validation_file_id, suffix="babbage-test", n_epochs=n_epochs)

job_id = response["id"]

print("Job ID:", response["id"])
print("Status:", response["status"])`

**Comment by wramalho** [comment]
Solution:

The newer `FineTuningJob.create` unliked the previous `FineTune.create` must be specified as:

openai.FineTuningJob.create([...], hyperparameters={"n_epochs":value, })

**Comment by microsoftbuild** [comment]
Glad that it's solved now. @logankilpatrick please update this example in the docs/API reference.

**Comment by eunos-1128** [comment]
@wramalho 

`openai.FineTuningJob.create([...], hyperparameters={"n_epochs":value, })`

This didn't work for me.

**Comment by eunos-1128** [comment]
@wramalho 

It worked for me. Thanks!

**Comment by logankilpatrick** [comment]
Sorry for the delay, deploying a fix now, should be live: https://platform.openai.com/docs/api-reference/fine-tuning/create in 2 or 3 minutes!

**Comment by alexorona** [comment]
Ty!
