### ISSUE TITLE
Engine Not found Error, when trying to get embeddings  

### ISSUE THREAD

**Issue by pratik98** [openai/openai-python#59]
I am trying to get embeddings using this example here -> [Get_embeddings](https://github.com/openai/openai-python/blob/main/examples/embeddings/Get_embeddings.ipynb) 
getting error at below line,
```
df['babbage_similarity'] = df.combined.apply(lambda x: get_embedding(x, engine='babbage-similarity'))
```

```
InvalidRequestError: Engine not found

The above exception was the direct cause of the following exception:

RetryError                                Traceback (most recent call last)
<ipython-input-14-7b798ddc3611> in <module>
      2 
      3 # This will take just under 10 minutes
----> 4 df['babbage_similarity'] = df.combined.apply(lambda x: get_embedding(x, engine='babbage-similarity'))
```

**Comment by hallacy** [comment]
Hello!  We're busy making some changes to the endpoint and paused new user access to the endpoints for the time being.  You can read more about it [here](https://community.openai.com/t/introducing-embeddings/13319/35?u=hallacy).  

Or did you previously have access and now this doesn't work?

**Comment by pratik98** [comment]
okay. No, this is the first time i was trying. Thank You.
