### ISSUE TITLE
Function call: return a "content" containing function_call instead of a "function_call"

### ISSUE THREAD

**Issue by Chiangkim** [openai/openai-python#594]
### Describe the bug

Hello,

While using function call, we met a bug that occurs occasionally. Even in GPT4.

Instead of returning a json with key "function_call", which it should be, GPT returns a json with key "content". This "content" contains "function_call" as a string.

case 1:

<img width="970" alt="MicrosoftTeams-image" src="https://github.com/openai/openai-python/assets/13915357/1e1f7506-13ae-41d6-881f-73d2f9fbdb2a">

case 2:

![Snipaste_2023-08-30_16-35-49](https://github.com/openai/openai-python/assets/13915357/4666900e-53a7-4b42-8c4d-0513164b9602)

GPT_MODEL = "gpt-4"
API_VERSION = "2023-07-01-preview"
openai.api_type = "azure"

### To Reproduce

It occurs occasionally. We cannot guarantee it can be reproduced.

### OS

Linux

### Python version

3.8.10

### Library version

0.27.8

**Comment by dereklegenzoff** [comment]
Hi @Chiangkim - the sample code we have in the documentation on [Function Calling in Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling) originally showed an incorrect pattern for appending the function calls back into the array of input messages where we were adding it into the content instead of the correct fields. I'm wondering if you might be using that older code and if it could be causing the problem.

Here is the updated code for adding the response to the array of messages:
```python
    # Add the assistant response and function response to the messages
    messages.append( # adding assistant response to messages
        {
            "role": response_message["role"],
            "function_call": {
                "name": function_name,
                "arguments": response_message["function_call"]["arguments"],
            },
            "content": None
        }
    )
```

**Comment by Chiangkim** [comment]
Hi Derek @dereklegenzoff ,

Thanks for your reply.

Actually as you can see from the 1st picture, it's a direct response from 
`response = openai.ChatCompletion.create( engine="gpt-4", messages=messages, functions=functions, function_call="auto", )

assitant_message = response["choices"][0]["message"]`

Meanwhile we are using up-to-date version of openai-python library.

**Comment by microsoftbuild** [comment]
Hi @Chiangkim 

Can you share the part of code that deals with passing the function definition to the chat completion model?

**Comment by rattrayalex** [comment]
Please let us know if this problem recurs.

**Comment by Chiangkim** [comment]
> Hi @Chiangkim
> 
> Can you share the part of code that deals with passing the function definition to the chat completion model?


hello, it happens occasionally, but in very few occasions. It's hard to reproduce this issue. Hopefully gpt4-turbo has solved this issue.

This is the last time I met this issue:
`
{
    "id": "37",
    "object": "chat.completion",
    "created": 1698807892,
    "model": "gpt-4",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "\{\"function\": \"function_name\", \"parameters\": {\"productName\": \"*******\", \"customerName\": \"*******\", \"startDate\": \"2023-10-01\", \"endDate\": \"2023-10-31\"}}",
                "function_call": null
            }
        }
    ],
    "usage": {
        "prompt_tokens": 1554,
        "completion_tokens": 59,
        "total_tokens": 1613
    }
}
`
