### ISSUE TITLE
Fine-tuning documentation is incorrect

### ISSUE THREAD

**Issue by lucas-aixplain** [openai/openai-python#596]
### Describe the bug

In [fine-tuning documentation](https://github.com/openai/openai-python#fine-tuning), the `openai.Model.delete` method does not receive the same input as the other listed methods. While, for example, `openai.FineTuningJob.retrieve` receives the fine-tune job id, `openai.Model.delete` should receive the name of the fine-tuned model. The documentation induces us to think both methods have the same parameters.

### To Reproduce

N/A

### OS

N/A

### Python version

N/A

### Library version

openai-python v0.27.10

**Comment by logankilpatrick** [comment]
Will be fixed soon! Thanks for flagging.
