### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by digital-mine** [openai/openai-python#6]
I'm very excited with the idea of using this technology.

I've applied and fulfilled the form to get the API key.

Just need to know how long it will take to actually get one.

Thanks

**Comment by IgorGanapolsky** [comment]
I'd like to use this Python library.  However, it tells me that I need an API key.  How do I get it?

**Comment by hallacy** [comment]
You can join the waitlist by filling out the form at https://beta.openai.com/!
