### ISSUE TITLE
n=X Parameter counts as scalar for total token count towards rate limit

### ISSUE THREAD

**Issue by MrMatch246** [openai/openai-python#605]
### Describe the bug

It appears as if using n>1 works as a multiplier on the total token number of prompt and longest response when the TPM rate is calculated. 

I had 5-7 requests with 1k total tokens each and n=5 and got a rate limit error saying my TPM was 76k

### To Reproduce

set n = 5  and create multiple requests having larger prompts and smaller responses within short time without violating the size(prompt)+max_tokens*n limit,
it will result in a rate limit error anyway.
e.g. Summarize this page in a sentence

### OS

-

### Python version

-

### Library version

-

**Comment by rattrayalex** [comment]
I can understand how that would be surprising; I'll see if we can update the documentation around this.
