### ISSUE TITLE
Why is Azure openai api throwing an exception when attempting to handle a quota throttling error?

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [openai/openai-python#607]
### Describe the bug

In the example below, the Azure openai quota is exceeded and generates an expected exception. However, while handling that exception, the openai api generates another exception. It looks as though the "error_data" variable is a string instead of a dictionary. The "error_data" string contains "Quota has been exceeded" instead of a dictionary like {"message": "Quota has been exceeded"}

Running miniconda and openai 0.27.4

Ref: [Why is Azure openai api throwing an exception when attempting to handle a quota throttling error?](https://learn.microsoft.com/en-us/answers/questions/1362313/why-is-azure-openai-api-throwing-an-exception-when)
Can you please help me.

### To Reproduce

In the example below, the Azure openai quota is exceeded and generates an expected exception. However, while handling that exception, the openai api generates another exception. It looks as though the "error_data" variable is a string instead of a dictionary. The "error_data" string contains "Quota has been exceeded" instead of a dictionary like {"message": "Quota has been exceeded"}

Running miniconda and openai 0.27.4

```
import os
import openai

openai.api_type = "azure"
openai.api_base = os.getenv("AZURE_OPENAI_ENDPOINT")
openai.api_version = "2023-05-15"
openai.api_key = os.getenv("AZURE_OPENAI_KEY")

# The intent here is to make 2 calls in rapid succession to generate
# an error that we have exceeded the quota.
response = openai.Completion.create(
engine="gpt-35-turbo"
messages=[
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Tell me a story about an elephant?"}
]
)
# Somewhat brittle test that may need to be done a few times to exceed
# the quota
response = openai.Completion.create(
engine="gpt-35-turbo"
messages=[
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Tell me a story about a fox?"}
]
)

AttributeError                            Traceback (most recent call last)
.
.
.
File ~\Projects\chatGPT\env_conda\lib\site-packages\openai\api_requestor.py:346, in APIRequestor.handle_error_response(self, rbody, rcode, resp, rheaders, stream_error)
       341 if "internal_message" in error_data:
       342     error_data["message"] += "\n\n" + error_data["internal_message"]
       344 util.log_info(
       345     "OpenAI API error received",
-->    346     error_code=error_data.get("code"),
       347     error_type=error_data.get("type"),
       348     error_message=error_data.get("message"),
       349     error_param=error_data.get("param"),
       350     stream_error=stream_error,
       351 )
       353 # Rate limits were previously coded as 400's with code 'rate_limit'
       354 if rcode == 429:
AttributeError: 'str' object has no attribute 'get'
```
Ref: [Why is Azure openai api throwing an exception when attempting to handle a quota throttling error?](https://learn.microsoft.com/en-us/answers/questions/1362313/why-is-azure-openai-api-throwing-an-exception-when)
Can you please help me.

### Code snippets

```Python
import os
import openai

openai.api_type = "azure"
openai.api_base = os.getenv("AZURE_OPENAI_ENDPOINT")
openai.api_version = "2023-05-15"
openai.api_key = os.getenv("AZURE_OPENAI_KEY")

# The intent here is to make 2 calls in rapid succession to generate
# an error that we have exceeded the quota.
response = openai.Completion.create(
engine="gpt-35-turbo"
messages=[
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Tell me a story about an elephant?"}
]
)
# Somewhat brittle test that may need to be done a few times to exceed
# the quota
response = openai.Completion.create(
engine="gpt-35-turbo"
messages=[
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "Tell me a story about a fox?"}
]
)
```

### OS

windows

### Python version

Python v3.7.1

### Library version

v0.27.4

**Comment by Evonne-12** [comment]
I also encounter this problem. Do you solve it?

**Comment by SaurabhSharma-MSFT** [comment]
@hallacy @logankilpatrick Do you have any suggestions on this issue ?

**Comment by odinhorizontal** [comment]
Same problem!
maybe change the "engine" in line 12 to "model" can work?

**Comment by lucasgadams** [comment]
I am getting this same error using the OpenAI (not azure) embeddings endpoint. I think there is an issue.

**Comment by rattrayalex** [comment]
This should be fixed in https://github.com/openai/openai-python/releases/tag/v1.2.2
