### ISSUE TITLE
Not retrying on error

### ISSUE THREAD

**Issue by gusvd** [openai/openai-python#608]
### Describe the bug

I'm running a simple LLMChain with ChatOpenAI and getting 'Error [TimeoutError]: Request timed out' errors very often.
But the main problem is that LangChain doesn't seem to be retrying to run the chain after the error.

At the very end of the error message I get:

```
...
  attemptNumber: 1,
  retriesLeft: 6
}
```

Here's the full error message:

```
Error in handler LangChainTracer, handleChainError: TimeoutError: The operation was aborted due to timeout
file:///Users/[redacted]/node_modules/langchain/dist/util/openai.js:6
        error = new Error(e.message);
                ^

Error [TimeoutError]: Request timed out.
    at wrapOpenAIClientError (file:///Users/[redacted]/node_modules/langchain/dist/util/openai.js:6:17)
    at file:///Users/[redacted]/node_modules/langchain/dist/chat_models/openai.js:517:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/[redacted]/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 1,
  retriesLeft: 6
```

### To Reproduce

1. Make enough sub-sequential calls to ChatOpenAI using the LLMChain.

In my case I'm looping over a 2000 array, using each one of the elements to populate the prompt template and calling the chain. 

### Code snippets

```Python
// OPEN AI SETUP
const llm = new ChatOpenAI({
  openAIApiKey: process.env.OPENAI_API_KEY,
  modelName: "gpt-3.5-turbo",
  max_tokens: 1800,
  // frequency_penalty: 0.1,
  temperature: 0.1,
  timeout: 30000,
  maxRetries: 5,
});

//LLM CHAIN
const chain = new LLMChain({
  llm: llm,
  prompt: promptTemplate,
});

//LOOP OVER THE DATASET AND CALL LLM
for (const [index, name] of names.entries()) {
  const result = await chain.call({
    name: name.firstName,
  });

...

 console.log(result.text);
}
```

### OS

MacOS

### Python version

Node v20.5.1

### Library version

openai 3.3.0

**Comment by ShantanuNair** [comment]
@gusvd I may be onto something here, I did a bunch of investigation, but can you first confirm if you leave it running for your timeout duration, that langchain does indeed retry but only after the timeout you set? There's an issue with async acreate calls where it timeout only after the complete timeout seconds. This means if you want possibly long generations, you have to suffer the issue that, when a retry is needed, it will only happen after the timeout maxes out :/

**Comment by wcummings** [comment]
I seem to be having the same issue, at least I see the error trapped in my catch block says "attempt: 1", which leads me to believe the retries aren't happening.

**Comment by rattrayalex** [comment]
Great news, this is ready in a [beta of our upcoming v1.0.0](https://github.com/openai/openai-python/discussions/631)! Please try it out and let us know what you think.

(_Note, OP seems to have intended to post on the openai-node repo; that library also supports auto-retry now_).

**Comment by gusvd** [comment]
Sorry I took so long to reply and I'm glad to see you were able to implement a solution. I'll answer your questions for future reference.

> but can you first confirm if you leave it running for your timeout duration, that langchain does indeed retry but only after the timeout you set? 

Langchain doesn't retry, ever. Id does respect the {  timeout: 30000 } parameter. So in this case it will timeout after 30seconds instead of the default 600 seconds. But it won't retry, ever.
