### ISSUE TITLE
Azure OpenAI KeyError on 500

### ISSUE THREAD

**Issue by KyleKing** [openai/openai-python#609]
### Describe the bug

Currently, 500 errors from Azure OpenAI do not return a dictionary with key `"error"`. This leads to a generic APIError/KeyError when it could attempt to return the message from the instead, which is more useful for end users

### To Reproduce

Any request to Azure OpenAI that fails because of a non-specific Server Error

Example response:

```json
{
    "activityId": "123-123-123",
    "message": "Internal server error",
    "statusCode": 500
}
```

### OS

Linux

### Python version

3.11.3

### Library version

v0.28.0

**Comment by rattrayalex** [comment]
The latest version of this library should handle this better. 

cc @kristapratico @RobertCraigie
