### ISSUE TITLE
openai.FineTuningJob.list_events doesn't support api_base

### ISSUE THREAD

**Issue by 00arthur00** [openai/openai-python#615]
### Describe the bug

when query new fine tune events with openai:
openai.FineTuningJob.list_events(id="ft-abc123", limit=10,api_key="xxxx",api_base="xxxx")

the http request doesn't go to api_base domain, instead go to the offical api site.

### To Reproduce

1. set up a nginx proxy for openai official api
2. query fine tune job event with openai.FineTuningJob.list_events(id="ft-abc123", limit=10,api_key="xxxx",api_base="xxxx")
3. http requests go to offical api site instead the nginx proxy.

### Code snippets

```Python
openai.FineTuningJob.list_events(id="ft-abc123", limit=10,api_key="xxxx",api_base="xxxx")
```

### OS

linux

### Python version

python 3.10

### Library version

openai-python v0.28.0

**Comment by 00arthur00** [comment]
related pr: https://github.com/openai/openai-python/pull/612

**Comment by RobertCraigie** [comment]
Looks like the corresponding PR was merged!
