### ISSUE TITLE
Announcing An OpenAI Microservice Quickstart for AWS

### ISSUE THREAD

**Issue by lpm0073** [openai/openai-python#617]
### Describe the feature or improvement you're requesting

Just a heads up that I've released v0.1.0 of [https://github.com/FullStackWithLawrence/aws-openai](https://github.com/FullStackWithLawrence/aws-openai), a REST API implementing each of the [30 example applications](https://platform.openai.com/examples) from the official [OpenAI API Documentation](https://platform.openai.com/docs/api-reference/making-requests?lang=python) using a modularized Terraform approach. Implemented as a serverless microservice using AWS [API Gateway](https://aws.amazon.com/api-gateway/), [Lambda](https://aws.amazon.com/lambda/) and the [OpenAI Python Library](https://pypi.org/project/openai/). Leverages OpenAI's suite of AI models, including [GPT-3.5](https://platform.openai.com/docs/models/gpt-3-5), [GPT-4](https://platform.openai.com/docs/models/gpt-4), [DALL·E](https://platform.openai.com/docs/models/dall-e), [Whisper](https://platform.openai.com/docs/models/whisper), [Embeddings](https://platform.openai.com/docs/models/embeddings), and [Moderation](https://platform.openai.com/docs/models/moderation).

### Additional context

This is a non-commercial community-oriented project. Contributors are welcome. Next steps: add some of the "cookbook" ideas.

**Comment by ShantanuNair** [comment]
@lpm0073 Can it handle long running chains? I moved away from lambda because of the 15 minute limit, but otherwise it is a great experience.
