### ISSUE TITLE
Make `openai.proxy`  configurable for individual request.

### ISSUE THREAD

**Issue by elonzh** [openai/openai-python#620]
### Describe the feature or improvement you're requesting

Currently `openai.proxy` is a global  variable for every OpenAI request, but we have multiple  deployments with different settings like `api_type`, `api_base` etc. 

Everything is configurable now except `proxy`. 😢

**Comment by RobertCraigie** [comment]
This is fixed in our [upcoming v1 beta](https://github.com/openai/openai-python/discussions/631) as you can configure the proxy on a per request basis by instantiating a new client with a different proxy or using the `.with_options` method!

```py
import httpx
from openai import OpenAI

client = OpenAI(
    http_client=httpx.Client(
        proxies="http://my.test.proxy.example.com/",
    ),
)

# or per-request
with httpx.Client(proxies="http://my.other.proxy.example.com/") as http_client:
  client.with_options(http_client=http_client).chat.completions.create(...)
```
