### ISSUE TITLE
please add OPENAI_API_BASE to documentation

### ISSUE THREAD

**Issue by jmikedupont2** [openai/openai-python#624]
### Describe the feature or improvement you're requesting

please add OPENAI_API_BASE "https://api.openai.com/v1 to the readme

**Comment by THEGAMECHANGER416** [comment]
I would like to work on this issue

**Comment by rattrayalex** [comment]
That environment variable is no longer available, but support for the `OPENAI_BASE_URL` env var will be added soon, along with docs in the README.

cc @RobertCraigie

**Comment by rattrayalex** [comment]
This is now supported with the `OPENAI_BASE_URL` environment variable.
