### ISSUE TITLE
Support text and image pair query?

### ISSUE THREAD

**Issue by lucasjinreal** [openai/openai-python#627]
### Describe the feature or improvement you're requesting

Since the new gpt4v avaible on mobile phones, will be available on python as well?

### Additional context

We really need text and image pairs query nowadays

**Comment by cesarandreslopez** [comment]
Use case would be generate descriptions of images, for instance.

I agree this would be very useful.

**Comment by alex-wenner** [comment]
Any update on this? Would it be possible to leverage something like `extra_query` https://github.com/openai/openai-python/blob/3355f033164ac8521076458235210ccca7945adb/src/openai/resources/chat/completions.py#L60C9-L60C20 seen here?

In reference to V1

**Comment by RobertCraigie** [comment]
The SDK has been updated to include the functionality announced today during the DevDay keynote.
