### ISSUE TITLE
No SSL certificate exception not handled

### ISSUE THREAD

**Issue by maximerdy1** [openai/openai-python#628]
### Describe the bug

Hey guys, first time I'm reporting a bug so I hope I'm doing it the right way :)

Yesterday, I tried to use the openai-python library in async, just as written in the documentation (see code below)

`completion = await openai.ChatCompletion.acreate(
        model="gpt-4", messages=test_messages
    )`

I was already using the sync method (and it worked) and wanted to do it in async, but it didn't work and the exception was absolutely not clear. It just said : Error communicating with OpenAI

I didn't find anything useful, neither on Google nor with chatGPT, so after like 2 hours trying to see if I missed a comma, I decided to give up and do it with aiohttp, so without the openai-python library, and doing this gave me a ClientConnectorCertificateError that told me that I actually didn't install the ssl certificates. 

Therefore I installed those certificates by running this command in my terminal: /Applications/Python 3.11/Install Certificates.command

After doing so, I tried the acreate method again and it finally worked! I'm therefore suggesting that you try to improve the exceptions handling in that case, because it was really unclear if that was caused by my api key, my internet connection, a mistake in my code or something else, and I'm sure other people might have the same issue :)

### To Reproduce

1. Make sure you don't have the ssl certificates installed in Python (not sure how to do so :/)
2. Just make a request to the API using the openai-python library in async (with acreate)

### OS

macOS

### Python version

Python v3.11

### Library version

openai-python 0.28.1

**Comment by rattrayalex** [comment]
Thanks @maximerdy1 , nice job filing your first bug!

We've rewritten the the SDK to use `httpx`, which makes requests differently – hopefully it'll provide a more helpful error message in this case. Unfortunately, if it doesn't, I suspect it'd be quite difficult for us to improve the situation. 

I'm sorry for the debugging you had to go through, that sounds quite difficult!
