### ISSUE TITLE
Incorrect error displaying when context size is larger than organization TPM

### ISSUE THREAD

**Issue by asim-shrestha** [openai/openai-python#630]
### Describe the bug

When you make a request to the OpenAI API and the context length exceeds your organizations allowed tokens per minute for the specific model, you will receive the following error:

```
Rate limit reached for default-gpt-4-large in organization org-xxxxxxxxxxxx on tokens per min. 

Limit: 150000 / min. Current: 0 / min. Contact us through our help center at help.openai.com if you continue to have issues.
```

This is confusing because it makes the issue appear to be at the organization level, when in fact a bug in your code is just causing your context to be too large. Instead, the following error message should appear:

```
This model's maximum context length is 4097 tokens, however you requested 150678 tokens (150000 in your prompt; 678 for the completion). Please reduce your prompt; or completion length."
```

### To Reproduce

1. Use the OpenAI python client
2. Use any open ai chat completions endpoint with far too large a context length
3. Observe error 

### OS

macOS

### Python version

^3.9

### Library version

^0.27.8

**Comment by perryHV** [comment]
Hii @asim-shrestha  I want to work on this issue please assign me.

**Comment by asim-shrestha** [comment]
@perryHV I don't have the auth to do that :) I imagine you can just make a PR

**Comment by ansumanswain** [comment]
could you attach the corresponding repo?

**Comment by asim-shrestha** [comment]
Assuming it should all be in this repo

**Comment by ansumanswain** [comment]
yes, Assuming it should all be in this repo

**Comment by rattrayalex** [comment]
This is backend API behavior, not Python library behavior. 

I do agree that messaging could be better, so I hope we'll be able to make an associated backend change.

**Comment by asim-shrestha** [comment]
Awesome, Stainless looks great by the way
