### ISSUE TITLE
Missing HTTP/2 support because python requests only supports HTTP/1.1

### ISSUE THREAD

**Issue by gastonmorixe** [openai/openai-python#632]
### Describe the bug

This official python library for OpenAI is relying on python requests which does not support HTTP2 which is much more efficient. 

I recommend exploring switching to [HTTPX library](https://www.python-httpx.org/async/).

#### OpenAI python lib / cli:

<img width="1800" alt="image" src="https://github.com/openai/openai-python/assets/637225/04494767-c733-45d1-ad23-cbea670eeac9">

<img width="1800" alt="image" src="https://github.com/openai/openai-python/assets/637225/63e74e41-736f-4b87-a80e-799b3ed8bb68">

#### Using custom script HTTPX (uses HTTP/2):

<img width="1800" alt="image" src="https://github.com/openai/openai-python/assets/637225/e212185b-def9-47d0-92d7-9c3a5a5964aa">

<img width="1800" alt="image" src="https://github.com/openai/openai-python/assets/637225/4d8ec595-a36c-416c-9680-ad1db4fee7c0">

### To Reproduce

1. pip install openai
2. Setup a proxy and intercept the traffic
3. `$ openai -v api chat_completions.create -m gpt-3.5-turbo -g user "Hello world"`
4. Check it uses HTTP/1.1 as it's the only version requests supports

### Code snippets

HTTPX with HTTP/2 basic example:

```bash
$ python openai-httpx.py --user "hey, how are you doing?" --system "Act as robot" --model "gpt-4"
```

```python
import httpx
import os
import argparse
import asyncio
import json
import sys

timeout = httpx.Timeout(10.0, read=None)

async def create_chat_completion(user, system, model):
    url = "https://api.openai.com/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {os.getenv('OPENAI_API_KEY')}",
        "Content-Type": "application/json",
        "Accept": "text/event-stream",
        "Connection": "keep-alive"
    }

    data = {
        "model": model,
        "messages": [{"role": "system", "content": system},
                     {"role": "user", "content": user}],
        "stream": True
    }

    async with httpx.AsyncClient(http2=True) as client:
        async with client.stream('POST', url, headers=headers, json=data, timeout=timeout) as response:
            async for line in response.aiter_lines():
                if line.startswith("data: "):
                    json_str = line[len("data: "):]
                    if json_str != '[DONE]':
                        frame = json.loads(json_str)
                        delta_content = frame.get('choices', [{}])[0].get('delta', {}).get('content', '')
                        sys.stdout.write(delta_content)
                        sys.stdout.flush()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--user", required=True, help="User message to OpenAI")
    parser.add_argument("--system", required=True, help="System message to OpenAI")
    parser.add_argument("--model", required=True, help="Model to use for completion")
    args = parser.parse_args()

    asyncio.run(create_chat_completion(args.user, args.system, args.model))
```

### OS

macOS 14 23A344

### Python version

Python 3.11.4

### Library version

openai 0.27.8

**Comment by RobertCraigie** [comment]
Hey! We've just published [a beta for a fully-rewritten v1 of the Python SDK](https://github.com/openai/openai-python/discussions/631), which does use httpx under the hood.

Unfortunately, it currently doesn't support passing additional arguments to the httpx client which is required to enable http2 support but we're hoping to have an update out shortly to support this which will look like:

```py
import httpx
from openai

client = OpenAI(
  http_client=httpx.Client(http2=True),
)
```

We'd love your feedback, so please give it a try and share your thoughts (good and bad, major and minor) in the linked discussion!

**Comment by winchesterdeeplay** [comment]
https://github.com/winchesterdeeplay/openai-python-httpx

**Comment by RobertCraigie** [comment]
@winchesterdeeplay I'd highly encourage you to try out the [v1 beta](https://github.com/openai/openai-python/discussions/631) so that you don't have to maintain your own fork!

**Comment by rattrayalex** [comment]
This is now available in the v1 beta!

```py
client = OpenAI(
  http_client=httpx.Client(http2=True),
)
```

Please give it a try and share your feedback.
