### ISSUE TITLE
No module named 'openai'

### ISSUE THREAD

**Issue by Handale1808** [openai/openai-python#637]
### Describe the bug

I have uninstalled openai and reinstalled it with pip and pip3, 
I have checked that pip and openai are installed in the same folder
and various other internet solutions but nothing has worked
please help

I know its not a bug but i can't figure out how to log a normal issue :'(

### To Reproduce

all i say is import openai

### OS

Windows

### Python version

3.1.1

### Library version

0.28.1

**Comment by bc1Carlos** [comment]
You need to make sure that the Python interpreter your IDE is selecting to run the files has the necessary library installed. 

Assuming you are using VS Code you can use SHIFT+CTRL+P and then type Python: Select Interpreter to view a list of the interpreters and check which one you are using.

Sometimes when you work with virtual environments you have separate interpreters each with different libraries downloaded.

![Screenshot 2023-10-06 141129](https://github.com/openai/openai-python/assets/97136831/1c61d09f-57f4-4379-b39d-38a7f6658d70)

**Comment by dmarcelop** [comment]
I'm having the same problem.  How was this resolved?
I've tried reinstalling openai and get "requirement already satisfied". When I attempt to import it responds with "No module named 'openai'"

**Comment by Handale1808** [comment]
So i was coding a plugin for unreal and i had to install open ai through unreal's python terminal with the following commands:
import sys
import pip
pip,main(['install', 'openai'])
subprocess.check_call(["pip", "install", "openai"])
check_call(["pip", "install", "openai"])
pip install openai
