### ISSUE TITLE
Can't send files - missing purpose

### ISSUE THREAD

**Issue by not4fame** [openai/openai-python#65]
Hi I am trying to send files for finetuning from my api service (not command line)
I tried:
`return json.loads(requests.post(
            'https://api.openai.com/v1/files',
            headers={'Authorization': 'Bearer '+ os.getenv("OPENAI_API_KEY")},
            json={"purpose":"fine-tune"},
            files={'file': "\n".join(data)}
        ).text)`
and
`return json.loads(requests.post(
            'https://api.openai.com/v1/files',
            headers={'Authorization': 'Bearer '+ os.getenv("OPENAI_API_KEY")},
            params={"purpose":"fine-tune"},
            files={'file': "\n".join(data)}
        ).text)`  

but I got `"'purpose' is a required property"` error

and when I try:
`return json.loads(requests.post(
            'https://api.openai.com/v1/files',
            headers={'Authorization': 'Bearer '+ os.getenv("OPENAI_API_KEY")},
            files={"purpose":"fine-tune", 'file': "\n".join(data)}
        ).text)`

I got ` "'' is not one of ['fine-tune', 'answers', 'search', 'classifications'] - 'purpose'"` error

What am I missing?

**Comment by hallacy** [comment]
I think you might you might not need the json param and might just need to another tuple on the files param.  Here's how we do it in this repo: https://github.com/openai/openai-python/blob/main/openai/api_resources/file.py#L36

**Comment by not4fame** [comment]
Perfect. Worked like a charm.
