### ISSUE TITLE
v1.0.0b2: Types not working correctly when Literals not used for stream parameter for completions.create

### ISSUE THREAD

**Issue by kyczawon** [openai/openai-python#652]
### Describe the bug

When stream is a bool variable, typing does not select the correct overloaded function implementation in  `client.chat.completions.create`. This results in the following error:

```
Argument of type "bool" cannot be assigned to parameter "stream" of type "Literal[True]" in function "create"
  "bool" cannot be assigned to type "Literal[True]"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Passing in a Literal works as expected, and so does 'unpacking' the dynamic value into Literals.

It appears that typing does not select the overloaded function correctly that contains the relevant types (line 624 in `Async Completions`):
```
stream: Optional[Literal[False]] | Literal[True] | NotGiven = NOT_GIVEN,
```

### To Reproduce

The following code doesn't work:

```
client = AsyncOpenAI()
stream = True if 0 == 0 else False

await client.chat.completions.create(
    model=request.model,
    messages=[
        {
            "role": "user",
            "content": "",
        },
    ],
    stream=stream,
)
```

This code works correctly:

```
client = AsyncOpenAI()
stream = True if 0 == 0 else False
if (stream == True):
    await client.chat.completions.create(
        model=request.model,
        messages=[
            {
                "role": "user",
                "content": "",
            },
        ],
        stream=stream,
    )
else:
    await client.chat.completions.create(
        model=request.model,
        messages=[
            {
                "role": "user",
                "content": "",
            },
        ],
        stream=stream,
    )
```

### OS

macOS

### Python version

3.9.13

### Library version

1.0.0b2

**Comment by RobertCraigie** [comment]
Thanks for the bug report! We're looking into this.

I *think* the line you mentioned isn't what's causing the error as despite its name, `Literal[True] | Literal[False]` will be treated the same as `bool` by type checkers. I suspect the actual issue is that we're missing another overload definition that returns `ChatCompletion | Stream[ChatCompletionChunk]` if `stream` is a `bool`.
