### ISSUE TITLE
Unable to use Python 3.12 due to aiohttp dependency unable to build wheel.

### ISSUE THREAD

**Issue by dlroy88osu** [openai/openai-python#654]
### Describe the bug

I am sure that aiohttp will catch up, but meanwhile, I figure I would through this on your radar for potential work around.

### To Reproduce

Running Python 3.12.0 
pip install openai

### OS

any

### Python version

3.12.0

### Library version

current

**Comment by RobertCraigie** [comment]
Thanks, this is a known issue with the current SDK, however there are workarounds - https://github.com/openai/openai-python/issues/645.

This has been fixed in our [v1 beta](https://github.com/openai/openai-python/discussions/631) as we've switched to httpx which is a pure python library.

**Comment by dlroy88osu** [comment]
@RobertCraigie You are beautiful! Thank you! Playing in V1 beta now! Thanks!!! @RobertCraigie
