### ISSUE TITLE
JSONDecodeError when trying to stream chat completion

### ISSUE THREAD

**Issue by marioluan** [openai/openai-python#663]
### Describe the bug

After sending a request to chat completion API using `stream=True`, sometimes, the api returns a single response with two chunks inside of it. For example:
```
b'{"id": "chatcmpl-8BnB0NvhQxY0szkmjMdM5px67189w", "object": "chat.completion.chunk", "created": "2023-10-20T17:02:14+00:00", "model": "gpt-4", "choices": [{"delta": {"content": "\'s"}, "index": 0}]}{"id": "chatcmpl-8BnB0NvhQxY0szkmjMdM5px67189w", "object": "chat.completion.chunk", "created": "2023-10-20T17:02:14+00:00", "model": "gpt-4", "choices": [{"delta": {"content": " language"}, "index": 0}]}'
```

My expectation was to get one chunk per response:
```
b'{"id": "chatcmpl-8BnB0NvhQxY0szkmjMdM5px67189w", "object": "chat.completion.chunk", "created": "2023-10-20T17:02:14+00:00", "model": "gpt-4", "choices": [{"delta": {"content": "\'s"}, "index": 0}]}'
```

```
b'{"id": "chatcmpl-8BnB0NvhQxY0szkmjMdM5px67189w", "object": "chat.completion.chunk", "created": "2023-10-20T17:02:14+00:00", "model": "gpt-4", "choices": [{"delta": {"content": " language"}, "index": 0}]}'
```

### To Reproduce

1. Send a request to chat completion with `stream=True`
2. Consume each chunk of the stream
3. Check the contents of each chunk
4. One of the chunks will have two payloads inside of it

### OS

Linux

### Python version

3.10.11

### Library version

openai v0.27.10

**Comment by ercanucan** [comment]
Observing exact the same issue while streaming chunks. The issue seems to occur sporadically. Reproducible with openai-python v0.28.1 on the client-side with FastChat architecture on the server side.

cc @fh1ch @bufferoverflow

**Comment by rattrayalex** [comment]
Fixed in [v1](https://github.com/openai/openai-python/discussions/631)
