### ISSUE TITLE
Consider switching to httpx as the HTTP client library

### ISSUE THREAD

**Issue by agronholm** [openai/openai-python#665]
### Describe the feature or improvement you're requesting

Currently, this project uses `requests` and `aiohttp` to provide synchronous and asynchronous interfaces, respectively. The `httpx` library, in contrast, is an actively maintained project that supports both with a consistent interface. On top of that, it works with the alternative `trio` async event loop implementation.

**Comment by rishabhRsinghvi** [comment]
@agronholm I am interested.

**Comment by agronholm** [comment]
> @agronholm I am interested.

Well, we need to get the maintainers interested too for this to move forward.

**Comment by agronholm** [comment]
Ah, indeed! I didn't realize this since this work was done in a separate branch.
