### ISSUE TITLE
Invalid URL 'gpt-3.5-turbo/fine_tuning/jobs': No scheme supplied. Perhaps you meant https://gpt-3.5-turbo/fine_tuning/jobs?

### ISSUE THREAD

**Issue by Rugaliz** [openai/openai-python#666]
### Describe the bug

When using fine tuning I uploaded a file with success and when creating a job using the resulting job id I get this error:
`Error communicating with OpenAI: Invalid URL 'gpt-3.5-turbo/fine_tuning/jobs': No scheme supplied. Perhaps you meant https://gpt-3.5-turbo/fine_tuning/jobs?`

### To Reproduce

This is the python code I'm running:
`response = openai.FineTuningJob.create(training_file_id, model)`

for model I'm using "gpt-3.5-turbo"

I'm using openai library version 0.28.1

### OS

linux

### Python version

3.11

### Library version

0.28.1

**Comment by rishabhRsinghvi** [comment]
@Rugaliz I am interested.

**Comment by rattrayalex** [comment]
Please upgrade to the v1 of this package.

The problem may have been that you had set the base url to be a model.
