### ISSUE TITLE
GPT4V - API

### ISSUE THREAD

**Issue by alex-wenner** [openai/openai-python#670]
### Describe the feature or improvement you're requesting

I am requesting GPT4V API support. The ability to provide image input with the purpose of multimodality.

This feature has been out for a little bit now with ChatGPT Plus mobile and web. Even if this is not on the V1 release roadmap, it would be nice to understand timeline.

Any information on this functionality would be great. Thanks

**Comment by RobertCraigie** [comment]
The SDK has been updated to include the functionality announced today during the DevDay keynote.
