### ISSUE TITLE
Images too different

### ISSUE THREAD

**Issue by paulocoutinhox** [openai/openai-python#674]
### Describe the bug

Im using dall-e 3 api but images with same prompt on chatgpt generate too much different images.

Prompt: "cartoon style + king davi from bible"

From Python:
![e48d86e9840af5871a27df0db9eb6909](https://github.com/openai/openai-python/assets/395096/1b2c0041-52c2-4e15-b4c7-01bd117e3d9e)

From ChatGPT:
<img width="844" alt="image" src="https://github.com/openai/openai-python/assets/395096/eec851da-80da-4267-a75b-47a40266365f">

What im doing wrong?

### To Reproduce

In python call api with prompt "cartoon style + king davi from bible".

In chatgpt use prompt "cartoon style + king davi from bible".

### OS

macOS

### Python version

3.9

### Library version

latest

**Comment by lostmygithubaccount** [comment]
the ChatGPT version writes a prompt for you (I think you can click it to see), so it's not actually the same prompt

**Comment by paulocoutinhox** [comment]
So, what i need say to ChatGPT to it generate a prompt too? I tried:

```
Generate image prompts for each phrases below. Each prompt need be on their line. I want without quotes. I want in language {c.language_default}. Don't put numbers on prompts begin.\n\n{story_text}
```

But the horrible images still generating.

**Comment by lostmygithubaccount** [comment]
you could probably figure out what ChatGPT/GPT-4 is doing to construct the prompts to DALLE-3

but it's not sending what you say in the chat, it takes that and adds some style/other "prompt engineering" before calling the image model. if you click on the DALLE-3 thing in chat I think you can see what it sent exactly

**Comment by paulocoutinhox** [comment]
I use the same chatgpt prompt:

```
A cartoon-style image of a historical king inspired by the biblical figure of David, but not depicting any real person. The king has olive skin, dark brown hair, and is wearing a regal, ancient Middle-Eastern outfit typical of the era, complete with a crown and a lyre in his hand, symbolizing his attributes as a musician and a warrior. He stands in a pastoral landscape that could resemble the ancient hills of Judea, with a city in the far background. His expression is thoughtful and noble, as he looks towards the horizon.
```

<img width="1486" alt="image" src="https://github.com/openai/openai-python/assets/395096/42a8acaf-ba2d-4a87-bac9-e3fb0a9024ff">


And the results:

<img width="537" alt="image" src="https://github.com/openai/openai-python/assets/395096/e9c24786-9e5f-4c0e-92dd-5ee444c84f33">

**Comment by lostmygithubaccount** [comment]
ah sorry, then I do not know what's going on

**Comment by RobertCraigie** [comment]
Please ask API related questions in the community forum! https://community.openai.com/
