### ISSUE TITLE
timeout param is not handled correctly, resulting in no timeout being set

### ISSUE THREAD

**Issue by ilyastam** [openai/openai-python#675]
### Describe the bug

Passing a timeout to `openai.ChatCompletion.create` doesn't do anything. Likely due to he incorrect logic here: https://github.com/openai/openai-python/blob/main/openai/api_resources/abstract/engine_api_resource.py#L101
If pass 3, according to this I will have no timeout.

### To Reproduce

call a completion api with a small timeout

### OS

any

### Python version

any

### Library version

v0.28.1

**Comment by RobertCraigie** [comment]
This should be fixed in v1 which was just released! You can read the changelog [here](https://github.com/openai/openai-python/discussions/631).

**Comment by boyleconnor** [comment]
The file that @ilyastam linked to no longer exists in the current commit of `main`. I think this [permalink](https://github.com/openai/openai-python/blob/284c1799070c723c6a553337134148a7ab088dd8/openai/api_resources/abstract/engine_api_resource.py#L101) should point to the line that @ilyastam was linking to.
