### ISSUE TITLE
v1.0 drops embeddings_util.py breaking semantic text search

### ISSUE THREAD

**Issue by mrbullwinkle** [openai/openai-python#676]
### Describe the bug

The previous version of the OpenAI Python library contained `embeddings_utils.py` which provided functions like `cosine_similarity` which are used for semantic text search with embeddings. Without this functionality existing code including OpenAI's cookbook example: https://cookbook.openai.com/examples/semantic_text_search_using_embeddings will fail due to this dependency.

Are there plans to add this support back-in or should we just create our own cosine_similarity function based on the one that was present in `embeddings_utils`:

```python
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
```

### To Reproduce

Cookbook example cannot be converted to use v1.0 without removing the dependency on `embeddings_utils.py` https://cookbook.openai.com/examples/semantic_text_search_using_embeddings

### Code snippets

```Python
from openai.embeddings_utils import get_embedding, cosine_similarity

# search through the reviews for a specific product
def search_reviews(df, product_description, n=3, pprint=True):
    product_embedding = get_embedding(
        product_description,
        engine="text-embedding-ada-002"
    )
    df["similarity"] = df.embedding.apply(lambda x: cosine_similarity(x, product_embedding))

    results = (
        df.sort_values("similarity", ascending=False)
        .head(n)
        .combined.str.replace("Title: ", "")
        .str.replace("; Content:", ": ")
    )
    if pprint:
        for r in results:
            print(r[:200])
            print()
    return results


results = search_reviews(df, "delicious beans", n=3)
```

### OS

Windows

### Python version

Python v3.10.11

### Library version

openai-python==1.0.0rc2

**Comment by mrbullwinkle** [comment]
@RobertCraigie, makes sense. Thank you for the super fast response!

**Comment by CristianPQ** [comment]
@mrbullwinkle
In the meantime, I hope this piece of code can help you.

source: https://learn.microsoft.com/en-us/azure/ai-services/openai/tutorials/embeddings?tabs=python-new%2Ccommand-line


```
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def get_embedding(text, model="text-embedding-ada-002"): # model = "deployment_name"
    return client.embeddings.create(input = [text], model=model).data[0].embedding

def search_docs(df, user_query, top_n=4, to_print=True):
    embedding = get_embedding(
        user_query,
        model="text-embedding-ada-002" # model should be set to the deployment name you chose when you deployed the text-embedding-ada-002 (Version 2) model
    )
    df["similarities"] = df.ada_v2.apply(lambda x: cosine_similarity(x, embedding))

    res = (
        df.sort_values("similarities", ascending=False)
        .head(top_n)
    )
    if to_print:
        display(res)
    return res


res = search_docs(df_bills, "Can I get information on cable company tax revenue?", top_n=4)
```

**Comment by mrbullwinkle** [comment]
@CristianPQ you beat me to adding a ref to that code sample to this issue after I added it earlier today. I am the author of that code sample. :relaxed:

**Comment by patham9** [comment]
Very unprofessional that such functions just get removed. It is a moving API one cannot rely on, very annoying.

**Comment by bhaniraj** [comment]
@RobertCraigie , is the support added in cookbook repo  for the functions provided in embeddings_utils.py ?

**Comment by rattrayalex** [comment]
@logankilpatrick , can you help here?

**Comment by julianlevy** [comment]
Hi folks - any updates on the cookbook yet?

**Comment by jawwadturabi** [comment]
Still can't see the updates on the cookbook

**Comment by the-rich-piana** [comment]
Why the frick would you guys remove this. This API is god awful.

**Comment by davidgilbertson** [comment]
FWIW, if you're using embeddings from the OpenAI API, you can get cosine similarity with just `a @ b`, since they're normalized to 1 anyway (assuming `a` and `b` are NumPy arrays or tensors or similar, not plain lists)

**Comment by davidgilbertson** [comment]
Also BTW there is still a reference to `embeddings_utils` in the actual user guide in the docs here: https://platform.openai.com/docs/guides/embeddings/use-cases

**Comment by dsantiago** [comment]
But documentation is still stale. Still using the old `embeddings_utils`

https://platform.openai.com/docs/guides/embeddings/use-cases

In **Text search using embeddings** section.

![Image](https://github.com/user-attachments/assets/6b341f3d-2909-436d-8cbd-13b8c6741bf5)
