### ISSUE TITLE
Getting ChatCompletion error via Azure OpenAI

### ISSUE THREAD

**Issue by samedovzaur** [openai/openai-python#680]
`openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)
  

  What is that what should i do ? (FYI upgrading openai doesn't work out)

**Comment by RobertCraigie** [comment]
I'm not sure what's showing you that error message because instead of updating the version, you should downgrade the version, you can do so with
```sh
pip install openai<1
```

**Comment by kar-m** [comment]
Hey @samedovzaur , I just had the same issue, I think it's because they pushed an update to the package a couple hours ago. I installed the version 0.28.1 and it works. Thanks!

**Comment by samedovzaur** [comment]
Thank You King👑!

**Comment by samedovzaur** [comment]
> I'm not sure what's showing you that error message because instead of updating the version, you should downgrade the version, you can do so with
> 
> ```shell
> pip install openai<1
> ```
> 
> Or ideally you can migrate to the v1 SDK, you can do so by running `openai migrate`.

I was downgrading it but man what time slayer thing it is to do :)

**Comment by samedovzaur** [comment]
It happens again 

> 0.28.1

man i do keep getting the same error again is this same for you as well?

**Comment by RobertCraigie** [comment]
You'll have accidentally installed the new version somehow.
