### ISSUE TITLE
Missing `client.audio.speech`?

### ISSUE THREAD

**Issue by Manouchehri** [openai/openai-python#681]
The example at https://platform.openai.com/docs/guides/text-to-speech/quick-start doesn't work. Not sure if you forgot to push an update to this repo?

```
dave@mbp openai-test-1 % python3 main.py
Traceback (most recent call last):
  File "/Users/dave/Work/openai-test-1/main.py", line 10, in <module>
    response = client.audio.speech.create(
               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Audio' object has no attribute 'speech'
```

**Comment by Manouchehri** [comment]
My bad, I misread `1 PM PST` as `1 PM EST`.

**Comment by TimoKorinth** [comment]
What do you mean? Is there a roadmap when we can expect the latest version? In the keynote they just said: Now ;-)

**Comment by Manouchehri** [comment]
![image](https://github.com/openai/openai-python/assets/7232674/c5a4cc30-a94a-4790-b84c-69942a904b6f)

> New releases will be rolling out after 1 PM PST.

**Comment by TimoKorinth** [comment]
Oh, ok! Thanks ;-)

**Comment by tn493** [comment]
Oh my god, we have to wait plenty 20 minutes...I can't wait to hear tts-1-hd.

**Comment by TimoKorinth** [comment]
No, you can use it right now: pip3 install git+https://github.com/openai/openai-python.git@main  ;-)

**Comment by TimoKorinth** [comment]
And it's awesome! Even with other languages.

**Comment by tn493** [comment]
Thanks very much bro!
