### ISSUE TITLE
AttributeError: 'Audio' object has no attribute 'speech' in 1.0.1

### ISSUE THREAD

**Issue by janewu77** [openai/openai-python#683]
AttributeError: 'Audio' object has no attribute 'speech'

Traceback (most recent call last):
  File "/Users/xxx/src/jshare-llm-demo/openai-demo/tts.py", line 12, in <module>
    response = client.audio.speech.create(
AttributeError: 'Audio' object has no attribute 'speech'

```
from pathlib import Path
from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="xxxxxx",
)

speech_file_path = Path(__file__).parent / "speech.mp3"
response = client.audio.speech.create(
  model="tts-1",
  voice="alloy",
  input="Today is a wonderful day to build something people love!"
)

response.stream_to_file(speech_file_path)
```
=============================

> OS: mac OS
> python: 3.9.*
> openai: 1.0.1

**Comment by Zeazy** [comment]
+1

**Comment by RobertCraigie** [comment]
A new version of this SDK will be published after 1pm PST with support for the newly announced endpoints. https://github.com/openai/openai-python/issues/681
