### ISSUE TITLE
openai 1.0.1 is missing model and other things seems behind the docs

### ISSUE THREAD

**Issue by JoeGaffney** [openai/openai-python#684]
Hey,

openai 1.0.1 is missing model and other things seems behind    

```
response = self.client.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Images.generate() got an unexpected keyword argument 'model'
```

Main docs page mentions model can be used
https://platform.openai.com/docs/guides/images/generations

![image](https://github.com/openai/openai-python/assets/11944251/d8d4ecb8-3644-4dd7-bf91-5a21104ed6a5)

**Comment by xtsAU** [comment]
Audio Speech Create aswell

**Comment by RavioliSauce** [comment]
Hi there!

It looks like you might be using an older version of the `openai` package which doesn't include the new features you're trying to access.

Could you please try upgrading the package to the latest version by running the following command in your terminal? This solved the issue for me, and you should be able to access all the new features after upgrading.

```bash
pip install openai --upgrade
```

**Comment by RobertCraigie** [comment]
The `v1.0.0` and `v1.0.1` versions of the SDK do not include the newly announced endpoints, you need to upgrade to `v1.1.0` to use them.

**Comment by JoeGaffney** [comment]
Right I see there has been 1.1.0 added to pypi since i posted.
