### ISSUE TITLE
Assistant API url Invalid

### ISSUE THREAD

**Issue by Adityabhaskar685** [openai/openai-python#686]
Code 

![image](https://github.com/openai/openai-python/assets/76844310/57d7616c-bde9-4864-ac72-485ffc216f6f)

Error

![image](https://github.com/openai/openai-python/assets/76844310/91920b85-1fa1-4391-8169-06e225bd1a16)

openai version - 1.1.0

**Comment by mehmetkoca** [comment]
Same here, I got same issue myself

**Comment by Kabilan108** [comment]
Having the same issue here

**Comment by ryanzola** [comment]
+1, Same issue here

**Comment by vvvv-ops** [comment]
Same

**Comment by jacc** [comment]
+1

**Comment by Jeremaiha** [comment]
How did you manage to figure out the `beta` package?
I'm using the V1.1.0 and getting the following error:
'---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/Users/gshiklov/TheGG-Machine/GG-AssistantHandler.py](https://file+.vscode-resource.vscode-cdn.net/Users/gshiklov/TheGG-Machine/GG-AssistantHandler.py) in line 7
      11 client = OpenAI(openai_api_key=OPENAI_API_KEY)
      12 # assistant = Assistant()
----> 13 methods = inspect.getmembers(openai.types.beta.assistants, predicate=inspect.ismethod)
      15 # Print the names of the methods.
     16 for method in methods:

AttributeError: module 'openai.types.beta' has no attribute 'assistants''

**Comment by tytung2020** [comment]
I have another error: NameError: name 'client' is not defined
![image](https://github.com/openai/openai-python/assets/37324680/2faa72e2-3a7d-40e9-af48-e16fe41f089a)

**Comment by tytung2020** [comment]
from openai import OpenAI

client = OpenAI()
