### ISSUE TITLE
gpt-4-1106-preview only has 4096 tokens?

### ISSUE THREAD

**Issue by JarJarBeatyourattitude** [openai/openai-python#687]
I got this error while trying to generate with gpt-4-1106-preview:

Generating with model: gpt-4-1106-preview ...
Error while generating: Error code: 400 - {'error': {'message': 'max_tokens is too large: 5500. This model supports at most 4096 completion tokens, whereas you provided 5500.', 'type': 'invalid_request_error', 'param': 'max_tokens', 'code': None}}

This seems unexpected, since max_tokens is supposed to have a much higher ceiling than that.

Anyone now what could be happening? Thanks.

**Comment by kdcokenny** [comment]
Same error as well. It also shows this error when I try on playground.

**Comment by JarJarBeatyourattitude** [comment]
Just checked and I'm getting a similar error for gpt-3.5-turbo-1106.

**Comment by dosenhosenjoe** [comment]
These models can only output 4096 tokens but input tokens are 128k for 4 turbo and 16k for the new 3.5 turbo

**Comment by kcolemangt** [comment]
Each of the new models [returns a maximum of 4,096 output tokens](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo). This includes:

- GPT-4 Turbo `gpt-4-1106-preview` 
- GPT-4 Turbo with vision `gpt-4-vision-preview` `gpt-4-1106-vision-preview`
- Updated GPT 3.5 Turbo `gpt-3.5-turbo-1106`

**Comment by RobertCraigie** [comment]
Thanks for adding the context Keith & dosen!

**Comment by ugoborghetti** [comment]
But why? This breaks a lot of apps... it used to work

**Comment by iamdroppy** [comment]
it makes no sense as tokens will try to finalize response as much as possible. there's no feasible way to analyze document except to:

-- NEVER ON DB: Outputs 128k - make a token compression; super summarize the subject of the response BUT not the actual response, run until 32k
-- NEW OUTPUT: try to make an understandable response on 10.000k max tokens (albeit hard), but you can always use embeddings
input - make a token compression, save

Sample (fictial token count):
User (10 tokens): A very small question to do an article about X.
~~**old:** 128k: Very large output - above 100k -- embed ~~
32k (1000 tokens, replacement for 128k): A reinterpretation of the 128k

total tokens 1010. Some bit of engineering there for those who want outputs to be 128k. I think there's one other way to hack it.

Anyway, 128k output rule is not a great idea.
