### ISSUE TITLE
CRITICAL BUG: images.generate does not work on Azure OpenAI

### ISSUE THREAD

**Issue by nicolaschaillan** [openai/openai-python#692]
openai_api_version = "2023-09-01-preview"
            client = AzureOpenAI(azure_endpoint = openai_api_base, api_key=openai_api_key, api_version=openai_api_version)

            response = client.images.generate(
                prompt=prompt,
                size=size,
                n=n
            )

Fails with:

{'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by kristapratico** [comment]
Hi @nicolaschaillan, Azure OpenAI Dall-E is not supported in the v1 SDK yet, but support will be added soon.

https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart?tabs=command-line&pivots=programming-language-python#install-the-python-sdk

**Comment by kristapratico** [comment]
@nicolaschaillan I will share as soon as I have an ETA. As a stop-gap, it is possible to access Azure OpenAI DALL-E by passing in a httpx custom transport:

```python
import time
import json
import httpx
import openai


class CustomHTTPTransport(httpx.HTTPTransport):
    def handle_request(
        self,
        request: httpx.Request,
    ) -> httpx.Response:
        if "images/generations" in request.url.path and request.url.params[
            "api-version"
        ] in [
            "2023-06-01-preview",
            "2023-07-01-preview",
            "2023-08-01-preview",
            "2023-09-01-preview",
            "2023-10-01-preview",
        ]:
            request.url = request.url.copy_with(path="/openai/images/generations:submit")
            response = super().handle_request(request)
            operation_location_url = response.headers["operation-location"]
            request.url = httpx.URL(operation_location_url)
            request.method = "GET"
            response = super().handle_request(request)
            response.read()

            timeout_secs: int = 120
            start_time = time.time()
            while response.json()["status"] not in ["succeeded", "failed"]:
                if time.time() - start_time > timeout_secs:
                    raise openai.OpenAIError("Operation polling timed out.")

                time.sleep(int(response.headers.get("retry-after")) or 10)
                response = super().handle_request(request)
                response.read()

            if response.json()["status"] == "failed":
                error_data = response.json()["error"]
                message = error_data.get("message", "Operation failed")
                code = error_data.get("code")
                raise openai.OpenAIError(message, code)

            result = response.json()["result"]
            return httpx.Response(
                status_code=200,
                headers=response.headers,
                content=json.dumps(result).encode("utf-8"),
                request=request,
            )


client = openai.AzureOpenAI(
    azure_endpoint="<azure_endpoint>",
    api_key="<api_key>",
    api_version="<api_version>",
    http_client=httpx.Client(
        transport=CustomHTTPTransport(),
    ),
)
image = client.images.generate(prompt="a cute baby seal")
print(image.data[0].url)
```

Once support is officially added, you can remove the `http_client` keyword argument and the custom transport class from your code and all should work as expected. Let me know if that helps.

**Comment by ashjeanbird** [comment]
Hey @kristapratico, I made an update to the docs per @nicolaschaillan suggestion. Can you please take a look to see if it works and if there is anything else that I should add? Happy to add any additional details.

**Comment by kristapratico** [comment]
@ashjeanbird I'll take a look.

@StephenHodgson yes, the Azure Dall-E endpoint contains a `:submit` for the initial call. However, it's not enough to just append this to the endpoint. The initial call returns a status monitor which has to be checked until the final result is ready. This code shows how to workaround this for now: https://github.com/openai/openai-python/issues/692#issuecomment-1797181743

**Comment by StephenHodgson** [comment]
Yeah I don't understand why Microsoft went so far different with this endpoint implementation. Super frustrating.

**Comment by ashjeanbird** [comment]
@kristapratico thank you for checking out my PR https://github.com/openai/openai-python/pull/766. I have made a change to reflect the [known issues](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python%2Cdalle-fix#known-issues) verbiage link and the associated [workaround](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python%2Cdalle-fix#dall-e-fix).

**Comment by kristapratico** [comment]
@nicolaschaillan @StephenHodgson @ashjeanbird Azure OpenAI now supports Dall-E 3. See this [Quickstart](https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart?tabs=dalle3%2Ccommand-line&pivots=programming-language-python) for details. It is supported on version 1.2.4 or greater of the openai library.

Please note that if you wish to continue to use Dall-E 2 you must either use the 0.28.1 version of the library or use 1.X version with the [workaround](https://github.com/openai/openai-python/issues/692#issuecomment-1797181743).

**Comment by kristapratico** [comment]
Are you using Dall-E 2 or 3?

Dall-E 3 is currently only available on SwedenCentral: https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart?tabs=dalle3%2Ccommand-line&pivots=programming-language-python

You'll need to deploy the dall-e-3 model (you can do this from the Azure OpenAI Studio) and then target the deployment name in the method call:

```python
result = client.images.generate(
    model="dalle3", # the name of your DALL-E 3 deployment
    prompt="a close-up of a bear walking through the forest",
)
```

**Comment by kristapratico** [comment]
I'm sorry for the confusion. I'm relaying your feedback to the team.

For clarity,

Azure OpenAI supports two models for image generation: Dall-E 2 and Dall-E 3

Dall-E 2 is available in East US. You can use version 0.28.1 of the openai library to access it. If you want to use this model version with v1.X of the openai library, then you can copy the code from the [workaround](https://github.com/openai/openai-python/issues/692#issuecomment-1797181743).

Dall-E 3 is currently only available in SwedenCentral. You can use v1.2.4+ of the openai library to access it. Note that you must first deploy the dall-e-3 model from the Azure OpenAI studio and pass your deployment name in the `model` parameter when calling the API.

I am reaching out, but not sure yet when Dall-E 3 will be supported in US regions. The model documentation will be updated when it becomes available in more regions: https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#dall-e-models-preview

**Comment by StephenHodgson** [comment]
I'm guessing whenever this goes in https://github.com/Azure/azure-rest-api-specs/pull/26582

**Comment by brunobraga** [comment]
I am having this issue as well... If helps anyone, solution below.

Code that I expected to work:
```
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    azure_endpoint=f'https://{os.getenv("AZURE_OPENAI_API_INSTANCE_NAME")}.openai.azure.com',
    api_version=os.getenv('AZURE_OPENAI_API_VERSION'),
)
response = client.images.generate(
    prompt='dancing cat',
    size='512x512',
    n=1
)
image_url = response.data[0].url
```

Alternative code that works fine:

```
url = "{}/openai/images/generations:submit?api-version={}".format(
    f'https://{os.getenv("AZURE_OPENAI_API_INSTANCE_NAME")}.openai.azure.com',
    os.getenv('AZURE_OPENAI_API_VERSION')
)
headers= { "api-key": os.getenv("AZURE_OPENAI_API_KEY"), "Content-Type": "application/json" }
body = {
    "prompt": "dancing cat",
    "n": 1,
    "size": '512x512'
}
submission = requests.post(url, headers=headers, json=body)
operation_location = submission.headers['Operation-Location']
status = ""
while (status != "succeeded"):
    time.sleep(3) # workaround rate limit
    response = requests.get(operation_location, headers=headers)
    status = response.json()['status']
image_url = response.json()['result']['data'][0]['url']
```

**Comment by cohml** [comment]
@kristapractico Is [this workaround](https://github.com/openai/openai-python/issues/692#issuecomment-1797181743) (i.e., implementing `CustomHTTPTransport `) still required for accessing DALL-E via Azure OpenAI?

**Comment by kristapratico** [comment]
> @kristapratico Is [this workaround](https://github.com/openai/openai-python/issues/692#issuecomment-1797181743) (i.e., implementing `CustomHTTPTransport `) still required for accessing DALL-E via Azure OpenAI?

The workaround is only necessary if you're using Azure with DALL-E 2. Azure DALL-E 3 is supported by the library.

**Comment by cohml** [comment]
> The workaround is only necessary if you're using Azure with DALL-E 2. Azure DALL-E 3 is supported by the library.

Thanks for the quick reply.

Do you know if that is set to change at some point? Or if you're forever stuck with DALL-E 2, are you forever stuck with `CustomHTTPTransport`?

**Comment by kristapratico** [comment]
> > The workaround is only necessary if you're using Azure with DALL-E 2. Azure DALL-E 3 is supported by the library.
> 
> Thanks for the quick reply.
> 
> Do you know if that is set to change at some point? Or if you're forever stuck with DALL-E 2, are you forever stuck with `CustomHTTPTransport`?

As far as I know, there won't be updates to Azure DALL-E 2 in the future, meaning the workaround will be necessary to use it with this library. Are you able to migrate to DALL-E 3?

**Comment by StephenHodgson** [comment]
> > Do you know if that is set to change at some point? Or if you're forever stuck with DALL-E 2, are you forever stuck with `CustomHTTPTransport`?
> 
> As far as I know, there won't be updates to Azure DALL-E 2 in the future, meaning the workaround will be necessary to use it with this library. Are you able to migrate to DALL-E 3?

Good to know so I can document this in my client libraries.

**Comment by ronaldchoi** [comment]
> @nicolaschaillan I will share as soon as I have an ETA. As a stop-gap, it is possible to access Azure OpenAI DALL-E by passing in a httpx custom transport:
> 
> ```python
> import time
> import json
> import httpx
> import openai
> 
> 
> class CustomHTTPTransport(httpx.HTTPTransport):
>     def handle_request(
>         self,
>         request: httpx.Request,
>     ) -> httpx.Response:
>         if "images/generations" in request.url.path and request.url.params[
>            ...
> ```
> 
> Once support is officially added, you can remove the `http_client` keyword argument and the custom transport class from your code and all should work as expected. Let me know if that helps.

This workaround does not work with my Azure setup and always hits the "[429 Too Many Requests]" errors.

After some debugging, I was able to fix it by adding a default value for the "retry-after" header:

```python
time.sleep(int(response.headers.get("retry-after", 0)) or 10)
```

**Comment by kristapratico** [comment]
@ronaldchoi thanks for spotting the bug. I'll update the example in my comment.
