### ISSUE TITLE
Using Azure OpenAI with AAD example broken link in OpenAI v1 Release Notes Discussion

### ISSUE THREAD

**Issue by achandmsft** [openai/openai-python#700]
https://github.com/openai/openai-python/discussions/631 links to https://github.com/openai/openai-python/blob/v1/examples/azure_ad.py

Fix: Should be https://github.com/openai/openai-python/blob/main/examples/azure_ad.py

**Comment by RobertCraigie** [comment]
Thanks for the report! I've updated the link in the discussion.
