### ISSUE TITLE
Cannot import OpenAI from openai

### ISSUE THREAD

**Issue by omnific9** [openai/openai-python#701]
The pypi page shows this example
```
from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="My API Key",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)
```

Similar examples using openai.OpenAI can be found in official docs for Dalle-3:

```
from openai import OpenAI
client = OpenAI()

response = client.images.generate(
  model="dall-e-3",
  prompt="a white siamese cat",
  size="1024x1024",
  quality="standard",
  n=1,
)

image_url = response.data[0].url
```

However, this code will cause the following error (with openai==1.1.1):
ImportError: cannot import name 'OpenAI' from 'openai'

Tested this on both local Windows and a Databricks notebook.

**Comment by RobertCraigie** [comment]
@buptpriswang You're likely not using the right environment. What does `import openai; print(openai.VERSION)` output for you?

**Comment by jonathanrstern** [comment]
Have the same problem:

`import openai; print(openai.VERSION)` --> `0.28.1`

Previously I've relied on the global client, but I'd like to start initializing my client the correct way.

**Comment by RobertCraigie** [comment]
You'll be using the wrong environment either when installing openai or running python.

There isn't much I can do to help you unfortunately, apart from recommending that you use a venv and activate it https://docs.python.org/3/library/venv.html

**Comment by jonathanrstern** [comment]
So there's no way to use python 3.9 or 3.10 with openai?

**Comment by RobertCraigie** [comment]
No this library supports Python 3.7 and upwards. The issue is with your environment, you're using `3.11` to install the library but then using `3.9` to access it.

You'll have to ensure that you're using the same python version to install *and* access the library.

**Comment by omnific9** [comment]
@buptpriswang in my case, I had PyCharm open and installed the latest version of openai in terminal, but my PyCharm environment didn't get updated properly. It worked after I reloaded the project. On my Databricks looks like I couldn't uninstall an older version of openai so I couldn't get 1.1.1 installed. Just a perfect storm that made me think it was something bigger than what it really is.

**Comment by lostmygithubaccount** [comment]
I believe in y'all

**Comment by jonathanrstern** [comment]
thanks @RobertCraigie

**Comment by buptpriswang** [comment]
thanks @RobertCraigie @omnific9  it should use v1.1.0
