### ISSUE TITLE
ChatCompletion with Azure 

### ISSUE THREAD

**Issue by samedovzaur** [openai/openai-python#704]
`openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)

Keep getting this error, although yesterday downgraded openai version it worked today it showes the same error with downgraded and upgraded model as well!
What should I do ?

**Comment by mrbullwinkle** [comment]
@samedovzaur we updated the Chat examples for Azure OpenAI today on learn.microsoft.com to a tabbed experience to show you the code you would need for both the version released today, as well as the older version to allow time to test before you migrate:

<img width="641" alt="image" src="https://github.com/openai/openai-python/assets/31510320/f991e466-d663-4407-9df0-0194625cf942">

<img width="630" alt="image" src="https://github.com/openai/openai-python/assets/31510320/f09b690d-0c05-4e25-adcc-977446b13647">

https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python

https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/chatgpt?tabs=python-new&pivots=programming-language-chat-completions

I am able to swap back and forth between versions without issue as long as I update my code accordingly.

I can repro that error message if I try running the code that was written for version `0.028.1` with the `1.1.1` library installed. But code written for `1.1.1` executes without issue.

**Comment by samedovzaur** [comment]
Thank you! I'll dive into it.
