### ISSUE TITLE
chat-create-response_format - response_format={"type": "json_object"} does not follow other default types for that param

### ISSUE THREAD

**Issue by Hendler** [openai/openai-python#705]
Most are `Typing.Literal`, not `Dict`. This is especially confusing given that the default param is a `str` and  the documentation seems to imply the [type is str](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format). Instead it requires ` response_format={"type": "json_object"} `
```
openai.chat.completions.create(
            model=model_type,
            messages=prompts,
            response_format="json_object" 
        )
```
produces:
```
openai.BadRequestError: Error code: 400 - 
{'error': {'message': 
"'json_object' is not of type 'object' - 'response_format'", 
'type': 'invalid_request_error', 'param': None, 'code': None}}
```

I haven't dug deeper; perhaps this has a reason I am missing, such as it is detected as dict, so the api "knows" the type.

**Comment by RobertCraigie** [comment]
I appreciate that other `response_format` parameters in the API accept strings and this is different but I'm not sure how you've seen that the documentation implies the type here is a string? In the link you shared it says the type it accepts is `object`.

<img width="637" alt="Screenshot 2023-11-07 at 09 24 10" src="https://github.com/openai/openai-python/assets/23125036/d0c1bb13-5c3e-4473-a54e-32fdebf1424f">

**Comment by Hendler** [comment]
Thank you for the quick response. Documentation consistent for that endpoint (I misread).
Other endpoints appear to accept literals. Only a consistency issue.
