### ISSUE TITLE
Type incompatibility between ToolAssistantToolsFunctionFunction and Function

### ISSUE THREAD

**Issue by rgbkrk** [openai/openai-python#710]
`Function` from `types/chat/completion_create_params.py` is not compatible with `ToolAssistantToolsFunctionFunction` from `types/beta/assistant_create_param` because `description` is not a required field. 

I have existing code that's emitting a `Function` schema and using the type. Now that I'm transitioning some work over to assistants, I'd like to use the same function schema generation I've had before. For the moment I'll probably switch to using `ToolAssistantToolsFunctionFunction`, however these types may need some alignment.

**Comment by Alisultani1** [comment]
What I do

**Comment by RobertCraigie** [comment]
This has been fixed in `v1.2.0`! You can now use the following type: `from openai.types import FunctionDefinition`, the previous type definitions have been removed.

**Comment by rgbkrk** [comment]
Rad, I love it. Thanks for all the rapid releases.
