### ISSUE TITLE
How can I use Async with Azure?

### ISSUE THREAD

**Issue by sachalachin** [openai/openai-python#712]
Just now I'm updating from 0.28.1 to the latest version and migrating. I am currently using ```
await openai.ChatCompletion.acreate
```. I understand in migrating that I need to instantiate a Client, however there doesn't appear to be an Async client for Azure, only the standard `AzureOpenAI()` that doesn't appear to support Async.

Any guidance would be much appreciated - if this is a case of it not being implemented yet then I would just keep using 0.28.1 until there is Async support for Azure.

**Comment by RobertCraigie** [comment]
Hi @sachalachin, you can import the `AsyncAzureOpenAI` class instead.

```py
from openai import AsyncAzureOpenAI

client = AsyncAzureOpenAI()
await client.chat.completions.create(...)
```
