### ISSUE TITLE
AttributeError: type object 'OpenAI' has no attribute 'beta'

### ISSUE THREAD

**Issue by GlitterMessi** [openai/openai-python#717]
I use openai version is 1.1.1
When I code like this:
```
from openai import Client as client
 self.client = client.beta.assistants.create(
            name=name,
            instructions="This is a test assistant",
            tools=[{"type": "code_interpreter"}],
            model="gpt-3.5-turbo-110"
        )

```
it happens :AttributeError: type object 'OpenAI' has no attribute 'beta'

**Comment by RobertCraigie** [comment]
This is happening because you need to instantiate the client, e.g.
```py
from openai import OpenAI

client = OpenAI()

assistant = client.beta.assistants.create(
    name=name,
    instructions="This is a test assistant",
    tools=[{"type": "code_interpreter"}],
    model="gpt-3.5-turbo-110",
)
```

**Comment by michaeldayCK** [comment]
More foundational, I'm having issues importing `OpenAI` prior to instantiation.

`ImportError: cannot import name 'OpenAI' from 'openai'`

Python 3.8.15
openai Version: 1.2.2

**Comment by RobertCraigie** [comment]
@michaeldayCK that will be happening because you're running code in a different environment than the one you're installing the library to. You'll be unintentionally using the old version, you can check which version you have with this code:
```py
import openai
print(openai.VERSION)
```

**Comment by michaeldayCK** [comment]
Ah, thank you. Changing the sys.path to the right package did the trick.
