### ISSUE TITLE
TypeError: object ImagesResponse can't be used in 'await' expression

### ISSUE THREAD

**Issue by Showdown76py** [openai/openai-python#723]
With `AsyncOpenAI`, `openai.images.generate` does not work correctly when it is used with await, but it works without await. This seems to work perfectly in NodeJS, but not here in Python.

Example code:

```
response = await openai.images.generate(
    model="dall-e-3",
    prompt=prompt,
    n=1,
    quality="hd",
    response_format="b64_json",
    size=("792x1024"
)
```

And here is the traceback:

```
Traceback (most recent call last):
  File "app.py", line 83, in dall_e
    response = await openai.images.generate(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object ImagesResponse can't be used in 'await' expression
```

By removing `await`, it works correctly, but it is obviously not running asynchronously.

**Comment by RobertCraigie** [comment]
Can you share a full code snippet? I suspect you're using the module level client.

The method is defined with async so it should be impossible to not use await. https://github.com/openai/openai-python/blob/main/src/openai/resources/images.py#L438

**Comment by Showdown76py** [comment]
> Can you share a full code snippet? I suspect you're using the module level client.
> 
> The method is defined with async so it should be impossible to not use await. https://github.com/openai/openai-python/blob/main/src/openai/resources/images.py#L438

You were right! I used `openai` instead of the client. Thank you!
