### ISSUE TITLE
Support for generate function's json object

### ISSUE THREAD

**Issue by Dragon-GCS** [openai/openai-python#726]
For using func_call, hoping there is a parse tool to genenrate a json object of funtion's description. Like that:

1. Write an utils function with docstring

  ```python
  def foo(a: str, b: int = 0) -> None:
      """"
      Description for funcion
  
      Args:
          a(str): argument a
          b(int): argument b
      """"
  ```

2. Parse the `foo`

  ```python
  from openai.xxx import parse
  
  parse(foo)
  ```
  will get the output
  ```json
  {
    "type": "function",
    "function": {
       "name": "foo",
       "description": "Description for funcion",
       "parameters": {
          "type": "object",
          "properties": {
             "a": {"type": "str", "description": "argument a"},
             "b": {"type": "int", "description": "argument b"},
           },
           "required": ["a"],
        },
      },
  }
  ```

Maybe can use the `inspect` to get the argmument name and annotions, use `func.__doc__` and `re` to extract the descriptions of function and argmuents, or even call GPT to do that.
If this is ok, mayby I could try to do it.

**Comment by lucasgadams** [comment]
@Dragon-GCS  use pydantic (Model.schema) or use something like https://github.com/PrefectHQ/marvin

**Comment by RobertCraigie** [comment]
In case it helps, you can create a JSON schema from a function definition very easily with Pydantic

```py
import json
import inspect

import pydantic

def foo(a: str, b: int = 0) -> None:
    """
    Description for funcion

    Args:
        a(str): argument a
        b(int): argument b
    """

schema = pydantic.TypeAdapter(foo).json_schema()
doc = inspect.getdoc(foo)
if doc:
    schema['description'] = doc
print(json.dumps(schema, indent=2))
```

**Comment by Dragon-GCS** [comment]
> In case it helps, you can create a JSON schema from a function definition very easily with Pydantic
> 
> ```python
> import json
> import inspect
> 
> import pydantic
> 
> def foo(a: str, b: int = 0) -> None:
>     """
>     Description for funcion
> 
>     Args:
>         a(str): argument a
>         b(int): argument b
>     """
> 
> schema = pydantic.TypeAdapter(foo).json_schema()
> doc = inspect.getdoc(foo)
> if doc:
>     schema['description'] = doc
> print(json.dumps(schema, indent=2))
> ```

This is helpful for me, thanks. I can close this issue now.
