### ISSUE TITLE
JSON errors not decoded into APIError correctly

### ISSUE THREAD

**Issue by pencil** [openai/openai-python#734]
The following code does not work as expected since the release of 1.0:

```python
import openai
client = openai.Client(api_key='...')
file = open('demo.wav', 'rb')
try:
    client.audio.transcriptions.create(model="whisper-1", file=file)
except openai.BadRequestError as e:
    print(e.code)
    print(e.message)
```

This prints
```
None
Error code: 400 - {'error': {'message': 'Audio file is too short. Minimum audio length is 0.1 seconds.', 'type': 'invalid_request_error', 'param': 'file', 'code': 'audio_too_short'}}
```
so it appears `e.code` is not getting set correctly to the expected value of `audio_too_short`. Similarly `param` and `type` are not getting decoded correctly from the error response.

Here is a 0s WAV file that can be used to reproduce the issue: [demo.wav.zip](https://github.com/openai/openai-python/files/13299045/demo.wav.zip)

**Comment by RobertCraigie** [comment]
Thanks for the bug report, I can reproduce the error. Working on a fix.

**Comment by RobertCraigie** [comment]
This has been fixed in v1.2.2!

**Comment by pencil** [comment]
@RobertCraigie Thank you for the quick fix! I just tested 1.2.2 and can confirm that this is now fixed.

**Comment by take0x** [comment]
In this context, `print(e.message)` shows the same message as `print(e)`.
Is this by design? Is there a way to get `message`?

**Comment by RobertCraigie** [comment]
Ah that is a separate bug, thanks for reporting!

**Comment by take0x** [comment]
> In this context, `print(e.message)` shows the same message as `print(e)`. Is this by design? Is there a way to get `message`?

It doesn't seem to have been fixed yet in v1.9.0.
Could someone please fix it?

**Comment by RobertCraigie** [comment]
Ah sorry for the delay in fixing this @take0x, this is a little tricky.

Right now you can get the message that the API responded with by using `err.body.get('message')`.

**Comment by take0x** [comment]
> Ah sorry for the delay in fixing this @take0x, this is a little tricky.
> 
> Right now you can get the message that the API responded with by using `err.body.get('message')`.

Thank you for the alternative suggestion. I'll try it!
