### ISSUE TITLE
client.audio.transcriptions.create takes one positional argument but 3 were given

### ISSUE THREAD

**Issue by maylad31** [openai/openai-python#735]
I was just trying to update my code with latest openai. But i get this response. I just pass model, file and prompt as i did in previous versions.

**Comment by RobertCraigie** [comment]
You will have to make method calls like this:

```py
from openai import OpenAI
from pathlib import Path

transcription = client.audio.transcriptions.create(
    file=Path('filepath'),
    model="whisper-1",
)
```

**Comment by maylad31** [comment]
I am calling it the same way

**Comment by RobertCraigie** [comment]
Can you share a full code snippet?

**Comment by maylad31** [comment]
this was my previous code when i was using previous openai version(0.27.2)
@retry(stop=stop_after_attempt(2), wait=wait_fixed(3))
def get_transcript(file_location):
    transcript = openai.Audio.transcribe("whisper-1", open(file_location,"rb"),response_format="verbose_json",prompt="Umm, let me think like, hmm... Okay, here's what I'm, like, thinking.",language="en",request_timeout=30)
    return transcript

Now i updated to 1.1.1 and replaced openai.Audio.transcribe with client.audio.transcriptions.create

**Comment by RobertCraigie** [comment]
Yes you need to pass the arguments with names, you cannot pass them positionally anymore
```py
@retry(stop=stop_after_attempt(2), wait=wait_fixed(3))

def get_transcript(file_location):

          transcript = openai.audio.transcriptions.create(model="whisper-1", file=open(file_location,"rb"),response_format="verbose_json",prompt="Umm, let me think like, hmm... Okay, here's what I'm, like, thinking.",language="en",request_timeout=30)

          return transcript
```

**Comment by maylad31** [comment]
Just one last thing, If i don't update to 1.1.1 and continue to use 0.27.2, is there an issue? I guess they both are calling the same api?

**Comment by RobertCraigie** [comment]
Yes they are both calling the same API but the v0 version will not be updated whenever the API is updated, unlike the v1 version which will continue to be updated.

So you will have to update to v1 if you want to use any of the features announced on devday and any features in the future.
