### ISSUE TITLE
Add back support for OPENAI_API_BASE environment variable

### ISSUE THREAD

**Issue by igoralveslima** [openai/openai-python#745]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

For my environment I need to configure this library via environment variables. I use to be able to define the base URL via `OPENAI_API_BASE` but no longer can. I am also not able to define a base_url and a `AZURE_OPENAI_ENDPOINT` at the same time. 

I understand v1 now exposes the ability for set base_url with  `_httpx.URL`, but after reading the httpx documentation, it does not seem immediately clear how to do so via environment variables.

**Comment by rattrayalex** [comment]
Thanks, we're working on this! It'll be under a different name.

**Comment by igoralveslima** [comment]
Great to hear, thanks for the reply @rattrayalex

**Comment by johanste** [comment]
In the meantime, there are docs [here](https://github.com/openai/openai-python#microsoft-azure-openai) that shows how to use the library to talk to Azure OpenAI endpoints.

**Comment by piiq** [comment]
Hi 👋, is there any update on this one?

I've seen in https://github.com/openai/openai-python/issues/624 that it's going to be `OPENAI_BASE_URL` instead of `OPENAI_API_BASE`, but IIUC it's not there yet

**Comment by rattrayalex** [comment]
This is indeed supported now with the `OPENAI_BASE_URL` environment variable, as documented here: https://github.com/openai/openai-python#configuring-the-http-client

**Comment by piiq** [comment]
@rattrayalex I don't see any mention of the env variable in the section you linked. Also from my test yesterday this variable is not supported. Could you kindly explain how to use the env variable, please?

**Comment by piiq** [comment]
Sorry, my comment yesterday (deleted) was not accurate. It's all good on my end, thanks a lot.
🙏💪❤️

**Comment by levy9527** [comment]
I've test on my computer, in 2024, openai 1.6.x, you still can and should use the env var: `OPENAI_API_BASE`
