### ISSUE TITLE
Implement retrieving information about all threads without providing a thread id

### ISSUE THREAD

**Issue by mirandadam** [openai/openai-python#750]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Please implement fetching all the thread ids available from the python library.

That would be similar to calling the following, which works as of 2023-11-09 9:16 UTC:
```python
r = httpx.get(
    "https://api.openai.com/v1/threads",
    headers={
        "Authorization": "Bearer " + api_key,
        "Content-Type": "application/json",
        "OpenAI-Beta": "assistants=v1",
    },
)
``` 

The existing ```OpenAI.beta.threads.retrieve``` requires a specific thread id, and calling it with an empty id produces #749.

*At this time this endpoint does not seem to be documented. See https://platform.openai.com/docs/api-reference/threads/getThread*

### Additional context

See issue #749 for an actual bug triggered by trying to retrieve information about all the threads using the existing 
```OpenAI.beta.threads.retrieve```.

**Comment by rattrayalex** [comment]
That endpoint is not generally available at this time.

**Comment by mirandadam** [comment]
Thanks for the quick reply. As of this moment the httpx snipped above now throws *ReadTimeout/TimeoutError: The read operation timed out* instead of returning the thread list, which from your answer I understand is the expected outcome.

The feature suggestion remains, though, to aid with voluntary application housekeeping. If the outstanding threads make no difference to OpenAi, this is hardly a priority.
