### ISSUE TITLE
Get request headers data

### ISSUE THREAD

**Issue by SOSwifty** [openai/openai-python#757]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

When sending a request to openAI through this library in removes a lot of valuable metadata that comes back via headers, keeping those headers as part of the response would be great.

**Comment by RobertCraigie** [comment]
You can access the response headers, see these docs: https://github.com/openai/openai-python?tab=readme-ov-file#accessing-raw-response-data-eg-headers
