### ISSUE TITLE
Hope to cancel "required_args" mecanism. Upgraded openai-python (v0->v1) refuses argumment "repetition_penalty"

### ISSUE THREAD

**Issue by TissueC** [openai/openai-python#767]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I notice that about 2 weeks ago  [vllm](https://github.com/vllm-project/vllm)  has merged pr about adding an argument `repetition_penalty` aligned with huggingface. (refer to [pr 1424](https://github.com/vllm-project/vllm/pull/1424))

However, openai-python also graded to v1 several days ago. it refuses the unknown argument repetition_penalty. The following is the detail error.
` xxx/examples/openai_chatcompletion_client.py", line 72, in <module>
    chat_completion = client.chat.completions.create(
  File "/opt/conda/lib/python3.10/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'repetition_penalty'`

This conflict makes that we can not depend openai library for open-source models and self-defined arguments (much more than repetition_penalty). This library has been factually used in many API-based model deployment library like fastchat and vllm. 

I really hope that the `required_args` can be removed. At least, we can modify its behaviors without modifying the source code of openai-python.

### To Reproduce

1. git clone vllm and setup it.
2. Make some request using vllm and openai, add arguments `repetition_penalty` 
3. The error happens.

### OS

Linux

### Python version

Python v3.10

### Library version

openai v1.2.2

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll consider this. We us that to help enable good typing of overloads, which is an important feature.

**Comment by RobertCraigie** [comment]
This is not anything to do with `required_args`, what you're trying to do is pass a custom request parameter which is supported by the `extra_body` argument.

```py
from openai import OpenAI

client = OpenAI()
client.chat.completions.create(
  model='gpt-4',
  messages=....,
  extra_body={'repetition_penalty': 2},
)
```
