### ISSUE TITLE
Response Format `verbose_json` in Audio Transcription with V1 Library

### ISSUE THREAD

**Issue by Doma1204** [openai/openai-python#770]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

There is a few response formats documented in the [OpenAI documentation](https://platform.openai.com/docs/api-reference/audio/createTranscription#audio-createtranscription-response_format), but it seems that the V1 library only supports for the response of response format `json`.

It is fine when using the V0 library as it will return an entire response body. However, since V1 library return a Pydantic model, and the [`Transcription`](https://github.com/openai/openai-python/blob/v1.2.2/src/openai/types/audio/transcription.py#L8) model only has a `text` property. Even if I request the transcript in `verbose_json` format, the extra properties (e.g. `duration`, `language`) are dumped after parsing to a Pydantic model.

It should be able to add the extra properties to the Pydantic model. Can the team work on it, please?

**Comment by RobertCraigie** [comment]
> Even if I request the transcript in verbose_json format, the extra properties (e.g. duration, language) are dumped after parsing to a Pydantic model.

What do you mean here? Even properties that aren't defined on the Pydantic model should still be accessible at runtime if the API includes it in the response body.

For the other response formats, you'll currently have to access the data using [raw responses](https://github.com/openai/openai-python?tab=readme-ov-file#accessing-raw-response-data-eg-headers) unfortunately. We're looking into ways to improve this in the future.

**Comment by Doma1204** [comment]
I'm sorry, that's my fault. I got confused about the raised exception. I was accessing the segments properties with dot syntax (`result.segments[0].id`) and there's an error. I looked at the source code and thought all other properties are gone.

Thanks for the clarification.

**Comment by RobertCraigie** [comment]
No worries!
