### ISSUE TITLE
TypeError: 'ChatCompletionMessage' object is not subscriptable

### ISSUE THREAD

**Issue by roland71** [openai/openai-python#774]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

    content_with_padding_02 = "\u200B\n\n" + response_02.choices[0].message['content']

TypeError: 'ChatCompletionMessage' object is not subscriptable

### To Reproduce

    content_with_padding_02 = "\u200B\n\n" + response_02.choices[0].message['content']

TypeError: 'ChatCompletionMessage' object is not subscriptable

### Code snippets

```Python
content_with_padding_02 = "\u200B\n\n" + response_02.choices[0].message['content']

TypeError: 'ChatCompletionMessage' object is not subscriptable
```

### OS

macOS

### Python version

3.11.4

### Library version

1.0.1

**Comment by RobertCraigie** [comment]
The `[]` syntax is not supported, you need this instead:

```py
content_with_padding_02 = "\u200B\n\n" + response_02.choices[0].message.content
```

**Comment by gMerm** [comment]
thanks
