### ISSUE TITLE
ValueError for missing api_version when calling with_options() on an (Async)AzureOpenAI client instance

### ISSUE THREAD

**Issue by gleason-m** [openai/openai-python#779]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Calling `with_options()` on an AzureOpenAI or AsyncAzureOpenAI client instance throws a ValueError exception:
> ValueError: Must provide either the `api_version` argument or the `OPENAI_API_VERSION` environment variable

### To Reproduce

Initialize an AzureOpenAI client and call `with_options()` on it.

### Code snippets

```Python
from openai import AsyncAzureOpenAI

client = AsyncAzureOpenAI(
    azure_endpoint="",
    api_key="mykey",
    api_version="2023-07-01-preview",
)

copied_client = client.with_options(timeout=30)
```

### OS

ubuntu 22.04

### Python version

v3.10.12

### Library version

opeanai v1.1.2

**Comment by rattrayalex** [comment]
Thanks for reporting, we'll try to fix this on Monday.

**Comment by Mikkolehtimaki** [comment]
Still running into this on openai-1.3.3 client.

**Comment by rattrayalex** [comment]
Thank you for following up @Mikkolehtimaki , I'm so sorry we let this slip! We'll take a look soon.

**Comment by RobertCraigie** [comment]
This will be fixed in the next release, sorry for the delay!

**Comment by chenxy1021** [comment]
> 该问题将在下一个版本中修复，抱歉延迟了！

Still not fixed

**Comment by rattrayalex** [comment]
This should have been fixed in https://github.com/openai/openai-python/pull/858 which was released in https://github.com/openai/openai-python/releases/tag/v1.3.5

Can you try that version and share the traceback you see, along with your code causing it?

**Comment by ahmedbr** [comment]
I have same error with the following set of requirements:

openai==1.10.0
langchain==0.1.4
langchain-community==0.0.16
langchain-core==0.1.16
langchain-openai==0.0.5
