### ISSUE TITLE
Redirects aren't working anymore on version 1.x (with private api)

### ISSUE THREAD

**Issue by fredi-python** [openai/openai-python#785]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

So, I am running a private API, that is/was compatible with the openai python library.
In one of my endpoints, I am redirecting to another endpoint, to give model specific rate limits with slowapi.
`return RedirectResponse(url="/v1/chat/completions/llama-70b-chat")` <- this works just fine with version 0.28 and you get no response status code failure, but on the newest version, its raising an error saying response code was 307.

### To Reproduce

1. Make a openai library compatble fastapi server, with one endpoint redirecting to another.
2. call the first endpoint with library version 0.28 and with the newest version 1.x
3. you can see that the endpoint works on older versions, as they seem to allow redirects. But on newer versions it throws you the response code failure

### Code snippets

```Python
# FASTAPI EXAMPLE
import time

import fastapi
from starlette.responses import RedirectResponse

app = fastapi.FastAPI()

@app.post("/v1/chat/completions")
def chat_compl():
    return RedirectResponse(url="/v1/chat/completions/new")

@app.post("/v1/chat/completions/new")
def chat_compl():
    return {"id": f"chatcmpl-fag4646utg49a",
            'object': 'chat.completion',
            'created': int(time.time()),
            'model': f'test',
            'choices': [
                {'index': 0, 'message':
                    {'role': 'assistant',
                     'content': "This is a test."},
                 'finish_reason': 'stop'}],
            'usage': {'prompt_tokens': 17, 'completion_tokens': 16, 'total_tokens': 33}}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)


# CLIENT EXAMPLE VERSION 0.28 (working)
import openai

openai.api_base = "http://localhost:8000/v1"
openai.api_key = "Some random text"

response = openai.ChatCompletion.create(
    model="test",
    messages=[
        {"role": "system", "content": "Doesnt matter what you write here"},
        {"role": "user", "content": "Doesnt matter what you write here"}
    ])

print(response)


# CLIENT EXAMPLE VERSION 1.x (Not working)
import os
import openai
from openai import OpenAI

client = OpenAI(base_url="http://localhost:8000/v1", api_key="some random text")

response = client.chat.completions.create(
    model="test",
    messages=[
        {"role": "system", "content": "Doesnt matter what you write here"},
        {"role": "user", "content": "Doesnt matter what you write here"}
    ]
)

print(response)
```

### OS

Arch Linux

### Python version

Python 3.11.5

### Library version

openai v1.x

**Comment by RobertCraigie** [comment]
Yes redirects are not enabled by default, if you want to enable them you'll have to instantiate a custom http client with follow_redirects=True

https://github.com/openai/openai-python?tab=readme-ov-file#configuring-the-http-client

https://www.python-httpx.org/quickstart/#redirection-and-history

We'll look into documenting this better and improving the error message.

**Comment by fredi-python** [comment]
Thanks a lot, but why did you remove the default for allowing redirects? That would make such things much more easier.

**Comment by RobertCraigie** [comment]
We changed the underlying http library we use and they decided to not allow redirects by default.

The reasoning, which I agree with, is outlined here: https://github.com/encode/httpx/discussions/1785

**Comment by fredi-python** [comment]
Ok I guess I need to find a way for request specific rate limits in fastapi then, instead of just redirecting to another endpoint that has the custom limit.

**Comment by RobertCraigie** [comment]
What do you mean sorry?

You can still enable redirects in v1
```py
import httpx
from openai import OpenAI

client = OpenAI(
  http_client=httpx.Client(
    follow_redirects=True
  )
)
```

**Comment by fredi-python** [comment]
Oh sorry, should have given you more context.
So, I am running a private openai package compatible API, that also has rate limiting. But the library I am using for rate limiting (slowapi) doesn't have a feature to set payload specific rate limits for the endpoints (fastapi).
That's why I was using redirects, to set a custom rate limit on the endpoint where it gets redirected to when the model in the payload equals `llama-70b`

**Comment by rattrayalex** [comment]
Closing because this can be enabled with [the code shown here](https://github.com/openai/openai-python/issues/785#issuecomment-1806836046). We turn it off by default to help highlight cases where you're doing unnecessary amounts of traffic.
