### ISSUE TITLE
Streaming Completions for Assistant Thread Output

### ISSUE THREAD

**Issue by R-802** [openai/openai-python#792]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Add streaming functionality to assistant messages.

**Comment by rattrayalex** [comment]
Thanks for the suggestion! I've passed it along to the right team.

Ideas like this for the API belong at community.openai.com – I'm going to go ahead and close this because it's not an issue with the Python library specifically.
