### ISSUE TITLE
Tool invocation via API

### ISSUE THREAD

**Issue by sidhujag** [openai/openai-python#797]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Can we have tools invoked by the API so we can have control over access:

# Example #
# Assuming you've already uploaded your files and have their IDs
```
file_ids = ["file-123abc", "file-456def"]

response = openai.Tool("retriever").create(
    file_ids=file_ids,
    query="Find information about GPT-3 capabilities"
)

# For Code Interpreter
code_snippet = """
with open('my_uploaded_file.txt', 'r') as file:
    data = file.read()
    # Process data...
"""
response = openai.Tool("code-interpreter").create(
    code=code_snippet,
    file_id="file-123abc"
)
```

This would remove the need for local sandboxed environments to run the tools. In a work around we can instruct through inference to run a tool but its not ideal as context is misused for data parameterization.

**Comment by rattrayalex** [comment]
Thanks for the suggestion! I've passed it along to the right team.

Ideas like this for the API belong at community.openai.com – I'm going to go ahead and close this because it's not an issue with the Python library specifically.
