### ISSUE TITLE
ChatCompletion Not Accessible via openai.types in init.py

### ISSUE THREAD

**Issue by Freerasinbread** [openai/openai-python#799]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [ ] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Environment:

openai-python version: Most recent version
Python version: 3.11.2
Operating System: Win 11

Description:
I have encountered an issue where ChatCompletion cannot be accessed via openai.types as one would expect from the module's __init__.py. This is causing type hinting and direct import issues for developers trying to use type hints with the openai client for chat-based operations.

Steps to Reproduce:

1. Install the latest version of openai-python client.
2. Attempt to import ChatCompletion using the following code snippet:
`from openai.types import ChatCompletion`
3. Observe the ImportError that occurs.

Expected behavior:
I expected to be able to access all types relevant to chat completions directly through openai.types for consistency and convenience when using type hints.

Actual behavior:
An ImportError is raised when attempting to import ChatCompletion from openai.types, suggesting that it is not exported properly in __init__.py.

Possible Fix:
Ensure that ChatCompletion and other relevant types are accessible through openai.types by adjusting the __init__.py file accordingly.

### Additional context

Access to consistent and correct type hints is crucial for developing robust applications with proper static code analysis. The current inability to import ChatCompletion as expected hinders this process and could lead to less type-safe code.

Thank you for looking into this matter. I am looking forward to the fix.

**Comment by Andres-Ventura** [comment]
I can take on this issue. Please assign to me :)

**Comment by RobertCraigie** [comment]
You can import all types from `openai.types.chat`.
