### ISSUE TITLE
Add copy thread API

### ISSUE THREAD

**Issue by Undertone0809** [openai/openai-python#801]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

It seems that there is not copy thread API. I think it's a common scenario to use it.

A possible design is as follows:

```python
from openai import OpenAI

original_thread_id = "xxx"
client = OpenAI()
thread = client.beta.threads.copy(thread_id=original_thread_id)
```

I want to hear your thoughts.

**Comment by rattrayalex** [comment]
Thanks for the feature request! API suggestions like this belong in community.openai.com – I'm going to close this issue since it's not specific to the Python library, but it doesn't mean we won't consider the API.
