### ISSUE TITLE
How to get usage in streaming response?

### ISSUE THREAD

**Issue by sailxjx** [openai/openai-python#818]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

We can use `print(dict(completion).get('usage'))` to get the token usage of the request, but in streaming mode, there is no way to get the token usage. It would be great if there was a way to retrieve token usage in streaming mode as well.

**Comment by hansh0801** [comment]
i also got same issue.

**Comment by rattrayalex** [comment]
The API does not support `usage` in streaming at this time; when it is, support will be included in the Python SDK.
