### ISSUE TITLE
add list method for  threads object

### ISSUE THREAD

**Issue by codemee** [openai/openai-python#822]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

It seems that there's an undocumented GET endpoint for the threads in the underlying OpenAI API that can list all the treads. It's convenient for developers to see all the threads since this can't be done in the Assistants page in the playgound site.

**Comment by rattrayalex** [comment]
If and when that endpoint becomes officially documented, this library will support it.

**Comment by BernardasJuzumasBiomapas** [comment]
There is also an issue with not being able to remove threads that were created during test runs. Currently, there is no way to access previous threads either from UI or from API. This is incredibly frustrating.

**Comment by codemee** [comment]
@BernardasJuzumasBiomapas this might be help to find out all the threads you created.

```python
def list_threads(api_key):
    response = requests.get(
        'https://api.openai.com/v1/threads?order=desc&limit=20',
        headers={
           'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}',
            'OpenAI-Beta': 'assistants=v1'
        }
    )
    if response.status_code == 200:
        return response.json()['data']
    return None
```

**Comment by BernardasJuzumasBiomapas** [comment]
> @BernardasJuzumasBiomapas this might be help to find out all the threads you created.
> 
> ```python
> def list_threads(api_key):
>     response = requests.get(
>         'https://api.openai.com/v1/threads?order=desc&limit=20',
>         headers={
>            'Content-Type': 'application/json',
>             'Authorization': f'Bearer {api_key}',
>             'OpenAI-Beta': 'assistants=v1'
>         }
>     )
>     if response.status_code == 200:
>         return response.json()['data']
>     return None
> ```
Thanks!
Not sure if this is just me, but I am not allowed to use the API key to perform this query. Had to get my session key from the browser UI to make it work.

**Comment by codemee** [comment]
I think someone disable it. The response status code is 401.

**Comment by codemee** [comment]
Accessing the endpoint outside a browser session is blocked by the server now.

![image](https://github.com/openai/openai-python/assets/1037913/28518bf1-40b9-490d-bf1d-b42b06736bb2)

**Comment by jizidoro** [comment]
this issue is still happening

**Comment by omni-kight** [comment]
Same here
