### ISSUE TITLE
Client objects are not pickle-able for multiprocess programs

### ISSUE THREAD

**Issue by XuehaiPan** [openai/openai-python#837]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I am developing a program that employs multiprocessing to enhance efficiency through parallel execution. Python relies on the `pickle` module for object serialization and inter-process communication. It would be nice if we let all classes in the `openai` package be pickle-able。

### To Reproduce

1. Create an `OpenAI` or `AsyncOpenAI` client.
2. Serialize the client using the `pickle` module.

### Code snippets

```Python
import pickle

from openai import OpenAI, AsyncOpenAI


client = OpenAI(api_key='sk-...')
async_client = AsyncOpenAI(api_key='sk-...')

pickle.dumps(client)  # TypeError: cannot pickle '_thread.RLock' object
pickle.dumps(async_client)  # TypeError: cannot pickle '_thread.RLock' object
```

### OS

macOS

### Python version

Python 3.11.6

### Library version

openai v1.3.0

**Comment by antont** [comment]
usually pickling does not make sense for client objects, as they hold a connection that a single process only can use.

but i think you can pass the data objects between processes, because they are Pydantic classes which support serialization in json at least out of the box.

**Comment by RobertCraigie** [comment]
Like @antont mentioned, it doesn't make sense for client objects to be pickled. You should be able to share the data the API returns between processes but you'll have to instantiate a new client for every process.
