### ISSUE TITLE
Keep Conversation History

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [openai/openai-python#845]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

When using the API, it should be the case that conversation history is kept. While one can do this manually (by providing the history in the prompt), this costs additional API tokens...

**Comment by thezapalsky** [comment]
The fundamental architecture of the OpenAI API is based on a vanilla encoder-decoder model. 
To provide context for the conversation (such as chat history) it needs to be explicitly passed with each API call. 
Without this additional context, the model lacks information to generate meaningful responses. Therefore, including the chat history in the prompt is necessary for the API to infer and respond appropriately.

I don't think there's a way to omit that, given the architecture of the core model's engine.

**Comment by antont** [comment]
> To provide context for the conversation (such as chat history) it needs to be explicitly passed with each API call. 

Is this different with assistants where the service seems to store the threads?

**Comment by ImahnShekhzadeh** [comment]
[This API wrapper](https://github.com/0xacx/chatGPT-shell-cli) allows for interactive interaction (i.e. where the context is stored), maybe this could be an interesting addition for the official API?

**Comment by rattrayalex** [comment]
Thanks for the suggestion! I suggest you look into the new assistants API.
