### ISSUE TITLE
Continue fine tuning a model e.g. text-davinci-002

### ISSUE THREAD

**Issue by eyaler** [openai/openai-python#86]
I am only able to define the base model for fine-tuning as ada, babbage, curie or davinci. I would like to be able to (1) fine tune on the official fine tuned models, e.g. text-davinci-002 to allow me to compare my fine tuning to the default latest and greatest. And of lesser importance: (2) continue a fine-tuning on my own models.

**Comment by hallacy** [comment]
Thanks for writing in @eyaler! I'll forward this along to the fine tuning group

**Comment by hallacy** [comment]
This has now been implemented! https://beta.openai.com/docs/guides/fine-tuning/continue-fine-tuning-from-a-fine-tuned-model

**Comment by hallacy** [comment]
Well, (2) has.  Newer models take awhile for us to deriksk, though we roll them out when we can

**Comment by eyaler** [comment]
@hallacy thanks! should i open a new issue for (1)?

**Comment by hallacy** [comment]
I would probably suggest no, but there are reasons for yes:
No: Frankly this repo doesn't have the ability to support this request.  The ability to finetune comes from our API and this repo serves mostly as a wrapper to the API.  I wouldn't be able to take any action on this repo to enable the feature in the future.

Yes: There isn't a publicly facing place for developers to vote on OpenAI feature requests.  Arguably, the best places for making your wishes known to openai are either (and this is the currently preferred method) writing in to support@openai.com with your request, in a repo like this (and then having other developers emoji react or +1 or something), or @ing us on social media.

Hopefully that helps.  Let me know if it doesn't
