### ISSUE TITLE
Pylint complains when using Stream[ChatCompletionChunk]: E1133 not-an-iterable

### ISSUE THREAD

**Issue by mroedder-d7** [openai/openai-python#870]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I´m constructing a chat completion response:
```
query_response: Stream[ChatCompletionChunk] = client.chat.completions.create(
            ...
            stream=True,
        )
```
Then, when iterating over the chunks, it works but Pylint raises an error:
```
        for chunk in query_response:
            choice = chunk.choices[0]
```
Error:
**Non-iterable value query_response is used in an iterating context**

### To Reproduce

1. Create a chat completion with streaming enabled
2. Read chunks by iterating over the Stream
3. Run pylint

### OS

macOS

### Python version

3.11.5

### Library version

1.3.5

**Comment by RobertCraigie** [comment]
Please report an issue with pylint, this class is iterable so there's a bug in their logic.

Personally I'd also recommend just disabling lint rules like this and instead use a type checker, e.g. [Pyright](https://github.com/microsoft/pyright), as those pylint rules are essentially just a much more limited version of type checker.
