### ISSUE TITLE
Allow filename to be passed as a parameter into `files.create`

### ISSUE THREAD

**Issue by davidgonmar** [openai/openai-python#871]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [x] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Right now, you can only pass a FileTypes file object into the `files.create` function. Therefore, when doing
```py
with open("some_file.txt", "r") as f:
        file = f.read()
    openai_file = openai.files.create(file=file, purpose="assistants")
```
there is no way of passing a filename into the request (altough the endpoint accepts one, the library provides no way of passing one manually).
A workaround I found is 
```py
response = openai.files.create(file=Path(file_path), purpose="assistants")
```
but I think many people don't know about it, and you cannot provide a different filename than the one in the file system.

I can look into the library and make a PR myself if the feature sounds good:)

**Comment by RobertCraigie** [comment]
You can pass a file name by passing a tuple instead of the file contents directly. The API is the same as the underlying http library https://www.python-httpx.org/quickstart/#sending-multipart-file-uploads

**Comment by davidgonmar** [comment]
Got it! Thanks:)

**Comment by nonconvexopt** [comment]
It does not work in my case. Below are my code:
```
for file in st.file_uploader('이미지 또는 PDF 파일 업로드', accept_multiple_files=True):
    st.session_state.files[file.name] = client.files.create(
        file=(file.name, file),
        purpose='assistants',
    )
```

However, GPT answers 'file-<some random string>' as a file name when asked.

**Comment by nonconvexopt** [comment]
@RobertCraigie It does not work in my case. Below are my code:
```
for file in st.file_uploader('이미지 또는 PDF 파일 업로드', accept_multiple_files=True):
    st.session_state.files[file.name] = client.files.create(
        file=(file.name, file),
        purpose='assistants',
    )
```

However, GPT answers 'file-<some random string>' as a file name when asked.
