### ISSUE TITLE
Unclear how to use the new AsyncClient at scale - memory leaks or timeouts

### ISSUE THREAD

**Issue by rohan-mehta** [openai/openai-python#874]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I have a containerized FastAPI server.
- When I create new clients per request, I see a big memory leak. This is the same as #820.
- When I create a global AsyncClient that is reused across requests, I see regular `httpx.PoolTimeout`s. Similar to #821, except mine is async

As a result, its not clear how to use the new library at scale. It seems like the optimal solution would be to manage a pool of AsyncClients and scale them up/down as QPS goes up/down. Looking for suggestions/advice on how to handle this. Thanks! 

### To Reproduce

Use this as the client:
```
def get_openai_client() -> AsyncOpenAI:
    if not hasattr(get_openai_client, "client"):
        get_openai_client.client = AsyncOpenAI(
            api_key="...",
        )
    return get_openai_client.client
```

And then send a bunch of requests/see timeouts.

### OS

Linux

### Python version

3.11

### Library version

1.3.4

**Comment by rattrayalex** [comment]
I recommend instantiating the client once, using expanded connection pool limits, like those suggested here: https://github.com/openai/openai-python/issues/821#issuecomment-1811659617

**Comment by richardknudsen** [comment]
@rattrayalex for any other future readers that may stumble over the following as well: 
Shouldn't it be `httpx.AsyncClient` instead of `httpx.Client`?
