### ISSUE TITLE
[Security][PIP] [Github] Setup  dependabot in the repo

### ISSUE THREAD

**Issue by omonimus1** [openai/openai-python#879]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Setup Dependentbot in the repo, to have a daily scan for possible outdated dependencies, which represents a vulnerability risk. 
Assignee: @omonimus1
PR presented:

**Comment by rattrayalex** [comment]
As mentioned elsewhere, we use a separate system to perform this. We'll consider doing this more publicly in the future, but I don't expect it to happen soon.
