### ISSUE TITLE
CI pipeline is not running Unit tests

### ISSUE THREAD

**Issue by omonimus1** [openai/openai-python#881]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

CI pipeline is not running Unit tests.

### To Reproduce

1 . Open a PULL request against the main branch. 
2. See that tests do not run => Is clear when observing the ci.yml file

### OS

ANY

### Python version

ANY

### Library version

ANY

**Comment by rattrayalex** [comment]
This is for security reasons – an OpenAI engineer must manually approve each contributor to allow tests to be run. I know it's surprising and disappointing, sorry about that.
