### ISSUE TITLE
Error from openai import OpenAI

### ISSUE THREAD

**Issue by lolminerxmrig** [openai/openai-python#883]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

1.py", line 1, in <module>
    from openai import OpenAI
ImportError: cannot import name 'OpenAI' from 'openai' (C:\Python311\Lib\site-packages\openai\__init__.py)

from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="yxv9HaaUBM3Pz",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)

### To Reproduce

Win 10 x 64
python 3.11

from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="yxv9HaaUBM3Pz",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)

### Code snippets

```Python
from openai import OpenAI

client = OpenAI(
    # defaults to os.environ.get("OPENAI_API_KEY")
    api_key="yxv9HaaUBM3Pz",
)

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Say this is a test",
        }
    ],
    model="gpt-3.5-turbo",
)
```

### OS

win 10 x 64

### Python version

python 3.11.4

### Library version

open 10.1

**Comment by antont** [comment]
What version of the lib do you have installed? The version info `open 10.1` does not make sense. Current is 1.3.5, https://github.com/openai/openai-python/releases/tag/v1.3.5. The import in your code works with current versions.

```
>>> import openai
>>> from openai import OpenAI
>>> 
```

**Comment by lostmygithubaccount** [comment]
might wanna delete that API key from the message and rotate it...

**Comment by lostmygithubaccount** [comment]
to expand on that, go here: https://platform.openai.com/api-keys, delete that key you posted in the issue, and create a new one

your API key is essentially a password to your account and I or anybody seeing this could take it and use your account for malicious purposes (e.g. just running it in a for loop to cost you a lot of money)

I'd recommend keeping the key in a `.env` file or some other way of loading it into an environment variable to avoid accidentally leaking it

**Comment by rattrayalex** [comment]
It seems you may have installed the wrong package somehow.
