### ISSUE TITLE
response_format error

### ISSUE THREAD

**Issue by ruian1** [openai/openai-python#887]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

```
completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Can you generate an example json object describing a fruit?",
        }
    ],
    model="gpt-3.5-turbo",
    response_format={"type": "json_object"},
)

---------------------------------------------------------------------------
BadRequestError                           Traceback (most recent call last)
Cell In[5], line 1
----> 1 completion = client.chat.completions.create(
      2     messages=[
      3         {
      4             "role": "user",
      5             "content": "Can you generate an example json object describing a fruit?",
      6         }
      7     ],
      8     model="gpt-3.5-turbo",
      9     response_format={"type": "json_object"},
     10 )

File ~/anaconda3/envs/llama/lib/python3.10/site-packages/openai/_utils/_utils.py:299, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    297             msg = f"Missing required argument: {quote(missing[0])}"
    298     raise TypeError(msg)
--> 299 return func(*args, **kwargs)

File ~/anaconda3/envs/llama/lib/python3.10/site-packages/openai/resources/chat/completions.py:598, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_p, user, extra_headers, extra_query, extra_body, timeout)
    551 @required_args(["messages", "model"], ["messages", "model", "stream"])
    552 def create(
    553     self,
   (...)
    596     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    597 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 598     return self._post(
    599         "/chat/completions",
    600         body=maybe_transform(
    601             {
    602                 "messages": messages,
    603                 "model": model,
    604                 "frequency_penalty": frequency_penalty,
    605                 "function_call": function_call,
    606                 "functions": functions,
    607                 "logit_bias": logit_bias,
    608                 "max_tokens": max_tokens,
    609                 "n": n,
    610                 "presence_penalty": presence_penalty,
    611                 "response_format": response_format,
    612                 "seed": seed,
    613                 "stop": stop,
    614                 "stream": stream,
    615                 "temperature": temperature,
    616                 "tool_choice": tool_choice,
    617                 "tools": tools,
    618                 "top_p": top_p,
    619                 "user": user,
    620             },
    621             completion_create_params.CompletionCreateParams,
    622         ),
    623         options=make_request_options(
    624             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    625         ),
    626         cast_to=ChatCompletion,
    627         stream=stream or False,
    628         stream_cls=Stream[ChatCompletionChunk],
    629     )

File ~/anaconda3/envs/llama/lib/python3.10/site-packages/openai/_base_client.py:1063, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1049 def post(
   1050     self,
   1051     path: str,
   (...)
   1058     stream_cls: type[_StreamT] | None = None,
   1059 ) -> ResponseT | _StreamT:
   1060     opts = FinalRequestOptions.construct(
   1061         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1062     )
-> 1063     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~/anaconda3/envs/llama/lib/python3.10/site-packages/openai/_base_client.py:842, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    833 def request(
    834     self,
    835     cast_to: Type[ResponseT],
   (...)
    840     stream_cls: type[_StreamT] | None = None,
    841 ) -> ResponseT | _StreamT:
--> 842     return self._request(
    843         cast_to=cast_to,
    844         options=options,
    845         stream=stream,
    846         stream_cls=stream_cls,
    847         remaining_retries=remaining_retries,
    848     )

File ~/anaconda3/envs/llama/lib/python3.10/site-packages/openai/_base_client.py:885, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    882     # If the response is streamed then we need to explicitly read the response
    883     # to completion before attempting to access the response text.
    884     err.response.read()
--> 885     raise self._make_status_error_from_response(err.response) from None
    886 except httpx.TimeoutException as err:
    887     if retries > 0:

BadRequestError: Error code: 400 - {'error': {'message': "Invalid parameter: 'response_format' of type 'json_object' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'response_format', 'code': None}}
```

### To Reproduce

1. run the code block 
2. error

### Code snippets

```Python
completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Can you generate an example json object describing a fruit?",
        }
    ],
    model="gpt-3.5-turbo",
    response_format={"type": "json_object"},
)
```

### OS

22.04.1-Ubuntu

### Python version

3.10.13 

### Library version

 1.3.5

**Comment by rahulkbhatnagar** [comment]
The error you are encountering is due to the incorrect use of the response_format parameter in your code. The error message indicates that the response_format parameter set to {"type": "json_object"} is not supported with the model you are using, which is gpt-3.5-turbo.

The response_format parameter in the OpenAI API is used to specify how the response should be formatted. However, not all response formats are supported by all models. In this case, it seems that the gpt-3.5-turbo model does not support the json_object response format.

To resolve this issue, you can either remove the response_format parameter from your request or change the model to one that supports the json_object response format, if such a model exists. If you remove the response_format parameter, the response will default to the standard text format that is generally supported by all models.

**Comment by rahulkbhatnagar** [comment]
Here is a revised version of your code without the response_format parameter:

completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": "Can you generate an example json object describing a fruit?",
        }
    ],
    model="gpt-3.5-turbo",
)

**Comment by ruian1** [comment]
Thanks. It's the exact code from the Readme. Please update the Readme.

**Comment by rahulkbhatnagar** [comment]
Oh sure.

**Comment by rattrayalex** [comment]
You need to use `model` of `gpt-4-1106-preview` or `gpt-3.5-turbo-1106`. 

> It's the exact code from the Readme

The README of this project does not showcase `response_format`. Is there somewhere else you copied this code from?

**Comment by ruian1** [comment]
> You need to use `model` of `gpt-4-1106-preview` or `gpt-3.5-turbo-1106`.
> 
> > It's the exact code from the Readme
> 
> The README of this project does not showcase `response_format`. Is there somewhere else you copied this code from?

<img width="918" alt="Screenshot 2023-11-27 at 9 04 54 PM" src="https://github.com/openai/openai-python/assets/9713428/0c2278a4-7881-4f7c-aa6a-d5d2f3374fe9">

**Comment by rattrayalex** [comment]
Ah, thank you, sorry about that! We'll get that fixed up.

**Comment by kpetrianakis** [comment]
So, let me please ask for confirmation. `response_format={"type": "json_object"}` is only supported by model `gpt-4-1106-preview` ?

**Comment by rattrayalex** [comment]
Only by `gpt-4-1106-preview` or `gpt-3.5-turbo-1106`.

**Comment by Arvin-Feng** [comment]
response = client.chat.completions.create(
  model="gpt-3.5-turbo-1106",
  response_format={ "type": "json_object" },
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Who won the world series in 2020?"},
    {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
    {"role": "user", "content": "Where was it played?"}
  ]
)

openai.BadRequestError: Error code: 400 - {'error': {'message': "'messages' must contain the word 'json' in some form, to use 'response_format' of type 'json_object'.", 'type': 'invalid_request_error', 'param': 'messages', 'code': None}}

**Comment by jiew9404202** [comment]
Even I chose to use model "gpt-3.5-turbo-1106", I still got the same error mentioned as Arvin-Feng. Is there anything wrong?

**Comment by rattrayalex** [comment]
As the error message says, you must use the word "json" in your message.

For example, the last message in @Arvin-Feng 's code could be `{"role": "user", "content": "Where was it played? Please respond with json."}`

**Comment by jiew9404202** [comment]
@rattrayalex Thanks. It works once I add the word "json" in the messages
