### ISSUE TITLE
Calling OpenAI async no longer works after latest update

### ISSUE THREAD

**Issue by tyler-suard-parker** [openai/openai-python#888]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

Trying to use OpenAI asyncrhonously via aiohttp.  This worked in the last version of the API (like 2 or 3 weeks ago), why isn't it working now?

import openai
from aiohttp import ClientSession
self.session = ClientSession()
openai.aiosession.set(self.session)

Exception: AttributeError: module 'openai' has no attribute 'aiosession'

### To Reproduce

Run the code above

### Code snippets

```Python
import openai
from aiohttp import ClientSession
self.session = ClientSession()
openai.aiosession.set(self.session)
```

### OS

Windows 11

### Python version

Python 3.9

### Library version

openai v1.3.5

**Comment by rattrayalex** [comment]
See the documentation for how to make async requests with v1: https://github.com/openai/openai-python#async-usage
