### ISSUE TITLE
@rattrayalex  @RobertCraigie  - hey there - Keiji from Azure OpenAI here!

### ISSUE THREAD

**Issue by goldenk4** [openai/openai-python#901]
@rattrayalex  @RobertCraigie  - hey there - Keiji from Azure OpenAI here! 

We have written a more extended Azure OpenAI migration guide in our documentation: https://aka.ms/oai/v1-python-migration

Would it be possible to add it to the main body of this Guide?

_Originally posted by @gojira in https://github.com/openai/openai-python/discussions/742#discussioncomment-7525272_

**Comment by RobertCraigie** [comment]
@goldenk4 please stop spamming this repository.
