### ISSUE TITLE
Fix code example for Streaming section in Readme

### ISSUE THREAD

**Issue by jamesev15** [openai/openai-python#903]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

There are a couple of errors in the examples provided for the streaming section.

1. First Issue   
This is the example code, the last line should be **print(chunk.choices[0].delta.content)**    
```python
from openai import OpenAI

client = OpenAI()

stream = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(part.choices[0].delta.content)
```
2. Second Issue    
This is the example code, the last line should be **print(chunk.choices[0].delta.content)**    
```python
from openai import AsyncOpenAI

client = AsyncOpenAI()

stream = await client.chat.completions.create(
    prompt="Say this is a test",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
async for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(part.choices[0].delta.content)
```

### To Reproduce

If you run the snippet provided, there are **None** values as result
```python
from openai import OpenAI

client = OpenAI()

stream = client.chat.completions.create(
    model="gpt-4",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(part.choices[0].delta.content)+
```

Result:
None
None
None
None
None
None

### OS

linux

### Python version

Python 3.10.12

### Library version

openai v1.3.3

**Comment by rattrayalex** [comment]
Thanks! I'll have a fix up shortly.
