### ISSUE TITLE
Support for Azure OpenAI extentions

### ISSUE THREAD

**Issue by eavanvalkenburg** [openai/openai-python#910]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

Azure OpenAI also has additional endpoints for extentions, especially for the "on your data" functionality, would be great if this package also supports that feature, it is described here: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions it mostly consists of a slightly different endpoint and additional fields in the request, and the output adds a enhancement field with citations, latest version: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-12-01-preview/inference.yaml

**Comment by kristapratico** [comment]
@eavanvalkenburg the v1 library does support "on your data", you can see example code here: 
https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python#create-the-python-app

Any additional fields for 2023-12-01-preview can be added into the `extra_body`. Does this work for you?

**Comment by eavanvalkenburg** [comment]
damn, missed that! thanks! @kristapratico

**Comment by linjungz** [comment]
Hi, I've tried the `extra_body` for enhancements with Vision but it doesn't work.

Here's my code:
```
response = aoai_client.chat.completions.create(
                        model=os.environ.get("AZURE_OPENAI_API_DEPLOYMENT"),
                        extra_body={
                            "enhancements": {
                                "ocr": {
                                    "enabled": True
                                },
                                "grounding": {
                                    "enabled": True
                                }
                            },
                            "dataSources": [
                                {
                                    "type": "AzureComputerVision",
                                    "parameters": {
                                        "endpoint": "MYENDPOINT",
                                        "key": "MYKEY"
                                    }
                                }],
                        },
                        messages=messages,
                        temperature=0,
                        max_tokens=2000,
                        top_p=0.95,
                        frequency_penalty=0.0,
                        presence_penalty=0.0,
                        stream=True,
                    )
```

The error is here:

```
2024-01-11 14:23:23.454 Uncaught app exception
Traceback (most recent call last):
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/Users/junlin/sandbox/gpt-math-teacher/app.py", line 113, in <module>
    response = aoai_client.chat.completions.create(
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/openai/_base_client.py", line 1112, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/openai/_base_client.py", line 859, in request
    return self._request(
  File "/Users/junlin/sandbox/gpt-math-teacher/venv/lib/python3.9/site-packages/openai/_base_client.py", line 949, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': '1 validation error for Request\nbody -> enhancements\n  extra fields not permitted (type=value_error.extra)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

Seems the `enhancements` is not supported? 
I'm using the 2023-12-01-preview.

Could you kindly help to check?

**Comment by kristapratico** [comment]
@linjungz are you accessing the chat completions extensions endpoint? It's necessary to work with dataSources/enhancements. See how the AzureOpenAI client is constructed in this sample: https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?tabs=command-line%2Cpython-new&pivots=programming-language-python#create-the-python-app

The `base_url` keyword argument must be passed into the Azure client, routing to the specific extensions endpoint. Let me know if this works for you.

**Comment by ishaan-jaff** [comment]
Hi @kristapratico running into the same issue, we set `azure_endpoint` any reason why we need to set `base_url`? 

I can confirm I don't see the error when using `base_url`

**Comment by kristapratico** [comment]
@ishaan-jaff `base_url` needs to be used since it allows for altering the path to ensure we hit the chat completions extensions endpoint (note the `extensions` at the end):

```
client = openai.AzureOpenAI(
    base_url=f"{endpoint}/openai/deployments/{deployment}/extensions",
    api_key=api_key,
    api_version="2023-08-01-preview",
)
```

This builds a URL for the request that looks like: {endpoint}/openai/deployments/{deployment}/extensions/chat/completions?api-version=2023-08-01-preview

Right now this will not work with regular chat completions (same as above, minus extensions), which is what you target when you use `azure_endpoint`.

**Comment by ishaan-jaff** [comment]
Makes sense, thanks !
