### ISSUE TITLE
 base_url of OpenAI Client Instance Cannot Be Modified Due to Missing Update in Setter Method

### ISSUE THREAD

**Issue by xuing** [openai/openai-python#913]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

I encountered an issue where the `base_url` of an OpenAI client instance couldn't be modified. This is due to the setter method of `base_url` not updating `self._base_url`.

### Possible Solution
I suggest modifying the setter method for base_url to ensure self._base_url is also updated. Additionally, incorporate handling for the trailing slash of the URL, as done in [the __init__ method](https://github.com/openai/openai-python/blob/17ac6779958b2b74999c634c4ea4c7b74906027a/src/openai/_base_client.py#L346C1-L346C69):
~~~python
@base_url.setter
def base_url(self, url: URL | str) -> None:
    url = url if isinstance(url, URL) else URL(url)
    url = self._enforce_trailing_slash(url)
    self._base_url = url
    self._client.base_url = url
~~~

### To Reproduce

1. Set up an OpenAI client instance with initial parameters including base_url.
2. Attempt to modifybase_url.
3. Observe that self._base_url within the client instance remains unchanged, indicating that the modification has not been applied.

![image](https://github.com/openai/openai-python/assets/11143269/d7260044-eff1-48a7-97a6-348c1ff437e0)

### Code snippets

```Python
import os

from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
    base_url="https://api.openai.com/v1",
)
print(client.base_url)
client.base_url = "https://newurl.example.com/v1"
print(client.base_url)
```

### OS

Windows11

### Python version

Python 3.12.0

### Library version

1.3.6

**Comment by tomoish** [comment]
I may be able to fix it.
I have confirmed that it works correctly using your Possible Solution. After writing a test, I will submit a pull request.

**Comment by RobertCraigie** [comment]
Thanks for the report, while we fix this you should be able to use `client.with_options()` to set the base URL instead.

**Comment by RobertCraigie** [comment]
This will be fixed in the next release! https://github.com/openai/openai-python/pull/919
