### ISSUE TITLE
404 here.. 

### ISSUE THREAD

**Issue by johnda98** [openai/openai-python#918]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

https://github.com/openai/openai-python/blob/main/chatml.md.  404

### To Reproduce

https://github.com/openai/openai-python/blob/main/chatml.md

### Code snippets

```Python
ddd
```

### OS

Mac 

### Python version

na

### Library version

na

**Comment by rattrayalex** [comment]
That file does not exist. What was trying to link you to it?

**Comment by johnda98** [comment]
darn good point should have sent u content page.  docs.. related to token
counting..

*John D Allen.*



*Voice  +1 417 300 4812 ** CST  | ***@***.***
***@***.***>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | johnda98#4728 - discord.*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by rattrayalex** [comment]
Thanks! cc @logankilpatrick – looks like an outdated link to "ChatML" on [this page](https://platform.openai.com/docs/guides/text-generation/managing-tokens).
