### ISSUE TITLE
Anyio>4 support

### ISSUE THREAD

**Issue by Shulyaka** [openai/openai-python#921]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

The project depends on anyio>=3.5.0,<4, however I would like to use it in a project that requires anyio==4.1.0

### Additional context

https://pypi.org/project/anyio/#history
https://github.com/openai/openai-python/blob/e36956673d9049713c91bca6ce7aebe58638f483/pyproject.toml#L14

**Comment by rattrayalex** [comment]
Thanks, we'll look into whether there are any changes in 4.x that would cause problems and relax the restriction if not! It'd be helpful if you could try it out and report whether you encounter any issues.

We primarily use `anyio` through our dependency `httpx`, and [this comment](https://github.com/encode/httpx/pull/2885#discussion_r1380357349) makes it seem that httpx should work well with anyio 4.x, so I imagine this will be safe to allow.

cc @RobertCraigie

**Comment by RobertCraigie** [comment]
This restriction will be lifted in the next release, https://github.com/openai/openai-python/pull/928.

**Comment by Shulyaka** [comment]
Thank you!
