### ISSUE TITLE
Easy way to get a context window for a model

### ISSUE THREAD

**Issue by Sciencealone** [openai/openai-python#925]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

The current version of `openai-python` (v1.3.7) does not contain any method to get the size of context window for a model used for a chat completion. It might cause some overload or underutilization of a model. 

Definitely, some model names are clear enough (like gpt-4-**32k**) but the majority of them must be manually checked using the correspondent tables at https://platform.openai.com/docs/models.

It would be great to fix this inconsistency by any or all of these measures:

1. Include the size of the context window in the name of each model.
2. Improve the model object (https://platform.openai.com/docs/api-reference/models/object) by adding the size of context window.

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

This sounds like a feature request for the underlying OpenAI API (specifically, the models endpoints) and not the Python library, so I'm going to go ahead and close this issue.

Would you mind reposting at [community.openai.com](https://community.openai.com)?
