### ISSUE TITLE
Delete thread message... It seems the API supports delete message but python library doesn't have it implemented 

### ISSUE THREAD

**Issue by ihubanov** [openai/openai-python#930]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

The need for this feature came because with the newer model where input is 120k tokens, when the conversation  gets longer and longer, one message might cost up to $1.2+ So users might want to cleanup the thread conversation and leave only desired number of messages in history...
I've already implemented this feature in my fork below, and would be very happy if we also have it in the official repo as well.
Link to my fork commit: https://github.com/openai/openai-python/commit/6c408960577d22604f1086edc913cc6500752521

### Additional context

Also some related discussion here: https://community.openai.com/t/how-to-limit-the-number-of-messages-or-tokens-that-are-persisted-in-a-thread-to-maintain-context-in-open-ai-assistants/531814

**Comment by rattrayalex** [comment]
The library will support this endpoint as soon as it is officially documented.
