### ISSUE TITLE
For events of the same openai job, the id returned each time the list_events method is called may be different.

### ISSUE THREAD

**Issue by keepsaunter** [openai/openai-python#938]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

When I call the list_events method to get the job log, the ID of the same log returned by two repeated calls is sometimes different, which leads to the error "Given after argument was not found in items." when I use the get_next_page method to get the next page.
![image](https://github.com/openai/openai-python/assets/29244475/2ec782e6-e03a-42c0-a799-c387b4424f29)
## Called twice with the same parameters, some jobs have different IDs.
![image](https://github.com/openai/openai-python/assets/29244475/9f6c61cd-4fd3-4687-a88f-8bd840d54590)

### To Reproduce

```python
from openai import AzureOpenAI

client=AzureOpenAI(
  azure_ad_token=token,
  azure_endpoint=endpoint,
  api_version=api_version
)

events = client.fine_tuning.jobs.list_events(fine_tuning_job_id=job_id, limit=10)
events.get_next_page()
```

### Code snippets

```Python
from openai import AzureOpenAI

client=AzureOpenAI(
  azure_ad_token=token,
  azure_endpoint=endpoint,
  api_version=api_version
)
client.fine_tuning.jobs.list_events(fine_tuning_job_id=job_id, limit=10)
```

### OS

macOS

### Python version

Python v3.10.13

### Library version

openai v1.3.5

**Comment by rattrayalex** [comment]
Terrific, thank you @pkranen !

Since this isn't a library bug, I'm going to go ahead and close this issue.

**Comment by keepsaunter** [comment]
> @keepsaunter , good catch. We have a fix and it will roll out with the next release. Thanks for reporting!

Could I know the specific repair time?

**Comment by pkranen** [comment]
It will reach all regions by the end of this week.
