### ISSUE TITLE
Make the OpenAI API model names and info available under an enum

### ISSUE THREAD

**Issue by hdragos** [openai/openai-python#952]
### Confirm this is a feature request for the Python library and not the underlying OpenAI API.

- [X] This is a feature request for the Python library

### Describe the feature or improvement you're requesting

It would greatly help to have the names and several fields of interest (like max tokens) of the available OpenAI models under some sort of enum.

This would greatly help with the model validation and accessing the fields of interest. For now, if we want a list of available models, we need to declare it ourselves (see code below).

```PY
from dataclasses import dataclass


@dataclass
class ChatGPTModel:
    name: str
    max_tokens: int


CHAT_GPT_MODELS = {
    "gpt-3.5-turbo": ChatGPTModel(name="gpt-3.5-turbo", max_tokens=4000),
    "gpt-4": ChatGPTModel(name="gpt-4", max_tokens=8000),
}

```

### Additional context

If needed, I can add this change myself (however some guidance would be necessary).

**Comment by rattrayalex** [comment]
Thanks for the suggestion!

I don't think we'd want to include info like `max_tokens`, since that may be subject to change.

However, exposing a union of the model names would be something we can do, and clearly helpful.

For now, you can hack around this like so:
```py
import openai
from typing import *

model_type = get_type_hints(openai.types.chat.completion_create_params.CompletionCreateParamsBase)['model']
model_union = get_args(get_args(n)[0])[1]
model_arr = list(model_union.__args__)

print(model_arr)
```
gives you 
```py
['gpt-4-1106-preview', 'gpt-4-vision-preview', 'gpt-4', 'gpt-4-0314', 'gpt-4-0613', 'gpt-4-32k', 'gpt-4-32k-0314', 'gpt-4-32k-0613', 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-16k-0613']
```

I don't recommend relying on this in production as the ordering of the types may change.

**Comment by RobertCraigie** [comment]
The model names are now defined in a named enum :) https://github.com/openai/openai-python/blob/main/src/openai/types/chat_model.py
