### ISSUE TITLE
Broken link on docx

### ISSUE THREAD

**Issue by blackboxdelta** [openai/openai-python#958]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

https://platform.openai.com/docs/guides/text-generation/managing-tokens 

![image](https://github.com/openai/openai-python/assets/136206577/20b6a6a1-efef-46a2-9e85-7069e22f33bb)

The hyper link is broke. 404.

### To Reproduce

Click The [ChatML documentation](https://github.com/openai/openai-python/blob/main/chatml.md) explains how messages are converted into tokens by the OpenAI API, and may be useful for writing your own function.

### OS

Windows

### Python version

NA

### Library version

NA

**Comment by rattrayalex** [comment]
dup of https://github.com/openai/openai-python/issues/918#issuecomment-1845127996

cc @logankilpatrick
