### ISSUE TITLE
Multiple document upload assistant update seems not working

### ISSUE THREAD

**Issue by ElioErrico** [openai/openai-python#990]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [x] This is an issue with the Python library

### Describe the bug

I'm trying to upload multiple files on openai Assistant.

- I didn't find the way to upload just one file to a set of existing file already uploaded to the assistant.
- So if you want to add just one file you need to upload a list of already uploaded files plus the new one you want to upload

The problem in my case is that proceeding as above it upload just 2 files of the list.

### To Reproduce

Create file n°1:
```
file_1 = client.files.create(
    file=open("'Test_1.txt', "rb"),
    purpose="assistants"
)
```

Create file n°2:
```
file_2 = client.files.create(
    file=open("'Test_2.txt', "rb"),
    purpose="assistants"
)
```

Create file n°3:
```
file_3 = client.files.create(
    file=open("'Test_3.txt', "rb"),
    purpose="assistants"
)
```
Then we can update the assistant with 3 files:

```
assistant = client.beta.assistants.update(
    assistant_id="asst_ ........ Dmo3S",
    file_ids=[file_1.id , file_2.id, file_3.id]
)
```

Than if you go in the assistant you see that only 2 documents are uploaded (attached image)
Let me know if it is a bug or I missed something.

Thanks
![Cattura](https://github.com/openai/openai-python/assets/143315119/1c7b45fd-6396-4369-ade0-00bedb98753f)

### OS

Windows 10

### Python version

Python v3.12

### Library version

openai 1.5.0

**Comment by rattrayalex** [comment]
You may need to keep checking the assistant as to whether the assistant has indexed all files. 

We're working on adding helpers to the SDK to make this sort of things easier.
