### ISSUE TITLE
Stuck on how to output max number of characters

### ISSUE THREAD

**Issue by tonyphoang** [openai/openai-python#999]
### Confirm this is an issue with the Python library and not an underlying OpenAI API

- [X] This is an issue with the Python library

### Describe the bug

What I'm trying to do:
I'm trying to output a max number of tokens (ex:600 tokens) in the AI response from a variable input. 

Example below:
Input
500-1000 tokens
output
<600 tokens

Via documentation (https://platform.openai.com/docs/api-reference/completions/create#chat/create-max_tokens)
- max_tokens
- The maximum number of [tokens]that can be generated in the completion.
- The token count of your prompt plus max_tokens cannot exceed the model's context length. 

Question:
It looks like the only way to control the tokens used is the max_token variable however it's the total tokens (input+output). Is there a way to control the max tokens of the output? 

### To Reproduce

    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": context_template},
            {"role": "user", "content": prompt}
        ],
        max_tokens=600
    )

### OS

macOS 

### Python version

3.9.6

### Library version

openai=1.60

**Comment by Androbin** [comment]
You can try [Counting tokens for chat completions API calls](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb).

```python3
CONTEXT_LENGTH_BY_MODEL = {
    ...
}
context_length = CONTEXT_LENGTH_BY_MODEL[model]
num_tokens = num_tokens_from_messages(messages, model)
max_tokens = min(max_tokens, context_length-num_tokens)
```

**Comment by rattrayalex** [comment]
Thank you @Androbin !

@tonyphoang , if you'd like further help from fellow developers on how to use the OpenAI API, I recommend joining the OpenAI Discord!
